### ISSUE TITLE
[Multiple] Logs related issues

### ISSUE THREAD

**Issue by wlhUser** [ukanth/afwall#1002]
First of all, thanks for providing and maintaining this very useful project.

If tested a bit with a self-compiled version of the firewall (3.2.0-Beta, test on lineageos 16 [Android Pie]), and found that the logs are never populated, even though the protocol service was turned on.
However, the messages about blocked applications had been present in dmesg.

In the end, after some debugging, I discovered that, at least in my case, everything works fine if I  rename the files:
afwall/aFWall/src/main/res/raw/aflogshell => aflogshell**b**
and 
afwall/aFWall/src/main/res/raw/aflogshell**b** => aflogshell

The busybox file contained the command for system and the system file the command for busybox.

Hope I'm not too wrong with my analysis.

Best Regards

wlh

**Comment by megusta-01** [comment]
i've same issue with android 10 and app 3.3.1 from playstore 
Is it fixed with newer version?

**Comment by ioogithub** [comment]
I have this issue as well, I am on LineageOS (Android 9). I have never seen a log.

Does anyone know where I can find those files that whlUser mentioned? I went looking for them but I don't see that path in my system. I would like to fix this and start using afwall but I really do need some working logging.

**Comment by pieterhouwen** [comment]
@ioogithub If you have your ADB shell with root open it's at: /data/data/dev.ukanth.ufirewall/app_bin

I renamed the files like @wlhUser suggested but still got nothing.

**Comment by irontechmonkey** [comment]
Thanks @wlhUser for some nice digging and @pieterhouwen for describing the location of the files. 
Logging is failing for me as well after reboot or after a particular FC (reported here https://github.com/ukanth/afwall/issues/1085). To get logging working again I've been disabling/enabling logging or changing the target and busybox - not necessarily changing but going through the process of selecting the same thing even if there is only one item. I'm going to try renaming the 2 files to see if that is applicable to my case and if the fix persists after reboot. Will chime in after testing. Thanks again.

[EDIT] Even after renaming those 2 files, then after forced stop of Afwall app restart of app, no logging until playing with the settings. Still good to know about this as they might (or might not) be related.

**Comment by exec228** [comment]
When entering log screen, one can see events from several hours ago. "pull-down gesture" does not work.

To refresh log, I must switch preferences: Log Target=NFLOG, then back to Log Target=LOG.

This operation allows log to come to an adequate state, and the log view even can be refreshed by "pull-down gesture".

Is it normal behaviour?

Xiaomi Redmi Note 7 "lavender", Havoc OS 2.9 (Android 9)

**Comment by ioogithub** [comment]
Why was this issue closed, is there a fix or instructions ? When I got the email, I just opened the app, looked again and there are no logs. It has been over a year for me and I am now using a newer version (v3.4.0) from fdroid.

I have tried all of the things discussed in this thread however I have never seen any logs. A firewall without logs is really not that useful.

**Comment by ukanth** [comment]
Most of the issues has been addressed in 3.5.0 version of AFWall+ which was released yesterday.If the problem stills exist on 3.5.0, please reopen it.
