### ISSUE TITLE
(v2.9.9) Need to re-apply rules manually on connectivity change ?

### ISSUE THREAD

**Issue by lemonsqueeze** [ukanth/afwall#1003]
Hi,

Many thanks for AFWall+, does wonders:
I'm using it on an old phone where something was eating up bandwidth to block everything except wanted apps. Phone is running Android 4.2.2 so the latest version available here is 2.9.9.

One minor issue i noticed, even though i have "Apply firewall rules on every connectivity change" enabled, I have to manually re-apply rules after data connection comes up/changes otherwise everything is blocked. Looks like AFWall+ connectivity change trigger is working though, i'm seeing the notifications and super user shell notice.

Do you know what might be happening ? Maybe a race condition there / would need to wait a bit for settings to take effect ?

Many thanks

**Comment by lemonsqueeze** [comment]
Looks like a reboot fixed it.

**Comment by ukanth** [comment]
Thanks. Closing the issue
