### ISSUE TITLE
(kernel) - Linux kernel (-11) denied

### ISSUE THREAD

**Issue by lemmy04** [ukanth/afwall#1018]
I'm running AFwall+ on a Samsung S5e (android 9 rooted with magisk) in "allow selected" mode.

I have all the core services allowed except [-10] Any App, if i check this AFwall basically does not block anything anymore...

I am getting a *lot* of (kernel) - Linux kernel (-11) denied even though that one is checked in core services...

any ideas?

**Comment by anmith** [comment]
see #981

**Comment by lemmy04** [comment]
duplicate of #981
