### ISSUE TITLE
mDNS blocked

### ISSUE THREAD

**Issue by lemmy04** [ukanth/afwall#1020]
I'm getting a lot of "mDNS (1020) blocked" but that app/service isn't even listed in the list of apps...

edit: Samsung S8+, still running android 8, rooted with magisk.

**Comment by ukanth** [comment]
add the following custom rules

```
$IPTABLES -A afwall-wifi-lan -m owner --uid-owner 1020 -j RETURN
$IPTABLES -A afwall-wifi-wan -m owner --uid-owner 1020 -j RETURN
$IPTABLES -A afwall-3g-home -m owner --uid-owner 1020 -j RETURN
```

**Comment by lemmy04** [comment]
Do I just copy these three lines into the "custom script" field, or do i need more in it?
https://github.com/ukanth/afwall/wiki/CustomScripts#adding-custom-rules defines $IPTABLES first, and all that...

**Comment by lemmy04** [comment]
ok i got it.
should I add the same rules with $IP6TABLES? I do have working IPv6 here.

**Comment by lemmy04** [comment]
well, so far this workaround seems to do the trick.

**Comment by lemmy04** [comment]
ok, I've solved "mDNS blocked" and "root blocked" with these four rules:

$IPTABLES -A afwall -p tcp --dport 53 -j RETURN
$IPTABLES -A afwall -p udp --dport 53 -j RETURN
$IPTABLES -A afwall -p tcp --dport 5353 -j RETURN
$IPTABLES -A afwall -p udp --dport 5353 -j RETURN
