### ISSUE TITLE
Phone becomes unstable after installing AFWall, freezes and reboots

### ISSUE THREAD

**Issue by jw243** [ukanth/afwall#1023]
AFWall+ Mode: whitelist

Android Rom: LineageOS 16,0-20190919-microG-payton

After installing AFWall on a freshly installed system, the system freezes and reboots by itself after a while,

Installed AdAway, but it is not activated.

[log.txt](https://github.com/ukanth/afwall/files/3714880/log.txt)
[IPv4rules.log](https://github.com/ukanth/afwall/files/3714886/IPv4rules.log)
[bugreport-payton-PQ3A.190801.002-2019-10-11-00-39-04.zip](https://github.com/ukanth/afwall/files/3714892/bugreport-payton-PQ3A.190801.002-2019-10-11-00-39-04.zip)
[connectivity.txt](https://github.com/ukanth/afwall/files/3714906/connectivity.txt)

System IPTables
Built-in BusyBox

Private DNS off

Fix startup data leak: unable to mount the directory (/system/etc/init.d)

Tor control does not work.

Any help would be appreciated.

**Comment by jw243** [comment]
I suspect, the problem is related to the presence of the SIM card. I had a stable system in the absence of the SIM card and the problems started shortly after inserting one, even when data connection was still via WiFi.

**Comment by ukanth** [comment]
I don't see any issues with AFWall+. This could be ROM issue. 
Try disabling Log service and see if that solves.
