### ISSUE TITLE
Samsung Upday penetrates through firewall

### ISSUE THREAD

**Issue by 63dhdbdb** [ukanth/afwall#1024]
Galaxy S7. By default there is a news app installed that occasionally shows breaking news. Somehow these news get pushed through even though Upday is disabled in the firewall. Other apps are blocked as expected. The notorious # 1000 is blocked, too. This has been going on for years. I don't want to remove the app beause it working seems to be a symptom of a way through the firewall. Please advise.

**Comment by ukanth** [comment]
Please provide more information. Notification can be pushed through other system application as well.

**Comment by develBuzz** [comment]
The app might use GCM (Google cloud messaging) which means messages will be transfered via google services?
