### ISSUE TITLE
App fc on applying rules

### ISSUE THREAD

**Issue by dogknowsnx** [ukanth/afwall#1025]
The new beta2 crashes on applying iptables and won't reopen (therefore no logs) on a Moto G5s running Android 9 ViperOS, Radium kernel, Magisk 20, EdXposed, Adguard default DNS. Clean installation of afwall.

No issues on previous beta build..

**Comment by ukanth** [comment]
Please provide logcat/crash details.

**Comment by dogknowsnx** [comment]
Reinstalled afwall from scratch, went about setting it up as usual. No matter what I try, at some point the app keeps crashing. Here are some logs - hope it helps:

**Comment by ukanth** [comment]
@manfred3000 , Thanks for the detailed logs. Its helpful. Can you please try this version ?

<notworking>

**Comment by dogknowsnx** [comment]
Thanx. Unfortunately the app still crashes whenever I try to apply iptables rules, e.g. on switching profiles..
New logs attached

**Comment by ukanth** [comment]
Good catch. Seems like you have disabled ipv6. This should solve your problem.

https://www.dropbox.com/s/lyasiiajtff8p7m/AFWall%2B_3.2.0-rel-Test2.apk?dl=0

**Comment by dogknowsnx** [comment]
Yes! Thanx alot. Did some quick testing and everything seems back to normal.
