### ISSUE TITLE
[3.20] LineageOS 16: AFWall+ closes on boot, log service failure and empty

### ISSUE THREAD

**Issue by develBuzz** [ukanth/afwall#1027]
Currently using:
- LOS 16 with Security Updates October 2019
- version 3.20 BETA 2(checked: same error with version 3.20)
- log service enabled
- no error if log service is disabled (checked)

If log serice is enabled log file is empty. 

Solution: switch back to 3.10, log works as expected. No error on boot. 

Log: 
10-20 00:36:44.706 E/AndroidRuntime( 2301): FATAL EXCEPTION: main
10-20 00:36:44.706 E/AndroidRuntime( 2301): Process: dev.ukanth.ufirewall, PID: 2301
10-20 00:36:44.706 E/AndroidRuntime( 2301): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{30ad649 u0 dev.ukanth.ufirewall/.service.LogService}
10-20 00:36:44.706 E/AndroidRuntime( 2301): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
10-20 00:36:44.706 E/AndroidRuntime( 2301): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-20 00:36:44.706 E/AndroidRuntime( 2301): 	at android.os.Looper.loop(Looper.java:193)
10-20 00:36:44.706 E/AndroidRuntime( 2301): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
10-20 00:36:44.706 E/AndroidRuntime( 2301): 	at java.lang.reflect.Method.invoke(Native Method)
10-20 00:36:44.706 E/AndroidRuntime( 2301): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-20 00:36:44.706 E/AndroidRuntime( 2301): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jw243** [comment]
Same problem here. In version 3.2.0 (donate version), log service does not work. Log protocoll is always empty.

**Comment by ukanth** [comment]
Please check this version.
https://www.dropbox.com/s/p9ibfqxrasgs158/AFWall%2B_3.3.0-Test.apk?dl=0

**Comment by desmonk** [comment]
> 
> 
> Please check this version.
> https://www.dropbox.com/s/p9ibfqxrasgs158/AFWall%2B_3.3.0-Test.apk?dl=0

On the same boat. Tested 3.3.0. Log still empty. Able to start at boot. But while enabling Startup data leak, got no confirmation toast. Speed is a bit slow than before on boot as well.

**Comment by ukanth** [comment]
Please provide logcat along with firewall rules. Otherwise I can't fix the problem.

**Comment by ukanth** [comment]
Fixed in 3.3.0. Closing.

**Comment by develBuzz** [comment]
Ty, it is fixed.
