### ISSUE TITLE
Notification icon can't be removed

### ISSUE THREAD

**Issue by unbranched** [ukanth/afwall#1029]
From v3.2.0 the notification icon is always on. If I toggle the option Preferences->UI Preferences->"Show notification icon" nothing changes.

**Comment by est61** [comment]
Yep same here, the only thing that solves this temporarily until this is fixed is going to Apps > afwall > Notifications > and uncheck **Firewall Service**

**Comment by ukanth** [comment]
From android 8, AFWall+ needs to run in background and do not disable "Firewall Service" if you want the rules to be applied on connectivity change.

**Comment by unbranched** [comment]
@ukanth I don't get your answer, here we're speaking about the notification icon, not the firewall service. est61 solution is just to remove the notification.

I'm using Android 8 since 2 years and the icon always correctly disappeared before version 3.2.0.

**Comment by oushidian** [comment]
I've been able to remove the permanent notification since Android 7 while still getting the "apply" notification. I can't remember how to do it on 8 but on 10 you can select really specific notification to allow through the app control settings.

**Comment by serious-angel** [comment]
@ukanth Dear Developer, please, make it possible to remove an icon from notification bar at the top of screen, but leave it in a drawer like other apps do. This won't disable service, but just hide an icon from clear view.

**Comment by ukanth** [comment]
Making it optional is hard. I have removed this option and you can use Android settings to disable notification icon.
