### ISSUE TITLE
Tor Control Does Not Work

### ISSUE THREAD

**Issue by jw243** [ukanth/afwall#1030]
LOS 16 (MicroG) 24/10/2019
AFWall 3.2.0
Magisk 20.0 (same with addonsu)
Orbot 16.1.0-RC-2
Private DNS

Tor control does not work. Internet access of apps through tor is blocked. Is there anything I can do about that? Or could this be fixed in an upcoming version?

Thanks!

**Comment by jw243** [comment]
I have found an extremely simple solution to the problem of tor control not working with default settings of AFWall and Orbot. Maybe you could include this in your FAQs. Do the following, if your app cannot connect to the internet via tor, even though you checked the tor check box in AFWall (in addition to choosing at least one of the check boxes for Wifi, Mobile data, VPN...) :
- In Orbot tap the three dots in the top right corner.
- Select "Settings".
- Scroll down to section "Debug".
- Tap on "Tor TransProxy Port", remove "auto" and type "9040". Press "OK".
- Tap on "Tor DNS Port", remove "auto" and type "5400". Press "OK".
- Return to Orbot main screen, tap the three dots in the top right corner. Select "Exit".
- Start Orbot again and connect to tor. Now tor control in AFWall should work flawlessly.

**Comment by nikonakoneko** [comment]
I tried this fix and it doesn't work for me. What info do you need to investigate or what can I do to investigate myself?

**Comment by jw243** [comment]
I don't understand your problem. Just follow the steps above and it should work.
