### ISSUE TITLE
Logging does not work since 3.1

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#1034]
I was using version 3.0 since yesterday. I could enable logging when I needed it.
Now I installed AFWall+ 3.1 and when I try to enable logging in the settings, a toast tells me: "Kernel is missing LOG / NFLOG support". Is there something I can do about it? What details can I provide to assist debugging the problem?

**Comment by ghost** [comment]
Is this related to Changelog entry "Log service process bug" and https://github.com/ukanth/afwall/issues/991 ?

**Comment by andreskrey** [comment]
Same issue here. AFWall 3.2.0. Android 8.0.0, Kernel 3.18.17. Moto G6. Logs are empty. Blocking seems to be working.

**Comment by h1z1** [comment]
For the sake of posterity, what distro?  Seems like a lot of problems are related to Lineage.

**Comment by andreskrey** [comment]
Stock Motorola

**Comment by ghost** [comment]
Stock [SHIFTPhone](https://www.shiftphones.com/en/) Android 8.0.0 Kernel 3.18.60 [ShiftOS-G](https://forum.shiftphones.com/forums/shiftos.61/)

**Comment by ukanth** [comment]
Please check this version.
https://www.dropbox.com/s/p9ibfqxrasgs158/AFWall%2B_3.3.0-Test.apk?dl=0

**Comment by ghost** [comment]
I am running the F-Droid version signed with a different certificate. So I unfortunately cannot install this version without loosing my configuration.

**Comment by ukanth** [comment]
Fixed in 3.3.0. Closing.

**Comment by IeP4nieF** [comment]
I can't confirm, that this is fixed in 3.3.0. After installing 3.3.0 (f-droid.org) there are still no logs available.

**Comment by IeP4nieF** [comment]
After upgrading to 3.3.1 the bug is fixed. Thanks!
