### ISSUE TITLE
Samsung S8+, Andoid 9, Magisk 20.1, AFwall+ 3.2.0 (donate) - sometimes rules don't get updated

### ISSUE THREAD

**Issue by lemmy04** [ukanth/afwall#1036]
Sometimes changed rules dont get applied until i disable and re-enable the firewall...

What detail can I provide to debug this?

**Comment by nutpantz** [comment]
S7 edge Android 8,  I'm only getting about 60%  success of rules being updated 20% I get rule update failed. On my Lenovo phab 2 Android 6 even less successful I had to downgrade as the rules usually failed to be applied with the error shown.

**Comment by ukanth** [comment]
Please share the rules with log messages from menu-show rules-export

**Comment by lemmy04** [comment]
will do. problem is, it happens randomly...

**Comment by lemmy04** [comment]
Here are my rules:
https://susepaste.org/50573949

What I noticed is, whenever this happens there's also no afwall+ "icon" in the notifications anymore. Almost looks as if AFWall has crashed and left netfilter tables in an inconsistent state.

**Comment by ukanth** [comment]
Please check this version. 

https://www.dropbox.com/s/p9ibfqxrasgs158/AFWall%2B_3.3.0-Test.apk?dl=0

**Comment by lemmy04** [comment]
...how can i transfer my rules from the donate version to the free version that you sent me?
If you want to send me a (donate) build of that test version you could contact me / send it to me on telegram: https://telegram.me/lemmy98

**Comment by nutpantz** [comment]
No better for me

Rules say they applied fine but don't work
My rules for the test attached

**Comment by ukanth** [comment]
@nutpantz , just disable and enable once. Also please provide rules menu-showrules -export.

**Comment by nutpantz** [comment]
I have 5 profiles of various apps groups of apps that I switch between. Can you email a way to import rules to the basic version?

**Comment by ukanth** [comment]
that's fine. any profile rules will do.

**Comment by nutpantz** [comment]
Try this

**Comment by ukanth** [comment]
Fixed in 3.3.0. Closing.
