### ISSUE TITLE
Logging service empty on a poco F1

### ISSUE THREAD

**Issue by yoshimo** [ukanth/afwall#1037]
I am running a poco f1 with MI 10.3.7.0 with afwall+ 3.2.0 that is rooted with magisk.
Having a log about attempted connections and notification toasts doesn't work consistently.
Most of the the time the log is completely empty and can only be made partially working for a brief period of time by disabling the logging service and re-enabling it.

Would be great if this problem could be solved.

**Comment by ukanth** [comment]
Please share the rules with log messages from menu-show rules-export

**Comment by ukanth** [comment]
Please check this version.
https://www.dropbox.com/s/p9ibfqxrasgs158/AFWall%2B_3.3.0-Test.apk?dl=0

**Comment by yoshimo** [comment]
Doesn't seem to change things.
I had started voth allowed and forbidden apps and no toast and no log message showed up, even after restarting the phone.

**Comment by ukanth** [comment]
Please share the rules from menu-show rules-export

**Comment by ukanth** [comment]
No logs or info. Reopen it when you have it,
