### ISSUE TITLE
"Error purging IP tables" error appears on Android 10

### ISSUE THREAD

**Issue by philipfong** [ukanth/afwall#1038]
Device: Pixel 3a, Android 10 (latest November build)
AFWall version: 3.2.0

Steps to reproduce:
1. Clear app data and app cache
2. Tap 'Show rules' in 3-dot menu
3. Tap 'Flush rules' in 3-dot menu
4. Exit app, restart device, open app
5. Switch firewall option from 'Allow selected' to 'Block selected'
6. Tick 3 boxes next to any app (in this case, I chose Chipotle, for testing)
7. Tap 'Enable firewall' in 3-dot menu
8. Tap 'Disable firewall in 3-dot menu

Observed: Error message appears 'Error purging IP tables'. At this point, the 3-dot menu still shows 'Disable firewall'. It is unclear what state the firewall is in.

Expected: Rules are removed. 3-dot menu will show 'Enable firewall' so that rules can be reapplied.

NOTE: This is NOT reproduced with AFWall version 3.1.0. I have since rolled back.

**Comment by ukanth** [comment]
Please share the rules with log messages from menu-show rules-export

**Comment by philipfong** [comment]
It looks as though I ran into some problems even with the rolled-back version of the app. Maybe this is an issue with Android 10? Here are logs: https://pastebin.com/raw/ZVa5LiHQ

**Comment by ukanth** [comment]
Please check this version.
https://www.dropbox.com/s/p9ibfqxrasgs158/AFWall%2B_3.3.0-Test.apk?dl=0

**Comment by philipfong** [comment]
New logs https://pastebin.com/raw/zSjWWuSV

I no longer see the "error purging" error but the app gets stuck in a state where it thinks that the firewall is enabled (however it's not) and tapping disable does nothing, enable does nothing, and also hitting apply does nothing. I will flush rules, clear app data and try again.

**Comment by ukanth** [comment]
You should apply the rules before trying to disable.

**Comment by philipfong** [comment]
It seems as though when I install the test app and try these steps, it fails:

1. Purge rules
2. Clear app and cache data, reopen app.
3. Select filter to 'block selected'
4. Tick boxes for an app (in this case, I used a food delivery app for testing)
5. Tap 'enable firewall'

Observed: Connectivity is still available when opening the food delivery app. See the log that I posted in my previous comment.
Expected: Connectivity blocked

When I roll back to 3.1.0, the app works fine using the above steps.

Let me know if there's any other way I can help, or if you've been able to reproduce on a Pixel device with Android 10 (rooted with Magisk).

**Comment by ukanth** [comment]
Thanks. Can you post the firewall rules using 3.1.0 and the above test.apk with the mentioned steps. Seems like something is missing.

**Comment by philipfong** [comment]
Unfortunately I was unable to reproduce again with the exact steps I provided, but I have now reproduced the bug reliably with these steps:

1. Purge rules
2. Clear app and cache data, reopen app.
3. Select filter to 'block selected'
4. Tick boxes for an app (in this case, I used the food app called Chipotle)
5. Tap 'enable firewall'
6. Tap 'disable firewall'

Observed: In 3.3.0, the error "error purging iptables" appears. When the app is in this state, enabling/disabling firewall has no effect (no dialog/progress appears to the user)

Expected:  In 3.1.0, I am able to enable/disable over and over with no side effects. When enabling firewall in 3.1.0, the app "checks root access" and then applies all rules (shows 85/85 rules).

Here are logs from 3.1.0 with the steps repeated: https://pastebin.com/raw/ayV93Afr

Here are logs from 3.3.0 with the same steps: https://pastebin.com/raw/wLE3UDJm

**Comment by ukanth** [comment]
Fixed in 3.3.0. Closing.

**Comment by philipfong** [comment]
I have verified this as fixed in the 3.3.0 Play Store release. Fantastic troubleshooting and dev work! Thank you so much @ukanth for the time and effort.

**Comment by chrcoluk** [comment]
Have issue in 3.3.0 and android 9.

But it only seems to happen all the time if I am using custom rules.  When no custom rules it happens "some times".

Could the error be made more verbose "unable to purge iptable rules" is incredibly vague, it should list the exact shell response, which would report which rule it has problem deleting, or if its the afwall script that broken, I can manually purge the rules fine in terminal emulator.
