### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by drcouzelis** [ukanth/afwall#1045]
I apologize in advance, what I'm reporting is not an "issue". I didn't see my question documented anywhere else.

According to the Android settings "Memory used by apps" information, AFWall+ is consistently one of the apps that uses the most memory on my phone (currently showing 208 MB, beaten only by "Android OS").

This surprises me because I assumed AFWall+ can simply apply the changes to iptables and then exit, essentially using no resources after the firewall is applied.

Is there a reason AFWall+ continues to consistently use RAM?

...thank you very much for making such an excellent app!

**Comment by slarti-zak** [comment]
I can confirm high memory usage on an LG G6 Device with android 9:
![Capture+_2019-12-07-06-18-54](https://user-images.githubusercontent.com/13180178/70369528-55767900-18bb-11ea-8316-12119b87eb1b.png)

**Comment by drcouzelis** [comment]
According to Settings -> System -> Developer options -> Running services, AFWall+ is using under 7 MB of RAM.

In my opinion, this issue report can be closed.

Thank you again!
