### ISSUE TITLE
App downloads from Play Store not starting

### ISSUE THREAD

**Issue by cmonty14** [ukanth/afwall#1050]
Hi,
I have installed AFWall+ v. 3.3.1 on 3 different devices that are all rooted.
1 device is running Android 9, the other 2 devices are running Android 8.

With any device I'm facing the following issue:
app downloads in Play Store are not starting.

With this workaround the download starts:

1. Disable all firewall rules
2. Disconnect WLAN
3. Reconnect WLAN
4. Start app downloads
5. Enable all firewall rules

After reconnecting WLAN I noticed that the exclamation mark (!) behind the WLAN symbol disappears.
Once this exclamation mark is back the download fails.

There's no record in log, though.

Can you please advise how to fix this issue?

THX

**Comment by ukanth** [comment]
Enable "Media, Downloads, Download Manager" from system app.

**Comment by cmonty14** [comment]
This is already enabled.
Check the attached screenshot.
![Screenshot_20191205-180906](https://user-images.githubusercontent.com/12523591/70257484-a8044800-178a-11ea-858c-6afb0c7541e0.png)

**Comment by ukanth** [comment]
It could be uid 1000 or some other system app. Its hard to tell the specific one. It vary from device and vendor

**Comment by cmonty14** [comment]
Fair enough... however I hesitate to enable uid 1000 because there are many services/apps included that I don't want to get internet access. Please check attached screenshot.

And I don't understand why the log / protocol is empty.
I would expect that any blocked request should be logged there.
But this is probably another issue that should be addressed in a separate ticket.

![Screenshot_20191206-075700](https://user-images.githubusercontent.com/12523591/70302878-74fb9c00-17fe-11ea-86ec-42d5eb85414b.png)

**Comment by ukanth** [comment]
Agree. Have you tried installing busybox and try setting that in log preference. that might enable logs.

So you have internet, but unable to download only ?

**Comment by cmonty14** [comment]
Nope, I didn't install busybox, yet. 
I decided to install busybox module provided by Magisk and can confirm that logging is working now.

And yes, I have internet w/o any restriction, independant to which WLAN I'm connected.
There's no issue with F-Droid app downloads, just with Play Store.
I can search, display app details, list available app downloads, but I when I start the update the download is not starting.

**Comment by cmonty14** [comment]
**Update:**
I managed to enable busybox for logging in afwall's settings and identified the root cause:
blocked process / service with uid 1000 and app name "OPSkin"


![Screenshot_20191210-110702](https://user-images.githubusercontent.com/12523591/70520250-8d8cee80-1b3d-11ea-9773-87ce26bb4f8c.png)

This means once I allow uid 1000 to access the internet the issue with Play Store is solved.

Question:
Can I enable uid 1000 **and** restrict it to specific apps only?

THX

**Comment by ukanth** [comment]
You can disable captive portal via adb. It works sometime on some devices without allowing uid 1000

**Comment by cmonty14** [comment]
OK.
After reading additional info about "captive portal" I'm not sure if this would solve the issue with Play Store downloads not starting.
My understanding of "captive portal" is that the exclamation mark would go away after disabling it.
But this would imply that "captive portal" is the root cause for the issue with Play Store. Can you confirm this?

**Comment by HagenTronje** [comment]
> You can disable captive portal via adb. It works sometime on some devices without allowing uid 1000

I have the same download issue on a OnePlus7 with Android 10 (Magisk 20.2 AFWall+ 3.3.1).

Allowing  UID 1000 (OPSkin) to get through the firewall solves the issue. However as the OP i do have concerns about this solution and tried to disable the "Captive portal check" but all my attempts like

settings put global captive_portal_detection_enabled 0
settings put global captive_portal_server localhost
settings put global captive_portal_mode 0

failed so far.

What is the correct way to disable "Captive portal check" on Android 10?
