### ISSUE TITLE
Constant notifications on appID -11 (ICMP and Kernel) 

### ISSUE THREAD

**Issue by wwwdesign** [ukanth/afwall#1054]
Since moving to a new phone and setting up afwall again I have regular notifications that ICMP (-11) and kernel (sometimes 0, else  -11). 

The log tells me that when using the Browser the blocked destination host is somehow related to the page I (try to) access. 

I use whitelist mode and have allowed both kernel options and I can't find neither ICMP nor appID -11.

The reason I do mind is that the connection gets really slow, webpages are not accessible or WiFi connection even Drops! 

Running on rooted stock Oreo on Xperia Xz.

**Comment by starbrights** [comment]
Same for me here.

**Comment by ukanth** [comment]
Related/Duplicate to #1002
