### ISSUE TITLE
Wlan connection, no Logs

### ISSUE THREAD

**Issue by nerzwerk** [ukanth/afwall#1072]
Mi9t pro, Evox 4.0, Magsik root

There are 2 problems:

1.) If I activate ipv6 from time to time WLan connection lost. Reconnect after 10-30 sec.

2.) If I turn on logs and save, Afwall will be disabled. Have to turn off the log function, so I can reactivate Afwall

**Comment by ukanth** [comment]
Your kernel does not seem to support Log chain. Thats the reason logs does not work

**Comment by nerzwerk** [comment]
Ok thanks for reply.
