### ISSUE TITLE
Application (SecScanQR) not appear in apps list

### ISSUE THREAD

**Issue by crabvk** [ukanth/afwall#1073]
I installed [SecScanQR](https://f-droid.org/en/packages/de.t_dankworth.secscanqr/) from F-Droid and it's not appear in apps list. Tried to reinstall SecScanQR, AFWall+, reload Android - no luck.
All other apps from F-Droid, Google Play and direct apk installs are in the list.
I'm on LineageOS 16, Xiaomi Mi A1.

**Comment by lessload** [comment]
app "SecScanQR" not request internet permission. that why it does not appear in AFwall.
