### ISSUE TITLE
Adding a custom script results in a reboot

### ISSUE THREAD

**Issue by ErikSteiner** [ukanth/afwall#1075]
Hi there,
if I apply a custom script while I am on a WiFi, my phone crash and reboots if I disable it. It seems like it has a problem switching from WIFI to LTE or even switching mobile phone towers.

If the phone is rebooted it shows an X on LTE or on WiFi on the WiFi symbol. Showing that it has no connection. From there several reboots can happen making the phone unusable.

I am on LineageOS 17, but I know this behavior since LOS 16. If this behavior was introduced by a Afwall version or a ROM build has vanished. I am not sure.

I hope I catched the right error message in logcat.
[crash_filtered.txt](https://github.com/ukanth/afwall/files/4175111/crash_filtered.txt)

[iptables_on_rules.sh.txt](https://github.com/ukanth/afwall/files/4175113/iptables_on_rules.sh.txt)
[IPv4rules.log](https://github.com/ukanth/afwall/files/4175114/IPv4rules.log)

**Comment by ukanth** [comment]
Have you tried removing custom script ? It seems like captive portal line you have causing the issue by Android.   
> Caused by: android.os.ServiceSpecificException: Remote I/O error

**Comment by ErikSteiner** [comment]
Yes I tried that. That brought me to the point that a custom script leads to a hard crash and a reboot.
I commented some lines especially the captive portal line, but this was not the reason for the crash. It seems more a undefined and custom script related thing in general.

Currently I can avoid reboots by just not using a custom script, but that is a bit off.

**Comment by ukanth** [comment]
Then something wrong with your input script and operating system. I'm not be able to reproduce the same on my devices.

**Comment by ErikSteiner** [comment]
I am not sure. I copied the script to . /data/local/iptables_on_rules.sh.txt with 0755 permissions.

**Comment by ErikSteiner** [comment]
I tested the script without flushing and purging the rules/chains. For now I have no reboots or crashes. I am not sure if this would be called a fix.. 
[iptables_on_rules.sh.txt](https://github.com/ukanth/afwall/files/4190069/iptables_on_rules.sh.txt)
