### ISSUE TITLE
After updating the program from 3.3.1 to 3.4.0 logs were lost

### ISSUE THREAD

**Issue by OmlineEditor** [ukanth/afwall#1088]
I had lags in the version 3.3.1 program and everything worked fine. now there are no logs in the new version 3.4.0.  The log service is enabled. all settings were not changed. logs have disappeared from the net completely. always empty in the old form and in the new form of logs.

This problem occurs because of an error in the log service. your recommendations from the post do not help https://github.com/ukanth/afwall/issues/1067

Please improve and change the way this error is handled. I hope you can fix this problem in the future. I was only helped by reinstalling the app, it is very inconvenient. Fix the problem of falling logs.

**Comment by OmlineEditor** [comment]
another problem. if you clear the logs, they also disappear and no longer appear. the logs are empty again.

**Comment by eggithub** [comment]
I'm having the same issue. Also experienced this issue in 3.3.1. Logs are empty and new logs appearing and all logging is enabled.

Cheers!

**Comment by ghost** [comment]
Had the same issue with new verison, but found a solution:
1) Set logging to NFLOG + Busybox
2) reboot device
3) Set logging to System + log (not sure if order is important, but if unsure try last step: log + System)

After step 3 log is working again, no other way worked for me.

**Comment by OlsiIgitt** [comment]
Hi MokkoBird!
I can't find the option "NFLOG + Busybox"; I will only see under "Log Target" two options "NFLOG" and "LOG". What about "Busybox"? Under the option "Log fetch method" there is only one menu point "System". Under "Binaries" there is an option "BusyBox binary" with two sub-menus "Built-in BusyBox" and "System BusyBox".
Please specify your hint(s).

**Comment by ka223** [comment]
i can confirm this:
I am using 
- AFWall+ 3.4.0 (from F-Droid)
- Android 7.1

AFWall Settings
- Log fetch metod (System/Busybox), both tested
- Log Target (NFLOG) - there is only one option
- Turn on log service +
- Enable show toasts +

I would expect that connection messages are in "View log" and toasts, but the log is empty and toasts are only coming from my kitchen toaster ;)

**Comment by OlsiIgitt** [comment]
thanks for your answer.

> I am using
>    AFWall+ 3.4.0 (from F-Droid)
>    Android 7.1

I am using

    AFWall+ v3.4.0 (from Play Store)
    LineageOS 16.0 (~ Android 9)    Might be that's the difference???


> AFWall Settings
>    Log fetch metod (System/Busybox), both tested
>    Log Target (NFLOG) - there is only one option
>    Turn on log service +
>    Enable show toasts

My settings:

    Log fetch metod (System) - there is only one option!
    Log Target (NFLOG) - there are two options: (NFLOG / LOG) both tested
    Turn on log service +
    Enable show toasts

No connection / block messages in "View log" -> No success!

I only have hope for the next version...

**Comment by ka223** [comment]
@MokkoBird 
I have no log, only NFLOG.

I rebooted changed to busybox, rebooted again and changed to system.
Checked the log, there are a few entries, maybe it worked for a few seconds after reboot.
But logging is definitely not working (again).

EDIT:
I checked now, the log is empty (i did not clear the log).

**Comment by sunilvaltix** [comment]
Which version has this commit?

**Comment by sunilvaltix** [comment]
Hi, this is a pretty nasty bug. We should fix this. Without it, I don't even know if the firewall is doing anything.

Also, its possible that the system is getting rid of the service after some idle time (doze kicking in). Not sure. But it works for some time after disable, enable cycle of the log service, and then stops working after some time.

**Comment by ukanth** [comment]
Duplicate/Related to #1002
