### ISSUE TITLE
menu language

### ISSUE THREAD

**Issue by jonathanhzs** [ukanth/afwall#1089]
In your source code, the Chinese language name is zh and zh-rCN.
 But the corresponding statement in the configuration file is zh-cn, which causes the language display to be incomplete after the software is set.

**Comment by jonathanhzs** [comment]
zh-cn&zh-tw

**Comment by jonathanhzs** [comment]
In your source code, the Chinese language name is zh and zh-rCN.
 But the corresponding statement in the configuration file is zh-cn, which causes the language display to be incomplete after the software is set.

**Comment by ukanth** [comment]
It does point to the right resource in strings.xml 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/165996/91792240-b48ed180-ec32-11ea-907a-448e600f412f.png">

**Comment by ukanth** [comment]
Duplicate of #1143
