### ISSUE TITLE
Default behavior on chains

### ISSUE THREAD

**Issue by mpqo** [ukanth/afwall#109]
I would like to see an option to change the default behavior on chains.

Personally I've added to the custom scipts the following:

$IPTABLES -P INPUT DROP
$IPTABLES -P FORWARD  DROP
$IPTABLES -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

Maybe a GUI for such essential iptables options would be useful for paranoid users.

**Comment by ukanth** [comment]
This can be done via custom scripts.
