### ISSUE TITLE
icons are missing in the logs

### ISSUE THREAD

**Issue by OmlineEditor** [ukanth/afwall#1091]
in the new version  3.4.0 icons are missing. everything looks the same as in this screenshot. only white circles or squares:

![log](https://user-images.githubusercontent.com/13348933/74968544-0e187700-542c-11ea-8586-593e17338e28.jpg)

**Comment by ryosoftware** [comment]
+1

AFWall+ 3.4.0 + AFWall Unlocker 

Device: Xiami Mi 8
OS: Lineage 17.1

![Screenshot_20200420-083420_AFWall+](https://user-images.githubusercontent.com/31618496/79779695-12351800-833b-11ea-93ff-f4b4a6ece006.png)
