### ISSUE TITLE
AndroidOs Data Usage!!

### ISSUE THREAD

**Issue by azR-103** [ukanth/afwall#1094]
Hello how to stop androidOs using data in background.?
Also tested with many diffrent custom roms same issue.
![Screenshot_20200301-205035](https://user-images.githubusercontent.com/27334453/75629680-fe5a1900-5c09-11ea-908f-767ca2866543.png)

**Comment by ukanth** [comment]
It might be depend on what you have allowed in AFWall+ (system apps).
