### ISSUE TITLE
[FEATURE] Block Googles new Bluetooth API (Covid-19)

### ISSUE THREAD

**Issue by Nightwing0815** [ukanth/afwall#1107]
Hey there,

first of all: great work, i like the app!

Is there a possibility, to block google's new (planned) feature, which you can read here?
[click me softly](https://blog.google/inside-google/company-announcements/apple-and-google-partner-covid-19-contact-tracing-technology)
I don't like to share anything, that's the reason, why I#m using your app...

THX in advance & stay safe and healthy,

ToM

**Comment by eku** [comment]
@Nightwing0815 just don't install and run the Covid app(s).
