### ISSUE TITLE
[Bug] Sometimes permits are not properly applied

### ISSUE THREAD

**Issue by gallegonovato** [ukanth/afwall#1109]
Good afternoon:

First of all, thank you for your great application. 

I happen to only be ticking off those applications I'm going to use and I want them to connect to the internet.

But many times after checking the three boxes and hitting apply.  Afwall+ does not work well.  Having to hit it again and then scrolling to update.

Also sometimes when I turn on the phone I don't get the warning about applying rules.  Which it does sometimes if I hit reboot the phone.

Thank you very much for your help and time

**Comment by ukanth** [comment]
Please provide firewall rules + logs when it happens runtime. Seems like some of the rules are failing. I need more details. Otherwise I can't look into it.
