### ISSUE TITLE
Potential Compatibility Issues

### ISSUE THREAD

**Issue by TSUMahmud** [ukanth/afwall#1113]
Hi,
I notice in both classes `com/stericson/rootshell/SanityCheckRootShell.java`  and `com/stericson/roottools/SanityCheckRootTools.java`, you have the following code where you used `StrictMode `class which is introduced in API version = 28. (See this [link](https://developer.android.com/sdk/api_diff/28/changes/changes-summary)).

```
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                .detectDiskReads()
                .detectDiskWrites()
                .detectNetwork()   // or .detectAll() for all detectable problems
                .penaltyLog()
                .build());
        StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .penaltyDeath()
                .build());
```

As your minimunSDK is set to 21, these parts of the program may not execute normally in API < 28.

**Comment by ukanth** [comment]
Both of these classes were never used. As it was bundled with the library, I have kep it.
