### ISSUE TITLE
App keeps applying rules in background

### ISSUE THREAD

**Issue by FejKer** [ukanth/afwall#1115]
Once I enable firewall it applies my desired rules, however when I use my phone I can see it requests superuser permission and applies them once again. It happens every 30 minutes or so. It freezes my network connection for the time the app applies these rules. Is there anything I can do about it?

**Comment by hackel** [comment]
Disable "Active Rules" in Connectivity Preferences.  Can't imagine you'll like the result, though.

**Comment by ukanth** [comment]
It's a behaviour. As suggested above, you can disable "Active Rules".
