### ISSUE TITLE
3.4.0 - WiFi Connected - X & Exclamation Mark Next To WiFi Icon

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#1120]
**Describe the bug**
Wifi connects, but an X and ! exclamation mark appear next to the Wifi icon.

**Firewall Logs**
Please get the log from Menu -> Show Rules -> (menu) Export to storage and attach it here

[IPv4rules.log](https://github.com/ukanth/afwall/files/4940519/IPv4rules.log)

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - Android OS: OxygenOS 9.0.11

**Additional context**
In the overhead, when I slide it down, click on the Wifi icon to enable it, it now appears with an X on the lower right of the icon. Then on the upper right side where the WiFi icon appears next to the battery indicator, the WiFi icon shows an exclamation mark next to it. I can go online, but I'm not understanding why there is an x and ! exclamation mark appearing?

**Comment by n90p** [comment]
Looks like you're blocking the captive portal checks

**Comment by 0pLuS0** [comment]
It would of been nice to have an explanation on how to do all this... :(

Am I suppose to enable or disable the checks?

I've tried

```settings put global captive_portal_detection_enabled 1```
&
```settings put global captive_portal_detection_enabled 0```

I also enabled ```CaptivePortalLogin``` in AFWall+

Nothing works... :(

```This is what my settings show;```

>./adb shell
OnePlus5T:/ $ settings get global captive_portal_mode
1
OnePlus5T:/ $ settings get global captive_portal_server
null
OnePlus5T:/ $ settings get global captive_portal_http_url
null
OnePlus5T:/ $ settings get global captive_portal_https_url
null
OnePlus5T:/ $ settings get global captive_portal_fallback_url
null
OnePlus5T:/ $ settings get global captive_portal_detection_enabled 
1

Should I change them to this?

settings put global captive_portal_mode 0
settings put global captive_portal_server 127.0.0.1
settings put global captive_portal_http_url localhost
settings put global captive_portal_https_url localhost
settings put global captive_portal_fallback_url localhost
settings put global captive_portal_detection_enabled 0

THANKS

**Comment by n90p** [comment]
`captive_portal_detection_enabled 0` is for Android < 7
Use `captive_portal_mode 0`

**Comment by 0pLuS0** [comment]
Ahh ok, I just ran it, and it seems to be working...

THANKS
