### ISSUE TITLE
3.4.0 - Logs Show No Image?

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#1121]
**Describe the bug**
When viewing the logs, some of the entries show no icons.

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - Android OS: OxygenOS 9.0.11

**Additional context**
When I used AFWall+ in the Oreo version of OxygenOS and Oreo ROMS, if I remember correctly all the entries showed various icons, as they related to the apps, etc...

I've attached a screen shot of what I now typically see.

![AFWall+_Logs](https://user-images.githubusercontent.com/36190223/87863050-7cfbec80-c946-11ea-90c0-ce2af75f6b43.jpg)

**Comment by seedaeng** [comment]
I have exactly the same although not really an issue for me.
Redmi Note 8
Miui 11.0.9
Android 9

**Comment by seedaeng** [comment]
> I have exactly the same although not really an issue for me.
> Redmi Note 8
> Miui 11.0.9
> Android 9

I note it was also raised as an issue in  #1091 back in February
