### ISSUE TITLE
[Question] 3.4.0 - Can't Make WiFi Calls - How?

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#1122]
**Describe the issue**
I can't figure out what to enable in AFWall+ to make Wifi calls

**Firewall Logs**
Please get the log from Menu -> Show Rules -> (menu) Export to storage and attach it here

[IPv4rules.log](https://github.com/ukanth/afwall/files/4944779/IPv4rules.log)

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - Android OS: OxygenOS 9.0.11

**Additional context**
I've tried allowing both the phone and the phone entry that shows the various services and protocols in AFWall+ but I still can't make a Wifi call.

**Comment by 0pLuS0** [comment]
I am having to many issues with AFWall+ I give up using it, it's also been almost 2 weeks since making this issue report, with no reply from anyone to help resolve this.

With all due respect to the developer, I greatly appreciate your efforts, but since PIE came out AFWall is really bad, constant problems with connectivity issues, I also made issue reports about these too, constantly can't connect to the PlayStore and with Chrome online, I always had to disable and re enable AFWall+

For now I'm not using this....

**Comment by 0pLuS0** [comment]
@ukanth 

Hi, I know you must be busy, but any help would be appreciated.

THANKS

**Comment by ukanth** [comment]
Have you enabled logs in AFWall+ ? That should show the denied entries.
