### ISSUE TITLE
[ISSUE] Afwall is not listing Jellyfin

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#1126]
**Describe the bug**
It seems like Jellyfin is not listed in the app list after it is installed. Refreshing or searching does not produce any results, and I went through the whole list one of by one and I did nto see the icon either.

**Smartphone (please complete the following information):**
Samsung,  Havoc OS Android 9

**Additional context**
You can download the apk from here.

https://repo.jellyfin.org/releases/client/android/

**Comment by ukanth** [comment]
This app does not have "android.permission.INTERNET". AFWall+ lists applications with that permission. I did install the app and checked it's permissions. It does not have the permission.

Ref:
https://github.com/jellyfin/jellyfin-android/blob/c02436164a932c8e12729414301dfc98da6684ce/src/NativeShell/plugin.xml


I will add a preference to list the apps without this permission.
