### ISSUE TITLE
How to enable iptables logging to custom logfile?

### ISSUE THREAD

**Issue by cmonty14** [ukanth/afwall#1128]
Hello,
for analyzing things that are not working as expected with AFWall+ I want to enable logging to a custom logfile.

My intention is to add this
```
iptables -N LOGGING
iptables -A OUTPUT -j LOGGING
iptables -A LOGGING -m limit --limit 2/min -j LOG --log-prefix "IPTables-Dropped: " --log-level 4
iptables -A LOGGING -j DROP
```
add the bottom of a custom script file.

However I don't understand how to enable logging to a custom logfile.
Can you please advise.

THX

**Comment by ukanth** [comment]
It's usually logged at system level.  you can use `dmesg` to get it.
