### ISSUE TITLE
[FEATURE] TTL Spoof on Device Up

### ISSUE THREAD

**Issue by OdinVex** [ukanth/afwall#1131]
I'd love to be able to specify a rule or TTL spoof on a specific interface (any tether interface) when they're activated. My interface is swlan0 and I'd like to set the device interface to not decriment hops.

*Edit* Donate version.

**Comment by n90p** [comment]
You can modify ttl with custom script:
`$IPTABLES -t mangle -A FORWARD -i wlan0 -j TTL --ttl-inc 1`

Make sure your kernel supports TTL modifying

**Comment by OdinVex** [comment]
> You can modify ttl with custom script:
> `$IPTABLES -t mangle -A FORWARD -i wlan0 -j TTL --ttl-inc 1`
> 
> Make sure your kernel supports TTL modifying

Rooted, supports modifying ttl too. Kinda hoped TTL spoofing could just be added as an easy option instead but alright.
