### ISSUE TITLE
[ISSUE]Chinese language menu still wrong

### ISSUE THREAD

**Issue by jonathanhzs** [ukanth/afwall#1143]
**Describe the bug**

**Firewall Logs**
Please get the log from Menu -> Show Rules -> (menu) Export to storage and attach it here

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung]g9008w
 - Android OS: [e.g. LOS 15.1 ]los15.1

**Additional context**

**Comment by jonathanhzs** [comment]
9.9 new builder

**Comment by leoxxx** [comment]
Still need edit preferences file in 3.5.1.

**Comment by ukanth** [comment]
It will be fixed in next version.
