### ISSUE TITLE
[ISSUE]Attempt to view log when it has any entries in it causes FC 

### ISSUE THREAD

**Issue by irontechmonkey** [ukanth/afwall#1144]
**Describe the bug**
Possibly identical to https://github.com/ukanth/afwall/issues/1071

- Attempt to view log when it has any entries in it causes FC (which in turn makes it impossible to test for a few other issues).
- Log can be viewed when empty but if it has any entries then clearing it requires a few extra steps. 
-To clear log: Disable logging > open log and clear it > enable logging again.
- Attached catlog spans the following:
- Naked Browser Pro is run and blocked as expected > return to AF wall > attempt to view log = FC.
- Logging done on Android Oreo/LOS 15 w/Magisk. Reproduced on another device as well.

**Firewall Logs** captured today from same device in second test under same scenario.

[IPv4rules.log](https://github.com/ukanth/afwall/files/5214265/IPv4rules.log)

catlog (captured yesterday while testing)
[AfwallLogFC2020-09-10-21-21-53.txt](https://github.com/ukanth/afwall/files/5214266/AfwallLogFC2020-09-10-21-21-53.txt)

**Smartphone (please complete the following information):**
 - Device: Moto Z Griffin
 - Android Oreo: LOS 15.1
- Zfwall+ 3.5.0-BETA-1

**Additional context**
The other toast FC and logging fail after FC issues cannot be tested until this is cleared.

**Comment by ukanth** [comment]
Duplicate of #1071

**Comment by irontechmonkey** [comment]
fixed
