### ISSUE TITLE
full version

### ISSUE THREAD

**Issue by opa-rudi** [ukanth/afwall#1146]
Where can I get the full version? I do not have a google account. I want to be notified when an app connects to a specific ip/domain (like little snitch) and want to have a dialog where I can simply allow or deny for specific network. Is that possible with the full version?

**Comment by angela-d** [comment]
Donation link at the [very bottom](https://github.com/ukanth/afwall) of the readme.

I don't use google either, I donated this way and emailed ukanth at the seller paypal address after to let him know I would like a copy of the unlocker.
