### ISSUE TITLE
LTE does not turn back on unless device is restarted

### ISSUE THREAD

**Issue by yurihentai** [ukanth/afwall#1148]
**Describe the bug**
When mobile data is disabled or connection with mobile data on is lost, it won't turn back on, unless the device is restarted. The LTE icon doesn't show and no connection can be made via mobile data.

**Firewall Logs**
It doesn't show any long data, but sometimes it shows `ICMP` and `unknown`, sometimes `kernel`. I tried allowing kernel but it didn't fix the problem.

...tried it just now again, it doesn't give any log data. Strange.

**Smartphone (please complete the following information):**
 - Oneplus 6
 - LineageOS 17.1
- AFWall+ 3.4.0 from F-Droid

**Additional context**
I have mobile data (LTE) disabled unless I need it since I have limited data, and I have afwall+ on whitelist/allow selected mode. At first I thought it was a LineageOS problem since this never happened on any other device, but I tried rebooting the phone with afwall+ disabled, and I was able to freely enable and disable mobile data without problems. My guess is that it must be some firewall rule that I didn't allow, but the logs from the gui don't tell me which one it could possibly be.

**Comment by ukanth** [comment]
Kindly share details from  menu->show rules->export for both ipv4/ipv6 to see more details.
