### ISSUE TITLE
[ISSUE] Two miner bugs

### ISSUE THREAD

**Issue by peter099** [ukanth/afwall#1151]
I have LineageOS 14 on my Moto X Play and installed AFWall+ from F-Droid. The first issue i have is a notification icon that stays always visible in status bar. And the second issue i have is in Evie launcher the AFWall+ icon is not showing, it shows a generic icon instead.  

Edit: The second issue is related to Evie launcher, not to AFWall+.

**Comment by ukanth** [comment]
Notification persistent can be disable using default android behaviour. Hence closing this issue.
