### ISSUE TITLE
[ISSUE] App not listed

### ISSUE THREAD

**Issue by cyko69** [ukanth/afwall#1152]
**Describe the bug**
The app 'Muzei", latest f-droid build, doesn't show up in AFWall.

**Firewall Logs**
[IPv4rules.log](https://github.com/ukanth/afwall/files/5393872/IPv4rules.log)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 5 (whyred)
 - Android OS: LOS 17.1

**Additional context**
Reinstalled Muzei and cleared AFWall cache, still not showing up.

**Comment by JonnyTech** [comment]
If the app does not request network access then it will not apear on the list. As I understand it, muzei is a wallpaper manager, not a wallpaper downloader, so it does not need nor request network access.

![img_8](https://user-images.githubusercontent.com/3584732/96331278-f09bbb80-1053-11eb-925e-0c44345d185c.jpg)

If you install any of the muzei plugins then you should see them listed.

![img_11](https://user-images.githubusercontent.com/3584732/96331416-db735c80-1054-11eb-8d79-8f7612852c6e.jpg)

**Comment by cyko69** [comment]
Ok, then I think its an app issue because muzei itself has "featured art, a new painting every day" build in but you cant browse more than the preinstalled picture.
Thanks for looking into it
