### ISSUE TITLE
can not enable firewall after update 350 beta1

### ISSUE THREAD

**Issue by nutpantz** [ukanth/afwall#1158]
downloaded from github uninstalled 340 donate installed 350b1 activated exposed module and rebooted
stared afwall granted root and rules applied with sucess
enable firefox mobile rule >  rules fail  firewall disabled
enable firewall > rules fail
disable firefox , enable firewall >rules fail..
rules fail for everthing attemped after
no logs either

**Smartphone (please complete the following information):**
 - Device: lenovo pb2-650y
kernel 3.18.19
xposed module active 
 - Android OS: android 6

340 working fine for the most part
update to 350 and everything seems fine at first run and enableing of fire wall
then every change after applying rules fail and firewall is disabled.
logs turn on but do not showup. tried both built in and system for iptables and busybox.

**Comment by ukanth** [comment]
Please provide logcat along with firewall rules. Otherwise I can't fix.
