### ISSUE TITLE
[FEATURE] Merge Wifi and Data settings

### ISSUE THREAD

**Issue by Dakkaron** [ukanth/afwall#1163]
**Is your feature request related to a problem? Please describe.**
I understand why there is the option to block wifi and mobile data separately. But for my use case this is rather worthless. I have a data plan that is large enough that I don't really care whether an app uses wifi or mobile data.
But whenever my connection switches, Afwall needs to switch IP tables rules, which takes about a minute. So especially when the Wifi is flaky, my phone spends most of its time applying rules and thus not allowing internet.
What's worse though is that every time rules are applied there is a chance for that process failing and in this case apps that should never be allowed to connect to the internet are now free to do so.

This sucks, because that is the main use case that I use Afwall for: making sure that specific apps never see the internet. Because of that I already use the whitelist feature.

**Describe the solution you'd like**
I am not sure if it is possible with iptables, but if possible I'd like to have a setting that does away with the wifi/data split and just applies the rules globally/interface independent. That way, there would be no need to apply rules whenever wifi is connected/disconnected.

And it would save me from having to press two buttons to enable wifi for an app ;)

**Describe alternatives you've considered**
Make aplying really fast and stable? But I guess that's a lot more work.

**Comment by m-rey** [comment]
> Make aplying really fast and stable?

This may be theoretically possible: AFWall+ could try to generate and only apply the diff of the configs when switching. That way, if there are (hardly) no differences between both rule sets, it would apply quickly.

**Comment by ukanth** [comment]
Unfortunately I can't add this feature. AFWall+ already provides tons of features. This will make users more confused and I will end up supporting/explaining users about this behaviour if implemented. I would rather keep it separate.

**Comment by Dakkaron** [comment]
I understand that. What about this:

UI/UX stays the way it is. But the app checks for rules that are the same on all interfaces and applys them system-wide instead of interface specific.

**Comment by ukanth** [comment]
AFWall+ 3.5.0 has a feature(currently in beta) which has default action for both whitelist/blacklist for apps right after installation.
