### ISSUE TITLE
[ISSUE] 3.5.0-Beta-1 Export failed on LOS 17.1 

### ISSUE THREAD

**Issue by vsatmydynipnet** [ukanth/afwall#1165]
**Describe the bug**
I try to export Rules and/or Rules and Settings -> Results in Export failed withotu further info.

**Smartphone (please complete the following information):**
 - Device: Samsung A5 2017
 - Android OS:LOS 17.1, nogapps, Storage Access allowed

**Additional context**
It simply fails. So I am unable to export and transfer to another device.

Thank you for this great peace of Software!

**Comment by didierm** [comment]
Confirmed with 3.5.0-BETA-1 and "AFWall+ Unlocker" (which I bought today in addition to the earlier acquired Donate version, in order to be able to import/export dat with the Beta version, which I require because of https://github.com/ukanth/afwall/pull/1139).

Storage access is allowed, AFW runs with superuser rights.

straces (confirmed by logcat) : 

* Import : 
`[pid 26241] openat(AT_FDCWD, "/storage/emulated/0/afwall", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 EACCES (Permission denied)`

* Export : 
`[pid 26241] openat(AT_FDCWD, "/storage/emulated/0/afwall/afwall-backup-all-2020-12-26-20-38-31.json", O_WRONLY|O_CREAT|O_TRUNC, 0600) = -1 EACCES (Permission denied)`

Import/export functionality is essential during testing.

**Comment by didierm** [comment]
@vsatmydynipnet Label should probably be [bug] instead of [review] .

**Comment by didierm** [comment]
> @vsatmydynipnet Label should probably be [bug] instead of [review] .

Apologies, changing labels is probably at the privilege of the project owner.

**Comment by didierm** [comment]
It seems AFW 3.5.0-BETA-1 fails at any operation accessing internal storage.
Trying to export the IPtables rules yields : 
```
E AFWall  : /storage/emulated/0/afwall/IPv4rules.log: open failed: EACCES (Permission denied)
E AFWall  : java.io.FileNotFoundException: /storage/emulated/0/afwall/IPv4rules.log: open failed: EACCES (Permission denied)
E AFWall  : 	at libcore.io.IoBridge.open(IoBridge.java:496)
E AFWall  : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
E AFWall  : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
E AFWall  : 	at dev.ukanth.ufirewall.activity.DataDumpActivity$Task.doInBackground(DataDumpActivity.java:212)
E AFWall  : 	at dev.ukanth.ufirewall.activity.DataDumpActivity$Task.doInBackground(DataDumpActivity.java:188)
E AFWall  : 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E AFWall  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E AFWall  : 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E AFWall  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E AFWall  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E AFWall  : 	at java.lang.Thread.run(Thread.java:919)
E AFWall  : Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
E AFWall  : 	at libcore.io.Linux.open(Native Method)
E AFWall  : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E AFWall  : 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E AFWall  : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E AFWall  : 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
E AFWall  : 	at libcore.io.IoBridge.open(IoBridge.java:482)
E AFWall  : 	... 10 more
```

With the _/storage/emulated/0/afwall/_ folder temporarily removed : 
```
E AFWall  : /storage/emulated/0/afwall/IPv4rules.log: open failed: ENOENT (No such file or directory)
E AFWall  : java.io.FileNotFoundException: /storage/emulated/0/afwall/IPv4rules.log: open failed: ENOENT (No such file or directory)
E AFWall  : 	at libcore.io.IoBridge.open(IoBridge.java:496)
E AFWall  : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
E AFWall  : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
E AFWall  : 	at dev.ukanth.ufirewall.activity.DataDumpActivity$Task.doInBackground(DataDumpActivity.java:212)
E AFWall  : 	at dev.ukanth.ufirewall.activity.DataDumpActivity$Task.doInBackground(DataDumpActivity.java:188)
E AFWall  : 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E AFWall  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E AFWall  : 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E AFWall  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E AFWall  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E AFWall  : 	at java.lang.Thread.run(Thread.java:919)
E AFWall  : Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E AFWall  : 	at libcore.io.Linux.open(Native Method)
E AFWall  : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E AFWall  : 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E AFWall  : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E AFWall  : 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
E AFWall  : 	at libcore.io.IoBridge.open(IoBridge.java:482)
E AFWall  : 	... 10 more
```

**Comment by ukanth** [comment]
Have you tried on someother device ? It seems the storage is readonly.

**Comment by didierm** [comment]
Not tried on another device, but works perfectly fine with v3.4.0 (to which I have temporarily reverted).

**Comment by de-es** [comment]
Same here with 3.5.0-BETA-1, at least on one device. It's working on Swift (Wileyfox), but not on Lake (Moto G7+). Both running an uptodate LOS 17.1, exact same permissions and settings. 3.4.0 is working fine on Lake.

**Comment by ukanth** [comment]
This issue is fixed, will be available in the next beta.
