### ISSUE TITLE
[ISSUE] Web connection broken after upgrade

### ISSUE THREAD

**Issue by UltraBlackLinux** [ukanth/afwall#1166]
**Describe the bug**
My whole web connection broke after upgrading Termux, it won't work anymore, even though everything is granted.

Only fixable via clearing the app's data.

**Firewall Logs**
https://paste.ee/p/s7GbA
(Can't attach file, thanks github)

**Smartphone (please complete the following information):**
 - Device: cheryl
 - Android OS: LOS 17.1

**Comment by ukanth** [comment]
Firewall never activated. Seems like you haven't selected any apps ?

**Comment by UltraBlackLinux** [comment]
@ukanth I have almost all my apps selected.
