### ISSUE TITLE
[ISSUE] Work profile applications (Dual Apps Support) are incorrectly filtered

### ISSUE THREAD

**Issue by didierm** [ukanth/afwall#1168]
**Describe the bug**
With Dual App support enabled : 
* user applications from the Work profile are shown in the [System] filter ;
* system applications from the Work profile are shown in the [User] filter ;

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi9T
 - Android OS: LOS 17.1
 - Insular (Island clone) 5.1.2-42172be8
 - AFW 3.5.0-BETA-1
 
**Additional context**
Screenshots : 
![Screenshot_20201226-234337_AFWall+](https://user-images.githubusercontent.com/989004/103160438-70bd6a80-47d5-11eb-9ba1-dd89455ec595.png)
![Screenshot_20201226-234518_AFWall+](https://user-images.githubusercontent.com/989004/103160440-7450f180-47d5-11eb-8902-4dcd6a7015f9.png)

**Comment by didierm** [comment]
This issue occurs with both versions 3.4.0 and 3.5.0-BETA-1.

**Comment by ukanth** [comment]
Thanks. Fixed.
