### ISSUE TITLE
DROP instead of REJECT

### ISSUE THREAD

**Issue by EntropySmoke** [ukanth/afwall#1171]
**Is your feature request related to a problem? Please describe.**
For stealth reasons, it is best to use DROP on some packets instead of using REJECT. I did see the info that the author disagrees, but I bet many would love to a DROP feature.

**Describe the solution you'd like**
Provide a selection to choose between blocking via REJECT or blocking via DROP

**Describe alternatives you've considered**
Writing my own rules, which is painful for a Linux newbie...

**Comment by ukanth** [comment]
I was thinking about this. Sorry, but decided not to add support for DROP for many reasons which was discussed earlier.
