### ISSUE TITLE
[ISSUE] Default sort ("By name") is reset at approx. 50% of apps list

### ISSUE THREAD

**Issue by didierm** [ukanth/afwall#1172]
**Describe the bug**
Applying the default sort "By name (default)" results in a list of apps, where the sort order has been reset at approx. the middle of the list.

**Smartphone (please complete the following information):**
 - Android OS: LOS 17.1
 - AFWall+ 3.4.0 + Donate key

**Additional context**
I am using a Work profile (feature enabled in "Preferences > Experimental > Dual Apps Support").
Having the apps grouped together by Name is essential for enabling/disabling network access to primay/work profiles.
This is impossible, due to the sort being reset at approx. 50% of the list (see screenshot).

![image](https://user-images.githubusercontent.com/989004/103551347-82c09c80-4eaa-11eb-92da-3b31381f56dc.png)

**Comment by ukanth** [comment]
This is behaviour of AFWall+. Selected apps will be shown first, followed by non-selected apps. I don't intent to change it.
