### ISSUE TITLE
[ISSUE] After installing a new application, AFWall does not block it.

### ISSUE THREAD

**Issue by Nico207** [ukanth/afwall#1175]
**Describe the bug**
After installing a new application, AFWall does not block it.

**Firewall Logs**
[IPv4rules.log](https://github.com/ukanth/afwall/files/5826347/IPv4rules.log)

**Smartphone :**
 - Device: Xiaomi POCO F1
 - Android OS: LineageOS 17.1 (Android 10)

**Additional context**
AFWall enabled, log enabled, no custom script, IPv6 support disabled, su allowed to AFWall by Magisk v21.2 (app v 8.0.7)

In AFWall, if I try to "Apply" the rules, the new application continues to have access to internet.
I must reboot the phone to block it correctly. 

Here's a screen record of the problem in which I show the state of AFWall, then I install the application "Firefox Klar", which by default should not have access to the internet. But after the installation, the application still manages to connect to the Internet.
[
https://drop.infini.fr/recording_20210117_000704.mp4](https://drop.infini.fr/r/Ma6J7AAvSg#5/zL5dcv+uKsTbOjzaf0u/zy1AjURW4Zp4ILJvwMC6g=)

**Comment by ukanth** [comment]
Have you given permission to this app previously ? there was a bug in older version where it didnot clean up the permission when you uninstall it. 

Try do a clean install of AFWall+ and try to reproduct it and if you continue to have this bug, kindly report it as above.

**Comment by Nico207** [comment]
`Have you given permission to this app previously ?`
No, it's a first install

I tried with some other apps, and I can't reproduce this...
Another interesting fact : in this app, if I chose Google or Wikipedia as search engine, connection works (AFWall activated, this app not allowed). BUT, if I choose, DuckDuckGo or Qwant... connection doesn't work. 

So, maybe the problem is not AFWall...

**Comment by ukanth** [comment]
Thanks. Feel free to reopen it when you encounted this issue again.

**Comment by Nico207** [comment]
Hi ! 
I just encountered the problem again...
The application is NewPipe(debugVersion)
https://github.com/TeamNewPipe/NewPipe/files/6251337/app-debug.zip

Once installed, at the first launch (application not checked in AFWall), I can still access the network.

I thought I had a lead: I blocked WebView [10126] and WebBrowser [10120], but it did not change anything. 
I have a doubt... can an application use another Android component to access the network ?
How to be sure that the application is blocked or authorized (Currently, log doesn't seem to work properly) ?
