### ISSUE TITLE
Afwall keeps on asking for root permissions

### ISSUE THREAD

**Issue by dnd66** [ukanth/afwall#1177]
Hey everyone

Why does afwall keep on requesting new root permissions when nothing has been changed? 

E.g. on 6 February afwall requested 7 times root permissions within 30 minutes (according to this magisk screenshot). 

![Magisk Screenshot](https://user-images.githubusercontent.com/56778274/107287276-02212d00-6a62-11eb-8f1b-e8db1c6fd4b4.JPG)

At that time I was sleeping and not using the phone. Is this a normal behaviour?

If so, what are the causes that afwall automatically requests root when the phone is not being used?

Any inputs are appreciated!

**Comment by ukanth** [comment]
Frequent change in network enables AFWall+ to reapply rules. You can disable it under preferences-> Rules/Connectivity- > Active Rules.
