### ISSUE TITLE
[ISSUE] Afwall doesn't found all existing system apps, some sys-apps still steal network data

### ISSUE THREAD

**Issue by ghostplant** [ukanth/afwall#1178]
**Describe the bug**
I'm using the latest released afwall 3.4.0, and have granted root access to it.
I just choose "Allow selected apps" and uncheck all apps the Afwall can find, so that I expect to disable the network acess for all applications.
I also verified that any of apps listed in this managing list, and they can't get access to network as expected.
But I found a few system apps not listed in this list, but they can still steal the network data, these system apps are located at typical place like "/system/app/MzSecurity/MzSecurity.apk".

How to fix it to ensure all apps/sys-apps not able to get access to the network data?

**Smartphone (please complete the following information):**
 - Device: MZNote6 (rooted)
 - Android OS: 6.0

**Comment by ukanth** [comment]
Apps without INTERNET permissions can not use network. If you think if the app has INTERNET permission and still can access network, please provide more details like logcat/firewall rules etc..

**Comment by ghostplant** [comment]
I don't know how to get that log, but can I assume that afwall is booted after some system apps so that they have chance to use the network before the block?

**Comment by ukanth** [comment]
You can disable using Experimental preference call "Fix startup data leak". This will add a init.d script with default DENY for all the apps including system apps.
