### ISSUE TITLE
[ISSUE] Fails to build (with fix)

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#1183]
### Issue: Building AFWall+ with default settings doesn't work
gradle errors out about DBFlow not being found.

New maintainer as said here: https://github.com/agrosner/DBFlow
**Fix**
`sed -i "s/Raizlabs/agrosner/g" app/settings.gradle`

### Issue: Then complains about AndroidX packages not being enabled.

**Fix:**
Create app/gradle.properties and put
`android.useAndroidX=true
android.enableJetifier=true`

I guess I could have sent a pr or whatever but I've never done that before

**Comment by ukanth** [comment]
Issue has been resolved at jitpack.io level. Builds are passing.
