### ISSUE TITLE
AFWall+ (Donate) v3.5.0 - No internet access when Private DNS is enabled & No Logging

### ISSUE THREAD

**Issue by OswaldBoelcke** [ukanth/afwall#1191]
This is the follow on ticket of [this post](https://forum.xda-developers.com/t/5-0-root-3-5-0-afwall-iptables-firewall-10-apr-2021.1957231/post-84847015) on XDA.
Since 2016 when I purchased AFWall+ (Donate) I'm an absolutely satisfied user, and AFWall+ is one of the most important applications in my app port folio. Actually, I wouldn't use any Android device without AFWall+!
Currently running on a Samsung Galaxy S8+ (SM-G955F) with LOS 16.0, Magisk v22.1 and EdXposed.

Beginning of the week I've upgraded from v3.4.0 to v3.5.0 when the update for AFWall+ (Donate) was made available at Google PS.
Different to v3.4.0 that simply did run perfectly I experience (like some other members above) following issues: 

It seems to be absolutely incompatible with Private DNS, which I used to always have enabled. As soon as Private DNS is enabled (and it doesn't matter if I reapply the rules or disable and reenable the firewall) I don't have internet access with enabled firewall, or probably more precisely it seems to me that the DNS resolution always fails. My current work-around obviously is to run the device with disabled Private DNS.
After a change of connectivity (e.g. WiFi to mobile data or vice versa) I can't any longer access the internet. In settings, "Apply firewall rules on every connectivity change" is activated. I can't say if it really occurs; it might be that again the DNS resolution is the problem. To reapply the rules doesn't fix the issue, I need to disable and re-enable the firewall.
Last but not least I can't write any logs. Log service is enabled in settings, and I tried both log targets. However, none are recorded or written.

Attached logcat was taken while switching through different networks, AFWall rules re-applying and firewall disabled and re-enabled.
However, when I terminated the logcat I got a Matlog notification that the log was too large and had been shortened to 10,000 lines. I hope that the necessary information are nevertheless incorporated. For privacy reasons, I've "xxx"-ed very few information.

The attached screenshots are supposed to show that log service is enabled but none is recorded.
[2021-04-16-14-11-16.txt](https://github.com/ukanth/afwall/files/6326488/2021-04-16-14-11-16.txt)
![Screenshot_20210416-142134_AFWall+_(Spenden)](https://user-images.githubusercontent.com/21972717/115053547-c6299e80-9ece-11eb-933c-4cb64f9e60f5.png)
![Screenshot_20210416-142147_AFWall+_(Spenden)](https://user-images.githubusercontent.com/21972717/115053562-c9bd2580-9ece-11eb-8e7e-fb5e06e0b8d0.png)

**Comment by ukanth** [comment]
Can you please export show rules-> export when you don't get connection ?

**Comment by OswaldBoelcke** [comment]
@ukanth  Here we go... What I did, and I attach some screenshots to follow:
- I had connectivity with disabled Private DNS.
- Enabled Private DNS.
- Checked connectivity via browser; no internet access (or bad DNS resolution).
- Exported "rules" (1st of the two json-files)
- Disabled Private DNS.
- Checked again  connectivity via browser; internet access established.
- Exported "rules" (2nd of the 2 json's) although I couldn't see any difference to the first one.

I've meanwhile extracted v3.4.0 from my backup. Please advise if you don't require my support any longer because then I'm going to revert to 3.4.0. Thank you very much but especially for looking into my issue.

Remark: Github didn't allow to upload json-files i.e. I zipped both into one archive.
[AFWall Rules.zip](https://github.com/ukanth/afwall/files/6328730/AFWall.Rules.zip)
![Screenshot_20210417-081708_Einstellungen](https://user-images.githubusercontent.com/21972717/115104380-7dfa9280-9f47-11eb-8edb-e4a16d2c68c2.png)
![Screenshot_20210417-081720_Einstellungen](https://user-images.githubusercontent.com/21972717/115104382-82bf4680-9f47-11eb-806c-342dc9593386.png)
![Screenshot_20210417-081746_FOSS_Browser](https://user-images.githubusercontent.com/21972717/115104387-8652cd80-9f47-11eb-8161-00b60320684c.png)
![Screenshot_20210417-081920_Einstellungen](https://user-images.githubusercontent.com/21972717/115104389-8b178180-9f47-11eb-80a6-7aa4bdaf588c.png)
![Screenshot_20210417-081933_FOSS_Browser](https://user-images.githubusercontent.com/21972717/115104394-8eab0880-9f47-11eb-9177-04700d33c721.png)

**Comment by ukanth** [comment]
I mentioned that in XDA. after enabling private DNS, you will have to reapply the rules in afwall. It might take few seconds to reflect the change ? have you tried it ?

**Comment by OswaldBoelcke** [comment]
> I mentioned that in XDA. after enabling private DNS, you will have to reapply the rules in afwall. It might take few seconds to reflect the change ? have you tried it ?

Sorry, that was my bad. And affirmative, after enabling of Private DNS and re-applying of the rules connectivity was established after about 10 - 15 seconds. 
I guess my idiotic ticket can be closed. Sorry that I've wasted your time.

Stay safe and stay healthy!
Regards

**Comment by ukanth** [comment]
No problem at all. I'm here to help. This should be fixed in the next update. Also for the logging these steps helped few users. Can you try this https://forum.xda-developers.com/t/5-0-root-3-5-0-afwall-iptables-firewall-10-apr-2021.1957231/post-84817761 ?

**Comment by Nico207** [comment]
> Also for the logging these steps helped few users. Can you try this https://forum.xda-developers.com/t/5-0-root-3-5-0-afwall-iptables-firewall-10-apr-2021.1957231/post-84817761 ?

I confirm this work for me.  
Here are the steps given by @asripath  in the forum thread:  
> what worked for me to resolve the issue
> - changed log target to => `NFLOG`
> - in binaries option changed
>    - BusyBox to => `System`
>    - Iptable to => `Built-in`
> - turned log service `Off` and then `On`
> - in view log, changed logging to => `New style`
> - boot to recovery and clear cache
> 
> After reboot to system logging started working...
