### ISSUE TITLE
No internet access for allowed apps when Wifi is activated in white list mode (v.3.5.0)

### ISSUE THREAD

**Issue by geronimoge** [ukanth/afwall#1200]
**Describe the bug**
I am using the white list mode and AFWall+ v3.5.0 from F-Droid with donate functions.
Since the update to v3.5.0 some apps are sometimes able to get WiFi, sometimes not.
Within the logs I see that WiFi access is getting blocked for apps even though I allowed it for those apps (see **Additional context**).
Mobile data on the other hand seems to be working as expected.

**Firewall Logs**
[IPv4rules.log](https://github.com/ukanth/afwall/files/6349274/IPv4rules.log)

**Smartphone (please complete the following information):**
 - Device:Samsung S9
 - Android OS: https://forum.xda-developers.com/t/rom-s9-s9-unofficial-lineageos-18-1-21-03-2021.4203777/

**Additional context**
As an example here you see the behaviour for apps running as root
![root](https://user-images.githubusercontent.com/42838903/115522471-6c3d2600-a28c-11eb-95a4-266e3500ca4b.jpg)
![root_log](https://user-images.githubusercontent.com/42838903/115522522-77905180-a28c-11eb-9f62-20ecbe453904.jpg)

**Comment by ukanth** [comment]
what is the source/target ipaddress in those denied requests ? Because from  the rule what I can see is local ip packets might be getting blocked by AFwall+ as configured.

I can see LAN packets getting dropped

```
Chain afwall-wifi-lan (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   ........
   89  5828 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0         

```

**Comment by geronimoge** [comment]
As an example you can find the log for "Apps running as root" here.
I now see, that it's sometimes/always getting blocked when using mobile data as well.
[log_dump.log](https://github.com/ukanth/afwall/files/6349897/log_dump.log)

**Comment by geronimoge** [comment]
As additional information; I had these settings for all older versions of AFWall+ and that was always working.

My settings are:

- using white list mode
- having activated the checkboxes in the app list, when I want to give them access to the internet (see screenshot from first post)
- having no custom script
- preferences see following screenshots
![IMG_20210421_115852](https://user-images.githubusercontent.com/42838903/115536442-17a0a780-a29a-11eb-8f8a-8e7e20f82316.jpg)
![IMG_20210421_115907](https://user-images.githubusercontent.com/42838903/115536446-18d1d480-a29a-11eb-87a3-f91eb203f014.jpg)
![IMG_20210421_115929](https://user-images.githubusercontent.com/42838903/115536449-196a6b00-a29a-11eb-8498-9035a4d75ce2.jpg)
![IMG_20210421_115954](https://user-images.githubusercontent.com/42838903/115536452-1a030180-a29a-11eb-9b22-8bf385562660.jpg)
![IMG_20210421_120021](https://user-images.githubusercontent.com/42838903/115536455-1a9b9800-a29a-11eb-8bdd-e810e614ee67.jpg)
![IMG_20210421_120038](https://user-images.githubusercontent.com/42838903/115536458-1b342e80-a29a-11eb-8d25-d8aa915e129f.jpg)
![IMG_20210421_120101](https://user-images.githubusercontent.com/42838903/115536462-1bccc500-a29a-11eb-8a0f-16b071d605de.jpg)
![IMG_20210421_120127](https://user-images.githubusercontent.com/42838903/115536467-1c655b80-a29a-11eb-895a-80027e1a9fab.jpg)
![IMG_20210421_120149](https://user-images.githubusercontent.com/42838903/115536470-1d968880-a29a-11eb-8aa7-6640bf187c9c.jpg)

**Comment by ukanth** [comment]
why disable netd ? do you have dns proxy ?

**Comment by geronimoge** [comment]
I was following [this (german) tutorial](https://www.kuketz-blog.de/afwall-digitaler-tuervorsteher-take-back-control-teil4/) without using custom scripts.
There it is justified as follows (automatic translation):
_"So that AFWall+ can assign all DNS queries to the corresponding apps cleanly, you should disable DNS via netd"_

Back to my case: Until the update to v3.5.0 it was working without any problems.
Perhaps I should also say, that I use a Pi-hole.

[Here someone had a similar problem in 2019](https://www.mi-forum.net/threads/probleme-mit-afwall-android-10.8669/).
His solution (automatic translation):
"Uninstall AfWall+ and [reset the network in the settings](https://techwiser.com/fix-android-connected-to-wifi-but-no-internet/). Safe is safe.
Then disable netd under AfWall+ and allow the APP-UID 1000 (Unfortunately a heap of wood, which then goes through there).
Buffering this can then be done if you then [activate the server DNS as here](https://www.zdnet.de/88355345/miui-10-private-dns-aktivieren/).
Look for yourselves what. [Here are also still some](https://www.kuketz-blog.de/empfehlungsecke/).
Then in the "secret" menu insert a DNS server.
The Internet should still go and thus be a tick more anonymous.

**Comment by geronimoge** [comment]
Update:
- Within the Pi-hole, there are no entrys. So I assume that AFWall is blocking the requests within the phone beforethey get there.
- Everything seem to work just fine, when I'm switching DNS Proxy from 'Disable DNS via netd' to ’Auto’. But the question remains: Why does 'Disable DNS via netd' stopped working for me?

**Comment by ukanth** [comment]
If you disable DNS via netd, AFWall+ denies DNS queries explicitly.

**Comment by geronimoge** [comment]
Okay, thank you very much for your support.
I'll keep the mode in 'Auto' then.
So it was like a bug in the previous versions and should have been as in v3.5.0 upwards, right?

**Comment by ukanth** [comment]
Thanks. Closing this issue. Please reopen if required.
