### ISSUE TITLE
Issues with v3.5.1

### ISSUE THREAD

**Issue by Cris--** [ukanth/afwall#1201]
1. Cloning of the first profile didn't work. It let's AFWall reloading or crashing if i tried it.

2. Import of a rules backup didn't work. AFWall freezes completely.

crDroid 7.4, LOS18.1, A11 + LSPosed

Crash of profile cloning:
https://del.dog/ukylefihic

Complete log of these two issues:
[2021-04-20-01-02-38.txt](https://github.com/ukanth/afwall/files/6349389/2021-04-20-01-02-38.txt)

**Comment by SynapseScribe** [comment]
Import freezes for me too

**Comment by ukanth** [comment]
@Cris-- , Are you using default profiles or migrated profiles ?

**Comment by Cris--** [comment]
> 
> 
> Are you using default profiles or migrated profiles ?

sry, don't know anymore.
