### ISSUE TITLE
[ISSUE] iptables exited with status 4

### ISSUE THREAD

**Issue by bthylafh** [ukanth/afwall#1202]
[IPv4rules.log](https://github.com/ukanth/afwall/files/6352884/IPv4rules.log)
**Describe the bug**
When connectivity changes, AFwall complains that it can't apply changed rules.  This appears in the logcat:
`04-21 11:32:29.802 D/AFWall  (11069): command 'iptables -A afwall-wifi-lan -m owner --uid-owner 10138 -j afwall-reject' exited with status 4, retrying (attempt 1/10)`

That applies to IPv6 as well.

**Firewall Logs**
Firewall log attached.

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - Android OS: LOS 18.1

**Additional context**

**Comment by bthylafh** [comment]
My phone is rooted with the current rev of Magisk and I can successfully get root.

**Comment by ukanth** [comment]
Does afwall disable itself on connectvity change ?

**Comment by bthylafh** [comment]
It does not seem to, no. The quick tile is still colored in when I check it.

**Comment by ukanth** [comment]
Do you have privateDNS enabled ?

**Comment by bthylafh** [comment]
I do not.  I am connected to a VPN, however.

**Comment by ukanth** [comment]
You can ignore this warning. it will try apply the rules 10 time before it gives up. Seems like some process/firewall in your device is also agressively trying to use iptables (it could be android as well).

**Comment by bthylafh** [comment]
OK, thanks.
