### ISSUE TITLE
Fails to build on F-Droid

### ISSUE THREAD

**Issue by jspricke** [ukanth/afwall#1204]
Hi,

the latest version (3.5.1) fails to build on F-Droid:
```
/home/vagrant/build/dev.ukanth.ufirewall/app/../obj/local/mips/objs/run_pie/run_pie.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[2]: *** [/home/vagrant/build/dev.ukanth.ufirewall/app/../obj/local/mips/run_pie] Error 1
make[2]: Leaving directory `/home/vagrant/build/dev.ukanth.ufirewall/external'
Makefile:144: recipe for target '../libs/mips/run_pie' failed
make[1]: *** [../libs/mips/run_pie] Error 2
make[1]: *** Waiting for unfinished jobs....
```
https://monitor.f-droid.org/builds/log/dev.ukanth.ufirewall/20210419

Would be great if you could help us fix it.

**Comment by ukanth** [comment]
since run_pie is no longer used in the code, I have removed it completly. You can cherry pick this commit and do a build.

**Comment by jspricke** [comment]
Thanks, I disabled the build and we will wait for the next release.

**Comment by ukanth** [comment]
New build is up.

**Comment by linsui** [comment]
It failed again.

```
  CC      libbb/xreadlink.o
  CC      libbb/xrealloc_vector.o
  CC      libbb/xregcomp.o
  AR      libbb/lib.a
  LINK    busybox_unstripped
Trying libraries: m
 Library m is not needed, excluding it
Final link with: <none>
make[2]: Leaving directory '/home/vagrant/build/dev.ukanth.ufirewall/external/arm-linux-androideabi/busybox'
make[1]: Leaving directory '/home/vagrant/build/dev.ukanth.ufirewall/external'
Makefile:162: recipe for target 'arm-binaries' failed
make: *** [arm-binaries] Error 2
make: Leaving directory '/home/vagrant/build/dev.ukanth.ufirewall/external'
==== detail end ====
2021-05-18 06:23:20,373 DEBUG: Error encoutered, stopping by user request.
```

**Comment by ukanth** [comment]
It must be something happening at F-droid build servers. Builds are happening properly on my local.

**Comment by linsui** [comment]
The full log is https://monitor.f-droid.org/builds/log/dev.ukanth.ufirewall/20210516. You miss a `k` [here](https://github.com/ukanth/afwall/blob/fc30dc2f53b51d6cff7f6fb86f2ccc19f13e97af/external/Android.mk#L7)

**Comment by linsui** [comment]
By the way, does newer ndk versions work? We are considerring droping ndk r10e support.

**Comment by ukanth** [comment]
I will have to check out the NDK part.

**Comment by ukanth** [comment]
I added point release with the fix. 
https://github.com/ukanth/afwall/tree/v3.5.2.1

**Comment by linsui** [comment]
Thanks!

**Comment by ukanth** [comment]
Since the new build is up, closing this issue.
