### ISSUE TITLE
[ISSUE] After turning off log service, it continues to generate block notifications

### ISSUE THREAD

**Issue by MrEngineerMind** [ukanth/afwall#1207]
**Describe the bug**
When I saw that 3.5.x had a reworked Log function, I wanted to try it because the log function is intermit in 3.4.0.

Lost all rules/settings trying to do the update - so I uninstalled and reinstalled 3.5.1 from playstore and imported just the rules (not settings).

Turned on log, and it started to display blocks in notification - great!

Then 30 mins later, no more notifications or updates to the log list - so it looks like the log function in 3.5.1 is still unreliable :(

 So, I turned OFF the log service. But now I still am seeing NEW blocked notifications :(

 Please fix the log function.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android OS: A10

**Additional context**
Magisk, XprivacyLUA

**Comment by ukanth** [comment]
Have you disabled "battery savings" for AFWall+ ?

**Comment by MrEngineerMind** [comment]
Yes, I have these two things set:
1) Do not restrict (allow to run in the background)
2) Do NOT optimize battery usage.

**Comment by MrEngineerMind** [comment]
OK, here is some more info that might help figure out whats going on...

I rebooted the phone with log serviced enabled.
The log function started to function properly for an extended amount of time (hours), even after device lock and unlock.
However, when I then turned off the log service, I am still receiving block notifications. If I attempt to view the log, it says "Please enable log service via preferences. If enabled, then no log data.

So, I think it would be best to not combine two problems in this one ticket, so I change the title to reflect this one problem of continued notifications after turning off log service.

**Comment by ukanth** [comment]
This will get fixed in the next release. Thanks.

**Comment by MrEngineerMind** [comment]
OK, I want to add another observation...

If I turn off the log service, it will continue to generate block notifications, as this bug ticket reports.
But if I then reboot my phone, then the block notifications stop.

If I then turn on the log service, no block notifications or log events are generated.
But if I then reboot my phone, then block notifications and log events resume.

So, it seems whenever I turn on or turn off the log service, I must then reboot the phone for that change to take effect.

**Comment by ukanth** [comment]
is this the case 3.5.2 as well ?

**Comment by MrEngineerMind** [comment]
It seems like I can start and stop the log service, which will start and stop the block notifications without having to reboot my phone when using this new 3.5.2 version.

Thank you :)
