### ISSUE TITLE
[Question] About working of Afwall for IPv6

### ISSUE THREAD

**Issue by TontyTon** [ukanth/afwall#1211]
Here are few questions about working of the afwall for IPv6 protocol, I tried searching but couldn't find anything answering these questions.

- When 'IPv6 Support' is disabled, then IPv6 connections are blocked or allowed?
- What does 'Only Control IPv6 Chains' do? Is it applicable when 'IPv6 Support' is enable or disable or in both the cases?

Please can you explain a bit about these.

**Comment by ukanth** [comment]
- When 'IPv6 Support' is disabled, then IPv6 connections are blocked or allowed?

Allowed. If you do not enable ipv6 support, it does not modify the default chains. 

- What does 'Only Control IPv6 Chains' do? Is it applicable when 'IPv6 Support' is enable or disable or in both the cases?

That option overrides IPv6 chains (BLOCK/ALLOW). Recommeded option would be able to enable IPv6 support. In case if you don't want that, block all chains on control ipv6 ( this might block connections depending on your connectivity)

**Comment by TontyTon** [comment]
Thanks for the information.

PS - 
Consider adding the following to the description of IPv6 Support. As if a user assumes that it disables IPv6 for the system, then the user will be unaware that all apps are able to connect to internet using IPv6

> When 'IPv6 Support' is disabled, then IPv6 connections are blocked or allowed?
Allowed. If you do not enable ipv6 support, it does not modify the default chains.

**Comment by ukanth** [comment]
It's enabled by default.

https://github.com/ukanth/afwall/blob/beta/app/src/main/java/dev/ukanth/ufirewall/util/G.java#L420

**Comment by TontyTon** [comment]
Ya I know, but from personal experience, I disabled it thinking it will block access to IPv6 to all apps, but I use several tools whose results made me doubt that, but many people may not use such tools.
Its obviously your choice, I was just suggesting.
Thanks for wonderful tool.

**Comment by ukanth** [comment]
I got the exactly opposite feedback. Lot of people does not know how to enable this and ended up having non working firewall (if the connection is ipv6)
