### ISSUE TITLE
Error applying rules on Xperia 10 III

### ISSUE THREAD

**Issue by dec0de** [ukanth/afwall#1234]
**Describe the bug**
After configuring your firewall enabling/applying rules will create an error message (and no rules will be applied)

**Firewall Logs**
It's not really applicable here...

**Smartphone (please complete the following information):**
 - Device: Xperia 10 III
 - Android OS: 11

**Additional context**
A temporary solution seems to be to unbox the "IPv6 support" box and re apply the config.

**Comment by MarcoHannemann** [comment]
This issue has been already reported, see #1206

**Comment by ukanth** [comment]
Duplicate of #1206
