### ISSUE TITLE
[ISSUE] Internet May Not Be Available - Some Whitelisted Apps Can't Access Internet

### ISSUE THREAD

**Issue by akano12** [ukanth/afwall#1239]
**Describe the bug**
Some Whitelisted apps can't access internet unless afwall is completely disabled

**Firewall Logs**
[IPv4rules.log](https://github.com/ukanth/afwall/files/7227170/IPv4rules.log)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J6+ (SM-J610F)
 - Android OS: Stock Android 9

**Additional context**

Some apps like "Aptoide" "Spotify" can't connect to internet even when they're whitelisted in afwall,it  doesn't matter if you whitelist all "User" / "System" apps, they won't work unless afwall is completely disabled.

Additional Info:

1-it seems that those apps rely on the http message (204) received by UID 1000
2-even if all the UIDs are whitelisted, "Internet May Not Be Available" won't go away unless afwall is completely disabled, which means above apps will work 
3-Tried some of the suggestions mentioned here and there and in the README file but non did the trick

**Comment by takiainen** [comment]
I've had this issues as well for about a year now. Spotify says "no internet connection" and Element chat messages won't arrive unless I disable Afwall and turn on and off airplane mode. I get the message if I open the chat app, but not if it is in background. However, I cannot send images if Afwall is turned on . 

Everything works fine if I disable afwall completely. I'm using latest Afwall version from F-droid.
