### ISSUE TITLE
Error applying iptable rules, tap here to open settings.

### ISSUE THREAD

**Issue by CodeCracker-oss** [ukanth/afwall#1251]
My issue occurred after switching to a new device, the Pixel 6 running Android 12 November security update. Never occurred on previous pixel 4, android 11.

Current AfWall+ Donate Version: 3.5.2

I've been having an error which seems to be completely random, where it would alert me that iptable rules failed to apply, tap here to open settings. There would be an option to disable, not enable but indeed blocked apps could now access internet (Which they shouldn't in block selected mode) Clicking disable ran for a few seconds and then just stopped, not doing anything. The only fix was device reboot. Seems to happen once every other day.

I don't know if the magisk canary build im using to root would play a role in this error, but in case it would help:

Magisk Canary build version 23013, zygisk enabled.

Only have this 1 firewall app installed. As far as root apps, nothing is different from prior device other than using a canary version of magisk (required to root android 12, currently).

Log:

https://pastebin.com/58D3JNbr

**Comment by DanielRieken** [comment]
Duplicate of #1206?
Try 3.5.3_BETA1

**Comment by CodeCracker-oss** [comment]
@DanielRieken 

I do not believe it is a duplicate, i've seen that issue prior to opening a new one and didn't appear to be the same.

Where is that version 3.5.3_BETA1?
I don't see it in github release, or beta program in play store or on f-droid.

Would I have to compile from source? I can if need be, would just rather avoid it if possible.

**Comment by ukanth** [comment]
https://www.dropbox.com/s/f1fekfxpqmvw2mg/AFWall%2B_3.5.3_BETA1.apk?dl=0

**Comment by DanielRieken** [comment]
> I do not believe it is a duplicate, i've seen that issue prior to opening a new one and didn't appear to be the same.

you have the same error-messages as #1206, thats the reason I've linked to this issue...
_exited with status 4, retrying (attempt x/10)_

> Where is that version 3.5.3_BETA1? I don't see it in github release, or beta program in play store or on f-droid.

you can find it in #1206.

**Comment by DanielRieken** [comment]
@dhammel
So did 3.5.3_BETA1 solve your problem?

**Comment by CodeCracker-oss** [comment]
@DanielRieken 

I had installed the app about 5 hours ago, as I had the time. So i'll find out roughly around 3 days I suppose if it works. I'll post back then, or earlier if I receive same error.

**Comment by CodeCracker-oss** [comment]
@DanielRieken 

Issue still seems to persist, just received same error as usual.

**Comment by DanielRieken** [comment]
ok, thats sad :(

**Comment by ZeVince** [comment]
Just had the same issue while setting up a new Poco F3 with ArowOS Version: v11.0 Date: 2021-11-12
In my case, test version 3.5.3_BETA1 fixes the issue related to systematic "Error applying iptable"
Thanks !

**Comment by barrio** [comment]
i can confirm this issue for afwall+ on a poco f1 with lineage for microg. Root for adaway is requested as expected.

**Comment by brennoflavio** [comment]
Can confirm that problem, same setup than @barrio . Is there any workaround or build that solves this?

**Comment by DanielRieken** [comment]
@barrio @brennoflavio 
Try 3.5.3_BETA1 you can find it in #1206

**Comment by brennoflavio** [comment]
Thanks! Using here, so far so good. Will report if I catch up something.
