### ISSUE TITLE
[ISSUE] No internet access when Private DNS is enabled 

### ISSUE THREAD

**Issue by pixincreate** [ukanth/afwall#1268]
**Describe the bug**
I don't think #1191 is resolved. I still have to manually re-enable the script to get internet access. I didn't try the same on F-Droid. 

**Firewall Logs**
Please get the log from Menu -> Show Rules -> (menu) Export to storage and attach it here
[IPv4rules.log](https://github.com/ukanth/afwall/files/8148358/IPv4rules.log)

**Smartphone (please complete the following information):**
 - Device:  Nokia DRG
 - Android OS: LOS 18.1 Official

**Additional context**
Version 3.5.3 from Google Play Normal version.

**Comment by lvpha** [comment]
Same as above. 

Android 11, running 3.5.2 F-Droid version. No Internet access with private DNS.

**Comment by CelularBat** [comment]
**Describe the bug**
Same as above. If I turn on Private DNS notification says my WiFi has no access to private VPN server.
Also every time I reboot the phone  (while Private DNS is on) it has that connection issues.

_**Solution:**_  To fix it I need to:
1. Open AfWall and reapply the rules
2. Manually disconnect from WiFi and connect again
Now it works, but it's annoying. And stops me from having auto-connection to internet after reboot, which I need. 

Maybe there is a script which could automate this (like reapply the rules on start after rebooting ?)  (I have no idea about scripting here and what it's capable to)

**Firewall Logs**
```
AppID : 0
App Name : (root) - apps running as root
Total Packets Blocked: 12
[TCP] *Here is IP adress of my private DNS server(6)*
[TCP] *Here is another IP adress of my private DNS server(6)*
```

Instead that I have "(root) - apps running as root" whitelisted in rules. 

**Smartphone (please complete the following information):**

Samsung Galaxy S7 SM-G930F
LineageOS 19

AfWall 3.5.3 from Google Play Store (by Aurora Store)

**Comment by MIRK0** [comment]
I confirm the same behavior on my device (Samsung A40 SM-A405FN/DS stock rom, One UI 3.1, Android 11, with Magisk 27.0 applied, AFWall+ 3.6.0 normal, from Aurora Store).
Everytime I reboot, with Private DNS set, I get the notification WiFi (or 4G) haven't access to internet.
Also from the logs I see entries of blocked connections to Apps I have previously authorized to access internet.
I tried to delay various amount of seconds, but the behavior is always the same. To fix, I have to reapply rules, turn off-on Wifi (or 4G). I was looking for other people having the same behavior and found this issue.
