### ISSUE TITLE
[FEATURE] Add Uninstall Listener

### ISSUE THREAD

**Issue by bonbonboi** [ukanth/afwall#1285]
**Describe the solution you'd like**

When the user install an app 
The notification of "Open AFWall+ Configure Internet Permission" for that app is appear 

That notification must be cleared automatically when the user uninstalled the app.

**Comment by ukanth** [comment]
AFWall+ does cleanup the rules when the user uninstall the app. AFWall+ uses single notification for any app installation and it gets overwritten when another app is installed.

**Comment by bonbonboi** [comment]
> AFWall+ does cleanup the rules when the user uninstall the app. AFWall+ uses single notification for any app installation and it gets overwritten when another app is installed.

Understood. I'm talking about something else.

**Comment by ukanth** [comment]
I guess I have answered for that only. To simply for answer, It(clearning the notification) can't be done with current implementation.

**Comment by bonbonboi** [comment]
> I guess I have answered for that only. To simply for answer, It(clearning the notification) can't be done with current implementation.

So I better turn off "Enable Notifications" to stop being annoyed by that.
