### ISSUE TITLE
[ISSUE] Please release BETA1

### ISSUE THREAD

**Issue by Enkidu70** [ukanth/afwall#1287]
For many users, AFWall ist currently not usable due to rule applying problems. See #1206 & #1251.

BETA1 is available since September 21 and working fine.
See https://github.com/ukanth/afwall/issues/1206#issuecomment-920137140

But not available via Playstore and no donate version.

Please release BETA1 as a regular update, including donate version.

Tnx.

**Comment by alfureu** [comment]
I think more needs to be done, esp. in relation to support of Android 12. But I agree that an overall update would be great!

**Comment by Enkidu70** [comment]
3.5.3 seems not to include fixes of beta1 ( https://github.com/ukanth/afwall/issues/1206#issuecomment-920137140 ).

Apply rules failed as in 3.5.2. ( see https://github.com/ukanth/afwall/issues/1206#issuecomment-1170744870 and following).

**Comment by ukanth** [comment]
You should enable delay from preference if you see error while applying rules.

**Comment by Enkidu70** [comment]
> You should enable delay from preference if you see error while applying rules.

Tnx. I was not aware of it. Now it works fine.
