### ISSUE TITLE
[ISSUE] does not work on Havok 4.16 (android 11)

### ISSUE THREAD

**Issue by OmlineEditor** [ukanth/afwall#1288]
**Describe the bug**
clean new firmware, I put your program in the first application and try to turn on the firewall, but it doesn't work at all. I tried changing the iptables type option from the system to the built-in one, but it didn't help.

**Logs**
[log_AFWALL.txt](https://github.com/ukanth/afwall/files/8893983/log_AFWALL.txt)

**Smartphone:**
 - Device: Redmi Note 7
 - Android OS: Havok 4.16 Vanilla (android 11)

**Comment by OmlineEditor** [comment]
if you use an older version 3.3.1, then the firewall works and the rules apply. the problem is in the parameter for iptables unknown option "--log-prefix".
Remove this parameter.

**Comment by ukanth** [comment]
It seems like OS issue than AFWall+ issue. they have not compiled iptables/kernel properly. Ask them to fix it and change the kernel.
