### ISSUE TITLE
F-Droid metadata changes

### ISSUE THREAD

**Issue by licaon-kter** [ukanth/afwall#1299]
@ukanth Can you confirm this is a valid request from you?

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11329/diffs

Thanks

**Comment by ukanth** [comment]
Yes @licaon-kter. I made that pull request.

**Comment by licaon-kter** [comment]
Thanks

**Comment by ukanth** [comment]
My PR is closed without merging ? Should I raise another PR with rebased code ?

**Comment by licaon-kter** [comment]
I did comment there or left a reference iirc ;)

**Comment by ukanth** [comment]
Thanks. I missed the reference because I was reading it on mobile.
