### ISSUE TITLE
[FEATURE] add option to change default OUTPUT policy to REJECT

### ISSUE THREAD

**Issue by mailinglists35** [ukanth/afwall#1318]
**Is your feature request related to a problem? Please describe.**
I'm surprised to find the default filter table OUTPUT chain policy is left to ALLOW. This can lead to accidental short-lived data leaks when restarting or after starting app until rules are loaded.

**Describe the solution you'd like**
Allow a preferences option to change the default OUTPUT policy from ACCEPT to REJECT

**Describe alternatives you've considered**
I'm blocking things during boot using magisk startup scripts by simply changing OUTPUT policy to REJECT. But then when afwall starts, it changes the policy back to ACCEPT and there could be miliseconds until all rules load and data traffic can leak

**Additional context**
It's fine if you make me type "YES I KNOW WHAT I'M DOING" before enabling this.

**Comment by ukanth** [comment]
That's not the case in general or in AFWall. To prevent leaks, you can place a script under init.d using an option in AFWall, that will make the chain default's to reject. the same goes for network change.

**Comment by mailinglists35** [comment]
I finally understood how it works and solved it this way

on my magisk android 11 phone, I am able to run a script even before afwall, by placing a script in `/data/adb/post-fs-data.d/` with this contents:

````
fleur:/ # cat /data/adb/post-fs-data.d/afwall.sh
/system/bin/iptables -P OUTPUT DROP
````

at this early boot stage `OUTPUT` policy was `ACCEPT` then we change it to `DROP` which holds back everything.

so nothing gets out until I unlock phone then manually open afwall, which does:
- during load, changes `OUTPUT` policy to `DROP`
- after loading complete, changes `OUTPUT` policy back to `ACCEPT` - this is safe because the afwall chain ends with a `REJECT`

btw, my original request to change the default policy to `REJECT` is invalid, because the kernel only knows `ACCEPT` and `DROP` for `OUTPUT`:

````
fleur:/ # /system/bin/iptables -P OUTPUT REJECT
iptables: Bad policy name. Run `dmesg' for more information.
````

there is no need for custom script as during Apply, afwall temporarily changes the OUTPUT policy to `DROP`
