### ISSUE TITLE
[ISSUES] "default whitelist" & "clone profile" problem

### ISSUE THREAD

**Issue by 2DaysMayfly** [ukanth/afwall#1319]
"Default whitelist behaviour" problem (UI Preferences):
Changes cannot be undone; once marked it remains so even after.

"Clone profile" problem:
Profiles cannot be duplicated, are only adopted without settings (completely empty).

**Firewall Logs**
https://drive.google.com/file/d/1tnxuoim2i-Gv1q1EHd44u4MfIm4Icaf7/view?usp=drivesdk

**Smartphone:**
 - Device: [samsung galaxy s6] (rooted, magisk; LSposed framework)
 - Android OS: [LOS 18.1 unofficial]
 - AFWall+ (v3.5.3) (donate) 

**Additional:**
It is not known whether the "whitelist problem" also occurs with the "blacklist presetting" because I didn't want to make any further settings that I can't undo.

The same problems also exists at the same device with original STOCK ROM.

Otherwise, I am very satisfied.
Thanks for the great work!

**Comment by don-dolarson** [comment]
Same problem here.

OnePlus 5T
LineageOS 20 (official)

**Comment by ukanth** [comment]
This is fixed. Available in next release.

**Comment by ukanth** [comment]
Before cloning a profile, make sure you save and apply the rules once with that profile.

**Comment by 2DaysMayfly** [comment]
That's great, thank you very much about fixing the issue! :)

Btw: Which app (Android) do you recommend to log sys events containing
afwall and processes that have a handle on it?

Catlog and alogCat are tested but they didn't show me the event, that
sometimes kill the afwall process since 2 weeks; without a notification or
something else.

I think, another app, exactly an update of it, has made a conflict but I
don't find it.

At the moment I use a little macro to reactivate automatically afwall if it
will deactivated.

Best regards

robo-mo ***@***.***> schrieb am So., 18. Juni 2023, 08:47:
