### ISSUE TITLE
[ISSUE] Firefall disables automatically

### ISSUE THREAD

**Issue by hollysheep** [ukanth/afwall#1333]
**Describe the bug**
When i block an app and apply the new settings sometimes after that the firewall is disabled. when i try to enable it there is an error that this wasn't successful. I try it again and then it works.

**Firewall Logs**
Please get the log from Menu -> Show Rules -> (menu) Export to storage and attach it here

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 10 Lite 5G
 - Android OS: LineageOS 18.1 for microG
[IPv4rules.log](https://github.com/ukanth/afwall/files/11239667/IPv4rules.log)

**Comment by ukanth** [comment]
Please make sure you enable "Add Delay" under Rules/Preferences. That should solve the problem
