### ISSUE TITLE
[ISSUE] latest version is missing in F-Droid

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#1352]
**Describe the bug**
Dear ukanth,
The latest version of AFWall+ is missing in F-Droid. Their build monitor was reporting an error. Is this a problem which you can fix?

Thank you,
derflasher

**Comment by vsatmydynipnet** [comment]
+1 for F-Droid. I can not overwrite the installed F-Droid Package with the apk from Github and I do not want to fully deinstall to be able to use 3.6.0

Thank you very much.

**Comment by ukanth** [comment]
It's up now. Closing the issue
