### ISSUE TITLE
[ISSUE] Broken on 64-bit-only phones

### ISSUE THREAD

**Issue by Fry-kun** [ukanth/afwall#1364]
**Describe the bug**
Install Afwall on 64-bit-only phone, like Google Pixel 7 or 8.

**Firewall Logs**
```
command '/data/user/0/dev.ukanth.ufirewall/app_bin/busybox ls /sys/class/net' exited with status 1
```
(and similar errors with `iptables`, `ip6tables`, and `nflog`)

Running same command in adb shell shows 
```
/system/bin/sh: /data/user/0/dev.ukanth.ufirewall/app_bin/busybox: not executable: 32-bit ELF file
```

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8 Pro
 - Android OS: 14

**Additional context**
These phones don't support 32-bit code. Maybe can work around this by installing busybox from elsewhere?

**Comment by Fry-kun** [comment]
in `../app_bin/`, only `afwallstart` executes in shell.
`busybox`, `iptables`, `ip6tables`, and `nflog` are all not executable
I think this means Afwall is not usable at all on these phones

**Comment by Fry-kun** [comment]
Note: a partial workaround is installing "built-in BusyBox" module for Magisk and telling Afwall to use system binaries - that provides most stuff but not `nflog`

**Comment by gashtal** [comment]
Afwall seems to work fine on Pixel 7 and Android 13. Maybe this is a Pixel 8-only or Android 14-only problem? I have been holding off on upgrading to Android 14 because of potential compatibility issues with Afwall.
