### ISSUE TITLE
Trust/Untrusted network category

### ISSUE THREAD

**Issue by Magissia** [ukanth/afwall#190]
Hello, we have somewhat a nice number of categories now on afwall, vpn, 3g, roaming etc, but what about some more paranoid stuff ? 
I'm talkin about networks you trust, trust is important, and apps that allow this kind of configuration are rare : NOT SYNCING/CONNECTING IF NOT ON A TRUSTED NETWORK !

The best example i'm able to share with you is FolderSync that will initiate a sync only if connected to a trusted wifi network if you wish to do so.

The category would show by a checkbox for both trusted/untrusted networks.

How trusted network should work :

When using afwll in blacklist mode (checked stuff are blocked) checking the box will block the app if you are not connected to a trusted network.

When using afwall in whitelist mode (checked stuff are allowed) checking the bow will allow the app to connect even if the network is not trusted.

A "trusted network" menu should be added where the user can add networks based on SSID names and/or mac adress (most paranoid users should be able to use a combinaison of both)

A more advanced version of the trusted network, if some devs got time for it, would be to add ip and host field, and consider the network trusted if the public ip/host match. (this should be usable in combinaison of mac adress SSID  ip host for most paranoid users)

Another option would be to ignore or not the untrusted status of a network if connected to a VPN (and if there's a courageous dev for this, if connected to a trusted VPN, but i may be way too paranoid there ?)

The checkbox for this should only be shown when this option is activated because some devices screen are small and there would be way too much checkboxes. Or the trust network system should have it's own list (if it's the case i will come up with more crazy idea for paranoid people)

While it's not totally afwall role's, we could add the possibility to disable android's sync toggle when not connected to a trusted network.

Best regards, Magissia

**Comment by edgimar** [comment]
I'd like to add one use-case in which something like this feature would be useful:

One of the wifi networks I regularly connect to is a metered connection -- in other words, it has a maximum amount of data that can be used on it per month.  I would like to be able to set the firewall to block certain apps (or only allow certain apps) from using the internet when connected to this wifi network.  When connected to any other wifi network, however, the firewall would be less restrictive.

**Comment by ukanth** [comment]
I'm curious how this can't be done using tasker & profiles ?

**Comment by Magissia** [comment]
Current version has I think given room to work with external tools to check if the network is trusted and change profiles, as we don't seem to have profiles limits now, we could even have a profile per AP.

This issue was opened two years ago, i think current state of the software gives enough room for workaround, I think we can close it if nobody wants to send a pull-request with code to allow afwall to handle it directly.

**Comment by CHEF-KOCH** [comment]
This feature request makes no sense.
