### ISSUE TITLE
Feature request:  input chain

### ISSUE THREAD

**Issue by sniperle** [ukanth/afwall#217]
Please add a separate "input chain" to AFWall+, because just only "all input allowed from lan" is like doors wide open and IMHO to insecure. Thanks.

**Comment by Alestrix** [comment]
In surprised this hasn't been brought up again. Input filtering is IMHO a good and important feature.
Saying that Android is already secure by itself is like defying the whole purpose of this app.

**Comment by ukanth** [comment]
Duplicate of #15
