### ISSUE TITLE
Console command to enable or disable AFWall+

### ISSUE THREAD

**Issue by viharm** [ukanth/afwall#222]
This is not an issue, but a query.

I would like to remotely enable or disable AFWall+ as I use it primarily to block just one application. I have installed a SSH server and can access the target device remotely.

I tried to search in Github, http://crowdin.net/project/afwall as well as the XDA-Dev support forums; but with no success (I probably don't know what to search for).

Is there a shell command to enable or disable AFWall+ or even to enable or disable a blacklist rule?

Thank you

**Comment by LinkTree3** [comment]
I know this is an old question and it's closed but I wanted to ask if there has been any update on this since 2013? What is the best way to enable/disable the firewall using command line?

Thank you.

**Comment by ghu1234** [comment]
I have the same question and request. To enable a command line interface to control it. 
I see that sometimes something goes wrong with afwall (version: ) and upon simplying
clicking the apply button it starts working again. I want to do this via a script.
