### ISSUE TITLE
Feature Request: Blocking Ads with various block list!!! 

### ISSUE THREAD

**Issue by Oxtie** [ukanth/afwall#223]
Please add system wide ads BLOCKING featured using:
01. ADS Blocklist (adblock plus or fan boy's list) 
02. IP range blocklist (blockpost etc) 
03. Please see Outpost4 firewall's plug in features

It's critical that these things become part of Firewall instead of some browser extensions like this 
https://github.com/Gemorroj/noads-advanced

You should also get inspired by Ghostery plug in here
https://addons.opera.com/en-gb/extensions/details/ghostery/?display=en

**Comment by LucasBS1** [comment]
The author said "this feature makes the phone heavy".

Well... isn't this something for US to decide ?

Plus, heavy is me having to use Two apps instead of one to block stuff

So, no. The problem is not performance. There's cleary an agenda
