### ISSUE TITLE
"Error applying iptables rules" on AFWall+ 1.2.6 (and higher) with IPv6 enabled

### ISSUE THREAD

**Issue by oper8** [ukanth/afwall#227]
Since AFWall v1.2.6, I get "Error applying iptables rules" when I enable IPv6 support.  The following failure is shown in the logs:

```
======
Logcat
======

17:11:11 binary installation for armeabi-v7a succeeded
17:11:11 Starting root shell...
17:11:18 Root shell is open
17:11:55 logging using LOG target
17:11:55 command 'ip6tables -A afwall-reject -m limit --limit 1000/min -j LOG --log-prefix "{AFL}" --log-level 4 --log-uid' exited with status 1
Output:
ip6tables: No chain/target/match by that name.

17:34:15 command '/data/data/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-reject -m limit --limit 1000/min -j LOG --log-prefix "{AFL}" --log-level 4 --log-uid' exited with status 1
Output:
ip6tables: No chain/target/match by that name.
```

NOTE: When the error occurs, the AFWall+ icon indicates that the firewall is disabled, although the IPv4 rules did apply successfully.  
I have tried 1.2.6, 1.2.6.1, 1.2.7, and all exhibit the same error above;  version 1.2.5 does not present any errors.

Phone: Droid Razr Maxx XT912
ROM: CM10.1.3

**Comment by dicer** [comment]
Still get this on CM 13.1 with maserati:
root@maserati:/proc/net # cat ip_tables_targets | grep LOG  
NFLOG
LOG
root@maserati:/proc/net # cat ip6_tables_targets | grep LOG  
NFLOG
root@maserati:/proc/net # uname -a
Linux localhost 3.0.8-gfd81692 #1 SMP PREEMPT Sat May 28 15:43:17 2016 armv7l

**Comment by Geberation** [comment]
Getting the same error V3.6.1 android 15 Rooted 

i cant find the log output for the app ?? Where are they hidded?
