### ISSUE TITLE
Option convert to /system app

### ISSUE THREAD

**Issue by PonsAsinorem** [ukanth/afwall#243]
Create an option to convert AFWall to a system app. This should give AFWall better protection by being on a read-only sytem.

Once installed as a system app, add an option to install a backup script to /system/addon.d/ to protect both /system/app/AFWall and /system/etc/init.d/afwallstart to automatically restore AFWall and afwallstart after a ROM flash that supports it (like CM and derivatives).

Back up script: http://forum.xda-developers.com/showpost.php?p=49230936&postcount=1657

**Comment by ukanth** [comment]
Since it's a age of systemless apps, we no longer need afwall to convert as system app. Please feel free to open if you dont agree :)
