### ISSUE TITLE
Trying to add these rules disables Afwall

### ISSUE THREAD

**Issue by blurmonk** [ukanth/afwall#245]
Hi

I am trying to apply bunch of rules, including blocking some google ranges. When I apply them, Afwall disables itselfs. However I can pick one or two from the list below and apply them no problem. I am not sure if this is a problem with the number of rules or some ip. Since the custom script menu is very narrow it makes it hard to debug for me.

iptables -A INPUT -s 128.113.53.134 -j DROP
iptables -A INPUT -s 173.194.0.0/16 -j DROP
iptables -A INPUT -s 173.194.46.68 -j DROP
iptables -A INPUT -s 173.194.46.99  -j DROP
iptables -A INPUT -s 173.94.0.0/16 -j DROP
iptables -A INPUT -s 204.202.20.53  -j DROP
iptables -A INPUT -s 5.135.86.61 -j DROP
iptables -A INPUT -s 50.115.125.93 -j DROP
iptables -A INPUT -s 54.200.106.164 -j DROP
iptables -A INPUT -s 63.240.161.99 -j DROP
iptables -A INPUT -s 72.14.0.0/16 -j DROP
iptables -A INPUT -s 74.125.0.0/16 -j DROP
iptables -A INPUT -s 74.125.227.198  -j DROP
iptables -A INPUT -s 8.8.0.0/16 -j DROP
iptables -A INPUT -s 81.7.11.70 -j DROP

iptables -A OUTPUT -s 128.113.53.134 -j DROP
iptables -A OUTPUT -s 173.194.0.0/16 -j DROP
iptables -A OUTPUT -s 173.194.46.68 -j DROP
iptables -A OUTPUT -s 173.194.46.99  -j DROP
iptables -A OUTPUT -s 173.94.0.0/16 -j DROP
iptables -A OUTPUT -s 204.202.20.53  -j DROP
iptables -A OUTPUT -s 50.115.125.93 -j DROP
iptables -A OUTPUT -s 54.200.106.164 -j DROP
iptables -A OUTPUT -s 54.243.170.179 -j DROP
iptables -A OUTPUT -s 63.240.161.99 -j DROP
iptables -A OUTPUT -s 72.14.0.0/16 -j DROP
iptables -A OUTPUT -s 74.125.0.0/16 -j DROP
iptables -A OUTPUT -s 74.125.227.198  -j DROP
iptables -A OUTPUT -s 8.8.0.0/16 -j DROP
iptables -A OUTPUT -s 81.7.11.70 -j DROP
iptables -A OUTPUT -s 5.135.86.61 -j DROP

**Comment by CHEF-KOCH** [comment]
This was fixed after AFWall+ 1.2.4+

The best is to not copy and paste or if possible use the 'convert to' option, editors like VIM/Notepad++ or others have this. 
But we already added a similar check for this so in some situations it isn't necessary anymore.
