### ISSUE TITLE
RETURN target ignores Multiuser rules in 1.2.9

### ISSUE THREAD

**Issue by didierm** [ukanth/afwall#271]
Running KK 4.4.2 ; testing AFWall+ experimental Multiuser functionality in version 1.2.9 (due to issue #270, unable to test in 1.3.0.2).

Apparently, AFWall+ uses the **_RETURN_** target instead of **_ACCEPT_** when setting up rules (is this related to whitelist/blacklist functionality ?).

While this works for single-user setups, it appears to fail for multiuser, as qualifying packets in the secondary users chains are never ACCEPTed, but are subsequently REJECTed in the next user chain ?
#### Example :

A packet for application 1010061 (userid=10) matches in _afwall10-wifi-wan#9_.
It is my impression it then RETURNs, is matched again by _afwall0-wifi-wan#31_ (it should never enter the afwall0 target in the first place, as it is already matched in afwall10), and is subsequently REJECTed in _afwall0-reject#2_.

**_Manually changing the target in afwall10-wifi-wan#9 from RETURN to ACCEPT allows the packet to traverse, as intended._**

```
Chain OUTPUT (policy ACCEPT 111 packets, 9659 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1      223 16427 afwall10   all  --  *      *       0.0.0.0/0            0.0.0.0/0           
2      627 52147 afwall0    all  --  *      *       0.0.0.0/0            0.0.0.0/0           
3    41929 2400K afwall     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

```
Chain afwall10-wifi-wan (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
1        5   331 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 0
...
9       32  1920 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 1010061
...
12      80  4848 afwall10-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 0-999999999
```

```
Chain afwall0 (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
1        0     0 afwall0-wifi  all  --  *      eth+    0.0.0.0/0            0.0.0.0/0           
2      233 16482 afwall0-wifi  all  --  *      wlan+   0.0.0.0/0            0.0.0.0/0           
...
```

```
Chain afwall0-wifi (5 references)
num   pkts bytes target     prot opt in     out     source               destination         
1      233 16482 afwall0-wifi-postcustom  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

```
Chain afwall0-wifi-postcustom (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
1        0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 1014
2        0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 1010
3      203 14167 afwall0-wifi-fork  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

```
Chain afwall0-wifi-fork (2 references)
num   pkts bytes target     prot opt in     out     source               destination         
1      202 14107 afwall0-wifi-wan  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

```
Chain afwall0-wifi-wan (1 references)
...
31     145  8732 afwall0-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 0-999999999
```

```
Chain afwall0-reject (5 references)
num   pkts bytes target     prot opt in     out     source               destination         
1      120  7232 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 1000/min burst 5 LOG flags 8 level 4 prefix "{AFL}"
2      145  8732 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
```

**Comment by wttrtpy** [comment]
This issue still seems to exist with AFWall trunk (9a5ccab9) running on 4.4.4-based CM11.

**Comment by wttrtpy** [comment]
Nevermind, multi-user support seems to be fine; firewall logs show that DNS packets (port 53 with AppID 0) were being blocked. Un-blacklisting user 0 fixes the issue, as does adding a rule to allow traffic on port 53.

I don't quite remember needing to unblock this for a single-user setup. Also, tracking down this issue was hard because Firefox worked fine (it seems to do its DNS lookups in-process).

**Comment by Magissia** [comment]
Multi user still doesn't work as shown in #423

**Comment by mirfatif** [comment]
MIUI 9 Dual apps feature doesn't work either with AFWall+ 2.9.7.
UID is duplicated with prefix 999 like 12345 to 99912345.

Edit: "Block Selected" instead of "Allow Selected" trick works

**Comment by ajvsol** [comment]
Doesn't work with apps in Android for Work profile in v2.9.9. Edit: nevermind, found the setting under Experimental preferences.
