### ISSUE TITLE
One app is not blocked

### ISSUE THREAD

**Issue by Wishmesh** [ukanth/afwall#311]
Thanks for this app!

Device: Samsung Galaxy Mega 6.3 w/ Android 4.4.2 (just upgraded)
AFWall+ (v1.3.4.1)
Not using XPrivacy, antivirus, etc.

Internet restriction works for most of my apps. One app still show ads.

What I have tested:
--------------------------
* Enabled log in AFWall+, it shows AppID 10023, total packets blocked 43... and list of IPs.
* App still shows ads.
* Started to capture network packets via my router, and router shows traffic for the same IPs, that are supposedly blocked.
* Looked at the Firewall rules / IPTables Rules... AppID 10023 not found. This is ok I suppose.
* This all happens on WiFi. Just tested, on 3G also.
* DroidWall worked on 4.1.2 or 4.2.2 but on 4.4.2 the same problem as with AFWall+, one app is not blocked.

I can provide more debug info if needed. Your app looks promising, so want the fix :)

**Comment by E3V3A** [comment]
@CHEF-KOCH  Wow, thanks, I had no idea about all that WA stuff....
