### ISSUE TITLE
Blocking WLAN doesnt work 

### ISSUE THREAD

**Issue by agowa338** [ukanth/afwall#313]
I'm using a Samsung Galaxy S3 with the latest nightly Cyanogenmod Version and blocking network access over WLAN does not work.

**Comment by CHEF-KOCH** [comment]
Excuse me but why is that labeled as `Bug` even if there is only one person with a nightly rom that have such a problem? I've tried reproducing that with a stable Slim rom on my friends S3 and all works perfect (both chainfires Su and kosh's su), so there is no confirmation that this is really a AFWall+ problem. We simply don't have enough man power to support each change in every rom which may break SU/klogripper or other things.  

All logs seems okay the only thing is that the thread starter wrote [that the Browser is not been blocked](https://github.com/ukanth/afwall/issues/313#issuecomment-53936492), so WLAN seems to work generally (wrong thread title). The thread poster didn't provide which Browser he is using, on FF it works quite good here.

SU should be under /system/app and not priv-app, priv app is only for apps that needs to be running all the time in the background. Please use the latest Su cwm installer and try again if there is a problem. 

I hope this helped.
