### ISSUE TITLE
CustomScripts issues

### ISSUE THREAD

**Issue by shellshocker** [ukanth/afwall#331]
Hi,

I'm using AFWall+ v1.3.4.1 on an Android 4.4.2 CyanogenMod. I want to use CustomScripts but have some problems with the provided instructions (https://github.com/ukanth/afwall/wiki/CustomScripts).

You write the following under »Adding custom rules«:

> IMPORTANT: Never manually purge the OUTPUT chain - this will cause AFWall+ rules to be ignored. Use the 'afwall' chain instead.

Later you give some examples »Some examples«:

> # Flush/Purge all rules
> 
> $IPTABLES -F
> $IPTABLES -t nat -F
> $IPTABLES -t mangle -F
> $IP6TABLES -F
> $IP6TABLES -t nat -F
> $IP6TABLES -t mangle -F

Does this makes sense? Will this not delete the OUTPUT chain as well? Furthermore this isn't working. I have to use the following:

> # Flush/Purge all rules
> 
> $IPTABLES -F INPUT

Everything else ends in an error.

So I have two questions:
1. Which chain we should use? OUTPUT or afwall? And what's the difference here?
2. How can I flush / purge all rules? Code example isn't working for the startup script. For shutdown script everything is fine.

Thank you!
shellshocker

**Comment by ukanth** [comment]
1. You should always use afwall chain if you want afwall to filter the packets. 
2. You can flush the rules and reapply using AFWall+ ( menu-firewall rules). But if there are any other apps/services depends on iptables chains, that might not work if you flush all the chains.

**Comment by shellshocker** [comment]
@ukanth: Thanks for answering! :-)

I'm now using this Flush/Purge commands in my Custom StartUp Script:
> # Flush / Purge all rules expect OUTPUT
> $IPTABLES -F INPUT
> $IPTABLES -F FORWARD
> $IPTABLES -t nat -F
> $IPTABLES -t mangle -F
> $IP6TABLES -F INPUT
> $IP6TABLES -F FORWARD
> $IP6TABLES -t nat -F
> $IP6TABLES -t mangle -F

> # Flush/Purge all chains  
> $IPTABLES -X 
> $IPTABLES -t nat -X
> $IPTABLES -t mangle -X
> $IP6TABLES -X
> $IP6TABLES -t nat -X
> $IP6TABLES -t mangle -X

As you can see i left out OUTPUT rules to get cleared. When I add them AFWall+ gives a toast message "Firewall rules could not be loaded".

1. I could not find any apps/services which are depending on iptables when I'm trying to flush OUTPUT rules. So I really don't know what's the problem here. I always use this commands on my Linux servers.
2. What do you mean in FAQ with "Never manually purge the OUTPUT chain - this will cause AFWall+ rules to be ignored. Use the 'afwall' chain instead."? Because with the command "$IPTABLES -X" I'm doing exactly this. So will this be a problem? Could you clear things up?

**Comment by CHEF-KOCH** [comment]
@shellshocker 
Issue can be closed, I edited the mentioned part and will update some other things a little bit later.
Since there are different iptables and systems they not working the same. The main problem is also that everyone can compile there own iptables which means that some options maybe available or not for you.

**Comment by shellshocker** [comment]
@CHEF-KOCH 
Thank you. Now it's more specific. :)
