### ISSUE TITLE
Tasker integration is gone

### ISSUE THREAD

**Issue by daniel-pfeiffer** [ukanth/afwall#332]
This used to work.  But now when I tap on an AFwall+ task, it says:

Missing app -- To perform this action, the additional *plugin AFwall+ Tasker Plugin* must be installed.
Clicking ok takes me to the Play Store, where I can either deinstall or open AFwall+.

This is on CM11 and neither Tasker nor AFwall+ have data protection activated.

**Comment by ukanth** [comment]
@daniel-pfeiffer , Please mention the Tasker version and Android details. Thanks.

**Comment by daniel-pfeiffer** [comment]
I have updated both Tasker and Secure Settings last weekend.  Then I deleted the AFwall tasks, and could reacreate them without problem.
