### ISSUE TITLE
Feature: allowing incoming connection

### ISSUE THREAD

**Issue by giner** [ukanth/afwall#334]
Some applications (like f-droid) can accept incoming connections and it would be nice to have an option to allow inbound traffic.

**Comment by ukanth** [comment]
We do have allow incoming in preferences. Kindly check it

**Comment by CHEF-KOCH** [comment]
*bump* 
... or close it.

**Comment by tester19823** [comment]
Could you please specify where in Preferences this feature (i.e. allowing incoming connections) is located? I could not find it in the latest version.

**Comment by ukanth** [comment]
It's under Experimental menu "Enable inbound connections"
