### ISSUE TITLE
Rules of the active profile are not updated during import

### ISSUE THREAD

**Issue by sy-subrc** [ukanth/afwall#336]
When importing "preferences rules and profile settings" rules of the active profile are not imported. You have to switch to a not used profile before doing the import to ensure all rules of all profiles are imported properly.

**Comment by CHEF-KOCH** [comment]
As a temporary workaround you can backup the files manually via .e.g. SolidExplorer before you upgrade/clean install another AFWall+ version:

<code>/data/data/devv.ukanth.ufirewall/shared_prefs/</code>

>AFWallPrefs.xml

App/Firewall prefeences

>AFWallStatus.xml

Status (enabled/disabled)

>android-lockpattern_[id].xml

Lockpattern settings


>dev.ukanth.ufirewall_preferences.xml

AFWall+ saved settings

All files putted in directory _/data/data/devv.ukanth.ufirewall/shared_prefs/_ should have right permission to work correctly (rw-rw--) AND correct owner + group (different with each installation - use _ps_ or 3C Toolbox to identify the PID) !
