### ISSUE TITLE
Blocks IPv6 connections

### ISSUE THREAD

**Issue by tokudan** [ukanth/afwall#347]
I have an issue where AFWall+ is blocking IPv6 connections when IPv6 is enabled in the preferences.
The App (Conversations) is allowed to access the internet.
The app has the following permissions in AFWall+: LAN, WLAN, Mobile data, Roaming.
Still as soon as the firewall is enabled, the current connection times out and the app is not able to reconnect and all connections time out after 20 seconds.
Disabling the firewall (or disabling IPv6 in the preferences) results in the app working flawlessly again.

**Comment by CHEF-KOCH** [comment]
Hello, please provide the following information:
* Make sure no other software like XPrivacy/PrivacyGuard blocked the connection
* Make sure your XMPP server is running (check the uptime)
* A connection/firewall log
* AFWall+ & [Conversations](https://f-droid.org/repository/browse/?fdid=eu.siacs.conversations) version
* White-/blacklist mode
* Rules output
* Additional things that could help to solve these, rom, busybox, iptables, [...]

I quickly tested this [this](https://f-droid.org/repo/eu.siacs.conversations_46.apk) version which works fine under CM 11 (4.4.4) Android + Slim Rom + System Busybox + internal IPtables binaries and with the 1.3.4.1 + latest alpha versions from AFWall+.

**Comment by Artiom-M** [comment]
Is this really fixed? I have the same issue. When ipv6 is enabled it looks like all ipv6 connectivity is blocked... regardless of APP settings. ipv4 works as expected.

**Comment by aardzhanov** [comment]
this bug is not fixed!!!
Also I have issue https://github.com/ukanth/afwall/issues/461 on version 3.6.1

**Comment by aardzhanov** [comment]
this bug is not fixed!!!
Also I have issue https://github.com/ukanth/afwall/issues/461 on version 3.6.1
