### ISSUE TITLE
AFWall+ does not work on CM12 (20150219-NIGHTLY) due to non-PIE binaries

### ISSUE THREAD

**Issue by marcan** [ukanth/afwall#348]
Title says it all, really: the iptables and other binaries that come with AFWall+ are not built as PIE executables, so they do not work at all on current CM12 nightlies, which refuse to run non-PIE executables.

PIE executables do not work on ICS apparently, but the Chromium project has a shim that allows them to work, which might be useful:
http://code.metager.de/source/xref/chromium/tools/android/run_pie/run_pie.c

Edit: logcat:
I/AFWall  ( 8461): command '/data/data/dev.ukanth.ufirewall/app_bin/ip6tables -P INPUT ACCEPT' exited with status 1
I/AFWall  ( 8461): Output:
I/AFWall  ( 8461): error: only position independent executables (PIE) are supported.

**Comment by marcan** [comment]
Looks like AFWall+ uses the system iptables binary if present, but not ip6tables. I was able to work around this by copying my system ip6tables binary over the AFWall+ supplied one.

**Comment by cernekee** [comment]
Right, to support PIE it is necessary to pass a few extra compiler/linker flags to ./configure when building the native binaries.  This is how the OpenConnect Android build was updated for Lollipop:

http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/77543538d20975cc86db3520860d96e886cd804c?hp=e7593a96fdf0b9c1f21acf888b751494b98e1660
http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/165d2d2de3d2b4f853a8663f22b7564f927d9c3c?hp=77543538d20975cc86db3520860d96e886cd804c

Also, see the minor update to run_pie here:

https://codereview.chromium.org/913613002/

**Comment by ukanth** [comment]
@cernekee, Thanks for the input. I compiled all the binaries with PIE as default and using run_pie for ICS.
