### ISSUE TITLE
[Question] Build: API 17/18 fail, API 19 success

### ISSUE THREAD

**Issue by taro-k** [ukanth/afwall#351]
Hi, I am building AFWall with the latest Android SDK on Linux.
When I build with targeted API 17 or 18 like

```
% android update project -p . -s -t 1
% ant debug
```

I see the error like

```
-compile:
    [javac] Compiling 86 source files to /mnt/tmp/android/afwall_build/afwall/bi
n/classes
    [javac] /mnt/tmp/android/afwall_build/afwall/src/dev/ukanth/ufirewall/Api.java:354: error: cannot find symbol
    [javac]                                     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
    [javac]                                                                                     ^
    [javac]   symbol:   variable JELLY_BEAN_MR2
    [javac]   location: class VERSION_CODES
    [javac] /mnt/tmp/android/afwall_build/afwall/src/dev/ukanth/ufirewall/Api.java:546: error: cannot find symbol
    [javac]                     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    [javac]                                                                     ^
    [javac]   symbol:   variable KITKAT
    [javac]   location: class VERSION_CODES
```

But If I build with API 19, it succeeded.

1. Is it OK to use apk built with API 19 on Android 4.2.2/4.3 ?

2. If not, any advice to solve this error?

**Comment by cernekee** [comment]
> Is it OK to use apk built with API 19 on Android 4.2.2/4.3 ?

Yes, if the project is targeting API level 19 but includes Build.VERSION checks to handle older Android releases (as AFWall does), then it should be fine.

If the app mistakenly tries to call an API that is missing in your version of Android, you should see a crash/backtrace.

Do you want to give it a shot and send a patch if everything works correctly?

**Comment by taro-k** [comment]
Thanks. OK, I installed the apk build with API 19 to a Cyanogenmod 11 (Android 4.4.4) tablet and Cyanogenmod 10.1 (Android 4.2.2) phones. If I see any crash, I will report here.

By the way, according to your reply, I think we need to revise the Wiki for building. I will do it later.
https://github.com/ukanth/afwall/wiki/HOWTO-Compile-AFWall#build-via-command-line
