### ISSUE TITLE
different between mode WL BL

### ISSUE THREAD

**Issue by Andre3g** [ukanth/afwall#353]
Hallo,

What is a different between WL/BL mode?
My sugesstion: wl-default-policy=deny instead allow.
Or have I misunderstood something?

details below.

regards Andre.

- testbed
  afwall 1.3.4.1
  filt="policy|10019|10020"  ## uid
  iptables -L -n -v | egrep "$filt"

- test 1 WL (allow selected)
  rules wl-mode:
    [ ] 10019
    [x] 10020

root@android:/ # iptables -L -n -v | busybox egrep "$filt"
Chain INPUT (policy ACCEPT 5 packets, 318 bytes)
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
Chain OUTPUT (policy ACCEPT 34 packets, 3447 bytes)

  - default policy correct?
  - missing Allow 10020

- changes:
  - wl-mode -> bl-mode
  - invert ruleset
  - apply

- test 2 BL (block selected)
  [x] 10019
  [ ] 10020

root@android:/ # iptables -L -n -v | busybox egrep "$filt"
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10019

  - seems to be correct.

**Comment by CHEF-KOCH** [comment]
You're correct with the whitelist/blacklist statements. 
Whitelist mode should only allows selected apps to have network access (in and out / exception: LAN option checked/unchecked).

Some users (including me) reported that e.g. NTP and other services may need some UDP-packets to the DNS severs, which are not been blocked with root rights. Nobody knows why...
Please check non system apps only until someone knows why such services need that. In the meantime I will update our scripts for more security. 

So we still fighting with some _ghost_ traffic that's wrong displayed and of course the whole DNS stuff (mentioned now several times in other issue reports).
