### ISSUE TITLE
External binaries platform support for x64 only systems

### ISSUE THREAD

**Issue by CHEF-KOCH** [ukanth/afwall#359]
Currently AFWall+/iptables/busybox supports:

<code>*\AFWall+\aFWall\src\main\res\raw</code>:
* mips
* arm (no extra armv7 binaries and not always necessary)
* x86

But there is also:
* x64 (aarch64)
* mips64
* arm64

Busybox:
* arm64 daily's/nightly's can be found [here](https://s.basketbuild.com/devs/USBhost/busybox/arm64) (compiled by USBhost from the source)

IPtables:
* I think it's also ready (according to the mailing list)

Klogripper:
* Not ready yet

Nflog:
* Not ready yet

So anything that is related to the last mentioned x64 only stuff, it's problematic on several newer devices and tablets. Well, I know about this for a long time now but the question is to compile the binaries now and add them to the source, or we talking about the necessary of external binaries? - because my standpoint is already clear, imho dropping the internal binary stuff is the only solution to fix several problems and if all was well tested and documented there should be none with our stuff.

So some feedback on this would be nice.

**Comment by ukanth** [comment]
is it required. From my understanding, 32bit binaries should work on 64bit builds. 
https://source.android.com/source/64-bit-builds.html

**Comment by CHEF-KOCH** [comment]
After some more research it's not necessary (yet?). Since Google and other markets using strong terms/rules nobody knows if arm64 devices are forced to use such builds only (_various with device_ label) in the future. If that maybe happens or someone report other things I will re-open this ticket with proper info.
