### ISSUE TITLE
Mention on Notification Filter if it "filters in" or "filters out" items.

### ISSUE THREAD

**Issue by jidanni** [ukanth/afwall#360]
Notification Filter in Log Preferences: mention there if this "filters in"
or "filters out" items.

**Comment by CHEF-KOCH** [comment]
and ?

**Comment by jidanni** [comment]
I am just trying to say you should say "checking boxes below will exclude the item from the log."

**Comment by CHEF-KOCH** [comment]
Or instead of this we could add a description on that Notification Filter button. It's low prio but will be done.

**Comment by jidanni** [comment]
Yes sounds good!
