### ISSUE TITLE
Mention zoom on log menu items

### ISSUE THREAD

**Issue by jidanni** [ukanth/afwall#361]
In the log menu, there are two entries, "+", "-", which should be relabeled "+ zoom" and "- zoom", else one might assume they add and remove entries, or turn something on or off etc.

**Comment by CHEF-KOCH** [comment]
Imho it's clear enouth and well documented in the wiki, there is nothing mentioned about that you can add something to the whole log menu and + and - are international symbols for math, zoom, add/remove and such stuff. 

```java
	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		/* Common options: Copy, Export to SDCard and Refresh */
		SubMenu sub = menu.addSubMenu(0, MENU_TOGGLE, 0, "").setIcon(R.drawable.abs__ic_menu_moreoverflow_normal_holo_dark);
		sub.add(0, MENU_ZOOM_IN, 0, "+").setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
		sub.add(0, MENU_ZOOM_OUT, 0, "-").setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
		sub.add(0, MENU_COPY, 0, R.string.copy).setIcon(R.drawable.copy);
		sub.add(0, MENU_EXPORT_LOG, 0, R.string.export_to_sd).setIcon(R.drawable.exportr);
		sub.add(0, MENU_REFRESH, 0, R.string.refresh).setIcon(R.drawable.reload);
````

These are hard coded strings, means it's not added in strings.xml or there menu. We can edit it directly or add MENU_ZOOM_IN and MENU_ZOOM_OUT with proper string values.

Feel free to add a patch if it's really that important.

**Comment by jidanni** [comment]
Oh. By the way, I've never seen more than one or two items in that log, even after refreshing.

**Comment by CHEF-KOCH** [comment]
That's another possible problem, one by one please. There is already an open thread about that log thing which needs more information to reproduce and confirm such behavior.

**Comment by jidanni** [comment]
OK I opened #363 . Thanks.
