### ISSUE TITLE
Crash after adding new rule

### ISSUE THREAD

**Issue by paloliska** [ukanth/afwall#369]
I installed 2 new apps and allowed connection in AFWall. After hitting Apply crash occured. 
log:
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): FATAL EXCEPTION: Thread-2556
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at android.os.Handler.<init>(Handler.java:205)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at android.os.Handler.<init>(Handler.java:119)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at dev.ukanth.ufirewall.RootShell.showToastUIThread(RootShell.java:382)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at dev.ukanth.ufirewall.RootShell.complete(RootShell.java:215)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at dev.ukanth.ufirewall.RootShell.access$1000(RootShell.java:42)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at dev.ukanth.ufirewall.RootShell$1.onCommandResult(RootShell.java:298)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at eu.chainfire.libsuperuser.Shell$Interactive.postCallback(Shell.java:983)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at eu.chainfire.libsuperuser.Shell$Interactive.processMarker(Shell.java:903)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at eu.chainfire.libsuperuser.Shell$Interactive.access$2100(Shell.java:624)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at eu.chainfire.libsuperuser.Shell$Interactive$6.onLine(Shell.java:1056)
 > 04-24 09:23:35.300 E/AndroidRuntime(23724): 	at eu.chainfire.libsuperuser.StreamGobbler.run(StreamGobbler.java:92)
 > 04-24 09:23:35.370 E/AppErrorDialog(578): Failed to get ILowStorageHandle instance
 > 04-24 09:23:35.409 I/DEBUG   (628): [OnPurpose Redunant in preset_info] pid: 23724, tid: -1361051648, name: UNKNOWN  >>> dev.ukanth.ufirewall <<<
 > 04-24 09:23:36.799 I/Process (23724): Sending signal. PID: 23724 SIG: 9

AFWall 1.3.4.1
device info:
 > build.board: lx84
 > build.bootloader: unknown
 > build.brand: htc
 > build.cpu_abi: armeabi-v7a
 > build.cpu_abi2: armeabi
 > build.device: htc_v1_u
 > build.display: 1.00.118.4
 > build.fingerprint: htc/tmo_pl/htc_v1_u:4.2.2/JDQ39/1.00.118.4:user/release-keys
 > build.hardware: mt6582
 > build.host: vBuild1LX88
 > build.id: JDQ39
 > build.manufacturer: HTC
 > build.model: HTC Desire 310
 > build.product: tmo_pl
 > build.radio: unknown
 > build.serial: CC48VWX00649
 > build.tags: release-keys
 > build.time: 1399464550000
 > build.type: user
 > build.user: rdadmin
 > version.codename: REL
 > version.incremental: 1.00.118.4
 > version.release: 4.2.2
 > version.sdk_int: 17

**Comment by CHEF-KOCH** [comment]
Jupp, according to chainfire, su seems more or less bugged, cernekee need to look at this because he coded it. See #355 at his statement.

**Comment by ukanth** [comment]
This should be addressed in 2.x
