### ISSUE TITLE
[GUI] Help menu back icon not active

### ISSUE THREAD

**Issue by wbedard** [ukanth/afwall#371]
My device: Nexus 5 running Android 4.4.4 (AOSP)
App Version: AFWall+ (v2.0.0-ALPHA-2)

Description: When I enter the Help screen from the AFWall main screen menu, I am then unable to return back to the main screen by using the "back" icon in the upper left of the Help screen.  I can return back to the main screen using the normal Android "back" button on the device.  All other AFWall submenus (i.e. Logs, Preferences, etc) do not exhibit this problem.

**Comment by ukanth** [comment]
Thanks @wbedard. Next version should address this behavior
