### ISSUE TITLE
allowing forbidden traffic

### ISSUE THREAD

**Issue by mis2417** [ukanth/afwall#382]
please forgive no attachments and crude description 

problem is as follows:

application gReader is not allowed to access internet (WiFi) in settings, BUT it is still downloading content from feedly.com

http://imgur.com/2zjeXEk
http://imgur.com/Q5gzKTW

addional details:
gReader was installed before afwall+ and uninstalled (also before). it was never allowed in afwall+. 
afwall+ version is 1.3.4.1 (Google play store) 

need addional details?

**Comment by CHEF-KOCH** [comment]
This was discussed now several times that it isn't possible to block child processes that are depending on other stuff like 1000/Download Manager/GMS/GPS. Solving this can only be done by:

* Block Download Manager/1000/GMS or G Play-Sore
* Find the child process and block them via custom script (adb shell ps)
* Ask the app developer to fix this by implement it's own downloader 

We never fix stuff that are break other things, that's the reasons the custom script stuff exists.

**Comment by mis2417** [comment]
the problem is, it's not download manager but the app itself. and since it is a normal app, and afwall is running with root privs, it's your responsibility.

**Comment by CHEF-KOCH** [comment]
I already wrote the possibility's you have, take it or not. Of course it use the mention things, if not all would be already blocked, there is no per-app data leakage in AFWall+.

**Comment by mis2417** [comment]
whatever, just don't write you accept bug reports
