### ISSUE TITLE
Performance enhancement

### ISSUE THREAD

**Issue by kangyu** [ukanth/afwall#383]
We are working on a project called PersisDroid (http://www.cudroid.com/PersisDroid/) for detecting potential performance issues. Our tool could find performance degradation caused by improper usage of asynchronous executions.
  We find that in some cases your app may suffer a long processing delay.

  Case 1:
  **Related source code** Class: [AppListArrayAdapter](https://github.com/ukanth/afwall/blob/beta/aFWall/src/main/java/dev/ukanth/ufirewall/util/AppListArrayAdapter.java) Method: [getView](https://github.com/ukanth/afwall/blob/beta/aFWall/src/main/java/dev/ukanth/ufirewall/util/AppListArrayAdapter.java#L143)
  **Circumstance** Sometime it takes long to load all the icons of all apps.
  **Problem** *new LoadIconTask().execute(..);* This line of source code would load multiple icons in sequential in Android version greater than 4.0.
  **Suggested modification** I recommend invoke *executeOnExecutor* method to load icons in parallel with a thread pool.

  Case 2:
  **Related source code** Class: [MainActivity](https://github.com/ukanth/afwall/blob/beta/aFWall/src/main/java/dev/ukanth/ufirewall/MainActivity.java) Method: [showOrLoadApplications] (https://github.com/ukanth/afwall/blob/beta/aFWall/src/main/java/dev/ukanth/ufirewall/MainActivity.java#L533)
  **Circumstance** Sometimes slow on displaying applist. 
  **Problem** Source line: (new GetAppList()).setContext(this).execute(); executes the task of displaying the applist in a default queue. If not all the case 1 mentioned tasks of loading icons are finished, the show applist task should wait in the queue for executing. 
  **Suggested modification**  I recommend invoke *executeOnExecutor* method to show app list in parallel to the load icons task.

**Comment by CHEF-KOCH** [comment]
Thanks, could you provide a patch - because I like to compare it with Android Studios own performance diagnosis mechanism and possible fix some other things too.

**Comment by kangyu** [comment]
OK. I'll do it.

**Comment by ukanth** [comment]
Thanks @kangyu for suggestions. I've modified and I see the performance improvements. Closing it now.

**Comment by kangyu** [comment]
@ukanth That's great, sorry that I did not have time these days to patch the program.

**Comment by CHEF-KOCH** [comment]
Thanks.
