### ISSUE TITLE
checking for bogus entries, kernel process logging 

### ISSUE THREAD

**Issue by two-dogs** [ukanth/afwall#384]
AppID :	-11
Application's Name:	(Kernel) - Linux kernel
Total Packets Blocked:	86
[ICMPv6]ff02:0000:0000:0000:0000:0001:ffbb:c33e:null(1)
[TCP]23.59.189.99:80(5)
[TCP]185.33.22.13:10156(33)
[ICMPv6]ff02:0000:0000:0000:0000:0000:0000:0002:80(1)
[TCP]198.232.124.196:443(9)
[TCP]194.132.197.147:443(16)
[TCP]216.58.216.132:80(6)
[TCP]185.33.22.21:10156(1)
[TCP]93.184.215.151:80(6)
[TCP]194.132.196.194:443(8)

using afwall from f-droid, latest on rooted hisense tablet, older sero+ , on #android i was told;
05:17:18] <Khaytsus> Two_Dogs: No, you're confused or whatever you're using is confused.  The kernel does not connect or talk to things, period.

thnks in advance.

**Comment by CHEF-KOCH** [comment]
Please learn and read [how to post a bugreport](https://github.com/ukanth/afwall/wiki/HOWTO-Report-Bug). 

What do you want to show with you statement?
As I already wrote _the kernel_ is just another name for unknown traffic that comes from UID's lower <1000 which possible shows IGMP/ICMP/DNS,.. related things as explained over our [Android Kernel traffic](https://github.com/ukanth/afwall/wiki/Android-kernel-traffic) guide.

**Comment by two-dogs** [comment]
the kernel process is actually making the call or user garbage is collected in kernel process for logging purposes?

**Comment by CHEF-KOCH** [comment]
This is not a bug, it's a question. As written in the given link GitHub is not the correct place to ask common questions about the product, please use the XDA-Thread instead for that. 


But to answer your question, take a look at what the kernel generally does:
* [Kernel Source](https://android.googlesource.com/), [netd](https://android.googlesource.com/platform/system/netd/),....
* [TrafficStats](http://developer.android.com/reference/android/net/TrafficStats.html)
* [Kernel Overview](https://source.android.com/devices/tech/datausage/kernel-overview.html)
* [Android Basics 101: Understanding Kernels](http://www.xda-developers.com/android-basics-101-understanding-kernels-xda-developer-tv/)

Generally there are three types of networking permissions:
* Regular apps using the _PERMISSION_NONE_ permission counting android.permission.INTERNET which AFWall+ watches on 
* To manipulate apps or have access to them, _PERMISSION_NETWORK_ is required
* Core apps or system apps using the _PERMISSION_SYSTEM_ permissions (also uses PERMISSION_NETWORK)
* We learned from the controller that the given permission are depending how fwmark was called, to allow incoming/outgoing stuff like pings, icmp,....
* AFWall+ only listening on them and shows the log messages - deepening if android.permission.INTERNET was present on the system apps e.g. on the LOG target you can run dmesg to show the background stuff 
* Blocking such important things may resulting in data packages loss, network is unavailable and possible other problems
* The rest is [very well explained over here](https://android.googlesource.com/platform/system/netd/+/200e0b53817227453418a432b1384792c1bc29da/server/), what is listening and what are the core related network things

If there are additional question or something unclear, by email is public available, feel free to contact me and I will response as soon as possible and if I have some motivation.

**Comment by CHEF-KOCH** [comment]
To finally answer all kernel questions I worked the past few weeks on a documentation, I will add this in the Wiki if it's confirmed by a friend which knows a lot of more about kernels. 

I hope this helps to avoid common question how the OS works.
