### ISSUE TITLE
Include apk in github releases tab

### ISSUE THREAD

**Issue by rancidfrog** [ukanth/afwall#386]
It would be great to have APK available in releases: https://github.com/ukanth/afwall/releases

Thank you

**Comment by CHEF-KOCH** [comment]
Yes, maybe someday. It's already mentioned in the Wiki but as always it's done if it's done.

**Comment by ukanth** [comment]
https://github.com/ukanth/afwall/releases/tag/v2.0.0-BETA2

**Comment by CHEF-KOCH** [comment]
Thanks for adding this. Pointing to <code>https://github.com/ukanth/afwall/releases</code> also allows to fetch the latest version via scripts (as an example see my gist). I will also update the Wiki.
