### ISSUE TITLE
AFWall+ 2.x RC bugs and glitches 

### ISSUE THREAD

**Issue by CHEF-KOCH** [ukanth/afwall#388]
I removed the previous post since it was highly outdated + the fact some stuff was already fixed but I use this now for giving an detailed overview of AFWall+ 2.0 Beta+ bugs or visual glitches that needs to be fixed before the 2.0 final release could hit the Play Store/F-Droid.

1) SU promt each time you open AFWall+, sometimes it's visible but sometimes not (but in fact it ask every time you open AFWall+ for it [see also SU log that there is a useless request]). - NOT fixed, see also #315.
2) <s>Pressing the left hardware button gives 2 menus, but they're not visible (means no text + font). The main menu is still on the upper right corner with visible text, I guess something is wrong/missing in the layout or menu.</s> Fixed with 762a70cbf367e9438af485caf4e2af3c0cf1941a

![screenshot_2015-08-03-21-00-22](https://cloud.githubusercontent.com/assets/727123/9045521/04a704ce-3a24-11e5-893b-de4bfb59bede.png)

3) <s>On applying the rules you'll see a dialog (.... applying iptables rules...), on touching outside this dialog it disappear without anything. But iptables will be updated (according to the toast) in fact if you want to close AFWall+ you will get the dialog that that there are unsaved changes (but this is wrong).</s> Fixed with da2d7674595bf383eca63be29dbf911000b1d45a
4) <s>Language change glitch, choose another (non system lang) and go back to the main screen. Now close the app and re-open it + rotate you're screen. Close and re-open it again and see that the lang was changed to a mixed one. In some situations it's enough to rotate the screen to see such glitch.</s> Fixed with da2d7674595bf383eca63be29dbf911000b1d45a
5) <s>Crash on on clean/fresh installation. #396  & #399 </s> Fixed in RC, as a _workaround_ simply do a clean installation.
6) The Traffic Details windows use a different (black background), should be the same as the default one (grey).

I guess after this was fixed we can release a new final version to the mass without any negative feedback. Of course as always if this is too much I can help with patches and such stuff.

**Comment by ukanth** [comment]
Thanks. @CHEF-KOCH , Let me have a look at these issues.

**Comment by CHEF-KOCH** [comment]
Thanks for fixing it, but the language toggle glitch is sometimes still active. Right after a reboot, the popup that want to apply the new rules are in another language compared to the main chosen language. 1 only saw this once but it's still present (well low-prio, so what).

**Comment by ukanth** [comment]
@CHEF-KOCH, Can you close this and open a new one ? Some reported issues with Kingo Root and problem with menu doesn't open with menu key.
