### ISSUE TITLE
Removing profiles 1-3 not possible

### ISSUE THREAD

**Issue by PedobearIGER** [ukanth/afwall#391]
It doesn't seem to be possible to remove profile 1, profile 2 and profile 3. 
Why do they exist by default anyway? You could just click on "Add profile" if you should need another one..
![screenshot_2015-07-29-10-35-14](https://cloud.githubusercontent.com/assets/3111510/8953426/a5005578-35de-11e5-8dd6-597f74517e1d.png)
![screenshot_2015-07-29-10-44-36](https://cloud.githubusercontent.com/assets/3111510/8953557/b33df98c-35df-11e5-8078-3547b7dab4f2.png)

**Comment by ukanth** [comment]
Initial versions had default 3 profiles and later adding new profiles was introduced. This was to maintain backward compatibility. You could rename those from preferences and can't be removed.
