### ISSUE TITLE
Removing profile corrupts other profiles

### ISSUE THREAD

**Issue by PedobearIGER** [ukanth/afwall#392]
I have a list of profiles, lets assume it looks like this:

    Default
    
    
    
    A
    B
    C
    D
    E
    F
    G
    H

(The empty lines are Profile 1-3, which I could not remove and then renamed to nothing.)

After accidently deleting the profile "D", I directly added a new profile and called it "D". And now suddenly "E" has lost all settings, "F has got all the setting of "E", "G" has got all the settings of "F", "H" has got all the settings of "G" and so on. Every profile above "C" (including "C") is fine and unchanged though.

**Comment by PedobearIGER** [comment]
...wow I can't even restore the backup of my profiles without the paid version. That's seriously messed up!

**Comment by ukanth** [comment]
I will look into it today. It will be only for donate users !

**Comment by ukanth** [comment]
This issue is fixed in BETA 2
