### ISSUE TITLE
Changing order of profiles

### ISSUE THREAD

**Issue by PedobearIGER** [ukanth/afwall#393]
I have a lot of profiles and there is no way to neatly arrange the list, so I oftenly have a hard time findng the profiles I'm looking for. I would really like to be able to change the order in which they are displayed and being able to alphabetically sort them would also help a lot.

**Comment by CHEF-KOCH** [comment]
If you upload your profiles I could maybe help with this.

**Comment by PedobearIGER** [comment]
Thanks fir the offer, but I have a profile for every app that needs Internet access and every time I install a new app like that, I will create another profile. So I'm really looking for a long term solution here. 
Also (as I just found out), I can't import my exported profiles without the paid version...

**Comment by CHEF-KOCH** [comment]
Well, seems that you're doing it wrong, you doesn't need profiles for every new app installation. For that XPrivacy is a lot of better designed, I also see no argument for that anymore in Android M. As I noted you're also have profiles for enabling/disabling AFwall+ and I ask myself why you use such unnecessary things? Because the firewall should never be disabled, if yes the whole security argument seems obsolete. I highly suggest that you better work with custom scripts which would solve most of the problems.

About the export thing, that's correct how it is.

**Comment by PedobearIGER** [comment]
I don't want to simply give an application Internet access. I want to use Tasker to only give apps Internet access while I'm actively using them. If XPrivacy could do that, this would be great.
But this whole thing is more of a bandwidth saving measure than a privacy concern for me.

Btw, neither did I set up profiles for disabling the firewall, nor would I even think about disablng it (while I have an Internet connection).

**Comment by CHEF-KOCH** [comment]
> I don't want to simply give an application Internet access.

For this we have whitelist support. 


>  I want to use Tasker to only give apps Internet access while I'm actively using them
Tasker is not a firewall app like AFWall+ , apps doesn't connect to anything if they're not running (service/background/foreground). Installing apps doesn't automatically starts them - means no risk.

>  If XPrivacy could do that, this would be great.

Xprivacy have profile support and is a lot of better for restriction permissions (internet/system/network/notification/,...)

> But this whole thing is more of a bandwidth saving measure than a privacy concern for me.

Yes I'm also doing this on 4G/LTE+, but normally you can just use custom script(s) for this or ensure the apps you want to _block_ are not running (take a look at Amplify/AppOpsXposed/Greenify/Prevent Running/,... Modules). The mentioned apps are able to block the intents or just disable the activity after they're closed (often called _hard kill_).

Also note that more scripts/task's and processes coasts more cpu cycles which ends up with more battery consummation. I already wrote some examples in the Wiki how to use custom scripts for such apps that maybe need to running all the time but don't should connect on xyz connectivity. Feel free to mod the examples for your needs.
