### ISSUE TITLE
donation

### ISSUE THREAD

**Issue by joethelion** [ukanth/afwall#394]
Not a development issue!
Can't find other way to mention the following though.

On fdroid repository the donate link goes to home page of http://forum.xda-developers.com/
if you want few bucks for your good and appreciated work ...

**Comment by CHEF-KOCH** [comment]
* Donate version is available on [Google Play Store](https://play.google.com/store/apps/details?id=dev.ukanth.ufirewall.donate)
* The correct link is [this](http://forum.xda-developers.com/member.php?u=3249429), the donatetome must be removed by member, seems incorrect atm.

**Comment by ukanth** [comment]
I will add it later.

**Comment by CHEF-KOCH** [comment]
Another option would be to integrate an separate donating option in our README with an small hint that this is only in case if someone like to spent some money without getting any APK file.

To implement such thing we could use something like this:
```bash
<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=1111111111111" target="_blank"><img src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" /></a>
```

The ID must be replaced.

**Comment by ukanth** [comment]
Thanks @CHEF-KOCH and @joethelion   Added donate button on README !

I will work with F-Droid to add there as well. Thanks.
