### ISSUE TITLE
Another case of loss apps settings

### ISSUE THREAD

**Issue by Diltox** [ukanth/afwall#395]
Good day. 

Your AFWall wonderful app. Useful, precise and accurate. But I want to report a small issue.

In the situation move applications to the SD card when the device boots they sometimes for some unknown reason found by the system with some delay (at this time, their labels are inactive and not loaded icons). Not all and not always.

After a while everything returned to normal. BUT AFWall manages to forget their settings. And you have to configure it again.

By the way, it would be nice to have a sort apps by install time.

I hope it will be useful. Good luck and thanks for the app.

**Comment by CHEF-KOCH** [comment]
Hello, 
please re-label your topic, this have nothing todo with App2SD it's a common problem with profiles & settings, as explained over here -> #338 + #337 + #336 + #335. Some of them should be already fixed.


> By the way, it would be nice to have a sort apps by install time.

This is already implemented in AFWall+ 2.x, you can sort the applications by the name (will be default), by installation (update/upgrade) or UID. I think it's enouth, we also have a search and nobody needs to re-configure the app settings every day. 

Constructive feedback is always welcome.
