### ISSUE TITLE
New startup page for AFWall+ via http://<project-username>.github.io/afwall

### ISSUE THREAD

**Issue by CHEF-KOCH** [ukanth/afwall#408]
Hi, I've created a new startup page, maybe we can adopt this, it's the default skin _Cayman theme_ (imho it's the cleanest and looks best with the default Readme.md). An "Google Analytics" option is also available to find the project better on the www (of course needs an free ID).

The example can be found over [here](http://chef-koch.github.io/afwall). 

To activate this just go to the "Settings" button - scroll down until you see "GitHub Pages" and click on the "launch automatic page generator", you'll see the default Readme.md, click "Continue to layout" and you'll see a skin collection. Click on publish and it's done, the page is now available at <code>http://ukanth.github.io/afwall</code>.

Of course I will update soon or later the Overview for the final 2.x release and add some layout tweaks to it, as always as pull request. 

_Of course other skins are possible._

**Comment by ukanth** [comment]
Nice one @CHEF-KOCH . I always wanted to improve that. If you explain everything with screenshot, that would be great.

**Comment by CHEF-KOCH** [comment]
Well I thought I already did explain it?! :laughing: 

It's very easy to activate, don't worry I promise, just as explained you need go to the _Settings_ button, this will show project specific settings. Now just scroll down (to the middle) and you'll find the _GitHub Pages_ section, just click on the _generate ..._ button and you're mostly done. It's a automatically procedure to simplify things. The rest is as explained, in the next screen you can edit or choose the first page (default our Readme.md will be selected and visible). Now you can optional paste an Google Analytics ID in the right corner so that AFWall+ will be found very easy on the www. So, the last step is to choose the skin, I used the default skin, you can switch to every skin, wait some seconds and you'll see the result almost in real time. That's it, choose the skin (I like the first or the old "time" skin), click _publish_ and that's it, the output goes to the mentioned url which is now our new startup page. 

I'm not posting screenshots it's that easy nobody need that you can't destroy anything since everything can always be changed or reverted.

**Comment by CHEF-KOCH** [comment]
Seems you did it, second skin hm that looks a bit blurry on the Internet Explorer but okay.
