### ISSUE TITLE
Problems with Android 5.x

### ISSUE THREAD

**Issue by mase76** [ukanth/afwall#417]
Hi!
I have problems with my Xperia Z1 with CM12.1.
With activated Afwall there are reconnection problems in my wlan. I have to delete and reenter the connection. Otherwise I get the exclamation mark next to the wlan symbol. With deactivated Afwall it works fine as expected. I use the 2.0 alpha version from f-droid. I had the same version and settings in Kitkat without problems.
Can anybody confirm this issue?

**Comment by an0n981** [comment]
1. There us a RC avaiable.
2. If you are blocking UID 100 try entering this terminal command to disable captive portal detection:

su -c "settings put global captive_portal_detection_enabled 0"

**Comment by mase76** [comment]
Disabling captive portal detection seems to work.
Maybe this should be (optionally) done by afwall,
as it already has root permissions.

**Comment by ukanth** [comment]
Doing that using AFWall+ will violate playstore policy I guess. https://play.google.com/about/developer-content-policy.html (System Interference)
