### ISSUE TITLE
The language selector and the auto language detector are broken

### ISSUE THREAD

**Issue by softastur** [ukanth/afwall#421]
When you install for first time Afwall+ or try to change the application language in preferences menu, the language selector and/or the auto language detector don't work. The problems appears using Android 5.1.

Thank you.

**Comment by CHEF-KOCH** [comment]
Can you upgrade to 5.1.1 and see if that works or not works and report back? Thanks.

**Comment by softastur** [comment]
I tested it on Android 5.1.1 and it doesn't work

**Comment by CHEF-KOCH** [comment]
Sorry I can't confirm, it worked here (AOSP 5.1.1 r13). 

You can remove and wipe AFWall+ with it's settings and re-install and see if that fixed your problem. It's possible that during the upgrade from 1.x to 2.x that there are some _complications_.

**Comment by softastur** [comment]
Hi again.

I reinstalled Android and it doesn't work, also i tested on CyanogenMod and any good result. It's strange.

**Comment by CHEF-KOCH** [comment]
Okay I will look into this, please provide a screenshot.

**Comment by ukanth** [comment]
@softastur , what device are you using ?

**Comment by CHEF-KOCH** [comment]
This is only on a fresh installed AFWall+ + an CM nightly based rom . 

Symptoms are that even if you switch a language and restart the app, it shows on the language chooser that the correct language was used but the GUI still uses the system wide one.

**Comment by softastur** [comment]
Hi, sorry for the delay.

I reinstalled Afwall+ again and when it checks for root access the app crashes:

10-01 23:08:48.696    6574-8427/dev.ukanth.ufirewall E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-374
    Process: dev.ukanth.ufirewall, PID: 6574
    java.lang.NullPointerException: Attempt to invoke virtual method 'void a.a.a.c$c.a(java.lang.String, int, a.a.a.c$d)' on a null object reference
            at dev.ukanth.ufirewall.service.RootShell.b(RootShell.java:263)
            at dev.ukanth.ufirewall.service.RootShell.c(RootShell.java:245)
            at dev.ukanth.ufirewall.service.RootShell.a(RootShell.java:45)
            at dev.ukanth.ufirewall.service.RootShell$3.a(RootShell.java:346)
            at a.a.a.c$c$1.a(Shell.java:699)
            at a.a.a.c$c.a(Shell.java:983)
            at a.a.a.c$c.k(Shell.java:903)
            at a.a.a.c$c.e(Shell.java:624)
            at a.a.a.c$c$6.a(Shell.java:1056)
            at a.a.a.f.run(StreamGobbler.java:92)

I'll post another replay when i can debug the language specific part.

Bye.
