### ISSUE TITLE
Doesn't update the list of installed apps

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#425]
For about a two weeks or so, new installed apps haven't been visible in AfWall+. The issue might have started after I enabled "fix startup data leak" (now disabled; my HTC One M7 has never been "S-OFF") in the experimental settings.
I may have to do a complete reinstall. Manual " reload" doesn't solve the problem.

-CyanogenMod 12.1, HTC One M7
AFWall+ 2.0 alpha 2

**Comment by Magissia** [comment]
Check if the init. d script created by this option was actually deleted when you unchecked.
