### ISSUE TITLE
Known Widget problems on AFWall+ 2.x+

### ISSUE THREAD

**Issue by CHEF-KOCH** [ukanth/afwall#432]
These are the widget _bugs_ and _glitches_ in AFWall+ on the final 2.0 version.

Reproducible it via:
* Rom doesn't matter it's a software bug.
* Place all three available widgets on the screen.
* Clean install AFWall+ (also wipe all data if present) and not set anything in any preferences. 

1) The widget that shows a quick toggle (the round one to the left on the first screenshot) will always tell something about that the configuration is locked if we're pressing the enable/disable buttons. This is a logic failure since nothing was set (only on clean installation). A workaround is to set 'none' under the preferences, so this will be again accessible. 
2) The two widgets with the question mark in it doesn't allow to lose the focus on touching on an empty field. You must press the return hardware key. 
3) The mentioned widget from 1) isn't on center. The other one is always on center (which seems okay).
4) Widget from 1) isn't displayed correctly since different languages not fit with this. 
5) Reboot you're device and you notice that the two question mark widgets are present, the quick toggle widget needs some time to get the status and is only visible AFTER that. On slower devices you see nothing until it's calculated and it will be visible after all is done. On faster devices this is around ~1 second.
6) The two widgets that contains the question mark are a bit _confusing_, well not for me but they look exactly the same. So I suggest (if someone have an idea, to make a better ones). Maybe the configuration one with a wheel or something that will be seen as 'preferences' and the other one, I don't know ... surprise me. 
7) Possible #424 bug during profile names and not centered display messages. Only with multiple profiles. See 7) for screenshots.
8) The status icon (the small one from 1.) doesn't always show the correct status. This is on some rare conditions, like if you're changed directly the status from e.g. enabled -> to disabled or such.

![screenshot_2015-09-23-13-56-21](https://cloud.githubusercontent.com/assets/727123/10044477/aa75127a-61fb-11e5-976e-1e555b73a7ed.png)
![screenshot_2015-09-23-13-56-54](https://cloud.githubusercontent.com/assets/727123/10044481/ae7c3934-61fb-11e5-8282-64cbb75bbe34.png)

7) [Screenshots original by nutpantz, thanks for reporting]
![1b5dcc00-61cc-11e5-82d2-3aa3084be120](https://cloud.githubusercontent.com/assets/727123/10049849/b93248dc-6219-11e5-864b-5ae28a228791.png)
![5c37a610-61cc-11e5-8242-d7d9bdcbe4cd](https://cloud.githubusercontent.com/assets/727123/10049856/bf5f7ed2-6219-11e5-870e-1957e3aace11.png)
![7b4b4ad4-61cc-11e5-8426-8df6b608cba3](https://cloud.githubusercontent.com/assets/727123/10049862/c547d61e-6219-11e5-8bd4-b9803fcbe1e5.png)

**Comment by nutpantz** [comment]
On the mega i527m running cm11 4.4.4 with nova launcher, apex launcher and the oem launcher 
![screenshot_2015-09-03-09-14-10](https://cloud.githubusercontent.com/assets/12160507/10049383/1b5dcc00-61cc-11e5-82d2-3aa3084be120.png)
![screenshot_2015-09-19-19-16-32](https://cloud.githubusercontent.com/assets/12160507/10049450/5c37a610-61cc-11e5-8242-d7d9bdcbe4cd.png)
![screenshot_2015-09-19-19-17-49](https://cloud.githubusercontent.com/assets/12160507/10049477/7b4b4ad4-61cc-11e5-8426-8df6b608cba3.png)

**Comment by CHEF-KOCH** [comment]
Thanks, this is due profiles. I grab your screenshot and resize them and attach them.

**Comment by ukanth** [comment]
@CHEF-KOCH @nutpantz , Can you check with 2.1.1 ?

**Comment by CHEF-KOCH** [comment]
Nope, it's getting more worse, especially if you use an ROM with scalable DPI. If you reduce the DPI it will be getting more and more to the right corner. On higher DPI it's more central.

**Comment by ukanth** [comment]
Which ROM has scalable DPI ? I will test it with that ROM and see how to fix it ?

**Comment by CHEF-KOCH** [comment]
Well, every ROM supports the ability to change the DPI, but some coming with integrated support to change that (the UI needs to restarted for it). E.g. Resurrection Remix ROM which is based on CM (nightly's) have such option integrated. It's avaible for Samsung S4, S2 and some [others](http://androidxda.net/update-galaxy-s4-i9500-to-android-5-1-1-via-resurrection-remix-rom/). Newer CM versions also have some apps included to change that.

**Comment by nutpantz** [comment]
On my mega the nearest build 211 it is worse. Everything has moved down more and to the right more. Factory oem 442 almost completely unusable now, cm launcher, nova and apex all much worse.
Noting had been done to these installed roms like changing dpi or anything.

**Comment by CHEF-KOCH** [comment]
Yes this was due the latest update. Imho it should be set to center, all the time which also would work DPI or scaling independence. The other Widget works like that.

**Comment by nutpantz** [comment]
Newest update 212 no improvement for me on my mega. I think it's exactly the same

**Comment by CHEF-KOCH** [comment]
Yes, please wait and monitor changelog file to see what was fixed.
