### ISSUE TITLE
[regression] White/black list mode isn't changed on profile switching

### ISSUE THREAD

**Issue by ildar** [ukanth/afwall#439]
Just installed 2.1.1 from F-Droid.
I found that on profile change the Mode doesn't change visually.
I.e. I have one profile in White list mode and another in Black list mode. So they aren't changed on Profile switch. Although if I hide then show the AFW, it shows the mode correctly. And firewall works correctly.

**Comment by CHEF-KOCH** [comment]
Yes, it's not only the 'Mode' toggle, something really messed up with the latest releases. The language toggle, the Mode changer, enable/disable this is possible bugged. The strange part, after AFWall+ was proper configured up and you restarted the OS it seems to work.

**Comment by ukanth** [comment]
@ildar, This will be addressed in the next minor release.
