### ISSUE TITLE
frequent 'toast' messages from SuperSU

### ISSUE THREAD

**Issue by alanthehat** [ukanth/afwall#444]
I'm not sure whether I have V2.1.1 or V 2.1.2 

I did not notice previous versions generating 'toast' messages from SuperSU, but this version makes one every few minutes. 

I am using 3G & signal strength/quality seems to make little difference.

**Comment by CHEF-KOCH** [comment]
Please use the search, there are already reported and still opened threads for this (including several workarounds).
