### ISSUE TITLE
AFWall 2.1.1 - UI Preference, Active Rules toggle bug

### ISSUE THREAD

**Issue by sylikc** [ukanth/afwall#447]
I'm on Android 5.1.1 (though android version probably doesn't matter on this UI bug)

Anyways, in AFWall+ 2.1.1, ...

Setup:
1) Head into Preferences > User Interface
2) If _Active Rules_ checkbox is not enabled, set to CHECKED
3) Set _LAN Control_ to CHECKED
4) Exit Preferences.
Result: 3 checkboxes show on main UI.

Reproduce bug:
1) Head into Preferences > User Interface
2) Uncheck _Active Rules_...  _Roaming Control, *LAN Control_, _VPN Control_ should grey out
3) Check _Active Rules_... whatever was previously checked should show checked
4) Exit Preferences
Result: only 2 checkboxes show on main UI.

If you head back into preferences, the remaining checkboxes are not selected under _Active Rules_

It appears that when toggling Active Rules, the displayed UI indicates the dependent checkboxes are checked, when in fact they are not checked.

This bug could apply to other dependent checkboxes, though I haven't verified yet.

**Comment by ukanth** [comment]
I think it works as expected. If you uncheck Active rules, LAN/Roaming and VPN columns will not shown in main UI, because those are depend on "active rules" logic.

**Comment by sylikc** [comment]
Well the unchecking part is correct... the LAN/Roamin and VPN columns depend on the "Active Rules" logic.

However, the re-checking without exiting the setttings has an issue.  Unchecking doesn't clear the checkbox displayed, however, it has already been "unchecked" in logic

Step 2 and 3 in "Reproduce" does "uncheck" then "check" without exiting settings.  The way it is DISPLAYED is that the LAN/Roaming/VPN boxes stay checked.  However if you leave and come back, the LAN/Roaming/VPN boxes are unchecked.

Either ... the LAN/Roaming/VPN boxes should be automatically unchecked when unchecking "Active Rules" ... or, since they are DISPLAYED as checked, the boxes should show on the main window (meaning if you go right back into settings, the boxes should remain checked)

**Comment by ukanth** [comment]
Fixed in 2.9.x versions
