### ISSUE TITLE
Google Contacts & more

### ISSUE THREAD

**Issue by fysika** [ukanth/afwall#448]
Running Resurrection Remix 5.1.1 with the latest AFWall+ and SuperSU 2.49 (with granted access to AFWall+).
Couldn't find an issue representing mine, so there you go.

I can setup the filters for user apps just fine, but Google Contacts synching (which I want to allow) I cannot seem to setup right. I select it in the list, it gets shuffled upwards just fine, still showing selected (thus whitelisted). But if I refresh the list (drag down), the selection is gone again and Google Contacts remains blocked.

Edit (12:33): Seems to be all the yellow colored item I can't edit. Is this a rights/security issue?

**Comment by fysika** [comment]
Never mind, noob PEBKAC issue! /me slaps his face with a large trout.

**Comment by CHEF-KOCH** [comment]
... what?
