### ISSUE TITLE
AFwall on stock Gingerbread logging error + error applying iptables rules

### ISSUE THREAD

**Issue by thepahtmaster** [ukanth/afwall#449]
AFwall for Gingerbread versions 1.2.8 and 1.3.4.1 (which I understand was the last version to support GB),

I'm running stock Gingerbread 2.3.6 with the stock kernel 2.6.35.7 My device is rooted and AFwall has su permisions.

I've tried both the above versions of AFwall but neither are working properly:

(1) The (stock) kernel is reported as not supporting logging?
(2) There is an "error applying iptables rules" but without a log I can't investigate further; and
(3) "something" is happening because after the above error message, no apps are allowed to use my data connetion - it goes dead and my phone needs a restart.

Would it assist if I compled a version from source (have not done that before, but could give it a go).

**Comment by ukanth** [comment]
You should see the error message under Firewall Rules ( at bottom ). Looks like your stock kernel doesn't support LOG/NFLOG chains or even doesn't support iptables.
