### ISSUE TITLE
Root acces

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#450]
On Cyanogenmod, whenever root is being used a # symbol is visible on the notification bar.
Whenever an app performs a root action it should acces root, do it's thing and quit root acces again. 
Afwall however keeps root acces even after applying the rules. I need to manually close the app for the # symbol to dissapear.
Now, afwall also starts by itself every now and then aswell as on startup. 

Besides the fact that the 'root is beging used' # symbol is rather annoying to have permanently on the status bar. It shouldn't, after applying rules it should quit root access. (Perhaps for security reasons aswell)

**Comment by ukanth** [comment]
I'm not sure why cyanogenmod shows like that. But AFWall+ starts a shell in background and actively apply rules when there is a connection change. This is mainly used for Roaming/LAN/VPN support.

You can disable "Active Rules" If you don't want to AFWall+ runs in background.

**Comment by ghost** [comment]
Can't you make it so that the shell quits after applying rules. So that, when there is a connection change it opens the shell, applies the rules and quits it after it's done.

**Comment by ukanth** [comment]
Unfortunately no. it will make firewall applying rules slowly and might end up in race condition when frequent change in connection.

**Comment by ghost** [comment]
Right, I'll disable active rules then. Will the firewall still function properly with seperate LTE/wifi rules?

**Comment by ukanth** [comment]
as long as you don't want LAN/VPN/Roam option, then Yes.
