### ISSUE TITLE
Use tag v2.1.2 instead of V2.1.2

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#451]
Hi,

all previous Tags had a small "v" where 2.1.2 is now using a capital "V". This makes it hard on f-droid to detect new released versions of the app. Could it be possible to change the tag to v2.1.2 again and stay with the small " v" or are you planning to use the capital "V" now?

**Comment by ukanth** [comment]
Thanks for letting me know. My mistake and will fix it today.

**Comment by ghost** [comment]
@ukanth Thanks. Its also fine if you're just tagging the next release with a lowercase "v" and then we could close this issue and i'm just building the 2.1.2 manually on f-droid.

**Comment by CHEF-KOCH** [comment]
#460

**Comment by ghost** [comment]
Yes, seems it was already built manually so closing here.
