### ISSUE TITLE
CM 12.1 random reboot problems

### ISSUE THREAD

**Issue by Micha-Btz** [ukanth/afwall#453]
Hi there,

i have with my Sony Z1 Compact reboots, at least once a day. I don't know it it really has to do with afwall. But at some point i have to start digging.

At the reboot there are no kernel last_kmsg created, but  several thombstones. As mentioned, i don't
know it afwall crashed, because the device rebootet or reboot the device because afwall crashes.
So i want you to take a look at the debug output.

https://gist.github.com/Micha-Btz/332384b905e94185c1a0
https://gist.github.com/Micha-Btz/4a0e715db50349d0e9ee
https://gist.github.com/Micha-Btz/3bbb1103af2828051189
https://gist.github.com/Micha-Btz/880dc69ee696cd924a3b

Would be great if you can take a look, maybe the busybox is guilty.

Thanks Micha

**Comment by ukanth** [comment]
Just a glimpse at logs, it looks like klogripper (logging service) is crashing often. for now can you disable Logging service disabled ? I will have a look why it's crashing.

**Comment by Micha-Btz** [comment]
i don't know how to disable the klogripper, can you give me a hint?

**Comment by CHEF-KOCH** [comment]
You need to disable the logging service it's under Preferences -> Log -> 'Turn on log service' (must be set off). Also ensure you use the latest BusyBox (don't know if your ROM already integrated it, should be). But you can check with BusyBox on Rail app if it's proper installed, just install it, check the status and if it's says it's broken, let it fix an reboot. Try after that to re-enable the logging service and see if that still crashes.

**Comment by Micha-Btz** [comment]
ok, i have deactivated the logger, will see.
busybox is 1.22.1 directly from cm12.1

**Comment by CHEF-KOCH** [comment]
Latest BusyBox at time of writing is 1.24.1.

**Comment by howtosayhello** [comment]
Hi,
I'm having the same issue on a Z3C on CM12.1, found that AFWall is often crashing on route change so I have to force stop it and reapply rules to regain internet access. It would often reboot too.
@Micha-Btz Did you resolve this issue somehow ?

**Comment by Micha-Btz** [comment]
@howtosayhello 
i have disabled Logging service and have never a crash again. but i didn't test if it is working inn newer versions.

**Comment by howtosayhello** [comment]
@Micha-Btz Thanks for the info, tried it and it didn't reboot for 24h.
I can see in the change logs of 2.2.2 fix: additional steps to kill klogripper process.

**Comment by Micha-Btz** [comment]
[tombstone_02.txt](https://github.com/ukanth/afwall/files/381581/tombstone_02.txt)

tested today with v2.2.3 from f-droid. crashed within 30min :-(

**Comment by ukanth** [comment]
@Micha-Btz , klogripper has been removed from AFWall+ from latest beta. Please try latest beta.

**Comment by Micha-Btz** [comment]
@ukanth the log works well in latest beta 2.2.4.Beta3

the beta itself is sometimes a little bit laggy and sometimes it hangs completely 
sometimes at openen app, sometimes during scrilling through the app list

**Comment by ukanth** [comment]
@Micha-Btz . Thanks for the feedback. have you compiled using latest code ? because I have not released Beta 3 and i'm still working on improving performance.

**Comment by Micha-Btz** [comment]
@ukanth i have compile it yesterday evening by myself. One thing i also have is that after change the
internet source from wlan to mobile network, sometimes the rules doen't apply again. So that the changed device is not used and therefore internet is not working

**Comment by ukanth** [comment]
@Micha-Btz   can you send me logcat along with iptables rules when that happens ?

**Comment by Micha-Btz** [comment]
with latest version on f-droid v2.5.2 logging works well and the switch between wlan / mobile network
is as quick as the old release, so closing this.
