### ISSUE TITLE
Block all apps when reboot and have to apply rules manually

### ISSUE THREAD

**Issue by dun-x** [ukanth/afwall#454]
When I reboot my phone, AFWall+ icon show in notification with this "Firewall is running"  but all apps are blocked from internet. I have to open AFWall and apply rules manually.
I can't enable Log too, is there any alterlative way to know what connections have been blocked. Thanks 

I'm using Zenfone 5, Android 5.0

**Comment by CHEF-KOCH** [comment]
Ensure you unchecked the experimental option 'fix startup leak'. Since I've never heard of 'Zenfone' I can't tell anything about that ROM/Phone, does it use AOSP or it's on modified version?

**Comment by dun-x** [comment]
Oh. Zenfone 5 is name of the phone made by ASUS company. 
http://www.gsmarena.com/asus_zenfone_5_a501cg-7160.php 
I'm using stock rom. is there anything you want to know about this rom? I'll try to study it.

Ah, I have already check "fix startup leak".

**Comment by CHEF-KOCH** [comment]
We need an debug from the boot until you can access the first app which is blocked. Without it we can't fix anything.
