### ISSUE TITLE
How to disable the "afwall+ blocked:..." notifications 

### ISSUE THREAD

**Issue by horacioj** [ukanth/afwall#455]
Hi, 
Before posting, I performed a search in the issues list, but couldn't find anything. 
Is there any way to disable the "afwall+ blocked:..." notifications? 
Because they happen too often, and are very intrusive. 
Thanks

**Comment by CHEF-KOCH** [comment]
Yes, it's under Preferences - Log - 'Turn on log service' (ensure it's unchecked). Please close this, because this isn't any issue and had better been asked in the XDA thread.

**Comment by horacioj** [comment]
Thank you! 
Dumb me, couldn't find the settings
