### ISSUE TITLE
Reject to all except LAN

### ISSUE THREAD

**Issue by jonpolak** [ukanth/afwall#459]
There is a rule, when you're excluding everything except private LAN
`afwall-wifi-wan all -- anywhere !192.168.86.0/24`
I'm wondering if your intention wasn't `!{192.160.0.0/16,10.0.0.0/8,172.16.0.0/12}` being the set of all possible private networks. 

Do you distinguish between:
1. ALLOW app123 when connected to **my** LAN (meaning my ip is 192.168._86_.0/_24_)
2. ALLOW app123 if _destination_ is **my** LAN (dest addr is in 192.168._86_.0/_24_)
3. ALLOW app123 if _destination_ is **any** LAN (dest addr is in 192.168.0.0/**16**, 10.0.0.0/8)

**Comment by ukanth** [comment]
It should work with 192.168.X.X in this case.

**Comment by jonpolak** [comment]
In which direction? That I need to be connected to 192.168.X.X or that the
packet destination is 192.168.X.X.

**Comment by ukanth** [comment]
Once you are connected an IP in 192.168.X.X

**Comment by jonpolak** [comment]
From the IPtables rules, you've implemented /24  but above you're saying
192.168.x.x which is /16.
