### ISSUE TITLE
2.1.2 on F-Droid?

### ISSUE THREAD

**Issue by ZatsuneSakurako** [ukanth/afwall#460]
"We can't build this version: The build for this version was manually disabled. Reason: iptables C preprocessor /lib/cpp sanity check fails"
Version 2.1.2 will be on F-Droid?

**Comment by ukanth** [comment]
There are no major changes from 2.1.1, I can't find any logs why it fails. Could you get me the logs from f-droid build. So that I can check it ?

**Comment by ZatsuneSakurako** [comment]
I'm just a user, I don't know where to find them. My phone have that weird bug on the animation running... too fast

**Comment by ukanth** [comment]
Ok, I will work with F-Droid on this.

**Comment by ZatsuneSakurako** [comment]
I wanted to open an issue here in case you're not using F-Droid.

Should I close the issue here?

**Comment by ukanth** [comment]
Keep it open, I will close it once this is resolved.

**Comment by ZatsuneSakurako** [comment]
Okay

**Comment by ZatsuneSakurako** [comment]
2.1.3 Seems to be available on F-Droid now
