### ISSUE TITLE
FTP clients failing to work with afwall enabled

### ISSUE THREAD

**Issue by KopiasCsaba** [ukanth/afwall#463]
Hello!

Thank you for this great app!

I would like to share, that with afwall enabled (One plus one, latest rooted cyanogen os -- if that matters) ftp apps fail to work correctly. This happens when they are allowed to access the internet and the firewall is enabled.

I'm using this: https://f-droid.org/repository/browse/?fdid=be.ppareit.swiftp_free

Also tried this:
https://f-droid.org/repository/browse/?fdfilter=simple+ftp&fdid=org.primftpd

The symptoms are the following:
Login works, but file transfers behave weird, they are getting not 100% up/downloaded, or they are unable to  rename from "foobar.part" to "foobar".  Or random permission denied errors popping up.

With the firewall disabled all works fine. Strange uh?

So please check it out if you can, let me know if i can help in debugging!

Thank you very much!

**Comment by ukanth** [comment]
Logs would be really helpful. Otherwise it's difficult to understand the issue.

**Comment by KopiasCsaba** [comment]
Thats all:

D/SessionThread( 3010): Received line from client: PASV
D/CmdPASV ( 3010): PASV running
D/LocalDataSocket( 3010): State cleared
D/LocalDataSocket( 3010): Data socket pasv() listen successful
D/CmdPASV ( 3010): PASV sending IP: 192.168.1.52
D/CmdPASV ( 3010): PASV completed, sent: 227 Entering Passive Mode (192,168,1,52,166,59).
D/SessionThread( 3010): Received line from client: retr /sdcard/stuff/tmp/20160102_Kori2/IMG_20160102_143151.jpg
D/CmdRETR ( 3010): RETR executing
D/FtpCmd  ( 3010): Parsed argument: /sdcard/stuff/tmp/20160102_Kori2/IMG_20160102_143151.jpg
D/LocalDataSocket( 3010): onTransfer pasv accept successful
D/LocalDataSocket( 3010): State cleared
D/CmdRETR ( 3010): RETR opened data socket
D/CmdRETR ( 3010): Transferring in binary mode
D/SessionThread( 3010): Closing data socket
D/CmdRETR ( 3010): RETR done

While my ftp client on desktop says: "Could not read file ....", so it happened while downloading from the phone, upload was fine this time.

With ftp server demo.

**Comment by Gitoffthelawn** [comment]
Do you have _Linux kernel_ and _Linux shell_ whitelisted?  If not, try whitelisting them.

**Comment by lynxzp** [comment]
Hi, Linux kernel in whitelist help, but it's not obviously that problem in afwall. Because, in my situation, ftp transfer work, but files broken. I tried several ftp servers and clients before check afwall.

P.S. Linux kernel in whitelist fix low speed skype transferring file.

**Comment by ukanth** [comment]
Please provide firewall logs with iptables rules in order to understand the issue. Reopen this issue when you provide the same. Thanks !
