### ISSUE TITLE
vpn control 

### ISSUE THREAD

**Issue by mis2417** [ukanth/afwall#464]
perhaps it should be noted somewhere that unless you explicitly enable vpn control - all apps are permitted by default to use vpn connection, even if only "whitelisted are enabled". 
example : app is enabled only for lan, but when vpn is enabled on wifi - it can reach google.com without problems. 

afwall 2.1.3

**Comment by ukanth** [comment]
I need more information. Please read how to submit bug report from wiki. Please reopen when you provide the same.

**Comment by mis2417** [comment]
this is really quite simple.

when no vpn option is enabled in settings("VPN Control / Enable this to add additional features to control intrnet with vpn") any and all vpn connections are allowed by default. 
to illustrate:

![allowed](https://cloud.githubusercontent.com/assets/8217073/17413254/cd482318-5a80-11e6-8d95-5ad0c6a9099e.png)
![disallowed](https://cloud.githubusercontent.com/assets/8217073/17413274/dedc01b2-5a80-11e6-9ea0-abde8be8e6ee.png)
![novpn](https://cloud.githubusercontent.com/assets/8217073/17413283/e4b0ffde-5a80-11e6-95f1-43faef94cb82.png)

(please notice whitelist mode is selected)
i think it should be explicitly mentioned in settings, that unless "VPN Control" is enabled in settings, all vpn connections are allowed if vpn is active.
