### ISSUE TITLE
Blocking linux kernel even when it is whitelisted

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#475]
I enabled AFWall+ logging and "toasting" of blocked connection attempts.  The following two toasts later appeared:

```
 AFWall+ Blocked : (Kernel) - Linux kernel (-11) -239.255.255.250:null
```

and

```
 AFWall+ Blocked : (Kernel) - Linux kernel (-11) -null:null
```

This would not be a problem, except that I have the following whitelisted for all network types:  

```
  -11: (Kernel) - Linux kernel
```

This appears to be a bug.  Is it?

**Comment by ukanth** [comment]
Yes. it's a bug. I will fix it in next version

**Comment by Gitoffthelawn** [comment]
Great.  Thanks!

BTW, is the bug that it is being blocked or that it is reporting it as blocked when it is not?

**Comment by ukanth** [comment]
later is correct.

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Is this fixed? If so this can be closed, right?

**Comment by ukanth** [comment]
This is fixed.
