### ISSUE TITLE
None of the links in the About screen are functional

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#476]
None of the links in the About screen are functional.

(The link to the FAQ in the FAQ page works as expected.)

**Comment by ukanth** [comment]
Yes. It's fixed already  in playstore version. Are you on 2.1.1 ?

**Comment by Gitoffthelawn** [comment]
Yes, I'm on 2.1.1

Are the links supposed to be working in that version?  If so, they are not working for me.

**Comment by ukanth** [comment]
No. But it's fixed in 2.1.3

**Comment by Gitoffthelawn** [comment]
I didn't realize the Play Store version was slightly ahead of F-Droid.  Any reason why?

**Comment by ukanth** [comment]
F-droid build process has been changed and it's failing to build. I got logs from f-droid. I will fix it in the next version.

**Comment by Gitoffthelawn** [comment]
Great.  Thanks!
