### ISSUE TITLE
Afwall 2.1.1 Widget unable to disable firewall

### ISSUE THREAD

**Issue by KopiasCsaba** [ukanth/afwall#478]
Hi!

Putting the simple afwall widget onto the desktop says in a toast: Cannot disable firewall - password defined.

But, there is no password defined.

**Comment by ukanth** [comment]
It's fixed in 2.1.3. Please test it and let me know.

**Comment by KopiasCsaba** [comment]
I've tested it, and the problem persists:(

**Comment by ukanth** [comment]
Try to set the password to none or clean the data. I will check it.

**Comment by KopiasCsaba** [comment]
I did not have a password ever, now i've set it to something, then i set it to none, and yes: it has been solved!

(I've also enabled device admin, i'm sorry, i hope that doesn't have anything to do with my results)

**Comment by ukanth** [comment]
Have you used import/export feature ? Because I changed the way I set the password in previous versions and changed it in newer versions.

**Comment by ukanth** [comment]
This might be due to some old data issue. Hence closing.

**Comment by deMattin** [comment]
I had the same issue and in my case with AFwall+ 2.2.2 it has been, that there has been set no default value in:
preferences -> security -> enable protection
I set it to "none" and the widget worked immediatley

I've installed afwall+ long time ago (F-Droid) and am using it, but never used or set the password protection or the widget before.
