### ISSUE TITLE
Application stuck at start (checking root access)

### ISSUE THREAD

**Issue by syldub69** [ukanth/afwall#479]
Hi,
The app was well working on my rooted smartphone (Xiaomi RedMi 1S) since more than a year. But since few months (I think 11/2015), it doesn't work anymore. 
The app keep stuck at the start with a never ending message : "Status : Checking root access..." (look at the screenshot). I can't cancel this message, so I can't access to the application.
I have tried those but issue is still there : 
- cleared the app cache, 
- re-rooting my phone,
- uninstalled then reinstalled the app,
- upgraded the smartphone ROM...
  I use AFWall+ v2.1.3 (last version).
  Do you have an idea?

![screenshot_2016-01-06-01-11-40_dev ukanth ufirewall](https://cloud.githubusercontent.com/assets/16567425/12131603/5a765c3c-b414-11e5-8a66-ecacbe42d73f.png)
![screenshot_2016-01-06-01-12-25_com android settings](https://cloud.githubusercontent.com/assets/16567425/12131605/5f659fbe-b414-11e5-8168-7b7673d3c32c.png)

**Comment by ukanth** [comment]
Which su app you are using ?

**Comment by syldub69** [comment]
I was using the SuperSU version from TWRP 2.8.7.0.
I tried today to update SuperSU to last version 2.46.
Now the "Checking root access" stops then it asks to grant permissions to AFWall+. I grant them, and now it works.
Thanks for your support !

**Comment by ukanth** [comment]
Thanks. Kindly update playstore rating as well if you rated.
