### ISSUE TITLE
AFWall+ 2.1.3 auto disables

### ISSUE THREAD

**Issue by liphistius** [ukanth/afwall#481]
Steps to reproduce:
1) Select apps to be allowed through as normally.
2) Save rules
3) Activate firewall
4) Wait
5) AfWall returns a notification that it is disabled.

Issue has not been present in version 2.1.1 originally but after downgrading the app occasionally stops working although it indicates it is active.

Device: Redmi Note 2
Chipset: Mediatek MT6795 Helio X10
CPU: Octa-core 2.0 GHz Cortex-A53
OS: MIUI 7

**Comment by ukanth** [comment]
There could be multiple scenarios where afwall gets disabled itself. One of the main reason is if it's not able to apply a specific iptables rules after 'n' number of tries. 

Please attach the firewall logs from Menu->Firewall Rules-> export and attach/copy&paste here.

**Comment by centauross** [comment]
Hi, I have the same problem.  The afwall auto disables. You can download the steps for detect this issue and in the same sense you could get the logs of this moment through the link (I tryed to attache a .zip file, but it was not possible).  If you have any doubt, please do not hesitate in contact me.

For download the issue

http://bit.ly/1T9I4A5
