### ISSUE TITLE
Afwall disables itself if an usb ethernet card is added to the device 

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#483]
HI

I have a tablet that accepts usb ethernet card via otg usb converter. The problem is that whenever I add it to my device, Afwall does not like it and it disables the firewall and  it cant enable the firewall. Removing the network card makes Afwall very happy.

**Comment by ukanth** [comment]
Thanks for reporting the issue. It would be great if you could attach logcat or firewall log (menu-firewall rules-export) to find out why it's happening ?
