### ISSUE TITLE
Busybox update v1.24.1

### ISSUE THREAD

**Issue by CHEF-KOCH** [ukanth/afwall#484]
I compiled all latest busybox binaries with pie and no pie support. It can be downloaded over [here](https://userscloud.com/11r4tfnf18po). Would be nice if you merge it ukanth. Sr for no pull request but I sent it over Android app.

**Comment by ukanth** [comment]
First, We have pie wrapper for all executable. Second, I need busybox-defconfig for source build.  
Also just wondering is there a need to update busybox ?

**Comment by CHEF-KOCH** [comment]
Yes, CM and AOSP using outdated binaries for no reasons. Especially on Android 6.x this fixes some minor problems.

I will upload defconfig ^^.

**Comment by CHEF-KOCH** [comment]
I've uploaded all my configurations and scripts, which not require any pie wrapper, the patches (included aren't my but I've added in case someone want to see the progress and what was changed). Please [download](https://userscloud.com/syl39wzlqmby).
