### ISSUE TITLE
transproxy problem

### ISSUE THREAD

**Issue by marix11** [ukanth/afwall#488]
After updating to newest orbot, v15.1, transproxy script doenst work in afwall. V2.1.3

**Comment by CHEF-KOCH** [comment]
* [Report a Bug](https://github.com/ukanth/afwall/wiki/HOWTO-Report-Bug
* [CustomScripts](https://github.com/ukanth/afwall/wiki/CustomScripts)

**Comment by marix11** [comment]
Sorry i found solution in orbot
