### ISSUE TITLE
gui for ssh

### ISSUE THREAD

**Issue by c3ph3us** [ukanth/afwall#491]
Request to add gui control for enable/disable ssh

**Comment by CHEF-KOCH** [comment]
With 'GUI' you mean an toggle for port 22? I'm asking because it's integrated daemon runs on UID 0. So you need only GUI related things for other apps which want to connect to it's own binary on 22 and possible 23 for Telnet.

**Comment by c3ph3us** [comment]
To use system build in ssh regardless of app binary  (port control for each app  wold be nice thing - but you can begin with global port control deny/allow) this should be a primary goal for afwall to be an firewall app (i dont need to have afwall when i can run iptables via shell) afwall should concentrate to be gui interface not an wrapper editor for execution of custom rules

**Comment by c3ph3us** [comment]
In short add allow/deny of use  build in ssh 'button -switch preference for example' (i didnt check what min api targets app but switch is from 15 and in  pre u can use two state button) if u wish i can do some sample and show u when i deal with my pc  now im installing unix windows and setting up vpn server :) so im cut of from it :0

**Comment by c3ph3us** [comment]
Btw i use afwall with orbot and build in vpn and when i set rulles to afwall and orbot for app to allow traffic  i need to restart device for changes to work. Do u know the reason why the rules are not working after apply ?(both are set to use system iptables - but orbot is cut from su)

**Comment by CHEF-KOCH** [comment]
This is another topic which should be opened on Orbot issue tracker. The current Orbot version is bugged, I not updated it yet and tried but I've read all tickets which are Android related and it seems that there are common issue which needs to be fixed within Orbot. 


To stay on topic I got you now, thanks for the explanation.

**Comment by c3ph3us** [comment]
@CHEF-KOCH  ok i will open an issue on Orbot project 
btw afwall and orbot are behaving weird as they are detecting state wifi disabled (even the wifi is connected and applications are still working - tcp traffic) 
second thing that my wifi has exclamation mark and says no internet connection - but internet is working :D 

see https://github.com/n8fr8/orbot/issues/28

**Comment by ukanth** [comment]
Duplicate (or +1 usecase) of #15
