### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#493]

**Comment by CHEF-KOCH** [comment]
With Titanium Backup:
* Select AFWall+ -> delete data -> re-open AFWall+

Without Titanium Backup :+1: 
* Navigate to apps -> select AFWall+ Press force shutdown/close -> wipe data 


After that you can access AFWall+ like it was fresh installed.

**Comment by zalaf33** [comment]
I used the 1st option. Thanks for your help! :-)
