### ISSUE TITLE
widget disables firewall without dialog even if confirmation required in settings

### ISSUE THREAD

**Issue by nutpantz** [ukanth/afwall#498]
widget disables firewall without dialog even if confirmation required in settings.

**Comment by ukanth** [comment]
Disable confirmation is only for Main interface not for widget.

**Comment by nutpantz** [comment]
If there is no confirmation on disabling the firewall from the widget
Can there be an option for it to be removed?

Twice the firewall has been disabled because of the widget spacing with my big(I have to assume) fingers.

It's s bit of a hazard with no confirmation

**Comment by ukanth** [comment]
Nope. There is no point having confirmation for widgets. If there are more people requesting for the same feature I will consider adding it.
