### ISSUE TITLE
Log History

### ISSUE THREAD

**Issue by oliveirakrutt** [ukanth/afwall#504]
First all, this is a great app . And i have donated from 3 different accounts(my sons) because its best firewall i have seen for android.

But i think that is priority , like an app of security, have a log history of blacklist(blocked) and maybe of whitelist. Not only the last messages temporarily.

Congratulations one more time.

**Comment by ukanth** [comment]
Log History works has already started in 2.2.0. It doesn't have UI now, but in next few versions you will see complete log history and stats.

**Comment by oliveirakrutt** [comment]
Thanks for your reply. I think its an important feature.

**Comment by oliveirakrutt** [comment]
I was looking in my android and i have seen the log file . But i think that its records only the last items.
I had commented about a history file and/or gui for we can audit the results. I think its important to a software of security.
Thanks one more time.
