### ISSUE TITLE
afwall leaks Wi-Fi traffic for an blocked application for a short time

### ISSUE THREAD

**Issue by towlie** [ukanth/afwall#505]
I blocked Whatsapp for Wi-Fi and LAN and allowed it for mobile connections.
But when I reenable Wi-Fi the android connection manager and wireshark show me that some packets slip through the Wi-Fi device. (Enable Wi-Fi, disable Wi-Fi enable Wi-Fi)

Note: This only seems to happen for a short time when the connection was established. Because all traffic is blocked after that.
Android 4.4.4
Afwall log and wireshark analyisis:

```
AppID : 10108
Application's Name: WhatsApp
Total Packets Blocked:  5
[TCP]172.217.18.46(5)
```

![wireshark](https://cloud.githubusercontent.com/assets/6986141/13499168/6f0c820e-e15d-11e5-871e-1cf05446b7e9.jpg)
Afwall rules: https://gist.github.com/towlie/749f99f7b1cf9a402d75

**Comment by towlie** [comment]
Well it seems that afwall works only reliable on cm. I See that it randomly fails to block other apps for mobile Internet after some time.
Too Bad that there is no cm for this device.

**Comment by ukanth** [comment]
I've been using it for last few users and never failed once to block apps which I blocked. I've used it with Stock roms as well.

**Comment by towlie** [comment]
Oh I have a busybox installation there (busybox installer) could that conflict?

**Comment by towlie** [comment]
Nvm This just froze the android data counter and made me believe it fixed something...

---

Are you sure that my firewall rules are ok? Because figured out that afwall works perfectly when I do:
iptables -F
iptables -X
apply rules

But after reboot it becomes unreliable again, until I run these steps.
Is there a way to make this a permanent step in afwall? after every apply or something

Again files to compare:

After reboot: https://gist.github.com/towlie/f60d9c47a7dccb6eb80a
flush apply and not reboot: https://gist.github.com/towlie/8991565c90744794c523
