### ISSUE TITLE
Micro G causes error message in AFWall+

### ISSUE THREAD

**Issue by jw243** [ukanth/afwall#506]
I noticed an odd behaviour when microG (http://forum.xda-developers.com/android/apps-games/app-microg-gmscore-floss-play-services-t3217616) is combined with AFWall+. If the microG module GsfProxy.apk (version 0.1.0) is installed, but the two check boxes "activate device check-in" and "activate google cloud messaging" are left unchecked within microG settings (version 0.2.1), then there will be the following error message in AFWall (version 2.2.1) after booting the device: "error applying firewall rules". This error message does not appear, however, if the two check boxes are ticked or if GsfProxy.apk is not installed.

The same error message appears upon installation of NetworkLocation.apg version 1.6.2 (https://github.com/microg/android_packages_apps_UnifiedNlp/releases) instead of gsmcore. Since there aren't any relevant tick boxes in this app, only deletion of the app solves the problem.

I filed a bug report at the MicroG project page (https://github.com/microg/android_packages_apps_GmsCore/issues/103), but the developer suggested to file a bug report here.

I would be interested to know what possibly could cause the error message in AFWall+.

I am running Omnirom 5.1.1 on a Nexus 7 (2013) Wifi.

**Comment by ukanth** [comment]
Please attach error log from Firewall Rules after reboot. That will have the message for the issue.

**Comment by jw243** [comment]
Here is the error log:
[rules[1].txt](https://github.com/ukanth/afwall/files/162260/rules.1.txt)

**Comment by ukanth** [comment]
I see SuperSU shell is not able to start. Have you allowed su during boot from SuperSU app ?

**Comment by jw243** [comment]
That did the trick. SuperSU was indeed not allowed during boot. I changed it, and now there is no error message after boot. It's strange though, that the error message only appeared under the special circumstances mentioned in the first post.

Thanks a lot for your help.
