### ISSUE TITLE
 Preferences -> User Interface -> IPv6 Support : checkbox bug

### ISSUE THREAD

**Issue by iw2ngg** [ukanth/afwall#507]
Little bug: Preferences -> User Interface -> IPv6 Support

This setting, after any phone reboot, returns, always, to unchecked state...
and so the ip6tables rules are not automatically applied.

Thanks

**Comment by ukanth** [comment]
Thanks for this. It's fixed already.

**Comment by marix11** [comment]
Sorry for asking, coulnt find answer. Which version its fixed?

**Comment by ukanth** [comment]
sorry, it's fixed. But yet to be released :)
