### ISSUE TITLE
Block all but one app => still "Android OS" traffic

### ISSUE THREAD

**Issue by Obiwarn** [ukanth/afwall#508]
I block all apps and whitelist one app. 

When I look up "Data Usage" I see that the app generated 1.4 MB traffic, but Android OS also used 60 KB.

Can I block Android OS. Or is this inevitable and related to the 1.4MB app traffic?

**Comment by ukanth** [comment]
"Data Usage" is calculated before the packets gets dropped by iptables.

**Comment by Obiwarn** [comment]
@ukanth Oh. Is there an app for sniffing "real" data usage from the phone?

However, I am a bit confused since all other apps and services seem to disappear from the "Data Usage" table.

**Comment by ukanth** [comment]
One way to setup is to use wireshark at LAN level and see the packets are really slipping through firewall or not. 

There is a possibility it might slip through if you allow system level packages like "download manager/media or Android OS" etc., which can use used by any application (even those apps are not whitelisted)

**Comment by Obiwarn** [comment]
Thank you.
