### ISSUE TITLE
[enhancement/bug] ability to keep app in the recently used apps menu

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [ukanth/afwall#512]
Hi there, I recently purchased the Donator version of your app. Thanks very much.

I was hoping that you might add an option to allow afwall+ to appear in the recently used apps list, I haven't seen any other material based apps close them selves out of recently used before.

Apologies if this is already requested.

Also, someone mentioned to me that the donator version is not updated as frequently, I know it said the donator one was updates less frequently, but the other version didn't have a real explanation as to the differences between them.

Thanks!

Samsung Tab S2 8.0" (Wifi) Black (SM-T710) 5.1.1 in case you're wondering.

**Comment by ukanth** [comment]
Fixed it in 2.2.3
