### ISSUE TITLE
Any need for root write request when turning off WiFi?

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#523]
If I turn off WiFi, and cellular data is already disabled, _su_ will report that AFWall+ was given access to an interactive (root) shell. This makes perfect sense when switching from WiFi to cellular data (or vice versa); but if both mechanisms for data access are disabled, it seems unnecessary for AFWall+ to do anything.

Is there a bug or opportunity for streamlining?

**Comment by ukanth** [comment]
You mean root shell is running even if you turn off both wifi and data ?

**Comment by Gitoffthelawn** [comment]
I have things set up to show a toast whenever an app performs a function that requires root access.  As expected, AFWall+ will request root access when it writes _iptables_.  What's a bit odd is that it also does this when the user turns off WiFi (and cellular data is already turned off).  In this case, does _iptables_ need to be rewritten?

**Comment by ukanth** [comment]
It apply the changes when there is a connectivity change (on/off) . For your question, yes. it will apply the rules when WIFI is turned off (WLAN usecases)

**Comment by Gitoffthelawn** [comment]
Thanks.  So cell data is off and WiFi is on.  Then the user turns off WiFi.  Now there is no connectivity.  Why does iptables need to get written?

BTW, thanks for the massive cleanup effort you are working on! :+1:

**Comment by ukanth** [comment]
Valid point. It will make things complex if we start putting conditions around. We don't apply all the rules during the connectivity change. check fastApply logic in Api.java

**Comment by Gitoffthelawn** [comment]
@ukanth Thanks.  I agree, it will add some complexity.

I don't think there are too many conditions... I think, depending how you look at it, there are either 3 or 6 essential conditions.  So it's not too many, but it's definitely more than zero!  :-)

It's definitely something to think about, as there may be some good performance benefits.  On the other hand, it's not required.
