### ISSUE TITLE
Blocking the LTE modem on Droid4/Razr/Bionic leads to kernel wakelock. Was: AFWall on CM 13.0 will keep phone awake 100% of the time

### ISSUE THREAD

**Issue by dicer** [ukanth/afwall#525]
I'm running AFWall+ 2.2.3 on CM 13.0-20160412 (Android 6.0.1).
When AFWall is installed, blocking traffic works as supposed, but my phone uses tons of battery because AFWall keeps the phone constantly awake (as one can see in the battery stats). Awake time is 100% even if the screen is off for hours.

Better Battery Stats shows the following kernel Wakelock:
MAPAL_LITE_SOCKET_RECEIVE all the time. As well as "rx_wake" for about half the time.
Wifi is on and I'm connected to a cell network.

I found out AFWall is causing this by uninstalling one app at a time. First time around I uninstalled ALL apps and nothing changed. Then I rebooted and suddenly the phone was not awake all the time anymore.
So second time around I uninstalled one app at a time, rebooted, checked, uninstalled another one, rebooted etc... Until I uninstalled AFWall and after a reboot the Wakelock problem is gone.

Any idea on what could be causing this? Or how to further debug this? Any other information I can supply?

**Comment by ukanth** [comment]
Do you have Log Service enabled ?

**Comment by dicer** [comment]
That's actually another problem, cause IPv6 does not seem to have LOG target (only NFLOG). Weirdly enough "IPv6 Support" is disabled, but the log service still wants to apply the LOG rule for IPv6.. Actually the same as issue #227

So no, as much as I would like to enable logging, I can't. All the options I have enabled:
- Enable Notifications
- Show UID for apps
- Active Rules
  -- Roaming Control
  -- VPN Control
- Confirm box on AFWall+ disable

Log (none)

Security (all of them)

Experimental: Fix Startup Data Leak

Profiles (none)

Widgets (untouched and no widget used)

**Comment by ukanth** [comment]
I'm using with CM13 and never had any issues with AFWall+ even with log service enabled. Are you using SuperSU ? This seems more like some other issue rather than AFWall+
- Do a clean install of AFWall+
- Try disabling "Active Rules" under UI preference and observe the changes.
- Post your device and su details.

**Comment by fred777** [comment]
My Motorola Droid 4 with CM13 is also kept awake by this MAPAL_LITE_SOCKET_RECEIVE kernel wakelock, so I'm joining the club here, curious for any news...

**Comment by dicer** [comment]
@fred777: Have you installed any superuser app? Like the SuperSU ukanth
mentioned? I'm currently running it without anything special and with
the integrated su support of cmod13.

Haven't had time to test it yet, but I noticed the root symbol will not
go away at all anymore and applying the rules takes a lot longer than on
cm11 (skipped cm12, so I don't have experience there). So maybe it's
SuperSU missing?

**Comment by fred777** [comment]
No, I just have plain CM13 with built-in root access management.

EDIT: There are not so many places on the internet mentioning MAPAL_LITE_SOCKET_RECEIVE. It seems to be related to Motorola phones (do you have one?) and some radio-related closed-source library called libmoto_lte_ril.so My Droid 4 had been made for Verizon, but I'm using it on GSM/WCDMA. Maybe the culprit lies somewhere there...

EDIT2: Wakelock is gone - installing the GSM/UMTS patch from http://forum.xda-developers.com/showthread.php?t=2368572 did the trick for me...

**Comment by dicer** [comment]
Yep, also on Droid 4 and was about to report on that as well: The GSM fix gets rid of the wakelock on my phone as well. So this is not AFWall+ related, just triggered by it. Strange, but I think we can close this issue

**Comment by stargo** [comment]
The LTE modem on the Droid4/Razr/Bionic is a network device with the IP 192.168.157.2. If the system can't communicate with it, this will cause the wakelock. Do not block access to 192.168.157.2!

Installing the GSM patch removes the network device from android and uses a different RIL to access the remaining GSM/CDMA modem. This will also cause some failures, as the LTE modem is not only responsible for LTE but some SIM card management stuff.

**Comment by dicer** [comment]
Ah ok. Interesting. Just checked and it seems "Phone and Messaging Storage" (AppID 1001)  is the one trying to connect.:
[TCP]192.168.157.2:3002
[TCP]192.168.157.2:3265

As well as the Kernel (-1):
[TCP]192.168.157.2:3265

Should this be a new AFWall+ feature? A special rule like DNS?
Can someone help me out with a custom rule that would unblock all ports to 192.168.157.2 for those two appids? Never ventured into the custom rules.
