### ISSUE TITLE
Binary not found

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#527]
Hi
/system/bin/iptables not found when using custom script. I tried internal and system iptables without any luck ;(

I even used the sample header described in the custom scripts without any luck.

When I type /system/bin/iptables as  super user on the terminal I see that the binary is there. So I am not sure whey it is not able to find binary. When I disable custom script, it I can enable the firewall properly.

THis is a Samsung phone with Android 5.1.1. The device is rooted with Supersu.

**Comment by ukanth** [comment]
iptables binary is not the only one which requires afwall to be fully functional. You need to have compatible kernel as well. If stock rom doesn't support, put the rom which supports it properly.

Thanks.

**Comment by TriMoon** [comment]
Reading the OP, AFWall functions normally without using custom script...
IMHO, he just needs a different path used to call iptables...
he needs to post the line(s) he uses in his custom script that call iptables.

**Comment by gerroon** [comment]
@ukanth 
Afwall functions fine. The issue arises when I try to use custom script. Nomatter what I did, I could not get Afwall to find the iptables that it normally able to use. 

Here is the last one I tried

IPTABLES=/system/bin/iptables
IP6TABLES=/system/bin/ip6tables

$IPTABLES -A OUTPUT -s 54.229.0.0/16 -j DROP
$IPTABLES -A INPUT -s 54.229.0.0/16 -j DROP
$IPTABLES -A OUTPUT -s 216.58.0.0/16 -j DROP
$IPTABLES -A INPUT -s 216.58.0.0/16 -j DROP

Please bear in mind that "/system/bin/iptables" exists

**Comment by CHEF-KOCH** [comment]
You need to ensure that iptables exist in /system/bin because I think you maybe use the AFWall+ integrated one, then you not see this because you called iptables from the beginning from a different path. Try to ensure you use the correct path /system/bin/ OR afwall's path.

Sometimes it also can help if you call /bin only (without /system) because the kernel may link it different.

**Comment by gerroon** [comment]
@CHEF-KOCH 
Well Afwall works normal;y. This is an issue when I try custom script

**Comment by CHEF-KOCH** [comment]
Can you try to call iptables directly? Instead of <code>$IPTABLES</code> and <code>IP6TABLES</code> try to add the full path and see what happens.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH OK, I'm going to tease you: see, you didn't capitalize the first letters in _iptables_ ! :+1: :-)

Just teasing, my friend! :-)

**Comment by TriMoon** [comment]
Instead of sending the OP into different paths, why not just tell him the path to the integrated iptables of AFWall+ he needs to use?

**Comment by ukanth** [comment]
AFWall+ stores it's custom iptables under 

> /data/data/dev.ukanth.ufirewall/app_bin/iptables
> /data/data/dev.ukanth.ufirewall/app_bin/ip6tables
