### ISSUE TITLE
include dnsfproxy2 binary in afwall

### ISSUE THREAD

**Issue by pyc0de** [ukanth/afwall#528]
could you please include dnsproxy2 in afwall
I've been using dnsproxy2 to filter dnns requests,
but when switched to CM13 I got this error:
error: only position independent executables (PIE) are supported.

I've raised an issue in cernekee/dnsproxy2 but no answer so  far.

Anyway ability to filter dns traffic would be an important feature for afwall.
Thanks.

**Comment by CHEF-KOCH** [comment]
CM13 normally not needs AFWall+ since you usually can by default block and restrict apps, the menu is a bit tricky to find but's there. For the rest like startup you could use scripts and execute it via SManager. This also would allow combined with Tasker to apply stuff if certain conditions are changed e.g. switching from lan to cellular connection. 

I'm unsure but seems the road comes to an end, if we get an better GUI I see no issue to work with the Android integrated solutions, since you otherwise get more troubles.

**Comment by pyc0de** [comment]
Thanks, CHEF-KOCH, for your answer. Didn't ment to sound demanding). Sorry.
I wasn't aware of CM 13 built-in firewall.
Always used AFwall+ - it is very powerfull and well built app, with ability to distinguish between lan/wan/vpn.

But for sure, good gui powerfull firewall should be inegrated in Android.
Cheers!

**Comment by ukanth** [comment]
@CHEF-KOCH , Please keep the conversations within the topic. 

@pyc0de There is already a request to bring DNS support. I have even compiled with pie support. Whether bringing it to AFWall+ it still not decided.

**Comment by CHEF-KOCH** [comment]
:fearful:

**Comment by pyc0de** [comment]
ukanth, could you please share it?

**Comment by ukanth** [comment]
https://github.com/ukanth/dnsproxy2/tree/master/res/raw

**Comment by pyc0de** [comment]
still got error: only position independent executables (PIE) are supported.

**Comment by pyc0de** [comment]
I've built binary myself with APP_PLATFORM := 16, ndk-r8e
and still got this error, running it on CM13.
Could someone test this? Thanks!

**Comment by ukanth** [comment]
Use pie wrapper from afwall.

**Comment by pyc0de** [comment]
Corect me if I'm wrong, but pie wrapper runs pie binaries where this is not supported. In my case only pie binaries are supported, and I'm getting on all sorts of problems tryong to compile dnsproxy2 with pie support. Will try further.

**Comment by CHEF-KOCH** [comment]
I'm unsure if dnsproxy2 will work on 4.4+ devices due VpnService changes. Or it might work but not for VPN or any other seperate created adapter.

**Comment by pyc0de** [comment]
so we are out of reliable DNS filter then? Anyway I'm still unable to build dnsproxy2 with pie support due to linker problem. So I'm unable to test this. @CHEF-KOCH could you please test it on CM13/Android 6.0?

**Comment by ukanth** [comment]
@pyc0de , I got sometime to work on dnsproxy and you are right. it doesn't work with CM13 and I got the same error as you. I will spend some time today/tomorrow to try fixing it.

**Comment by pyc0de** [comment]
thanks @ukanth, if you need to test it - I can do it.

**Comment by ukanth** [comment]
@pyc0de , I managed to compile it with PIE support. Can you test it and let me know 

ARM V7
https://www.dropbox.com/s/f2vpkpgrnysefqu/dnsproxy2?dl=0

**Comment by pyc0de** [comment]
@ukanth, binary is working - I can make dns resolution from terminal: dnsproxy2 -l <hostname>

but as dns filter it fails - I can still see dns calls even when apps are not on the whtelist in afwall. Looks like @CHEF-KOCH was right.

Tested on CM13 latest nightly on Nexus 5.

**Comment by pyc0de** [comment]
@ukanth, are you planning to implement new dns filter in afwall+ in the future releases?

**Comment by ukanth** [comment]
I'm still exploring on DNS related stuff. Yes it will be coming in future releases.
