### ISSUE TITLE
Why is init.d needed to prevent startup data leak?

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#531]
AFWall+ includes an option, _Fix Startup Data Leak_, to "prevent data leaks during system startup".

Why is this needed?  Is the existing _iptables_ (from the previous session) not used during startup?

**Comment by ukanth** [comment]
iptables resets the rules on android startup. that's the reason we have startup script which sets all the chains(default) to block state till afwall starts and apply the rules

**Comment by Gitoffthelawn** [comment]
Thanks @ukanth 

Is the startup script you mentioned the one enabled by the experimental option _Fix Startup Data Leak_, or is it something else?

**Comment by ukanth** [comment]
That's right !

**Comment by Gitoffthelawn** [comment]
Sounds good.  Thanks again @ukanth .
