### ISSUE TITLE
UX/UI: Enabling and Disabling the Firewall

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#539]
For a majority of users, AFWall+ will be enabled most, if not all, of the time.  For this use case, `Disable firewall` is currently the **first** menu item.  This is not good, as it is the most dangerous menu item.  It is also directly above `Apply`, which is probably the most commonly used menu item.

Initially, I thought of making edits to  `afwall/aFWall/src/main/res/menu/menu_bar.xml` in order to simply move `Disable firewall` near the bottom of the menu.  But when the firewall is disabled, that menu item turns into `Enable firewall`, which, in that situation, is now the most important menu item.

So what to do?

Here are my UX/UI recommendations:

First, how about we remove the `Apply` menu item, and make it an icon on the main title bar?  Doing so makes this common action more accessible, as the user will no longer have to open the menu or completely back out of AFWall+ to apply changes.

Second, how about we remove the `Enable firewall` menu item altogether.  If the firewall isn't enabled, we should make this **_absolutely clear**_.  So, in this case, instead of the `Enable firewall` menu item, how about we add a large green button just below the title bar that allows the user to enable the firewall?  This makes it more clear that the firewall is disabled while simultaneously making it obvious how to enable it.

So how does the user disable the firewall now?  Simple: We move the existing `Disable firewall` menu item directly above the `Help` menu item.

**Comment by ukanth** [comment]
If possible could you put up a mock to visualize this ? Because, from the beginning this particular action/behavior is not changed from AFWall+ I really don't want to touch it until it's really required.

**Comment by Gitoffthelawn** [comment]
Yes, if I get some time, I'll create some mock ups.

Out of curiosity, what do you think of keeping everything the same, but just moving the `Disable firewall` menu item to directly above the `Help` menu item?

If that interests you, I can edit the code and submit the pull request.

**Comment by ukanth** [comment]
The problem is first time after installation, they need to enable firewall. So we can't move that above Help menu.

**Comment by Gitoffthelawn** [comment]
@ukanth Yes, I agree.  For initial installation, a special case will need to be added.

**Comment by CHEF-KOCH** [comment]
Imho we also could entirely remove that option because you could do this via:

* Widget
* Freeze the application within Android
* Uninstall the app
* Maybe by long pressing on an area (not implemented yet)

**Comment by someone-somenet-org** [comment]
It is somehow redundand to "apply" and to "enable".
On the other hand, it sometimes makes sense to be able to wipe all iptable chains.

Maybe try something like renaming "apply" to "apply and enable" and add an option to "Wipe all active rules".
Basically get rid of the enable button/function as it makes no real sense to keep as a separate feature. Just merge the functionality into apply and add a way to disable/wipe iptables.
