### ISSUE TITLE
Status of the code

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#540]
I noticed that the README states:

> The original codebase was derived from DroidWall by Rodrigo Rosauro. DroidWall was sold to AVAST in December 2011, and is no longer actively maintained.

It also states:

> AFWall+ is under the GNU General Public License v3.0.

What is status of this code?  If DroidWall was sold to AVAST, is this project still covered by the GNU Public License v3.0?  How does that work?

**Comment by ukanth** [comment]
Yes. The original work was derived from GPL 3.0 and I wanted to keep the same.

**Comment by Gitoffthelawn** [comment]
@ukanth Thanks!
