### ISSUE TITLE
Status notification is not updated when changing profile from Tasker/etc

### ISSUE THREAD

**Issue by sciamano** [ukanth/afwall#542]
I am using Tasker-like app to change profiles depending on WiFi network I am connencted to.
There is a status notification with the text like "Firewall is runnign (ProfileName)" and it shows an old profile name but not the new one applied by taskes-plugin. Only by calling the AFWall+ app, I can see/check that the new profile was actually applied.

**Comment by ukanth** [comment]
Can you mention the name of "tasker-like" app ?

**Comment by sciamano** [comment]
sure, I'm using Automate (from LlamaLab)
