### ISSUE TITLE
Custom script rules appear twice after reboot

### ISSUE THREAD

**Issue by jsalatiel** [ukanth/afwall#544]
According to custom scripts 'tutorial':
afwall-3g - This chain will only receive OUTPUT packets for the cellular network interface (no matter >if it is 2G, 3G, 4G, etc).
Please note that all those chains are **guaranteed** to be cleared before the custom script is executed, so you don't need to worry about rules cleanup on your script IF you are using those chains.

Well, i have a very simple rule added as a custom script 

$IPTABLES -I afwall-3g  -p udp --dport 53 -j ACCEPT ( needed to dns resolv work with bt thetering)

If i disable the firewall, and reenable it , i will see (correctly this):

Chain afwall-3g (21 references)
 pkts bytes target     prot opt in     out     source               destination  
  270 18181 ACCEPT     udp  --  \*      \*       0.0.0.0/0            8.8.8.8              udp dpt:53
30296 2481K afwall-3g-postcustom  all  --  \*      \*       0.0.0.0/0            0.0.0.0/0           

After rebooting , i am seeing this:
Chain afwall-3g (21 references)
 pkts bytes target     prot opt in     out     source               destination  
    0     0 ACCEPT     udp  --  \*      \*       0.0.0.0/0            8.8.8.8              udp dpt:53
    0     0 ACCEPT     udp  --  \*      \*       0.0.0.0/0            8.8.8.8              udp dpt:53
   37  4625 afwall-3g-postcustom  all  --  \*      \*       0.0.0.0/0            0.0.0.0/0           

I supposed the afwall script is being called without flushing in somepoint after reboot.

**Comment by ukanth** [comment]
Have you enabled "DNS + DHCP " for tethering ? Because that should allow port 53 for uid 0 and 9999 automatically.
