### ISSUE TITLE
DNS wont resolv on bluetooth thetering [ FIX SUGGESTION ]

### ISSUE THREAD

**Issue by jsalatiel** [ukanth/afwall#545]
When i connect my laptop to my android phone using bluetooth thetering, my laptop is unable to surf because the DNS server ( 192.168.44.1 ) is refusing connections.

After a little debugging, i found that the rule

36  2575 RETURN     udp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            udp dpt:53 owner UID match 0
was not matching when using bt theter.

So i started to dig and noticed that the userid when bt-thetering is NOBODY.

IN= OUT=rmnet0 SRC=179.196.177.78 DST=8.8.8.8 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=UDP SPT=34334 DPT=53 LEN=40 **UID=9999** GID=9999 MARK=0xf0065

Could you please add the rule to match udp 53 for **nobody** when the user allows (thetering) DHCP+ DNS services.

Thanks!

Thanks!

**Comment by ukanth** [comment]
it does add nobody and root when DHCP+DNS is checked

https://github.com/ukanth/afwall/blob/beta/aFWall/src/main/java/dev/ukanth/ufirewall/Api.java#L663

**Comment by 5nafu** [comment]
Hi, 
I have the same Issue. Debugging I found out that the corresponding chains `afwall-3g-tether` and `afwall-wifi-tether` are never referenced.

```
# iptables -n -L |grep tether
Chain afwall-3g-tether (0 references)
Chain afwall-wifi-tether (0 references)
natctrl_tether_counters  all  --  0.0.0.0/0            0.0.0.0/0           [goto]  state RELATED,ESTABLISHED
natctrl_tether_counters  all  --  0.0.0.0/0            0.0.0.0/0           [goto]
Chain natctrl_tether_counters (2 references)
```

**Comment by 5nafu** [comment]
Additional debugging: I checked the packages with tcpdump and saw that I would not receive an answer to a DNS request with the AFWall+ activated. 

Adding the rules manually to the `afwall` Chain[1] I do get Packages with a DNS answer, albeit a "refused" one. In the dmesg-Log I see two packages being logged:

```
[20160713_23:13:09.194854]@0 {AFL}IN= OUT=wlan0 SRC=192.168.1.25 DST=192.168.1.1 LEN=59 TOS=0x00 PREC=0x00 TTL=64 ID=5997 DF PROTO=UDP SPT=253 DPT=53 LEN=39 UID=9999 GID=9999 MARK=0xf0067 
[20160713_23:13:10.715936]@0 {AFL}IN= OUT=wlan0 SRC=192.168.1.25 DST=192.168.1.1 LEN=59 TOS=0x00 PREC=0x00 TTL=64 ID=6072 DF PROTO=UDP SPT=36144 DPT=53 LEN=39 UID=9999 GID=9999 MARK=0xf0067 
```

Unfortunately I can not see, why the Packages are being dropped....

If I deactivate the Firewall, I do get a correct answer from the same Host (`192.168.44.1`) as with the test before.

1)

```
iptables -I afwall 1 -p udp -m owner --uid-owner 0 -m udp --sport 67 --dport 68 -j RETURN
iptables -I afwall 1 -p udp -m owner --uid-owner 9999 -m udp --sport 67 --dport 68 -j RETURN
iptables -I afwall 1 -p udp -m owner --uid-owner 0 -m udp --sport 53 -j RETURN
iptables -I afwall 1 -p udp -m owner --uid-owner 9999 -m udp --sport 53 -j RETURN
iptables -I afwall 1 -p tcp -m owner --uid-owner 0 -m tcp --sport 53 -j RETURN
iptables -I afwall 1 -p tcp -m owner --uid-owner 9999 -m tcp --sport 53 -j RETURN
```

**Comment by tete1030** [comment]
Hi,
I have same issue when using USB Tethering. I found that the method it uses to detect tether status is incomplete.

https://github.com/ukanth/afwall/blob/beta/aFWall/src/main/java/dev/ukanth/ufirewall/InterfaceTracker.java#L166

It only detected Wifi hotspot mode. Bluetooth tethering and USB tethering should also be detected.

I will try to finish this and post a pull request.

**Comment by onolox** [comment]
Awaiting a cure.
