### ISSUE TITLE
Afwall no longer compiles. Errors downloading dependencies

### ISSUE THREAD

**Issue by optimumpr** [ukanth/afwall#547]
It appears some http addresses should be corrected.

Logcat:

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':aFWall'.
  > Could not resolve all dependencies for configuration ':aFWall:_debugCompile'.
  > Could not resolve org.bitbucket.ukanth:android-lockpattern:7.0.0.
   Required by:
       afwall:aFWall:unspecified
    > Could not resolve org.bitbucket.ukanth:android-lockpattern:7.0.0.
       > Could not get resource 'https://jitpack.io/org/bitbucket/ukanth/android-lockpattern/7.0.0/android-lockpattern-7.0.0.pom'.
          > Could not GET 'https://jitpack.io/org/bitbucket/ukanth/android-lockpattern/7.0.0/android-lockpattern-7.0.0.pom'.
             > peer not authenticated
  > Could not resolve com.afollestad.material-dialogs:core:0.8.5.8.
   Required by:
       afwall:aFWall:unspecified
    > Could not resolve com.afollestad.material-dialogs:core:0.8.5.8.
       > Could not get resource 'https://jitpack.io/com/afollestad/material-dialogs/core/0.8.5.8/core-0.8.5.8.pom'.
          > Could not GET 'https://jitpack.io/com/afollestad/material-dialogs/core/0.8.5.8/core-0.8.5.8.pom'.
             > peer not authenticated
  > Could not resolve com.afollestad.material-dialogs:commons:0.8.5.8.
   Required by:
       afwall:aFWall:unspecified
    > Could not resolve com.afollestad.material-dialogs:commons:0.8.5.8.
       > Could not get resource 'https://jitpack.io/com/afollestad/material-dialogs/commons/0.8.5.8/commons-0.8.5.8.pom'.
          > Could not GET 'https://jitpack.io/com/afollestad/material-dialogs/commons/0.8.5.8/commons-0.8.5.8.pom'.
             > peer not authenticated
  > Could not resolve com.github.Raizlabs.DBFlow:dbflow-core:3.0.1.
   Required by:
       afwall:aFWall:unspecified
    > Could not resolve com.github.Raizlabs.DBFlow:dbflow-core:3.0.1.
       > Could not get resource 'https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow-core/3.0.1/dbflow-core-3.0.1.pom'.
          > Could not GET 'https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow-core/3.0.1/dbflow-core-3.0.1.pom'.
             > peer not authenticated
  > Could not resolve com.github.Raizlabs.DBFlow:dbflow:3.0.1.
   Required by:
       afwall:aFWall:unspecified
    > Could not resolve com.github.Raizlabs.DBFlow:dbflow:3.0.1.
       > Could not get resource 'https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow/3.0.1/dbflow-3.0.1.pom'.
          > Could not GET 'https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow/3.0.1/dbflow-3.0.1.pom'.
             > peer not authenticated

**Comment by ukanth** [comment]
Seems like it's a problem at your end

Latest Travis builds are compiling properly.
https://travis-ci.org/ukanth/afwall/builds/140327667

**Comment by optimumpr** [comment]
Still nothing gets downloaded from jitpack.io/com...  You might have those on your computer already, that's why you don't get an error, but for someone who doesn't, there is "peer not authenticated" error...

**Comment by CHEF-KOCH** [comment]
Please won't open an ticket for each new compiler warning/error. Do this via email but I think GitHub is the wrong place for it, this is not an issue.

Please respect that others getting an notification then which could be annoying because we spent our private time on this. 

Thanks.

**Comment by optimumpr** [comment]
OK, guys. This was NOT a question, but an issue and on your side @ukanth . Graddle 2.10 that is mentioned in your gradle-wrapper.properties fails to download dependencies. I have changed it to 2.14 and now everything works. You are welcome...

@CHEF-KOCH : Please abstain from lecturing on private time and respecting others, which I always do. Cheers

**Comment by ukanth** [comment]
Thanks @optimumpr. Glad that you have resolved it.  Could you please close this issue ?
