### ISSUE TITLE
logs flooding by  A/libc: Fatal signal 13 (SIGPIPE) on temasek cm13.1 build 

### ISSUE THREAD

**Issue by c3ph3us** [ukanth/afwall#551]
my logs are flooding by exception 

```
 A/libc: Fatal signal 13 (SIGPIPE)
```

pleas see for full logs 
https://github.com/temasek/Changelogs/issues/10#issuecomment-233733126

**Comment by ukanth** [comment]
Seems like ROM issue to me. AFWall just uses dmesg which is default command

**Comment by c3ph3us** [comment]
reopening as i got this when i close afwall window 

6807-6807/dev.ukanth.ufirewall I/art: System.exit called, status: 0
6807-6807/dev.ukanth.ufirewall I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
763-1003/? D/GraphicsStats: Buffer count: 7
763-1003/? I/WindowState: WIN DEATH: Window{7e6602 u0 dev.ukanth.ufirewall/dev.ukanth.ufirewall.MainActivity}
763-778/? I/libprocessgroup: Killing pid 6840 in uid 10068 as part of process group 6807
763-778/? I/libprocessgroup: Killing pid 7566 in uid 10068 as part of process group 6807
763-778/? I/ActivityManager: Process dev.ukanth.ufirewall (pid 6807) has died
763-778/? W/ActivityManager: Scheduling restart of crashed service dev.ukanth.ufirewall/.service.RootShell in 1000ms
763-778/? W/ActivityManager: Scheduling restart of crashed service dev.ukanth.ufirewall/.log.LogService in 11000ms
763-1003/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 6807 uid 10068
10060-10060/? A/libc: Fatal signal 13 (SIGPIPE), code 0 in tid 10060 (dmesg)
333-333/? I/DEBUG: property debug.db.uid not set; NOT waiting for gdb.
333-333/? I/DEBUG: HINT: adb shell setprop debug.db.uid 100000
333-333/? I/DEBUG: HINT: adb forward tcp:5039 tcp:5039
333-333/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
333-333/? A/DEBUG: CM Version: '13.0-20160803-UNOFFICIAL-temasek-hlte'
333-333/? A/DEBUG: Build fingerprint: 'samsung/hltexx/hlte:5.0/LRX21V/N9005XXUGBOK6:user/release-keys'
333-333/? A/DEBUG: Revision: '0'
333-333/? A/DEBUG: ABI: 'arm'
333-333/? A/DEBUG: pid: 10060, tid: 10060, name: dmesg  >>> dmesg <<<
333-333/? A/DEBUG: signal 13 (SIGPIPE), code 0 (SI_USER), fault addr --------
333-333/? A/DEBUG:     r0 ffffffe0  r1 b6c40000  r2 00000283  r3 b6c4023f
333-333/? A/DEBUG:     r4 00000283  r5 b6c40000  r6 00000001  r7 00000004
333-333/? A/DEBUG:     r8 b6f98568  r9 00000000  sl 00000000  fp be8a1a3c
333-333/? A/DEBUG:     ip 00000000  sp be8a1988  lr b6f41ca9  pc b6e7de0c  cpsr 20060010
763-971/? W/NativeCrashListener: Couldn't find ProcessRecord for pid 10060
333-333/? A/DEBUG: backtrace:
333-333/? E/DEBUG: AM write failed: Broken pipe
333-333/? A/DEBUG:     #00 pc 00041e0c  /system/lib/libc.so (write+12)
333-333/? A/DEBUG:     #01 pc 00007ca5  /system/bin/toybox
333-333/? A/DEBUG:     #02 pc 00009a5d  /system/bin/toybox
333-333/? A/DEBUG:     #03 pc 0000a851  /system/bin/toybox
333-333/? A/DEBUG:     #04 pc 0000711d  /system/bin/toybox
333-333/? A/DEBUG:     #05 pc 00006d01  /system/bin/toybox
333-333/? A/DEBUG:     #06 pc 00007167  /system/bin/toybox
333-333/? A/DEBUG:     #07 pc 000173bd  /system/lib/libc.so (__libc_init+44)
333-333/? A/DEBUG:     #08 pc 00006c10  /system/bin/toybox
333-333/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_08
763-797/? I/BootReceiver: Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
763-899/? I/TemperatureHumiditySensor: Accuracy has been changed to 3
763-791/? I/ActivityManager: Start proc 10061:dev.ukanth.ufirewall/u0a68 for service dev.ukanth.ufirewall/.service.RootShell
10061-10061/? I/art: Late-enabling -Xcheck:jni
10061-10061/dev.ukanth.ufirewall W/System: ClassLoader referenced unknown path: /data/app/dev.ukanth.ufirewall-1/lib/arm
10061-10061/dev.ukanth.ufirewall I/AFWall: Starting Log Service: while true; do dmesg -c ; sleep 1 ; done for LogTarget: LOG
10061-10061/dev.ukanth.ufirewall I/AFWall: rootSession is not Null
10061-10061/dev.ukanth.ufirewall D/AFWall: logservice shell started
10102-10102/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10102-10102/? D/AndroidRuntime: CheckJNI is OFF
