### ISSUE TITLE
Version of afwall is older in F-Droid than the one in Google Play

### ISSUE THREAD

**Issue by ShapeShifter499** [ukanth/afwall#557]
As the title says, the F-Droid version is older than the one in Google Play. Why is this?

**Comment by ukanth** [comment]
It is same. I don't publish BETA versions to f-droid. Latest stable version is 2.2.3

**Comment by ShapeShifter499** [comment]
Ohhh that makes sense. 

I thought you could mark beta builds in F-Droid though.

**Comment by ukanth** [comment]
Yes. I could. But I just want to keep beta's with Playstore. Because hardly I get any reports from f-droid builds during beta.

**Comment by ShapeShifter499** [comment]
Alright then, I'll keep this in mind if I ever want to test a beta build. Thank you for taking the time to answer my questions.
