### ISSUE TITLE
lockscreen on non android rom

### ISSUE THREAD

**Issue by c3ph3us** [ukanth/afwall#558]
referring to: 
https://github.com/ukanth/afwall/commit/782078327258a2922069b4f90f512f90c34fd124

what about **CM roms** they have such thing like:
- device policy override 

![https- 2f 2fpicload org 2fimage 2fwpoglrl 2fdeleteme](https://cloud.githubusercontent.com/assets/10565704/17501430/1f3671b6-5dce-11e6-98a9-53dec8d9a478.jpg)

btw android has such thing like **trust agents** :) for things you want to achieve 
- one of them is a trust profile provider 

deep dive into lockscreen :)

**Comment by ukanth** [comment]
I'm sorry. I didn't understand this one. You meant to say, it won't work on CM roms ?

**Comment by c3ph3us** [comment]
@ukanth  you can use android  trust agent api to show notifications on locked  screen 
see:  https://nelenkov.blogspot.com/2014/12/dissecting-lollipops-smart-lock.html
