### ISSUE TITLE
App hangs in retrieving log data

### ISSUE THREAD

**Issue by rancidfrog** [ukanth/afwall#561]
When you select view log from menu app hangs and becomes unresponsive:
![Image of Yaktocat](https://s10.postimg.org/kqvbz0dk9/Screenshot_20160810_225808.png)

[ http://hastebin.com/ofoqexidel.vbs ]

**Comment by ukanth** [comment]
Please send me /data/data/dev.ukanth.ufirwall/databases/Logs.db file. I need large dataset like yours to optimize the logic. 

Thanks

**Comment by rancidfrog** [comment]
File is huge, 30+mb
Mostly filled with blocked Linux kernel -11

**Comment by ukanth** [comment]
Yes. I need it. please upload to dropbox or xda. That will help me fix the issue,

**Comment by PatriceVigier** [comment]
I have the exact same problem on your last version.
