### ISSUE TITLE
Allow/Block Webview per app

### ISSUE THREAD

**Issue by walrus543** [ukanth/afwall#562]
Since version 2.5.0:
"Webview filter(applist) - Another possible way apps can use webview to access internet. So now there is a separate system level application for webviews. Please whitelist/blocklist this app accordingly."

Being able to block Webview is a nice improvement but it breaks a lot of apps. For example, I can no longer download a [png file](https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Android_robot.png/504px-Android_robot.png) with my web brower (Atlas which is based off Webview).

Feature request: allow Webview for apps that already have Internet access and block Webview for apps that have no Internet access to avoid data leaks.

Thank you.

**Comment by Gitoffthelawn** [comment]
@Primokorn What is the source of that quote?  To which Android versions does it apply?

**Comment by walrus543** [comment]
@Gitoffthelawn the quote is from the official changelog.
I'm on Marshmallow.

FYI I already discussed about that with ukanth on XDA.

**Comment by Gitoffthelawn** [comment]
@Primokorn Thanks!  Apparently GitHub's search does not work properly.  Searching this repo for even a small piece of the text comes up nil.

@ukanth Is the new `webview` system level app within the firewall supposed to be present for all versions of Android, or just some of them?  I'm not seeing it on KitKat devices.

**Comment by ukanth** [comment]
Android decoupled it from system level to playstore to address critical security issues(http://www.techrepublic.com/article/how-to-avoid-the-android-jellybean-webview-vulnerability/). You can find it on playstore

https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en

I guess mostly on lollipop+ devices.

**Comment by Gitoffthelawn** [comment]
@ukanth Thanks.  Since the decoupled `webview` requires Android 5.0 or later, does that mean all pre-5.0 devices can leak data through `webview`?

If so, what can AFWall+ do about it?

**Comment by ukanth** [comment]
No, in order to use webview, the application requires INTERNET permissions. So it can't leak.
So, only download manager was using the system level webview. I will dig further to see the behaviour 
https://developer.android.com/guide/webapps/webview.html

**Comment by Gitoffthelawn** [comment]
@ukanth Thanks my friend.  I look forward to hearing what you discover.
