### ISSUE TITLE
AFwall+ 2.5.x hangs during connection change when logging is enabled

### ISSUE THREAD

**Issue by JasMan78** [ukanth/afwall#563]
**Device:** Motorola X 2014 (XT1092)
**OS:** CyanogenMod 12.1-20151117 Stable, Android 5.1.1

**Problem:** Since AFwall+ 2.5 I recognized connection problems after connection changes (activating WiFi, switch from WiFi to mobile data or vice versa, etc.). The LAN and Internet was not available from the phone. I had to wait for one or two minutes or sometimes restart the phone to solve the connection issue. After some researchs I found out, that AFwall+ hangs in such situations. It shows only its green window bar without any content (rules or menue). I removed the app and reinstallt it. I didn't import the old settings, but the problem is still present. After some more researchs I found out, that this problem only occurs, when logging is active in AFwall+. When I disable it, everything works fine. When I enable it e.g. during a Wifi connection, it shows also log entrys. But as soon as I change the connection AFwall hangs.
Everything worked fine on this device until the new log in AFwall+ 2.5
Find attached the logcat file.

[AFwall_Log_Failure.txt](https://github.com/ukanth/afwall/files/415392/AFwall_Log_Failure.txt)

**Comment by ukanth** [comment]
Can you also attach rules (Menu->Firewall Rules->Export) . Also try disabling active rules and observe the behavior.

**Comment by JasMan78** [comment]
I've disabled all rules, issue is still present.
Here are my rules. Thank you in advanced.

[afwall-backup-all-2016-08-12-17-30-16.json.txt](https://github.com/ukanth/afwall/files/415645/afwall-backup-all-2016-08-12-17-30-16.json.txt)

**Comment by ukanth** [comment]
Sorry, that export of rules. I want iptables rules.

**Comment by JasMan78** [comment]
Here's the export of the rules.
[IPv4rules.log.txt](https://github.com/ukanth/afwall/files/415840/IPv4rules.log.txt)

**Comment by ohnonot** [comment]
i suffered almost complete connectivity loss from this.

**it even happened when i did not interact with afwall+ in any way, right after booting up.**

disabling logging (menu -> preferences -> log) seems to have solved the issue completely, even after several reboots.
afwall+ v2.5.2 from f-droid.

btw, i think it's good that afwall defaults to blocking _everything_ in a case like this; better than the other way around.

**Comment by ghost** [comment]
Hi
I was having problems with the most recent versions of AFwall, and I think it is the same problem mentioned here, AFwall always hangs for me when connection changes. When I try to open AFwall it shows a blank screen with only the green window bar and then I get "AFwall is not responding". I never associated this with having logs enabled and downgraded to version 2.2.3 (fdroid)

Device; Sony Xperia S aka Lt26i, latest stock rom.

> btw, i think it's good that afwall defaults to blocking everything in a case like this; better than the other way around.

Sure is way better than allowing all apps without you want it.

**Comment by Gitoffthelawn** [comment]
@ohnonot wrote:

> btw, i think it's good that afwall defaults to blocking everything in a case like this; better than the other way around.

@Tony-il-Capo agreed with @ohnonot, and I agree as well. :+1:
