### ISSUE TITLE
xposed modul reboots

### ISSUE THREAD

**Issue by ka223** [ukanth/afwall#564]
Hi,

I just upgraded to 2.5.1 from afwall and activated the xposed modul.

After the first activation, the screen was black, only a hard reboot could restart the device.

Now the device is rebooting sometimes, I will keep watching 

Installed is CM13 with Xposed and Xprivacy.

Can I activate the afwall modul and use xprivacy simultaneously?

Thanks.

**Comment by Gitoffthelawn** [comment]
Where is it documented what this new Xposed module does?

**Comment by ka223** [comment]
I dont know the documentation, but in the options is it described as  
"Fix Downloadmanager Leak"
"... block apps downloading data using android build-in download manager ..."

**Comment by ukanth** [comment]
I use Xprivacy and AFWall+ together with CM13. Next time when you get a reboot just capture the logcat from developer option. I removed lockscreen notification option in 2.5.2. Because that could be the one of reason ( it was hooking systemui)

**Comment by ka223** [comment]
I updated this morning cm and cleared cache+devaik. 
No reboots since then, maybe it was a cm problem, sorry.

This issue can be closed (for now).

Thanks for this great app ukanth!

**Comment by ka223** [comment]
@ukanth 
is the current afwall xposed modul compatible with android 4.1?
I tested the module on my old device, but after activating the module (+reboot), the plugin option is not activatable in the afwall menu.
