### ISSUE TITLE
Connections' permissions sorting & filtering

### ISSUE THREAD

**Issue by antomonte** [ukanth/afwall#567]
This app is great, but I miss a lot being able to find easily which apps are allowed (or blocked) for a certain connection (wifi, data, roaming....)

Don't you think it would be even more great if you add any (or both!) of these?
- sorting option: per type or number of connection permissions
- filtering option: show only those kind of connection types chosen (wifi, data, roaming...)

**Comment by ukanth** [comment]
There seems to be no interest in this request. Hence closing it.
