### ISSUE TITLE
EU roaming will not be roaming anymore: firewall roaming rules need an update

### ISSUE THREAD

**Issue by androidunderground** [ukanth/afwall#569]
Next year, the EU will abolish mobile roaming charges in the EU and EU-associated countries. For phone/text/data roaming purposes, the EU will be a single country. AfWall+ needs an update to deal with this change.

The main reason for blocking data roaming with AfWall+ is to avoid international data roaming fees. When those roaming fees cease to exist, AfWall+ should no longer assume that you are roaming if you're anywhere in the EU with a EU SIM card.

To prepare for the upcoming change, AfWall+ needs an option to let mobile data pass unhindered if the SimCountryIso and NetworkCountyIso are both for EU countries, even if the codes are different. Something along the lines of:

> If SimCountryIso=NetworkCountyIso then roaming=no
> If SimCountryIso is in (list of EU country codes) and NetworkCountyIso is in (list of EU country codes) then roaming=no
> Else roaming=yes

AfWall+ already has permission to read SimCountryIso and NetworkCountyIso, so all it takes is 1) a few lines of code, 2) a list of EU country codes, and 3) an on/off switch in the settings to tell AfWall+ if it should see the EU as one country for firewalling purposes.

**Comment by ukanth** [comment]
@androidunderground, is it same as described here https://en.wikipedia.org/wiki/European_Union_roaming_regulations ?

**Comment by androidunderground** [comment]
Yep, that's it.

**Comment by ghost** [comment]
You definitely can't simply make the EU one region without the ability to turn that off. Carriers that provide unlimited data in your home country are not required to provide unlimited data in other EU countries.

**Comment by walrus543** [comment]
FYI EU roaming is now [official](https://www.cnet.com/uk/news/roaming-in-europe-is-now-free-heres-what-you-need-to-know/).

**Comment by Micha-Btz** [comment]
as @nyuszika7h say the ability to block roaming is important I thinks because the provider in Germany has new ideas to earn money. They have created a lot's of new tariff's with a lot of exceptions.

**Comment by ukanth** [comment]
This can be implemented with Profiles features. I don't intent to built this into firewall.
