### ISSUE TITLE
Pebble notification

### ISSUE THREAD

**Issue by kuebk** [ukanth/afwall#576]
Since last update I started to get notifications about applying rules on my Pebble smartwatch - is there a way to disable this behavior?

**Comment by ukanth** [comment]
No, currently there is no option to remove it.

**Comment by kuebk** [comment]
Do you plan to add it in future releases?

**Comment by ShapeShifter499** [comment]
@kuebk turn it off in the pebble app

**Comment by kuebk** [comment]
Didn't know it's possible that way, thanks. :-)
