### ISSUE TITLE
Cyanogenmod: change user -> connection refused

### ISSUE THREAD

**Issue by Af0x** [ukanth/afwall#581]
Hello,

My setup: AFWall+ v2.5.2 on my Cyanogenmod 13.0.20160920-NIGHTLY.

when I switch to another user and call the browser, connection gets refused. With "owner" account it works (I use "allow selected" and selected Browser with WIFI-Connection). If I disable AFWall+ it works fine.

Any idea how to solve this?

Regards,

Af0x

**Comment by ukanth** [comment]
You need to use blocklist mode and enable multiuser support from Experimental preference. Still doesn't work 100% perfect.

**Comment by Af0x** [comment]
hi, thanks for the hint. unfortunately it does not work for my environment. Plus I´d prefer keeping it on "allow selected" settings as it (hopefully) drops all disallowed traffic.
