### ISSUE TITLE
Wiki: System Applications to block or allow

### ISSUE THREAD

**Issue by walrus543** [ukanth/afwall#582]
> (vpn) - VPN Networking
> 
> If blocked, will not be able to use a VPN over the connection types blocked
> 
> Rec: Block if not using a VPN, otherwise enable only for connection types > being used to connect to the VPN

Not sure if it's correct since I made several dns/ip leak tests with Firefox when I'm connected to my VPN app.
The VPN is working even if the UID "VPN" is not checked.

My profile allows Internet access to my VPN app and Firefox (mobile data + VPN).

**Comment by ukanth** [comment]
@Gitoffthelawn , can you have a look ?

**Comment by Gitoffthelawn** [comment]
@ukanth Yes.  I added it to my list.  I'm overbooked right now, but hopefully I will have some time to take a look for you.

**Comment by Gitoffthelawn** [comment]
@Primokorn If you can provide any further details, that would be most helpful... thanks!

**Comment by walrus543** [comment]
@Gitoffthelawn
Here you go:

### My AFWall+ profile

My VPN (NordVPN - OpenVPN protocol) app has WiFi, mobile data and VPN enabled.
All other user apps only have VPN enabled (e.g Firefox beta)
(1016) VPN Network has no Internet access

### Custom script

I use a little custom script : https://webcloud.zaclys.com/index.php/s/yUXXO9E36Nnh14X

### VPN test

I'm connected to a server in Netherlands and I live in another country.
I did an IP leak test with Firefox beta and it shows an IP in Netherlands.
https://www.browserleaks.com/whois]
