### ISSUE TITLE
stale processes: constantly increasing number of su processes with every connection change

### ISSUE THREAD

**Issue by mark-orion** [ukanth/afwall#583]
I notice that the number of "su" processes created by afwall is increasing with every connection change (enabling Wifi, disabling mobile data etc.). It starts with 5 processes at every reboot of the phone and then increases to sometimes 50 or more until I reboot again.
My system:
Hardware: Fairphone 2
Operating System: FP OpenOS 16.08 based on Android 5.1

**Comment by Gitoffthelawn** [comment]
Hmmm... I noticed some weird _su_ bugs recently that got worse the longer the device was left on.  I wonder if the issue Mark is reporting is the culprit.

**Comment by ukanth** [comment]
Today I released a test version which address this issue, please test it

http://forum.xda-developers.com/attachment.php?attachmentid=3885532&d=1474781803

**Comment by mark-orion** [comment]
The test version seems to have the bug fixed. I only see five processes, number not increasing. I could not test everything because I could not import my settings due to "feature only available in donate version / key". This raises the following question:
How are you going to integrate the pay feature with F-Droid ? Although I used the donate version before, I am using a google free phone with F-Droid as main repository these days.

**Comment by ghost** [comment]
"Donate version" = paid version, NOT FOSS.
Same for the logs thing...
In my opinion, starting having non features aka features that are there but don't work if you not pay is not the way to go. If people want to help developers they will donate to the project, you (developers) don't need this kinda of non working features 'scam'.

I know this is a lot of work but paid features will ruin every open source app and you 'won't get any rich' nor popular by doing this.

I ditched google a long time ago because of free non-free apps, would be bad to see another FOSS app turning into one.

**Comment by Micha-Btz** [comment]
@ukanth can you please make a minor bug fix release?
for me it slows down my phone on CM-12.1.

**Comment by ukanth** [comment]
@Micha-Btz , it will be released tomorrow.

**Comment by ukanth** [comment]
Released. @mark-orion , send me an email, will send you donate key which will work with FOSS version. 

@Tony-il-Capo , AFWall+ source is still here and I have not integrated with any Google services like  License Verification ( which is not a hard thing to implement, but to keep the spirit of opensource ). I need some motivation to work on this project. Despite of almost all feature free initially, the piracy ratio was/is high.

**Comment by ghost** [comment]
> Released. @mark-orion , send me an email, will send you donate key which will work with FOSS version.
> @Tony-il-Capo , AFWall+ source is still here and I have not integrated with any Google services like License Verification ( which is not a hard thing to implement, but to keep the spirit of opensource ). I need some motivation to work on this project. Despite of almost all feature free initially, the piracy ratio was/is high.

I understand your point, but how people like me that don't use any google apps will get these "donate" features?

Only stupid people get pirate software that is actually free. Well, the piracy ratio will probably increase as people want those features working. 

I also think this violates some F-Droid standards and should be flagged.

> Even though such software can be included, when appropriately flagged, it is frequently the case that other "FOSS" software with these features is actually not entirely free.

AFwall+ it's a must have, especially for more advanced users but after this I will probably not update it again, on v2.2.3 all features work.

Thanks for you time, I'm just expressing my opinion.

**Comment by Gitoffthelawn** [comment]
@ukanth The thread is getting OT, but your comment and @Tony-il-Capo's response got me thinking: Besides money, what else could people provide that motivates you?

Motivation is very important! :+1:  You work so hard! :yum: 

Here's a little something extra for you to put on your digital shelf: :trophy: 

Perhaps something more than friendly emojis and kind words! :smiley: 

Let us know!

**Comment by ukanth** [comment]
@Gitoffthelawn , You just did it :) That's enough.
@Tony-il-Capo , Sure. I just expressed my opinion.

**Comment by breversa** [comment]
Sorry for posting here, but I'm having the same problem as @mark-orion : I'm getting rid of Google for privacy reasons and rely on F-Droid for apps, and of course, AFWall+ is the first I install when setting up a new device.

I'd love to support development and get a donate key in return, but I positively refuse to go through Google for that. Is there any other way ?

**Comment by ukanth** [comment]
@breversa , Please send me an email, I will send you the donate key which works with free/f-droid version ( BTW, you can find the paypal donate link at home page. )

**Comment by Gitoffthelawn** [comment]
Not sure if this is related or is a separate issue, but **in addition** to `su` asking for permission for `AFWall+`, `su` sometimes asks for permission for `AFwall+ [UID]`.  That's a literal string... the `[UID]` is **_not**_ replaced by a _uid_... it's literally the string `AFwall+ [UID]`.

**Comment by ghost** [comment]
> Please send me an email, I will send you the donate key which works with free/f-droid version

Very unorthodox method for non google users to get the non free addons, but I guess this app focus is not F-Droid repository anymore. F-Droid team and users also don't welcome antifeatures.
