### ISSUE TITLE
FC when trying to enter log settings in donate version.

### ISSUE THREAD

**Issue by hergen66** [ukanth/afwall#584]
I finally decided to donate and now i can't enter log settings any more - which is bit of a bummer, as detailed logging is supposed to be the main selling point of the donate version. Fresh install, than imported firewall rules from free version.

Logcat:
[2016-09-24_01-02-12.log.txt](https://github.com/ukanth/afwall/files/491277/2016-09-24_01-02-12.log.txt)

**Comment by ukanth** [comment]
It's a known bug, please do not import all preferences. it's fixed in recent version.
