### ISSUE TITLE
Expose color codes from layout folders

### ISSUE THREAD

**Issue by walrus543** [ukanth/afwall#586]
Hi,
AFAIK a light theme is not planned, not a priority but please consider removing hard-coded values from layout folders.
I can't convert AFWall+ to a light UI due to those color codes: https://parli.eu/v/lfslt
Please use color codes from values > colors.xml instead

Thanks a lot!

**Comment by ukanth** [comment]
@Primokorn , I will move it . Thanks for pointing it out.
