### ISSUE TITLE
F-Droid at 2.5.2

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#587]
I'm guessing it's a downstream issue, but thought you would like to know that F-Droid is still at version 2.5.2: https://f-droid.org/repository/browse/?fdfilter=afwall&fdid=dev.ukanth.ufirewall

**Comment by ukanth** [comment]
They have disabled auto update. So, It will take some time. I don't have any control over their release process

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/dev.ukanth.ufirewall.txt

**Comment by Gitoffthelawn** [comment]
Thanks.  Did they disable auto-update for all apps or just AFWall+?

**Comment by ghost** [comment]
v 2.6.0 is already there, obviously got flagged with non-free addons.

**Comment by Gitoffthelawn** [comment]
Yes, 2.6.0 got added in the last 10 hours.

**Comment by Gitoffthelawn** [comment]
@ukanth How does F-Droid get notified about new releases?  They are now stuck at 2.6.0, even though 2.6.0.1 was released several days ago.

I'm not sure if it's automated or human-generated, but the following page does indicate that someone/something at F-Droid knows that 2.6.0 is not the latest released version:
https://f-droid.org/wiki/page/dev.ukanth.ufirewall

**Comment by ghost** [comment]
If you want to get last version of AFWall from F-Droid, you need to be patient, like it was stated,  AFWall+ auto update is disabled. They probably need to review app at every update because of Anti Features, this also means low priority update.
They are aware of new releases
[F-Droid](https://f-droid.org/wiki/page/dev.ukanth.ufirewall)

> We don't have the current version of this app. (Check mode: Tags ^[0-9.vV]+$) 
> (Auto-update mode: None)
> The current (recommended) version is 2.6.0.1 (version code 15601).

**Comment by Gitoffthelawn** [comment]
That's my understanding as well.  Just wanted to make sure it's all on their end.
