### ISSUE TITLE
Translatable "About" and "FAQ"

### ISSUE THREAD

**Issue by TotalCaesar659** [ukanth/afwall#588]
Hello! Could you make windows "About" and "FAQ" translatable? It would be useful for those who doesn't know English. I would help with translating.
![screenshot_2016-10-03-04-29-48](https://cloud.githubusercontent.com/assets/14265316/19025687/053a4a80-8925-11e6-9990-e2930f90d716.png)
![screenshot_2016-10-03-04-28-25](https://cloud.githubusercontent.com/assets/14265316/19025688/0a881e7c-8925-11e6-9f56-48a2f95beb26.png)

**Comment by ukanth** [comment]
Currently it uses html files for this. I will think about changing it to strings.xml

**Comment by twckr** [comment]
I would support the idea of a translataple FAQ and About section

**Comment by Gitoffthelawn** [comment]
There are some minor issues with the FAQ and About sections that I was going to fix.  Specifically, the names of translation volunteers is getting chopped off.  If you are planning on switching it to strings.xml, I won't touch it until you do... unless you want me to fix it first (or you want to fix it).
