### ISSUE TITLE
Google Play blocked

### ISSUE THREAD

**Issue by Gringoise** [ukanth/afwall#592]
When the FW is enabled I cannot download anything from Google Play nor updating anything.
Google play - allowed
Media server - allowed
VPN - allowed 
DHCP+DNS - allowed
What else?

**Comment by ukanth** [comment]
Have you allowed "Google Play Services", can you see what is getting blocked in Log view ?
You need to allow "Download Manager" as well.

**Comment by Gringoise** [comment]
Yes, it is allowed. It is in the group "Google Contacts sync, Google play services, Google services framework, Google Account manager, Google backup transport"
The group is allowed

**Comment by ukanth** [comment]
can you see what is getting blocked in Log view ?

**Comment by Gringoise** [comment]
Yes:
- (kernel) - Linux kernel(0)
- Media Storage(10043)

**Comment by ukanth** [comment]
Have you tried allowing Media Storage(10043) ?
