### ISSUE TITLE
Not able to activate afwall, tested integrated and system tools.

### ISSUE THREAD

**Issue by Mannshoch** [ukanth/afwall#593]
Not able to activate afwall, tested integrated and system tools.

> 10-05 22:47:40.224 W/TOAST   (3367): toast owner:eu.chainfire.supersu   toast msg is :AFWall+ wurden Superuser-Rechte gewährt für eine interaktive Eingabe
> 10-05 22:47:41.834 I/AFWall  (1763): Error applying rules during preference change
> 10-05 22:49:23.024 I/AFWall  (1763): command 'ip6tables -A afwall -m state --state ESTABLISHED -j RETURN' exited with status 1
> 10-05 22:47:41.834 I/AFWall  (1763): Output:
> 10-05 22:47:41.834 I/AFWall  (1763): ip6tables: Protocol wrong type for socket.

**Comment by ukanth** [comment]
Please attach the logs from firewall rules.

**Comment by ukanth** [comment]
Switch to built in iptables.
