### ISSUE TITLE
Bluetooth theter stoped working

### ISSUE THREAD

**Issue by onolox** [ukanth/afwall#594]
The bluetooth tether was working, but 2 weeks past the tether stopped working, I have to disable afwall+ everytime I use theter.

Rules attached.

Android 6.0
Moto x 2014
[IPv4rules.txt](https://github.com/ukanth/afwall/files/518752/IPv4rules.txt)

**Comment by ukanth** [comment]
Thanks for the logs. I'll look into it.

**Comment by onolox** [comment]
If you need more logs, logcat, etc. just ask.

**Comment by ukanth** [comment]
Please send me the output of the following command

iptables -S

**Comment by onolox** [comment]
Here

[iptables .txt](https://github.com/ukanth/afwall/files/526180/iptables.txt)
[IPv4rules.txt](https://github.com/ukanth/afwall/files/526181/IPv4rules.txt)

**Comment by onolox** [comment]
In Kitkat I was using an app of the same base of yours, there BT tether was working, maybe you can find something in the source:

https://play.google.com/store/apps/details?id=com.jtschohl.androidfirewall

**Comment by onolox** [comment]
Bug fixed, thanks!

**Comment by onolox** [comment]
Hi, the problem have reappeared.
It started when I clicked apply rules twice, since then I can't tether anymore.

I know that the tether bug only appear if I click in apply rules, but a reboot in the phone makes the bug disappear. But since yesterday I cannot make it work with a reboot.

Other thing, if I invert selection and click apply rules, or select black list and apply rules, thether works, but it don't have to work in these cases.
[iptables.txt](https://github.com/ukanth/afwall/files/632609/iptables.txt)
[IPv4rules.txt](https://github.com/ukanth/afwall/files/632608/IPv4rules.txt)
