### ISSUE TITLE
Donations via Bitcoin

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#596]
Please provide a bitcoin address on your f-droid page and your github page to allow donations via bitcoin.  I am ready to donate now.
It would be great if we could also purchase the Pro version via bitcoin.  I don't have a google account, and I will not get one.  I love AFwall and I want to buy the Pro(Donate) version!

**Comment by vzool** [comment]
@rowyourboat I do support that you are trying to protect your privacy, and I respect this direction.
But, I'm wondering, if you don't have a google account, how can you receive notifications came from apps which used Google Cloud Messaging(GCM) to deliver their message to your device like Whatsapp, or how to install apps and keep track of new versions automatically?
Thanks

**Comment by aryoda** [comment]
Related to #638

**Comment by qubesuser146** [comment]
@vzool F-Droid and Yalp Store

**Comment by ukanth** [comment]
Added Bitcoin link long back. Hence closing this.
