### ISSUE TITLE
"Unable to remove AFWall+ startup script" message always displayed when disabling startup data leak fix

### ISSUE THREAD

**Issue by nyotov** [ukanth/afwall#597]
The "Unable to remove AFWall+ startup script" message is always displayed when disabling the fix for startup data leak (i.e. removing the afwallstart script). The script itself is removed successfully though.
I believe it has to do with 
`dev.ukanth.ufirewall.preferences.ExpPreferenceFragment.deleteFiles(Context ctx)`
always returning `false` ;)

**Comment by Gitoffthelawn** [comment]
Confirmed
