### ISSUE TITLE
Data leak when enabling WiFi or cell data

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#599]
First, I must apologize that I don't have more time to contribute to testing.  Hopefully contributing this bug report will be helpful.

I noticed that data is leaking past AFWall+ each time the user enables WiFi or cell data.

For example, if all connectivity is disabled in Android, and the user then enables WiFi, apps start sending packets almost immediately.  After about 5 seconds, AFWall+ finishes writing `iptables`.  As a result, for about 5 seconds, every app has free access to transmit/receive data from the internet.  At fast modern data speeds, much data gets transmitted in that time.

Tested on Android KitKat using AFWall+ v2.5.2 (v2.6.0.1 isn't working with WiFi).  _Active rules_ and _LAN control_ are enabled.

**Comment by ukanth** [comment]
This should not happen, because before we apply rules, we set OUTPUT to DROP. Please test with the latest version and let me know.

**Comment by Gitoffthelawn** [comment]
Will do.

**Comment by Gitoffthelawn** [comment]
If you will, please reopen.  I'll test on 2.9.0 within 5 days, and report back.
