### ISSUE TITLE
Toggling *Active rules* setting causes LAN control error

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#600]
Steps to reproduce issue:
1. Open AFWall+
2. Open Preferences->User Interface
3. Enable _Active rules_
4. Enable _LAN control_
5. Exit Preferences
6. Select _Apply_ in AFWall+ menu
7. Notice that LAN column is displayed in main table
8. Open Preferences->User Interface
9. Disable _Active rules_
10. Enable _Active rules_
11. Notice that _LAN control_ is still enabled.
12. Exit Preferences
13. Notice that LAN column is no longer displayed in main table

Tested on AFWall+ v2.5.2

**Comment by ukanth** [comment]
This issue is fixed in 2.7.0
