### ISSUE TITLE
afwall doesnt always apply ip table rules after phone restart - actually its gotten worse with android 6.01

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#601]
Using android 6.0.1
Most times after phone restarts, or switching between data and wifi, iptable rules tries to apply but doesnt complete, as my internet is stuck being offline.  Then i disable firewall and re-enable and then everything works again (very seldom), but most times i have to reboot my phone a couple of times to get it working.

**Comment by ukanth** [comment]
This issue is fixed in 2.7.0. Please reopen if it's not. Thanks.
