### ISSUE TITLE
cm13 sometimes no connection after connectivity switch

### ISSUE THREAD

**Issue by ka223** [ukanth/afwall#603]
Sometimes the afwall hangs by applying IP-table rules and I need manually to reapply the rules.

current google play version: 2.6.0.1

**Comment by ukanth** [comment]
Do you use SuperSU ? or native root ?

**Comment by ka223** [comment]
I use the build in cm13 root.
Maybe the problem started next to the last afwall update, but I can not be sure.  

I'm running on the current stable cm13 titan release.

**Comment by bfritz** [comment]
Pretty sure I've seen the same behavior, but I'm using native root on CM 12.1 and still on AFWall+ v2.5.2 .  Next time it happens, I will reapply rules to see if that restores connectivity.  (Feel free to ignore given that I'm on old versions; just hoping another data point might be useful.)

**Comment by ka223** [comment]
It is possible that this problem exist since 2.5.1 or 2.5.2 on my side too.

**Comment by 0xjxd** [comment]
Same behaviour on my op3 using Cm 13 native root. Wien switching from WiFi to mobile data and vice versa, there is no connection Till i apply rules manually again (sometimes afwall also crashes).

**Comment by walrus543** [comment]
Same issue here on my Nexus 5 (AOSP 6.0.1) but with Phh's Superuser. I'll try to identify the steps to reproduce the issue.
Sometimes I can't open AFWall+ at all (blank screen like a freeze). I have to force close the app. I thought it was due to Phh's Superuser but I was maybe wrong.

**Comment by ukanth** [comment]
I got multiple reports from users using native CM root and Phh's SuperUser. I will be testing the code with both of these and fix the issues. It would be great, if some of you just send me ANR report attached here/by email.

**Comment by Gitoffthelawn** [comment]
More data points: seen this happen with KitKat (LG) devices using Chainfire's SuperSU.

**Comment by ukanth** [comment]
It's difficult to fix things with OS Version + Superuser app. I need ANR/logcat etc.,

**Comment by drozdu** [comment]
I can confirm this, Cyanogenmod 12.1 with native CM root.
After I have flashed SuperSU problem is gone.

**Comment by ukanth** [comment]
Since I didn't get any ANR, I need your help guys. Please test the following build and let me know if this fixes the issues with native root & Phh's superuser app. 

TEST - 0
https://www.dropbox.com/s/k7sffrz1lqz8avu/AFWall%2B%202.7.0-TEST.apk?dl=0

**Comment by 0xjxd** [comment]
I couldnt install the app, it asks to Update the app and After confirming this it says "app could not be installed"...

**Comment by ukanth** [comment]
@0xjxd, you can't install from f-droid builds. This is generated using playstore key.

One more APK to test  ( TEST 1)
https://www.dropbox.com/s/urwp2ldfoo2jfjn/AFWall%2B%202.7.0-TEST-1.apk?dl=0

**Comment by ukanth** [comment]
Can someone help me resolve this issue ?

**Comment by 0xjxd** [comment]
If you Provide this app signed with F-Droid key i'm able to test this Version ;-)

**Comment by ukanth** [comment]
@0xjxd Sorry, I don't have control over f-droid builds and keys.

**Comment by bfritz** [comment]
> Can someone help me resolve this issue ?

I plan to do more testing to better understand how it is currently failing (v2.5.2).  I will test 2.6.x from f-droid and the APK linked above at the same time.  Unfortunately, it will likely be next week.  (In the middle of a big project launch now.)

@ukanth Is that APK built from the `beta` branch?  Would prefer to understand the changes prior to dropping the APK on my phone.

**Comment by ukanth** [comment]
@bfritz , Yes, it's built from beta branch. I will be releasing a stable build today. I got feedback from couple of users with same problem.

**Comment by ukanth** [comment]
This issue is fixed in 2.7.0. Please reopen if you still face the issue
