### ISSUE TITLE
iptables replaced by nftables

### ISSUE THREAD

**Issue by walrus543** [ukanth/afwall#604]
Hi,
XDA is down so I'll ask you here:
Is nftables possible/interesting for AFWall+?

Redhat post: [What comes after ‘iptables’? It’s successor, of course: `nftables`](http://developers.redhat.com/blog/2016/10/28/what-comes-after-iptables-its-successor-of-course-nftables/)

Thanks.

**Comment by ukanth** [comment]
No, I don't have plans to support nftables. May be in future If Android supports it.
