### ISSUE TITLE
Mask device informations?

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#605]
Hi! Given the extreme versatility of the app, I would propose to add another function (I hope it is not a idiotic thing or not relevant for the operations of the app): the ability to change (Root?) Or mask the identity device (Xposed module?) .. and, therefore, MAC Address, IMEI, Model ... in short, all the details available in the Settings + anything else useful to identify the device.

As I wrote, it might be idiotic or useless thing .. but I wanted to offer it the same because the app would become further polyvalent (and necessary!)

**Comment by ukanth** [comment]
Have you checked XPrivacy ?

**Comment by ghost** [comment]
Yes .. and do not work. Furthermore:
- Xprivacy is not on F-Droid (and I'm gradually making google store) and I would not know how to install and / or update it
- It does not allow the release of the pro-version with Bitcoin .. but only with google play credits
- It is not compatible with CyanogenMod and Replicant OS, but only with the "official" roms

In short, if possible, I would prefer to have this function directly into the firewall, please. I think it's easier and more efficient

**Comment by ukanth** [comment]
AFWall+ works based on underlying iptables which included in Android. I would like to keep that way. It's impossible to mask without Xposed and it's a duplicate effort of something which works better. 

To answer your question, I would like to keep AFWall+ as internet firewall and will add features around it.

**Comment by ghost** [comment]
If you want to add this ability using Xposed, okay .. it is what I proposed, otherwise I did not understand.

To be clear, I thought of a sort of open-source writing of the apps "device id changer" and "faker plus device".

**Comment by ukanth** [comment]
As I mentioned earlier, I don't have plans to introduce these features.
