### ISSUE TITLE
Log not working after turning it off and on again

### ISSUE THREAD

**Issue by schnapster** [ukanth/afwall#607]
Heya,

the log feature stopped working.
It worked perfectly fine, then I installed an app that was rather annoying requesting a lot of connections so I temporarily disabled the log/toasts.
After removing that app I enabled the log again, but no toast are displayed and the log shows as empty.
Other than that the firewall is working fine.
I try to uninstall and reinstall it, but that didn't help at all.
Any ideas how to fix it? What can I do to help solve this, any other logfiles I should provide?

Best regards

**Comment by ukanth** [comment]
Try setting logFetch option .

**Comment by schnapster** [comment]
Hey,

so I left the phone alone for awhile, and now the log and toasts work again.
Can't tell why exactly it started working again, I didn't do anything interesting besides using it as I usually do, not even a restart since I wrote the issue here.
