### ISSUE TITLE
Philosophical issue with "donation features" 

### ISSUE THREAD

**Issue by belevtsoff** [ukanth/afwall#609]
Doesn't keeping "donation features" closed source break the whole point of using an open-source firewall? I really want to donate, but getting a piece of closed-source code for this kinda feels wrong, 'cuz then it's not really a donation, but rather a purchase, don't you think?

**Comment by ukanth** [comment]
All donation features are right here in this same repository as open source, You can just remove the checks and compile it with all donate/paid features. 

I have not even integrated closed source validation frameworks like Google App Licensing libraries for validation. 

Thanks.

**Comment by belevtsoff** [comment]
@ukanth That's great news, thanks for the explanation! One more donation is guaranteed :)

**Comment by aryoda** [comment]
Related to #638
