### ISSUE TITLE
v2.7.0 not in F-droid??

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#611]
I cannot see the latest version being in F-droid.. why is this?
can you please update the repo ?

**Comment by ukanth** [comment]
Please raise the issue to F-Droid, I have tagged 2.7.0 build from my end.

**Comment by ukanth** [comment]
Seems like it's updated.

https://gitlab.com/fdroid/fdroiddata/commit/b4240d01fe69a739b98232d6a01fc23ff0bd0052

**Comment by ghost** [comment]
Was updated today? because im updating all my repo's just as usual and it still shows 2.6.0, so i dont get why thats happening?

**Comment by ukanth** [comment]
It should come in the next update batch I guess.
