### ISSUE TITLE
Wifi "connected, but no internet" issue with AFWall v2.8.0

### ISSUE THREAD

**Issue by killathe** [ukanth/afwall#618]
I think this might be similar as #603 or #612 still persistent in v2.8.0
When I leaf Wifi and later am connected to Wifi I get "connected, but no internet". And the Wifi symbol has an exclamation mark. I didn't recognize this as a AFWall problem for a long time and thought it would be CM13 Nightlys fault (and later switched to SlimRom to get the same issue). So I tested this on Samsung Glaxay S4 and S5. Both with CM13 and S4 with SlimRom.

I tried to pinpoint the problem, but it's confusing. Despite I get the message of "no internet" via wifi I sometimes still can surf the net. But sometimes I get no connection at all, even if I disable Wifi, then the mobile network sign also got this exclamation mark. In this case I need to disable AFWall and restart the phone.

**Comment by 0xjd** [comment]
I'm also still facing the issue in both versions (2.7.0 and 2.8.0). App doesn't crash anymore, but after every switch between wifi and mobile data i have to apply afwall rules manually again to get a connection...

**Comment by ukanth** [comment]
Do you have xposed ?
Do you have profiles enabled within AFWall+ ? 

@0xjd @killathe ,

Could you test this APK and let me know if you have issues ?

https://www.dropbox.com/s/7fgkkklgow3hy0c/AFWall%2B%202.9.0-BETA-1.apk?dl=0

**Comment by killathe** [comment]
Thanks for your reply.
No I'm not using xposed, or profiles within AFWall.
Seems there is a problem with the apk. After I hit install I get "App not installed".

**Comment by ukanth** [comment]
@killathe , Are you using F-droid builds ? Then you need to do clean install

**Comment by killathe** [comment]
Yes I installed from F-Droid. I've installed and tested. But problem is still the same.
If I disconnect wifi I get the ! symbol on mobile data. I switch wifi back on and get the ! on wifi. If I just apply rules manually it doens't change anything for me. I need to disable firewall completely. When the ! is gone, I can re-enable the firewall.

**Comment by killathe** [comment]
I've to correct myself.
With my S4 with SlimRoms the exclamation mark is now gone. After I installed AFWall beta (not via update), it was still there. Then I updated my Rom with the latest weekly build and wiped Cache+Dalvik Cache. After restart exclamation mark was gone.

Then I tried the same with my S5 with CM. Installed AFWall beta via Update. Tested: Exclamation mark still there. Restarted phone in recovery and wiped cache+dalvik cache. Reboot and tested: Exclamation mark still there. No success :/
I thought wiping cache was the solution. But doesn't seem so.

**Comment by ukanth** [comment]
I need firewall rules when you can't use internet. Please send me firewall rules from menu->show rules-> export to SDCard and attach it here.

**Comment by killathe** [comment]
Like I said in my first post. Internet via wifi is working most of the time. But it's the exclamation mark which persistently tells me I wouldn't be able to use wifi for internet. Well, I hope you can see something in the log which helps to get rid of it.
https://dl.dropboxusercontent.com/u/74168867/IPv4rules.log

**Comment by wizl** [comment]
This might not be a bug. I have been doing some research on sniffing network and Android connects to connectivitycheck.gstatic.com to check for connection. If there is no connection it gives the exclamation mark. From what I have read you can disable it in terminal and it will disappear.

`settings put global captive_portal_detection_enabled 0`
You have to reboot after this.

So this is actually showing that AFWall+ blocks the system processes. From my testing most VPN based firewalls don't block this so there is probably some data leaking.

**Comment by ukanth** [comment]
@killathe , Rules looks fine. Please disable captive portal by using the above command. 

@wizl Thanks for the input.

**Comment by Micha-Btz** [comment]
@wizl 

> settings put global captive_portal_detection_enabled 0

did you know if i had to set it after every boot?

**Comment by wizl** [comment]
@Micha-Btz the settings should stay permanent.

**Comment by killathe** [comment]
In Lineage 14.1 (Android 7.1.2) this doesn't seem to work anymore. Any ideas how to fix it?

**Comment by T-vK** [comment]
@killathe Please refer to #761 for Android N.

**Comment by Kein** [comment]
Any suggestions for Android 9?

**Comment by yuiop0113** [comment]
-[]()
