### ISSUE TITLE
Xposed DownloadManager leak fix blocking for all apps on wifi

### ISSUE THREAD

**Issue by agottschling** [ukanth/afwall#619]
I run afwall+ in Whitelist mode, and have the all apps option checked for wifi, however, when I turn on the Fix DownloadManager Leak Xposed integration, no apps that use the download manager can download files on wifi, even though the All Apps option should allow them to.

EDIT: Running CM13.1 Nightlies with AFwall+ v2.8.0

**Comment by ukanth** [comment]
I have the same settings and never had any issue. Can you mention any app in particular which was not able to download ?

**Comment by agottschling** [comment]
Pushbullet and Chrome when trying to download files. Using them to view webpages or send a text from my computer works, but not downloads.

**Comment by ukanth** [comment]
Is disabling the option in AFWall+ works with Downloads ?

**Comment by agottschling** [comment]
When I disable the Xposed plugin, the apps are able to download.

**Comment by ukanth** [comment]
Strange. I will check it.

**Comment by voidzero** [comment]
Chrome uses the system's download manager afaik
