### ISSUE TITLE
Fix Startup Leak - Grayed Out with Magisk v9 + Phh's SuperUser

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [ukanth/afwall#621]
Hi there, 

I've used your donator version for some time now, until recently (two updates ago?) suddenly Fix Startup Leak had de-selected and became un-selectable/grayed out. 

http://forum.xda-developers.com/apps/magisk/magisk-phh-s-superuser-android-pay-t3435921 says "su.d support (place scripts in /magisk/phh/su.d)" 

Is it possible for you to fix this issue? I don't know if this has already been asked or addressed on builds other than the donator version. (If so, could we have the option to enable beta participation like the regular afwall?)

Thanks for this great app and your time.

**Comment by ukanth** [comment]
It's already added  3f9a5ebea84d07620331c89e2b689fd5d1022dcf and tested by myself. Only one thing I observed was, by default there is no su.d folder inside magisk/phh/ . If you manually create one, then it works.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
I checked and the folder is there... I still can't turn the feature on. I'm using a Samsung Galaxy Tab S2 (SM-T710) 6.1 if that makes any difference.

**Comment by ukanth** [comment]
Sorry for the confusion, It wont work until I release the next version because I added that feature yesterday

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Is there any way possible to join beta group for donator app? Or can you send me it? As I understand it the standard edition + pay app you can, but I got donator some time ago thinking it was the same thing, less apps.

(I only ask because I am setting my device from scratch/new and in between x-privacy being down it is leaking with all these spammy google & sammy apps etc.)

Thanks for your time. 

Edit: I also noticed, despite approving permission for storage on prompt it was denied, I went to settings and allowed it, but that didn't seem to change anything since the new version isn't out.

**Comment by ukanth** [comment]
Kindly open another issue for better tracking. 2.9.0 is released on playstore.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
It appears to be fixed, thanks very much, happy holidays.

**Comment by ukanth** [comment]
Please review it on playstore. I'm tired of fighting with bad reviews if you don't mind :)

**Comment by walrus543** [comment]
@ukanth I just gave you 5 stars ;-)
Thanks for the fix.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
I did as soon as I saw your update. 👍  I never leave less than 4 stars for stuff I like with a bug and change to 5 when issue is fixed... some people do 1 star bombs and never update. 👎 

Sometimes it is hard to leave reviews though if you hit outside the box it closes it and you have to start over. (Google needs to fix this, make a confirmation to close if the dialog box has stuff written in it!) So sometimes I never send any review for an app ever. (very frustrating) 👎 (Not the case for afwall+) 👍 👍 👍 👍 👍
