### ISSUE TITLE
Active rules really needed for LAN control?

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#628]
Without *Active rules* enabled, the user can specify different rules for WiFi vs. mobile data.

The UI currently requires *Active rules* to be enabled to specify different rules for LAN.  Is this necessary?

**Comment by ukanth** [comment]
Yes. it's required to get IP address which can be changed upon connectivity change

**Comment by Gitoffthelawn** [comment]
Thanks.  Why does AFWall+ not need *Active rules* enabled when the user switched between WiFi and mobile data?  The IP address changes there too.  Thanks again.

**Comment by ukanth** [comment]
because we use interface level allow/block for WIFI (eth0 and equ for mobile data) for those. Put it in otherway iptables rules require ipaddress for LAN and not for WIFI and Mobiledata

**Comment by Gitoffthelawn** [comment]
Got it.  Makes good sense.  Thank you for the explanation.  I want to add a little more detail to the FAQ/Wiki.  When active rules are not enabled, the LAN gets the permissions for the WiFi, correct?

**Comment by rindeal** [comment]
Wouldn't it work if you simply (un)blocked the whole private address space? 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16?
