### ISSUE TITLE
[Feature Request] Long-press on app to launch it

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#629]
Within the rules list, long-press on an app to launch it.  Would be very useful for testing.

**Comment by ukanth** [comment]
Since we have system/user apps grouped based on uid/gid,it will be introduce unnecessary complexity.

**Comment by Gitoffthelawn** [comment]
Good point.

Wouldn't that be complex for system apps, but simple for user apps?

**Comment by ukanth** [comment]
Even simple apps like firefox and firefox beta will be using sample uid.

**Comment by Gitoffthelawn** [comment]
To clarify, if Firefox and Firefox Beta are installed on the same device, they will use the same uid?

**Comment by ukanth** [comment]
Yes, That's right

**Comment by Gitoffthelawn** [comment]
Thanks!  It's great to learn something new from you!  Much appreciated.
