### ISSUE TITLE
Possible to block mobile data after a particular date ?

### ISSUE THREAD

**Issue by championc** [ukanth/afwall#637]
Is it possible to block mobile data access after a particular date ?  In our country (and in many others I assume),  on a Pay As You Go tariff, I can get unlimited data for eur20 for 30 days access.  However, on day 31, it will start taking eur1 per mb.

Therefore, if I forget to top up again, or forget the anniversary date, I can easily end up being fleeced for a few mb of background data

**Comment by ukanth** [comment]
You can do it with Tasker plugin + profiles. Currently there are no plans to do it with in AFWall+
