### ISSUE TITLE
Donate version source, etc

### ISSUE THREAD

**Issue by jcrowgey** [ukanth/afwall#638]
Hi there,

I'm interested in the donate version:

1) how/where to donate without using play store; bitcoin?
2) how/where to review source code for donate version/build instructions?

Cheers!

**Comment by ukanth** [comment]
1. You can pay using paypal for now. I have bitcoin account as well. But not sharing it as of now.
Currently there is unlocker which I usually send it to people who request via email ( with / wo donation ), but that unlocker is closed source. 

2. Donate version is exactly same as Free version except name and icon. You can find the source of all donate features in this repo.

**Comment by wizl** [comment]
@ukanth I think people want to anonymously donate to you. That is why people request a bitcoin address. Most people who use this are people who give a lot on privacy.

You can easily create a new bitcoin wallet just for this purpose.

**Comment by jcrowgey** [comment]
@ukanth 
I don't have a paypal account and I don't have any money in my google account.  I do have easy access to bitcoin and was looking to donate.

In any case, I'm glad to know that building from source here should enable the missing features in the fdroid builds.

Cheers!
