### ISSUE TITLE
Disable remote control

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#639]
Hi! Please, add:
- the ability to disable these services to keep others from gaining access to the device via a remote terminal: SSH, SSHD, Telnet NC (net cat), Ping

- the ability to disable Package Manager, so that no apps can be installed remotely to the device. 

- the ability to disable ADBD.

**Comment by hackel** [comment]
None of that has *anything* to do with a network iptables firewall.  Do you even understand what you are asking or are you just copying and pasting?
