### ISSUE TITLE
Firewall is not activating

### ISSUE THREAD

**Issue by JakobDev** [ukanth/afwall#640]
I have AfWall+ 2.9.0 and want to activate it. But if I click on "Enable firewall" nothing happens. Nothing is blocked and the Button is still named "Enable firewall". I have a Wiki Lenny 2 with Android 5.1 who is rooted with KingRoot.

**Comment by ukanth** [comment]
This is addressed in 2.9.1

**Comment by JakobDev** [comment]
I got my Version from F-Droid
