### ISSUE TITLE
conflict with newer CM13

### ISSUE THREAD

**Issue by ildar** [ukanth/afwall#642]
ref: https://jira.cyanogenmod.org/browse/NIGHTLIES-3547
Since 4/Dec/16 I find my tablet unable to use internet. Disabling and re-enabling AFWall+ brings internet back. I dumped iptables and found "Chain OUTPUT (policy DROP)" (See the diff)

I guess CM introduced some firewall but that broke AFWall+ compatibility.
P.S. AFWall+ also started to hang on opening in 50% 

May I suggest AFWall+ stop relying on the default policy and set explicit
ACCEPT any any ?

**Comment by 0xjd** [comment]
i'm facing same issue! referenced in #641 #603 #612 or #618....

**Update**: Since i've updated to version 2.9.1 everything is working fine!

**Comment by ukanth** [comment]
Please share the log from menu-> Firewall rules-> send error report ( or export) and attach it here.
