### ISSUE TITLE
inspect contents of blocked packets

### ISSUE THREAD

**Issue by jcrowgey** [ukanth/afwall#643]
I'm curious if it's possible within the existing program (or if perhaps it would be easily modifiable) to enable inspection of blocked packets.

Essentially, the log feature shows me that certain programs (that I didn't expect to) were trying to use the internet.  I can see the IP, port, protocol that they were trying to use, but now I'd like to see what data they were trying to send.

Thanks!!

**Comment by ukanth** [comment]
You can use OS Monitor or Network Log for the same. I don't have plans to add it. In 2.9.2, you can query it.
