### ISSUE TITLE
Can it run without root in COSU mode?

### ISSUE THREAD

**Issue by sandys** [ukanth/afwall#646]
Hi,
We are looking to deploy a few Android devices with kiosk mode firewall using Android COSU . 
https://codelabs.developers.google.com/codelabs/cosu/index.html?index=..%2F..%2Findex#0

https://developer.android.com/work/cosu.html

We are trying to get internet in places with poor people who don't necessarily can afford it. 

We are willing to fund some amount of this is possible (atleast cover cost of any additional 6.0 devices).

**Comment by ukanth** [comment]
I'm not sure if it still valid. Never explored or interested. Feel free to reopen if required.
