### ISSUE TITLE
Rules are not applying after boot

### ISSUE THREAD

**Issue by gytisrepecka** [ukanth/afwall#647]
I have several rules defined, e. g. Instagram is not blocked when roaming, NVR viewer is blocked everywhere except LAN, etc. But these rules are applied only when I hit Apply manually - otherwise they are not effective. So after each reboot I have to re-apply them again. Tried switching on startup delay, didn't help. What coukd be the problem?

Device is Motorola Nexus 6 with latest Android 7.0 image from Google.

**Comment by keepasa** [comment]
I'm assuming you have option "fix startup data leak enabled"?   Also did you try enabling IPv6?

**Comment by gytisrepecka** [comment]
Unfortunately Fix startup data leak is not supported on my device even though I have SuperSU.

**Comment by keepasa** [comment]
I have another device (Nexus 7) running DU 7.1.1 with latest SU and also get symptom of "Fix startup data leak" fails to enable the check-mark.  Are you also running on 7.1?  If I reboot with firewall disabled, I have to enable it once booted or else no traffic.  If I reboot with firewall enabled, then it works ok, no need to cycle enable.

However on my Samsung S2 running DU 6.0.1 with latest SU, the  "Fix startup data lea" works just prefectly.  I'm beginning to think it may have something to do with Android Ver 7.x new restrictions?

**Comment by gytisrepecka** [comment]
I am running Android 7.0 (NBD91U).

**Comment by ukanth** [comment]
@keepasa , @kelmas . Please share the iptables rules with logs ( menu-> Firewall rules-> Send error report)  right after boot before reapply the rules manually.

Thanks.

**Comment by ukanth** [comment]
Thanks for the logs, can you execute the following command on your device (nexus 6)

ls -l /sys/class/net
ls -l /sys/class

also after reboot, before applying the rules, execute the following from adb/console

su
iptables -S

**Comment by ukanth** [comment]
Also, try enabling "su during boot" from SuperSU app.

**Comment by Gitoffthelawn** [comment]
@ukanth Does AFWall+ typically need `su` to be enabled during boot?  Or is this something you are only suggesting for troubleshooting purposes?

**Comment by ukanth** [comment]
@Gitoffthelawn , Yes. It's required for few devices.

**Comment by Gitoffthelawn** [comment]
To translate, it's not required for most devices, but is required for a few devices.

@ukanth If I got any of that wrong, please correct me.

**Comment by gytisrepecka** [comment]
Unfortunately I've got device software updated before running the commands. However, now with Android 7.1.1 (N6F26Q) rules does apply automatically on boot even without enabling **Startup delay**.

**Comment by saksham12** [comment]
I'm facing the same issue. After a reboot, the rules have to be applied manually. My device is a Nexus 5x running Android 6. I tried enabling su during boot.

**Comment by ukanth** [comment]
Fixed in 2.9.2
