### ISSUE TITLE
Visual glitch with the modern widget

### ISSUE THREAD

**Issue by walrus543** [ukanth/afwall#648]
Hi,
Anywhere I put the widget icon on my homescreen, the related features are always available at the same place and the right is cut.
Thanks.

Nexus 5 - Resurrection Remix 7.1.1 - AFWall+ 2.9.1 15902 - Nova launcher - 400 dpi instead of 480

Widget: https://osine.cozycloud.cc/public/photos/photos/05f8a94e24653dbedefd1a942a00aae6.jpg

As you can see, the widget icon is too big compared to other app icons.

**Comment by ukanth** [comment]
You can adjust using menu->Preferences-> Widgets-> X & Y Position.
