### ISSUE TITLE
Method to auto compare current iptables with AFWall iptables?

### ISSUE THREAD

**Issue by keepasa** [ukanth/afwall#649]
In order to solve any issue with other apps overwriting the iptables, in future, can AFWall compare the current iptables with the firewall saved ones and display some alarm or red dot if they do not match?  This can also help avoid manually re-applying iptables again if the iptables match, so no need to re-apply perhaps.

**Comment by ukanth** [comment]
Something like watchdog for iptables. It will be battery consuming. Let me think over it.

**Comment by Gitoffthelawn** [comment]
This could be an on-demand action, so as to not consume battery.

**Comment by ukanth** [comment]
Fastapply was introduced for this long back. Hence closing this.
