### ISSUE TITLE
"Fix startup data leak" checkbox not available (magisk+)

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#650]
If the "Fix startup data leak" checkbox is dimmed so that it cannot be enabled (checked), please reply to this issue so we can figure it out.

Please supply the AFWall+ version, Android version, `su` app, `su` app version, whether or not the Xposed Framework is installed, and whether or not AFWall+ is enabled in Xposed.  Here is a template:

**AFWall+ version:** 2.9.1
**Android version:** KitKat
**su:** SuperSU by chainfire
**su version:** 2.79
**Xposed installed:** Yes
**AFWall+ enabled in Xposed:** Yes

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@ukanth @Gitoffthelawn
 
AFWall+ (Donate) "Fix startup data leak" is gray and cannot be enabled. Recently Magisk updated making Phh's SuperUser no longer necessary/supported, Phh's SuperUser is now built into Magisk 11.1 + Magisk Manager 4.x (With compatibility fixes/feature enhancements.) 

**Magisk 11+ supports init.d natively now, new location is: magisk/.core/post-fa-data.d folder**, I don't know how to move the script there or even find the AFWall+ Fix startup data leak script, if you get the time, can you please assist/update? Was working excellent until I upgraded to Magisk v11.1 + Magisk Manager v4.1. You're probably very busy, but your assistance would be greatly appreciated when you have the time.

https://forum.xda-developers.com/apps/magisk/module-init-d-simulator-t3548645 (not recommended with Magisk v11.x + Magisk Manager v4.x (Shows location of change.)

**AFWall+ (Donate) version:** v2.91
**Android version:** Marshmallow v6.1 (December 1, 2016 security patch level) (Touchwiz - Samsung)
**SU:** Magisk Manager v4.1 - SuperUser (Built in)
**SU version:** 6:MAGISKSU (topjohnwu) (sdk23) (Built into Magisk Manager v4.x)
**:Xposed installed:** Yes (Magisk - Unofficial Systemless) (xposed-v87.0-sdk23-topjohnw)
**:AFWall+ enabled in Xposed:** Yes (In latest Material Design Xposed Installer v3.0.1)

Samsung Galaxy Tab S2 8.0" (SM-T710) (2015) (Wifi)

See old ticket issue previously resolved: https://github.com/ukanth/afwall/issues/621

Resources:
Magisk v11.x / Magisk Manager v4.x: https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445
(Magisk - Unofficial Systemless Xposed v87.0 (sdk23)): https://forum.xda-developers.com/xposed/unofficial-systemless-xposed-t3388268
Material Design Xposed Installer v3.0.x: http://forum.xda-developers.com/xposed/material-design-xposed-installer-t3137758

Apologies to @Gitoffthelawn for semi-hijacking this ticket, they beat me to the punch to post this issue myself. 

**Edit:** Gitoffthelawns post doesn't mention magisk, so definitely related issue but not the same mechanism, thought I would mention this.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@ukanth 
Hi,

Recent updates to Magisk have rendered the init-d simulator mod broken, author hasn't responded back.
Currently I can no longer use the feature again. I realize you probably have lots on your plate, however, it would be much appreciated if you could add a path to the new magisk spot for start scripts.

I'm assuming it's still the location I made in my earlier post, I am not a developer so I don't know.

Thanks

**Comment by tortugaverde98** [comment]
I was able to resolve this problem on my phone.
In Afwall, preferences, experimental, press "Startup directory path for script", and choose "/system/etc/init.d"
Once I did that, I could then check "Fix startup data leak".
I also checked that the script was in place with terminal:
cd /system/etc/init.d
ls
There I saw the afwall script.
I rebooted, went back into afwall, and it was still correct. I hope this helps.

**Comment by MrGlasspoole** [comment]
Tried what tortugaverde98 recommended but "Startup directory path for script" is only a grey popup with cancel. I cant select a path there.

Magisk v17.1
Android 7.0

**Comment by MrGlasspoole** [comment]
Tried what tortugaverde98 recommended but "Startup directory path for script" is only a grey popup with cancel. I cant select a path there.

Magisk v17.1
Android 7.0

**Comment by ljani** [comment]
I think "Startup directory path for script" used to work for me, but now with Magisk v18.0, the dialog is empty for me as well. Magisk v18.0 moved some stuff around, I'm not sure if it affects anything:

> - [General] Boot scripts are moved from <magisk_img>/.core/\<stage>.d to /data/adb/\<stage>.d

**Comment by ljani** [comment]
Also #917 adds support for the `/data/adb/<stage>.d/`.

**Comment by zputnyq** [comment]
Hi @ukanth,
My apology since SuperSU is deprecated, Fix startup data leaks on afwall + v3.1.0 is unable to detect path when SuperSU is in SBIN mode. I have a purpose on using SBIN mode

https://chainfire.eu/articles/981/SuperSU_v2.82_SR2_released

I'm on SuperSU 2.82 SR 5 android 6.0.1.
