### ISSUE TITLE
No buttons on Notification filter selection screen 

### ISSUE THREAD

**Issue by phipolis** [ukanth/afwall#652]
Current market versions of AFWall+, Android 7.1.1 on Nexus 6P

Preferences > Logs > Notification Filter screen shows the list of installed apps, but not the OK button, making it impossible to update the selection. See attached screenshot. I just updated from Android 7.0.0 to 7.1.1. I didn't have this problem the last time I used the notification filter, so it might have been a system change.

![screenshot_20170107-132538](https://cloud.githubusercontent.com/assets/6742702/21744230/a3e16820-d4df-11e6-9767-c09bd9327991.png)

**Comment by ukanth** [comment]
Fixed in 2.9.2
