### ISSUE TITLE
Notification filter options aren't saved (Google Pixel XL) 

### ISSUE THREAD

**Issue by lioux** [ukanth/afwall#653]
On latest AFWALL+ (Donate)  2.9.1,  Notification Filter options are never saved. This is a Google Pixel XL stock ROM 7.1.1 NMF26O. Supersu 2.79RC2. ElementalX P 1.02. I'm using built-in Busybox / iptables. However, I've already tried using system versions as well.

Notification Filter options are working fine on Nexus 6P and a Galaxy Nexus. 

Let me know if you need any further information or any tests.

**Comment by ukanth** [comment]
Please try 2.9.2
