### ISSUE TITLE
Traffic details are always zero 

### ISSUE THREAD

**Issue by Hamza-Megahed** [ukanth/afwall#654]
i use AFWall and seems pretty efficient dealing with IPTables (Android 7.1.1) , but i have a small problem which is all my traffic details are always zero in both upload and download for all applications

**Comment by vzool** [comment]
@Hamza-Megahed Can you make a screen shot for this. Thanks

**Comment by Hamza-Megahed** [comment]
Hi @vzool 

Firewall is activated but as you can see all traffic details uploaded and downloaded are zero and that for all applications , i even tried to reinstall it several times 
i'm using afwall+ 2.9.1 on nexus 5x android 7.1.1 

![2](https://cloud.githubusercontent.com/assets/2940656/21999203/94a0ef20-dc41-11e6-8733-cf3588719673.png)
![1](https://cloud.githubusercontent.com/assets/2940656/21999234/b77bd6fe-dc41-11e6-9b1b-16892f03d374.png)

Thanks.

**Comment by vzool** [comment]
@Hamza-Megahed Aha I see that.
But, it turns out that this problem in the Donate Version as well.
Thanks for your report, someone will fix it.

**Comment by Hamza-Megahed** [comment]
problem fixed in v 2.9.3 . thanks

**Comment by Abu-Khulzat** [comment]
Hi! The same issue is happening on Oneplus 6T OS 9.0.7. The traffic stats are always zero for all apps
