### ISSUE TITLE
Automatic Error Reporter [Feature Request]

### ISSUE THREAD

**Issue by vzool** [ukanth/afwall#668]
Hi,
The users of this application are increasing every single day, which may be associated with the lack of full error report for every single issue happened to many users in specific time frame.  I'm looking for a best quality that we can get from afWall.
So, I  suggest that we add a [Crashlytic from Fabric](https://get.fabric.io) which is library which should be bundled with app to report any unhandled exception from all users.
Even so,  it would be [integrated with GitHub](http://stackoverflow.com/questions/28220573/how-to-integrate-crashlytics-with-github) to create a new issue with every exception.
How wonderful of that? :)

**Comment by ukanth** [comment]
I thought about it, But we need to find an opensource analytics tool. Most of the users are from F-droid, As you might know, crashlytics has been acquired by Google and they will integrate with firebase which is closed source.

I would like to keep AFWall+ away from anything closed source,

**Comment by vzool** [comment]
This is a good reason, but what about [ACRA](http://www.acra.ch/) it's an open source solution and it does report unhandled exception to any URL we want (ex. afWall website) which then we can derive that request to create a new issue using GitHub APIs. This sounds promising :)

**Comment by Gitoffthelawn** [comment]
I have mixed thoughts on this.

On one side, reports of unhandled exceptions could very well be useful... if one or more people are committed to working on fixing them.  The notion of adding reports to GitHub is appealing.

On the other side, a firewall that generates it's own traffic is always a questionable practice.  People who use firewalls generally want as little traffic as possible.  Also, firewalls need to be as small and compact as possible so they don't occupy unnecessary resources.

I don't think there is a "right" or "wrong".  I think both perspectives have their virtues.

I welcome discussion. :)

**Comment by vzool** [comment]
@Gitoffthelawn Nice thinking & concerns,,, I got really busy even I didn't read this until now.

I think we can make like what **Mozilla Foundation** did, that we ask users to share their Bugs if whenever happened with kindly message like "Help us to improve the AFWall+, every Bugs matter!" and the title is "Community Calls You".

If user refuses at first time another message tells "Your space is reserved for you, if you desire to change, goto Preferences > Report." .
We even can show the user what data would be shared, like an example and where those information will goes in the Help/FAQ section.

We recommend to user, if you facing a problem with some type, that difficult to explain, enable reporting and try to replicate the event again, after that disable it if you prefer to do that. 

I guess report functionality should trigger and work only when fatal error occurs, I don't think it does monitor the application all times. I prefer to implement a Hook or a Dispatched Event to process this.

Server application will be uploaded to github and show what bugs reported by, I imagine that we can show commit for last commit that server application runs on, automatically on every new pull from main repository.

Discussion reveals great stuff, I like that. :)

**Comment by ukanth** [comment]
Current error reporting works. Hence closing this.
