### ISSUE TITLE
All apps aren't listed.

### ISSUE THREAD

**Issue by Rbagman** [ukanth/afwall#669]
I have the Red Moon (F-Droid) app installed and AFWall+ doesn't list the app. I assume block by default is securing this app.

> root@t03g:/ # cat /proc/12082/cmdline
> com.jmstudios.redmoon

**Comment by ukanth** [comment]
It doesn't have INTERNET permission, AFWall+ lists applications with INTERNET permission.

**Comment by Rbagman** [comment]
I did not know that.
