### ISSUE TITLE
UPNP broadcast blocked if LAN access is given

### ISSUE THREAD

**Issue by Superwallah** [ukanth/afwall#671]
I have a couple of apps that I only want to use in my LAN. I use them to control my home devices (lilke IP radio, Hifi receiver etc), but I don't want to have them "talking home" via the internet.

I have an app that tries to send UDP packets to 255.255.255.255:1900 which is SSDP via UPNP.
These packets are blocked by AFWall+ 2.9.1 as I can see from the log view.
The app has granted access to the LAN, but neither to Wifi internet nor to mobile internet.

255.255.255.255 should be opened in such a case.

**Comment by Superwallah** [comment]
same applies for UDP to 255.255.255.255:161 which is an SNMP broadcast. My printer plugin app tries to scan the local networks for printers with such a request. I would like to limit this app to the local network, too, by allowing "LAN", but no "Wifi" access.

**Comment by Superwallah** [comment]
https://github.com/ukanth/afwall/issues/326 is about a similar topic (mDNS local broadcasts). For me, it is not a question if a certain service (upnp, mdns...) is commonly known or used by users. It is just that I expect that an app that is meant for LAN usage will work if I set the "LAN" checkmark (and only this one) in AFWall. As long the IP request is based on a protocol that is defined in an RFC standard track, it should be accepted as "valid LAN traffic".

**Comment by ukanth** [comment]
Have you checked allow input request from Experimental preference ?

**Comment by pyc0de** [comment]
I confirm that even when 'allow input requests' is checked all snmp/upnp/mdns traffic is blocked.

**Comment by brunoligne** [comment]
Hello,
First, thanks for your great app !

I think i have the same problem with mDNS.
I use the iRobot Home application that tries to find the vacuum connected to my WiFi network. But AFWall+ blocks mDNS. I see it in the logs and the toasts. But I don't see how to ask the firewall to allow mDNS communicate.
mDNS (ID : 1020)
Destination : 224.0.0.251:5353
Protocol : UDP

mDNS does not appear in the list of aprobations.
I have checked 'allow input requests', but not best.
What to do in this situation ?

Little suggestion for improvement : it would be great if there was the ability to jump from an application listed in the logs, to the same application in the list of approvals. This would avoid having to look for a blocked application in the long list of apps to approve !

Sorry for my english. I'm french.

Thanks again.

**Comment by gerroon** [comment]
I have the same issue on 5.1. Is this a result of a bug, or it needs to be a feature req?

thanks

**Comment by gerroon** [comment]
@brunoligne have you resolved the issue? If so how?
