### ISSUE TITLE
Fully Integrated Dns_crypt works well with Afwall on both WIFI and Data

### ISSUE THREAD

**Issue by optimumpr** [ukanth/afwall#672]
I have successfully integrated Dnscrypt into a Lollipop rom and it fully works with Afwall.  You only need to white-list (allow internet access) to apps running as root. Tested with Opendns on both WIFI and Data.

I used the following CM commits: https://review.cyanogenmod.org/#/q/dnscrypt

P.S. This is not an Issue, but rather information, since Dnscrypt issue is closed

**Comment by ukanth** [comment]
Thanks, https://review.lineageos.org/#/q/dnscrypt

I will close this issue.
