### ISSUE TITLE
Feature Suggestion - Screen on/off  rules

### ISSUE THREAD

**Issue by EMK2000** [ukanth/afwall#678]
I have seen some other non-root firewall that can control the data traffic for screen on/off separately. Can your app also add this feature?

**Comment by Zulgrib** [comment]
You can set two different profile and switch them using tasker or similar

**Comment by ukanth** [comment]
Duplicate of #492

**Comment by SkyWheel** [comment]
@Zulgrib , could you please clarify how to do this? Never used a tasker before...
