### ISSUE TITLE
X86 support 

### ISSUE THREAD

**Issue by Zulgrib** [ukanth/afwall#681]
What is exactly the purpose of pushing an update to x86 users when the change log says you are dropping support for x86 ? Break app's function on purpose for people trusting you that kept auto update on ? If at some point you drop support for an architecture, don't make the update that drop support available for users of that architecture.

**Comment by Zulgrib** [comment]
https://lut.im/W0Lec00S8W/rI4OLxoq9ToDZL5O.png

https://lut.im/wvHVCok0AB/mGHHJf7nBChQTVic.png

**Comment by Magissia** [comment]
What is dropped exactly ? If the app works but x86 binaries are not shipped anymore this is not a problem, system's iptable and busybox could be used.

**Comment by ukanth** [comment]
Does AFWall+ stop working for you ? If you update from 2.9.1, all should work fine. Even If you install fresh also it should work fine. 

What actually dropped was built-in support for busybox for nougat. Prebuilt executables is not removed from AFWall+ yet. Going forward, from Nougat onwards, people need to install busybox on x86 devices.

I removed that line from changelog to remove confusion. Thanks

**Comment by Ergonomicmike** [comment]
Thanks for the clarification. I, too, was confused about dropping x86 support, as I have an Intel based Android tablet. (Asus Zenpad S 8.) I thought no x86 support meant that this latest version of AFW+ wouldn't work.
