### ISSUE TITLE
afwall-wifi-lan sometimes not referenced

### ISSUE THREAD

**Issue by Jonny007-MKD** [ukanth/afwall#687]
The last days I had the problem that my apps with only wifi-lan permissions could not communicate. I looked at the afwall+ rules and found this line: `Chain afwall-wifi-lan (0 references)`
So I tried to gather information for this issue, changed the permissions of another app and suddenly the chain is referenced: `Chain afwall-wifi-lan (1 references)`.
So right now, my apps can communicate to the LAN, which they weren't able to, before.

As soon as the problem reoccurs, I will upload my rules.

I'm running afwall+ 2.9.1 from F-Droid.

**Comment by ukanth** [comment]
This is addressed in v2.9.3
