### ISSUE TITLE
I need to enable all connections to access the local lan

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#689]
Hi

I do not remember this being an issue in the past but I just realized that the latest version does not let me connect to local network as long as I do not give full acess to the apps. Full access meaning that I have to enable Lan/Connection/Vpn (maybe vpn is not needed). 

I am talking about accessing devices that are in the same router not like trying to access another chained one. 

I have VPN/Lan/Connection (and with ip6 support). I am using 2.9.1  also inbound connections is enabled. Firewall is fuly functional except that the local lan access is not avail as long as I do not give internet access to the devices.

I tried this on Marshmallow and Nougat (lineage os) and I have the same issues with these devices however another Lollipop device does not seem to suffer from it.

**Comment by knezi** [comment]
I can confirm it does not work in 2.9.1 on Lineage OS, but it seems that it is resolved in 2.9.4. I've received the update just today.

Can you please check it again?

**Comment by gerroon** [comment]
I just updated my phone to Lineage OS 7.1 (the device above was another device) and I still have the same issue that I reported in this bug last year :( 

I used to haev Lollipop on this phone and Afwall worked fine, but  now with 7.1 only the apps with full internet access can see the local network properly. 

I seem to be able to get it work **if I disable my data plan**, so there is a bug there somewhere.

I do not have any scripts and I am using 2.9.9 from Fdroid

**Comment by gerroon** [comment]
So if an app is not allowed all the way, it cant search for things like Upnp/DLna, udp is block. Is there a way to get around this? Only apps with full acces are able to access the loal network fully :(

**Comment by ukanth** [comment]
Please reopen if you still have this bug in 3.x
