### ISSUE TITLE
Protokoll Filter funktioniert nicht

### ISSUE THREAD

**Issue by toaskoas** [ukanth/afwall#690]
Ich möchte gerne einige Meldungen deaktivieren. Wenn ich den Haken setze, aus der APP raus und wieder rein gehe, dann ist der Haken weg. Es wird nichts gefiltert.

Transate: I would like to disable some messages. If I put the hook, from the APP raus and go again, then the hook is gone. Nothing is filtered.

**Comment by treakiandroid** [comment]
human translated, please dont use horrible machine translations/menschlich Übersetzung, bitte nutzen Sie keine schrecklichen maschinellen Übersetzungen:

protocol filter dose not work

i would like to disable some messages/notifications (both is possible meant in this context...).
If i enable the checkbox, leave the app and open it again, it is unchecked again. It dose not filter.

**Comment by ghost** [comment]
You mean the notification filter? That seems to be broken for me as well.
