### ISSUE TITLE
[v2.9.5] Rules are not being applied, Manually Applying them again needed

### ISSUE THREAD

**Issue by rancidfrog** [ukanth/afwall#692]
Magisk Manager got notification of new update although not enabled in whitelist.
After applying rules again, MM cannot check for internet anymore.
![](https://s16.postimg.org/4wkq0fh2t/Screenshot_20170324-093021.png)
Somehow rules are not being forced. Or are not being applied over time, reboot, ?

MxPlayer was also able to check for new update even though it is not on whitelist:
![](https://s15.postimg.org/my365bgl7/Screenshot_20170331-195215.png)

**Comment by 9Morello** [comment]
I'm getting a similar error. Stock, fresh installed Lineage OS. Right after installed, AFWall works as expected, but after a reboot, it just stops enforcing rules altogether. Even if I reapply the rules, apps can freely connect to the Internet.

I'm using the latest version (2.9.4, downloaded from here).

Edit: seems like this is 2.9.4 specific. I reinstalled 2.9.1 and its working as intended. Seems like my issue is different from this one.

**Comment by rancidfrog** [comment]
It keeps happening on boot, after device switched off.
Or, sometimes on reboot.

Vlc was accessing video, even though it is not whitelisted,
I opened aafwall app and vlc stopped playback.

**Comment by rancidfrog** [comment]
Any updates on this?
As the whole poimt of firewall is to block/restrict access and currently it is not working sometimes.

**Comment by ukanth** [comment]
Please send error report when it happens. Without those information, I can't help.
