### ISSUE TITLE
[feature] Any way of limit 3g data independently of 4g?

### ISSUE THREAD

**Issue by pedrazadixon** [ukanth/afwall#693]
My current Internet plan allows 2gb for 3g surfing and 20gb for 4g LTE surfing. 
Any way of limit 3g data independently of 4g?

In Attachment file I have dual sim. but in the test I just change betwen 3g and 4g in only sim 1.
[IPv4_Rules_AChain.txt](https://github.com/ukanth/afwall/files/875923/IPv4_Rules_AChain.txt)

See also https://forum.xda-developers.com/showpost.php?p=71622150&postcount=3724

Thanks in advance.

**Comment by ghost** [comment]
That's got to be the most ridiculous thing I've ever heard. I feel sorry for you. Basically, your carrier is forcing you to use 4G and drain your battery more for a higher data cap.

**Comment by pedrazadixon** [comment]
@nyuszika7h Yes my friend, welcome to my country.
