### ISSUE TITLE
AFWall+ Permanently Disables Mobile Data connection even after Uninstall

### ISSUE THREAD

**Issue by evilrobotted** [ukanth/afwall#694]
I installed AFWall+ so that I could use it alongside OpenVPN. It works fine on WiFi, but it disables my Mobile Data while on WiFi, and then doesn't switch it back on once WiFi is turned off. Even manually cycling the Mobile Data Connection on and off doesn't do anything. It's like AFWall+ messed with some setting which disables the Mobile Data connection completely, with no option of getting it back. I had to uninstall AFWall+ completely, reboot, and then did a bunch of random tweaking in ADB like flushing iptables and things like that in order to get the connection back. Then... I reinstalled AFWall+ and the exact same problem happened again. It happens whether or not I have the Xposed module enabled and whether or not I have AFWall+ set as a Device Administrator. It just completely kills my Mobile Data connection. I don't even have access to anything on any network when WiFi is off now. I'm on Stock Marshmallow 6.0.1 Moto G4 rooted with Xposed. What can I do?

**Comment by ukanth** [comment]
Not possible with AFWall+ , It doesn't interfere with system level settings at all. Please check if you have any other application which is causing this issue.

**Comment by evilrobotted** [comment]
It only happens with AFWall+ and not DroidWall...

**Comment by ukanth** [comment]
Please send me logcat along with rules from firewall rules->export

**Comment by evilrobotted** [comment]
This issue is not happening any more since switching to StrongSwan instead of OpenVPN for Android. Obviously you are right that AFWall was not responsible.
