### ISSUE TITLE
Roaming not automatically detected

### ISSUE THREAD

**Issue by kverpoorten** [ukanth/afwall#697]
I live in Belgium and work in The Netherlands.

I use AFWall to avoid roaming for some apps in The Netherlands, while I still want to allow some other apps to roam.

When I cross the border and my phone starts roaming, AFWall does not seem to detect this. All apps still have access to the internet until I reapply the rules, after that, roaming rules are applied correct.

I have to repeat this process when coming back to Belgium after work.

**Comment by ukanth** [comment]
You need to enable "Active rules" to detect the Roaming changes and please follow the document on how to report these issues ( with rules and logs )

**Comment by kverpoorten** [comment]
I have active rules enabled.

I will check the documentation for the rules and logs and add them. From which moment do you want the logs? I'm driving when it changes from roaming to non-roaming, so pretty hard to get the logs then

**Comment by ukanth** [comment]
Send two error log(firewall rules->export log) before you reapply the rules and after applying the rules.
