### ISSUE TITLE
At boot: "Error applying firewall rules" and "Firewall enabled" Notification (5X MM 6.0.1)

### ISSUE THREAD

**Issue by Mesmurized** [ukanth/afwall#701]
For some time now (maybe since the prior stable release), I receive two Notif messages every boot: 
1) "Error applying firewall rules. Click to open settings." before the passcode screen; and 
2) "Firewall enabled" a min or so later
My tests show AFWall+ is not working. 

Once the phone is stable, I open AFWall+ and the GUI shows enabled. So I disable, then re-enable, but the "Working .. Applying iptables rules" window never goes away and must be closed. AFWall+ is still not working. 

A work-a-round ... disable firewall before rebooting and enable after. Works every time.

Note: I often forget to disable AFWall+ before rebooting ... and ~10% of the time it enables correctly.
Note2: Experimental feature start-up delay does not help

This may be related to issue #699 and #700 ... can't tell for sure

**Comment by ukanth** [comment]
Can you attach the rules from menu-show rules-export to SD or logcat.

**Comment by Mesmurized** [comment]
Sure. Rules & prefs attached

**Comment by ukanth** [comment]
@Mesmurized , Sorry , but I couldn't see the attachment

**Comment by Mesmurized** [comment]
I disabled security and exported again.

Just noticed. AFWall is NOT administrator. Might that have something to do
with my issue?

**Comment by Mesmurized** [comment]
Update: After waiting awhile, I decided to try again. This time I went
into Settings/Apps, cleared data/cache, then uninstalled.
Rebooted,reinstalled, reloaded rules .... and it appears to be working
fine at boot time. So as usual, it was a 'loose nut behind the wheel'.
:)

Take care. Will let you know if issue returns.

Charles Bazaar
