### ISSUE TITLE
Permanent notification - NOT AN  ISSUE

### ISSUE THREAD

**Issue by davidbravoclo** [ukanth/afwall#702]
AFWall+ (Donate)

Sorry because this is not an issue, but I don´t find other way to ask you about.

Actually I love this app and his functionality. I use it for controll mobile data and I have a question about the permanent notification

I turn the permanent notification option on

![1](https://cloud.githubusercontent.com/assets/28064662/25451736/c5566790-2a88-11e7-943c-a00b50a0452c.png)

![2](https://cloud.githubusercontent.com/assets/28064662/25451767/d8440f88-2a88-11e7-8429-034414055e9f.png)

And it works fine but I want to know if its posible to show it as the others "persistent notification" because I want to check if the service is running but not to see it on my notification bar every time.

I mean something like this...

![3](https://cloud.githubusercontent.com/assets/28064662/25451785/e6f4842c-2a88-11e7-93fc-0ab97ab59baa.png)

And hidden the icon

![4](https://cloud.githubusercontent.com/assets/28064662/25452369/113628ce-2a8b-11e7-95af-fac2f247dffc.png)

Thanks for your attention

**Comment by ukanth** [comment]
Currently it's not supported. I can add as an option.

**Comment by davidbravoclo** [comment]
OK I'll be waiting for. Thanks

**Comment by ildar** [comment]
Actually this is about lowering the notification priority, right? I want that too!

**Comment by ildar** [comment]
thanks a lot! works just as I wanted. I mean in BETA from F-Droid.
