### ISSUE TITLE
App force closes when trying to buy

### ISSUE THREAD

**Issue by Itsnothectic** [ukanth/afwall#703]
Im on LineageOS, AFWall is running as root through MagiskSU.
Every process is blocked from network activity except AFWall. AFWall is also a device admin.

I get the "AFWall has stopped" click to restart when clicking "Buy donate version or donate key".

V2.9.4 

Android 7.1.2 LineageOS without GApps or Play services.

SELinux is in Enforcing mode.

I would really like to see logs so is there in alternative method of payment while this gets fixed?

* AFWall+ Mode (whitelist [default enabled]/blacklist)
* [your text/file or link]
* Android ROM + exactly versions number
* [your text/file or link]
* What steps will reproduce the problem?
* [your text/file or link]
* Additional security software installed (like XPrivacy/Avast)? Is it really deactivated?!
* Magisk and Netguard, This problem happens even when offline.
* What is the expected output? What do you see instead?
* [your text/file or link]
* Attach your rules.log (IPv4 + IPv6)
* [your text/file or link]
* iptables -v -n -L
* [your text/file or link]
* ip rule list
* Not loaded
* ip route show table (number)
* [your text/file or link]
* iptables -L -t mangle (only on VPN)
* No VPN
* Type 'adb bugreport' via ADB (only necessary if there is a crash)
* Will get around to this by tomorrow.
* Please provide any additional information below (e.g. logcat).
* I dunno, I see "Adreno" a lot in logcat.
* Which binaries are used for BusyBox/IPTables?
* Auto IPTables and built in Busybox
* Which DNS-proxy option is in usage?
* This even happens in aeroplane mode
* Are the experimental options enabled/disabled?!
* No and there is no init.d support currently.

**Comment by ukanth** [comment]
You can donate and get unlocker using paypal/bitcoin
https://github.com/ukanth/afwall/wiki#making-donations

once donated, drop me an email. I will send you the unlocker APK, which works without gapps on multiple devices.

I will look into the crash.

**Comment by Itsnothectic** [comment]
Thanks, I juat sent a donation with reply email included.

**Comment by ukanth** [comment]
Thanks for your support.  I sent the unlocker apk to the email you mentioned.
