### ISSUE TITLE
Manifest prevents "adb backup" from backing up AFWall data

### ISSUE THREAD

**Issue by Vayu** [ukanth/afwall#706]
Is there any reason why AFWall is excluded from "adb backup"? It i disabled in manifest It specifies `android:allowBackup="false"`, but I don't really see good reason to exclude it. Can we enable back? I could make a PR, but it is literally one line change.

Relevant part of the Manifest
https://github.com/ukanth/afwall/blob/109a9f1b8846f78d04e9be67132af819a930bf40/aFWall/src/main/AndroidManifest.xml#L81

**Comment by ukanth** [comment]
It was disabled with reason. AFWall+ stores UID of apps instead of packages and UID changes every time when installing. So it doesn't make sense to use android backup.

**Comment by Vayu** [comment]
There is a bunch of other settings which could be backed-up. Would it break AFWall+ is one did a restore with wrong uids? (though it sounds like it may block something which doesn't need blocking and vice versa).

**Comment by avently** [comment]
I make backup with Titanium. But when i restore it only few apps get right settings. Thats because you store app's UID. Why don't you want to store app's package name? It will be really useful

**Comment by walrus543** [comment]
AFAIK it's already planned.
I stopped restoring AFWall+'s data through TiBu since logs didn't work anymore. The json file is working pretty well until package names are implemented.
