### ISSUE TITLE
Wrong traffic details

### ISSUE THREAD

**Issue by walrus543** [ukanth/afwall#711]
Hi,
It seems traffic details are not accurate. Here are the steps to reproduce the issue.  
The screenshots are related to the system component UID 1000. AFWall+'s app data have been cleared from the App info screen before these tests.

1. [First screenshot, taken at 08:52 am](https://forum.xda-developers.com/attachment.php?attachmentid=4153480&d=1495092120) // **no downloaded/uploaded data**  
2. [2nd screenshot after a reboot, taken at 08:54 am](https://forum.xda-developers.com/attachment.php?attachmentid=4153481&d=1495092120) // **=> no downloaded/uploaded data**  
3. [New reboot, new screenshot taken at 09:02 am](https://forum.xda-developers.com/attachment.php?attachmentid=4153475&d=1495091780) // **=> here we have downloaded/uploaded data**
4. [New reboot, new screenshot taken at 09:05 am](https://forum.xda-developers.com/attachment.php?attachmentid=4153476&d=1495091780) // **=> no downloaded/uploaded data**

Such an UID includes several packages (OnePlusPocketMode, System Settings, ANT HAL Service, Fused Location, Dev Tools...) but I guess the uploaded/downloaded data should always be the same.
**How could I have downloaded/uploaded data on the 3rd screenshot and nothing a few minutes later?** 

Thanks.
AFWall+ 2.9.4 - Android 7.1.2 - MagiskSU v12.

**Comment by kekukui** [comment]
For reference, this is related to bug #835
