### ISSUE TITLE
ClockSync app issues

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#712]
Hello all,

I'd like to use this http://amip.tools-for.net/wiki/android/clocksync  to sync with an NTP server I specify from within the app.

I'm currently using server ntp.derekgordon.com. There are several addresses mapped to it so I want to know if its possible to use an iptables rule to allow all of them incoming and outgoing (this is standard NTP protocol correct?), as it seems the NTP server queried interchanges with every new sync attempt, or is this an overkill method? Should i just narrow it down to a single IP address outgoing and incoming? But what about if that server is temporaily down during the query? So allow all of them, correct?

using nslookup for the derekgordon address shows 10 mapped ip's, so I'm thinking a custom script iptables -t-nat -A OUTPUT -p udp/tcp --dport 123 --to-destination IP address:123 for all 10 should do the trick.

here's a log, afwall denied an address mapped to one of the ntp.derekgordon.com addresses.
[iptables.txt](https://github.com/ukanth/afwall/files/1057814/iptables.txt)

**Comment by ghost** [comment]
hi all,

any answers for this "issue"? Maybe I don't know what I'm doing to allow the traffic for this app.

I've created a custom script as follows: iptables -A OUTPUT -m owner --uid-owner $APPLICATION-UID -p udp --dport 123 -j ACCEPT but when I check it in iptables -vL no traffic is passed over to it.

I guess my question is can afwall work with external NTP clients or no? What's strange is this is a root app and I've allowed apps running as root in afwall, yet it still does not communicate with the derekgordon.com server. Theres obviously some iptables rules or something else (I can't figure out what exactly) missing in afwall that I need to plug in to get this working.

Any suggestions?

**Comment by ghost** [comment]
Solved!

So I don't know if this is a bug of afwall, some misunderstanding of how iptables works on my end, or a clocksync bug, but I managed to get it working using the following details.

I enable wifi for ClockSync in afwall rules, dont know if it works for mobile but it seems as if afwall doesn't recognize it as a root app, no traffic is passed through it when I don't enable wifi for it even after having established these custom rules:

iptables -t nat -A OUTPUT -m owner --uid-owner $APPLICATION-UID -p udp --sport 123 -j ACCEPT
iptables -t nat -A INPUT -m owner --uid-owner $APPLICATION-UID -p udp --dport 123 -j ACCEPT

Maybe this helps someone else.

**Comment by peturbg** [comment]
thanks that you solved ans thanka you explain how you solve it. but why you need program to syncronize your watch when you have watch and you can open internet and aak what time is it, inude android clock programs you dont know what they have and they can spy on you, it is not conspiracy. everybody have the rights of privacy.
