### ISSUE TITLE
Tasker plugin does not work

### ISSUE THREAD

**Issue by usver1** [ukanth/afwall#717]
After updating to v 2.9.5 and migrating profiles Tasker plugin does not work correctly.
When I run a task in Tasker, AFWall+ randomly switches profiles or enables/disables firewall with complete disregard to configuration selected in Tasker plugin.
My setup is: CM13 with Magisk root v13, AFWall+ Donate v2.9.5, Tasker v4.9u4.

**Comment by ukanth** [comment]
I need more details. How many profiles you had previously. Please attach the following details

- logcat when profile switch happen
- Firewall rules - send error message - > Preferences section with logcat
- ls -l /data/data/dev.ukanth.ufirewall/shared_prefs

**Comment by usver1** [comment]
There are 4 profiles.
I have uninstalled AFWall+ and installed in again. Random profile switch stops. Now AFWall+ just crashes when I'm trying to disable it using Tasker plugin.

Logs:
[2017-06-22_093120_logcat.txt](https://github.com/ukanth/afwall/files/1093818/2017-06-22_093120_logcat.txt)
[error_message.txt](https://github.com/ukanth/afwall/files/1093819/error_message.txt)
[shared_prefs-ls.txt](https://github.com/ukanth/afwall/files/1093817/shared_prefs-ls.txt)

**Comment by usver1** [comment]
More logs. Task in Tasker:
	A1: AFWall+ Tasker plugin [ Configuration:Enable AFWall+ Timeout (Seconds):0 ] If [ %state Set ]
	A2: AFWall+ Tasker plugin [ Configuration:Disable AFWall+ Timeout (Seconds):0 ] If [ %state !Set ]
	A3: Modify PowerToggle state [ Configuration:Set current toggle to new state Timeout (Seconds):0 ] 

Instead of disabling/enabling firewall AFWall displays messages "Tasker: Applying firewall rules" and "Tasker: AFWall+ profile applied with success". Active profile is "Default" and AFWall does not switch it to another profile.

[2017-06-24_101656_logcat.txt](https://github.com/ukanth/afwall/files/1099488/2017-06-24_101656_logcat.txt)
[error_message.txt](https://github.com/ukanth/afwall/files/1099489/error_message.txt)
[shared_prefs-ls.txt](https://github.com/ukanth/afwall/files/1099490/shared_prefs-ls.txt)
