### ISSUE TITLE
Must allow root apps access on android 6?

### ISSUE THREAD

**Issue by forkoz** [ukanth/afwall#719]
Steps to reproduce:

1. Install Afwall, allow nothing.
2. Give individual app internet access
3. Can't connect

I really don't wish to give all root apps access, is this a bug?

**Comment by ukanth** [comment]
Please attach send error log from firewall rules.

**Comment by forkoz** [comment]
This is the log:

> AppID :	0
> App Name:	(root) - Apps running as root
> Total Packets Blocked:	20
> [2]224.0.0.22:0(5)
> [UDP]208.67.222.222:443(6)
> [UDP]208.67.220.220:443(9)
> 
> 	---------
> AppID :	10067
> App Name:	Firefox
> Total Packets Blocked:	7
> [UDP]192.168.1.1:4886(7)
> 
> 	---------
>

**Comment by ukanth** [comment]
I need iptables rules. Menu->Show Rules-> export to storage (or send error report)

**Comment by forkoz** [comment]
here they go: https://pastebin.com/3DxQVFRG

**Comment by ukanth** [comment]
Can you disable LAN option from preference->rules/connectivity and reapply the rules

**Comment by forkoz** [comment]
I disabled lan and re-applied. Issue remains.

**Comment by ghost** [comment]
i too, am reporting this issue, it seems that somehow blocking every with root from using internet causes the problem, which results in other apps not being able to connect

**Comment by nutpantz** [comment]
Im having the same issue on my note 4
Log
AppID :	0
App Name:	(root) - Apps running as root
Total Packets Blocked:	94
[TCP]2607:f8b0:400a:0807:0000:0000:0000:2003:443(7)
[TCP]2604:5580:0021:0000:0000:0000:9765:3485:443(57)
[TCP]2607:f8b0:400a:0800:0000:0000:0000:200a:443(3)
[TCP]2604:5580:0021:0000:0000:0000:4815:5b1d:80(4)
[TCP]2607:f8b0:400e:0c00:0000:0000:0000:0068:443(3)
[TCP]2607:f8b0:400e:0c00:0000:0000:0000:005e:443(12)
[TCP]2604:5580:0021:0000:0000:0000:9765:358c:443(8)

	---------
AppID :	1000
App Name:	Factory Mode
Total Packets Blocked:	6
[UDP]2607:5300:0203:0bdd:0000:0000:0000:0000:123(3)
[UDP]2604:5580:0021:0000:0000:0000:45a4:caca:123(3)

	---------

**Comment by nutpantz** [comment]
Is there any way to find out which app running as root needs network access?

**Comment by harbing3r1** [comment]
Can confirm the issue. Having to allow access to "[0] (root) - Apps running as root". Otherwise wifi connects and disconnects continuously.
Using latest 3.2.0 Beta, Android Pie, Magisk

**Comment by ghost** [comment]
i seem to be having the same issue
the thing is i'm using LineageOS on a Pocophone and with the last update (12-fev from 6-fev) i now can only connect to the internet with any app with the "(root) - Apps running as root" allowed. Before this i had it always blocked

maybe in this case it is due to some change in the OS during the update?

running v3.3.1 from F-Droid on LOS16
