### ISSUE TITLE
Setup rules for installed app via notification

### ISSUE THREAD

**Issue by avently** [ukanth/afwall#720]
AFWall has an option to show notification after new app installation. Its good and can be even better. What if you will add buttons to that notification like:
√ Wifi √ Mobile √ VPN   APPLY
If user will press on the button AFWall will remember the choice and will apply new settings (after Apply button will be pressed, of course). 

If you don't like buttons it can be checkboxes:)
What do you think?

**Comment by ukanth** [comment]
Default action has been added in 3.5.0. Thanks
