### ISSUE TITLE
Generation of iptables is too slow

### ISSUE THREAD

**Issue by avently** [ukanth/afwall#721]
After i apply rules takes ~30 seconds to finish the operation. 
I don't know why it is happening. I have 120 apps. 
If you need logs or something just ask. 

LOS 14.1, MagiskSU and SuperSU (i tried both).

**Comment by ukanth** [comment]
It's not the generation of the iptables rules, rather when executing those rules.
The reason it's slow because we execute the command one by one (by design). If a command fail to execute, we try again (upto 10 times - because various other factors involves )

I've been thinking of different ways to improve this without compromising the consistency of the rules. I'll update here if anything done on that front.

Thanks,

**Comment by avently** [comment]
@ukanth would be a good idea to check for difference between new rules and old rules before applying all rules. And you can apply only one rule vs all rules after app install. 
For example, AFWall is working. I installed an app. AFWall is showing a notification. I'm choosing to allow connection. AFWall is executing only one or two commands (for wifi, data, etc).

**Comment by chrcoluk** [comment]
yeah I think you need to speed it up, its very slow to apply, and may also be to blame why I have to manually apply after phone reboot as auto apply I think fails for this reason.

**Comment by ukanth** [comment]
@chrcoluk , @avently 

Can you guys test this version and let me know ?
https://www.dropbox.com/s/w90n1jprelh91z2/AFWall%2B%20Experimental.apk?dl=0

It's test version, you may want to take backup before trying this. I tested it on my main device and it applies rules much faster now.

**Comment by avently** [comment]
@ukanth takes 23 seconds to generate rules with new version  and 32 seconds on an old version. So yes, it's faster than before. 
Why don't you want to generate only difference and not the whole list of new rules everytime on app added/removed to/from AFWall block list? Is it hard to track? 

Update: checked multiple times. Sometimes it takes ~1 min to generate new rules. It's hard to check the right time because you removed loading indication.

**Comment by ukanth** [comment]
@avently , How are you calculating the seconds ? because on my device with LOS 13 & MagiskSU with around 130 apps, it takes a second to apply rules.

**Comment by avently** [comment]
@ukanth it shows "Applied" immediately. But apps can't connect to internet with "Connection refused". So I disabled access to Internet for browser and then enabled again. Then I started counting while internet will be available
