### ISSUE TITLE
DownloadManager Leak Fix (Xposed) doesn't work

### ISSUE THREAD

**Issue by Sirove** [ukanth/afwall#723]
I'm using AFWall 2.9.5 on CM13 (Xposed v87, AFWall ticked) with OpenVPN.

Tested it with QuickDic. It uses the integrated download manager to download dictionaries. It works even though it doesn't have internet access. Absolutely no check mark is set. I did a reboot to verify, still the same.

**Comment by peturbg** [comment]
remove afwall+2.9.5 it has data leaks and return to version 2.9.1 after version 2.9.1 even if afwall+ is blocking a program it connect, for exemple if version after 2.9.1 bloxk firefox, and save afwall+ whe  you open firefox you has internet but how when afwall+ has blocked firefox. include log om 2.9.4 and maybe on 2.9.5 dont work when log is enabled in 2.9.4 2.9.5 log is empty and how say log us turn on. when you retuen in version 2.9.1 it will work. and how is xpossed work on nougat i read that now can run.

**Comment by ukanth** [comment]
Xposed support might be dropped.
