### ISSUE TITLE
Automatically block Internet access of newly-installed apps.

### ISSUE THREAD

**Issue by ashesall** [ukanth/afwall#729]
I hope it's possible to automatically block apps when they are installed because most of the time, I open afwall after installing an app to block its Internet access.
I see two possible ways this can be implemented:
1. Prompt
afwall will prompt the user to block a newly-installed app much like Xprivacy and SuperSU. If the user configured a password, they will be prompted to enter it. Wrong password = automatically blocked Internet access.
2. Auto-block
afwall will automatically block Internet access to newly-installed apps without giving prompts or popups. This is faster. A toast notification, however, will be shown to inform which app was blocked.

Another minor request:
Please update the icons for LAN, switch and clear. Minor and purely aesthetic, however, will be greatly appreciated if implemented.

Thank you for your great work!

**Comment by walrus543** [comment]
Newly installed apps are automatically blocked if you use the Whitelist mode.

**Comment by ashesall** [comment]
@Primokorn 
Oh! I've been using the "Block Selected" mode since forever! Thanks for sharing, I never thought of trying the "Allow Selected" mode lol. 

However, what if I wanted to allow Internet access to the newly-installed app? I'd have to open afwall, check to allow, then apply new rules. I know I'm lazy ;) What if, there's a "Prompt" mode? That would be, I guess, awesome.

Thanks again, @Primokorn! I'll be saving more time now :)

**Comment by walrus543** [comment]
You're welcome ;-)
Duplicate: https://github.com/ukanth/afwall/issues/720
I think you can close this one.

**Comment by ashesall** [comment]
Right, thanks!
