### ISSUE TITLE
[Feature Request] AFwall Quick Tile

### ISSUE THREAD

**Issue by droidberg** [ukanth/afwall#732]
any chance you could add a afwall enable/disable quick tile?? thanks.

**Comment by walrus543** [comment]
FYI you can do it with Macrodroid and AFWall's plugin.

**Comment by hughwilliams94** [comment]
Just a quick query, as many users presumably use AFwall because it's open source. Are there any methods to do this which don't involve using MacroDroid (which from what I can tell is not open source).

**Comment by ukanth** [comment]
Added in 3.0.0
