### ISSUE TITLE
Version 2.9.6 not available via F-Droid

### ISSUE THREAD

**Issue by CryptGoat** [ukanth/afwall#734]
The current version (2.9.6) of AFWall+ is not available on F-Droid. Instead there's just version 2.9.5-BETA (15950): https://f-droid.org/packages/dev.ukanth.ufirewall/

It doesn't look like there have been any recent build attempts for the current version on the F-Droid server: https://f-droid.org/wiki/page/dev.ukanth.ufirewall

**Comment by ukanth** [comment]
Kindly raise the issue with F-droid, I have no control over their process.
