### ISSUE TITLE
F-Droid suddenly started offering me to upgrade to beta versions?

### ISSUE THREAD

**Issue by T-vK** [ukanth/afwall#736]
I'm still running 2.9.4. But a while ago an update appeared called 2.9.5-Beta and now 2.9.6-Beta. I feel very uncomfortable "upgrading" AFWall to a beta version, as even the 2.9.4 version is crashing from time to time. 

Could anyone enlighten me why we're suddenly seeing beta versions in F-Droid? Wouldn't it make much more sense to have the Beta as a separate app in F-Droid?

**Comment by ukanth** [comment]
You can blame me for that. It's a mistake I did. F-Droid builds are equal as Playstore builds. It's just the label I forgot to remove before tagging the build in Github. 

You can safely update to those builds. I'll make sure next versions are tagged properly.

**Comment by T-vK** [comment]
All right, thanks for the quick response.
