### ISSUE TITLE
Default to disabling all traffic

### ISSUE THREAD

**Issue by madduck** [ukanth/afwall#740]
Every now and then due to a variety of reasons, AFWall+ fails to apply the ruleset. Using `iptables-save`, I then either find a completely unprotected phone, or one with the ruleset partially applied.

IMHO, in case there's an error, AFWall+ should revert to a secure mode, e.g. using `DROP` as the `OUTPUT` chain policy. In fact, that should be the default anyway, for all chains.

In order to ensure that the ruleset gets fully applied in a transactional way, wouldn't it be better to compile the ruleset to a file to feed to `iptables-restore` anyway?

Thanks for your consideration,
-m

**Comment by madduck** [comment]
Any thoughts on this?

**Comment by ukanth** [comment]
iptables-save and restore doesn't work as expected on multiple devices. Also it intercepts other chains  as well which might cause issues with other OS functionalities.

**Comment by madduck** [comment]
Thank you @ukanth, that makes sense, but it's not actually the core of the issue. What do you think about improving the error handling such that an error applying the ruleset results in a protective firewall, rather than one that leaves the device open?

**Comment by ukanth** [comment]
I agree. There are some room to improve the error handing. In most scenario's it should handle. Do you have any particular usecase it's failing often ?

**Comment by madduck** [comment]
No, unfortunately not. I switch networks quite a bit, and every now and then (usually once every two days), I see the error when I next use my phone.

**Comment by ukanth** [comment]
Yes. Those are the most common one's which always fails.  I'm thinking of delaying the rules if it's already in progress. Lets see.

**Comment by madduck** [comment]
What is the resolution, @ukanth?
