### ISSUE TITLE
Possible conflation of packet reject logging?

### ISSUE THREAD

**Issue by madduck** [ukanth/afwall#741]
I recently experienced a weird issue wherein the open-source app Kore was reported by AFWall+ to be sending pings to sites like walmart.com, among others: https://github.com/xbmc/Kore/issues/434

Here's a screenshot showing the toast:
![screenshot_20170822-145412](https://user-images.githubusercontent.com/195073/29566426-292b5ac8-874a-11e7-857e-07db3902edfb.png)

The log has this instead:

    [ICMP]185.228.81.107:0(4726)

And this had me really stoked, especially since the target IP address would vary daily: from AT&T to walmart.com to the one above that's unassigned according to RIPE. Very strange.

Digging deeper, however, I found that `iptables -m owner --uid-owner 10188` at the top of the `afwall` chain actually doesn't see any such packet. Furthermore, I then tried the following rule at the top of the `afwall` chain:

    -d 185.228.81.107/32 -j LOG --log-prefix "[Kore unassigned] " --log-tcp-options --log-ip-options --log-uid

but this matches no packets, `dmesg` has nothing on this, while AFWall+ happily logs traffic _to this IP_ it apparently rejects.

So now I am obviously wondering why AFWall+ thinks it needs to log nonexistent ICMP packets to random IP addresses under the UID Kore runs as.

Could it be that AFWall+ reads too much off the `netlink` socket receiving the `NFLOG` output? Or somehow other gets confused presenting the data it does get?

Because it seems that the toasts only show up along with others about legitimately rejected packets from the same app/UID.

Or do you have any other ideas how I could track this down?

Thanks,
-m

**Comment by madduck** [comment]
Sorry, forgot to mention that I am using AFWall+ 2.9.6-BETA from F-Droid on a SuperMan-Rom (Samsung Galaxy S7 edge, hero2lte) 2.6.0, which is based on Android 7.0, and runs the "SuperStock" kernel 3.18.61. `iptables` is v1.4.20 if that matters. The v4 ruleset is available from http://scratch.madduck.net/2017-08-22-151108-vit-tJjUPx.txt

**Comment by t-m-w** [comment]
Having the exact same issue on Android 8.1, Lineage OS 15.1 (an unofficial build) on OnePlus 5, and ended up going through the same steps as you. It was telling me Linux Kernel was trying to access various random IP addresses, usually residential.

None of this was detected by my own iptables LOG entries, or a packet capture on my router (with AFWall+ disabled), and none of the iptables log rules on the phone had increased counts as a result of AFWall+'s reporting — not even AFWall+'s own nflog rules.

This is either an AFWall+ bug or an issue with nflog communication or the nflog binary it ships with.

Considering you have to pay for the Pro version to drill down on log entries, and the logging is bugged and showing false entries, it would be nice for this to get a response...

**Comment by ukanth** [comment]
It's a bug. will fix it.

**Comment by ukanth** [comment]
Duplicate/Related to #1002
