### ISSUE TITLE
Latest version not available as APK/F-Droid?

### ISSUE THREAD

**Issue by CryptGoat** [ukanth/afwall#744]
[Version 2.9.6.1](https://f-droid.org/packages/dev.ukanth.ufirewall/) is not available as APK via GitHub and not via F-Droid unlike previous releases, making the Play Store the only option to get the latest version.

Any info on why this is the case? Will ask about the F-Droid issue in their forum but it is currently offline:
https://forum.f-droid.org/

Will update once it is back online.

**Comment by walrus543** [comment]
We have no control over F-Droid builds so posting here is useless. AFAIK F-Droid team has to manually build this app so they will do it as soon as they read your thread.
I guess @ukanth forgot to upload the apk file on Github though.

**Comment by ukanth** [comment]
Thanks @Primokorn , I did upload the apk, for some reason it was not unsuccessful. I've updated the release with APK

https://github.com/ukanth/afwall/releases/tag/v2.9.6.1

@CryptOwl , you need to followup with F-Droid team.

**Comment by ukanth** [comment]
@CryptOwl , it's up now. Kindly close this issue
