### ISSUE TITLE
Conflicting documentation for changing DNS

### ISSUE THREAD

**Issue by Metaception** [ukanth/afwall#745]
I noticed a conflict in the documentation when attempting to change the default DNS.

The [DNS](https://github.com/ukanth/afwall/wiki/DNS#changing-default-dns) section says:
```
$IPTABLES -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 208.67.222.222:53 || true
$IPTABLES -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 208.67.222.222:53 || true
```

While the [Custom Scripts](https://github.com/ukanth/afwall/wiki/CustomScripts) section says:
```
# First two lines delete current DNS settings
$IPTABLES -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 208.67.222.222:53 || true
$IPTABLES -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 208.67.222.222:53 || true

# This two new lines set our new DNS to OpenDNS
$IPTABLES -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 208.67.222.222:53
$IPTABLES -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 208.67.222.222:53
```
The main difference seems to be the **A**, **I**, **D** options. A quick read of the man pages says **A** is addition while **I** is insertion, through I am not sure what the difference is. The **D** is, of course, deletion.

A DNS change guide on [XDA](https://forum.xda-developers.com/general/xda-university/guide-how-to-change-dns-android-device-t3273769) suggests you do all three:
```
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 8.8.8.8:53
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53
iptables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 8.8.8.8:53 || true
iptables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53 || true
iptables -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 8.8.8.8:53
iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53
```

Additionally, I was wondering if it was possible to set multiple DNS providers using this method?
All the examples so far have been for a single provider.

Anyways, great program! Slick interface and very stable!

**Comment by h1z1** [comment]
Don't see a conflict.  The custom script version is a bit safer by opting to remove any existing rules first then insert, which positions them above any others.  It's not strictly required but not invalid.  It would be more of an issue on append.

The rules from XDA however make no sense, they likely meant to do the same - delete first and append / insert.

```
iptables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 8.8.8.8:53 || true
iptables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53 || true
iptables -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 8.8.8.8:53
iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53
```

You can set multiple providers yes.  Two rules would be required for each.

```
iptables -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 8.8.8.8:53
iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53
iptables -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 8.8.4.4:53
iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 8.8.4.4:53
```

Worth noting some portals will not work as they intercept DNS when you first connect.  Chrome and Firefox have "portal detection" which is why it appears to work in a browser but in reality they are making life worse for everyone else.
