### ISSUE TITLE
Skype for Business does not sign in

### ISSUE THREAD

**Issue by mark-orion** [ukanth/afwall#747]
Skype for Business (formerly known as "Lync") is unable to sign in and receive calls with afwall+ enabled. I allowed incoming connections and enabled Skype for Business and "Exchange Services" in the afwall settings, but still cannot sign in with the firewall enabled.

**Comment by ukanth** [comment]
Enable Log and see if any other service getting blocked.

**Comment by mark-orion** [comment]
Thanks for the help. I did that and I had to enable "Linux Kernel" in order for Skype for Business to work.
