### ISSUE TITLE
/system/etc/init.d/afwallstart script double issue

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#748]
Hi and sorry for bad english.

First problem is in this line
`export PATH=/system/bin`

My android has ho "head" and "cut" binaries (or toolbox applets) in /system/bin directory, so I got `not found` for both.

Simple solution is change "export PATH" like this
`export PATH=/sbin:/system/sbin:/system/bin:/system/xbin`

Second problem is endless cycle when rinning from init.d (I add -x key to see everything, no more changes)
```
+ export 'PATH=/system/bin'
+ head -n 1 /proc/uptime
./afwallstart[5]: head: not found
+ cut -d . -f 1
./afwallstart[5]: cut: not found
+ startDt= 
+ :
+ '[' -d /data/data/com.android.providers.downloads ']'
+ sleep 1
+ :
+ '[' -d /data/data/com.android.providers.downloads ']'
+ sleep 1
+ :
+ '[' -d /data/data/com.android.providers.downloads ']'
+ sleep 1
+ :
+ '[' -d /data/data/com.android.providers.downloads ']'
+ sleep 1
+ :
+ '[' -d /data/data/com.android.providers.downloads ']'
+ sleep 1
+ :
+ '[' -d /data/data/com.android.providers.downloads ']'
+ sleep 1
+ :

and so on
```

Thanks

**Comment by krayon** [comment]
The second issue is as per #662
