### ISSUE TITLE
[suggestion] storing iptables rules

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#749]
Hi and sorry for ban english

Is it possible to export iptables rules in some file, and then import this rules by `/system/etc/init.d/afwallstart` script instead of using this ?
```
iptables -w -P INPUT DROP
iptables -w -P OUTPUT DROP
iptables -w -P FORWARD
```

Thanks

**Comment by BlueMax** [comment]
You could use iptables-save and iptables-restore for that. But i guess you would need to build these binaries yourself first though.

**Comment by ukanth** [comment]
I do not intent to build iptables-save or restore. Please reopen if it's still relevant.

**Comment by Fry-kun** [comment]
What was the reason for not building those?
Doesn't look like they would take up a lot of space (in fact, on my laptop they're ultimately symlinked to the same binary as `iptables`).
Using `iptables-restore` should make the rules apply much faster than running `iptables ...` for every entry sequentially, and would probably avoid bugs like #1206
