### ISSUE TITLE
Question: may the WhatsApp Wiki page be outdated?

### ISSUE THREAD

**Issue by brugnara** [ukanth/afwall#753]
Hi.

First of all, thank you for providing us a HowTo block WhatsApp, but I think it is now outdated.

I'm talking about [this page](https://github.com/ukanth/afwall/wiki/HOWTO-blocking-WhatsApp)

Here I've found a list that seems to be valid for me: https://myip.ms/view/ip_owners/90500/Whatsapp_Inc.html

Best regards.

EDIT: I blocked all the 20 CIDR listed but I'm still able to use WhatsApp so I finally solved blocking the domain `whatsapp.com` on the meraki console. 🙆‍♂️

**Comment by ukanth** [comment]
I don't manage that page. Please reopen if it's still relevant.
