### ISSUE TITLE
Some services starting significantly earlier than AFWall+. (Tasker for example)

### ISSUE THREAD

**Issue by T-vK** [ukanth/afwall#754]
After a reboot, I just noticed that the Tasker service started almost 10 seconds before the AFWall+ service. And this happens even though I'm using the startup leak fix and the xposed module. 

10 seconds is more than enough to leak significant amounts of data.

**Comment by ukanth** [comment]
if you have a startup leak, it blocks outgoing connection by setting OUTPUT chain to DROP during startup. So even when other services starts, it can't communicate to internet until AFWall+ services starts and apply proper rules.

**Comment by T-vK** [comment]
Okay, that's good to know. Is there a simple way to figure out if the startup leak fix is working properly?

**Comment by ukanth** [comment]
There are ways to do it. but I'm not sure whether those are simple in your terms.
