### ISSUE TITLE
Unable to check 'Fix startup data leak'

### ISSUE THREAD

**Issue by Glamhoth** [ukanth/afwall#758]
When trying to check that box it just automatically uncheck itself. I'm running LineageOS with BusyBox installed and init.d supported.

**Comment by poutrosgit** [comment]
Sometimes you have to close the app and then you can check the checkbox.

**Comment by ukanth** [comment]
This is fixed in BETA

**Comment by Glamhoth** [comment]
Fixed in 2.9.7.
