### ISSUE TITLE
[Request] Automatically switch profile if wifi/rmnet changes

### ISSUE THREAD

**Issue by ghtux** [ukanth/afwall#766]
Hi!

While it's not possible to set different dns servers without apps on Android, it would be nice to solve this by afwall itself. 

For wlan I force DNS server over ipfire but the custom afwall script which sets DNS server leads to no connection. Well it's meant to get blocked by the router. So an option to automatically change the profile would be great. So we could use different scripts with different DNS server rules.

I know tasker but I refuse to install apps outside F-Droid that aren't open

**Comment by devmarxx** [comment]
I would like to support this request. It would be great to have the opportunity to execute a custom script on network change.

At the moment it seems that with active script activated only firewall rules are reloaded on network change. Custom scripts are not reloaded. 

I use a custom script to disable IPv6, but on network change IPv6 somehow gets activated by the system again, so I need to reapply my IPv6 disabling script by hand. It would be great to get this done automatically by AFwall+.

My suggestion is to have an option under the custom rules settings to point to a custom script that is executed on network change. This would solve my IPv6 problem and would also provide a solution for mglinux's DNS question.

Thanx

marxx

**Comment by ghtux** [comment]
# Set a specific dns server for all networks except home WiFi (192.168.150.0/24) 
# Delete dns 
$IPTABLES -t nat -D OUTPUT ! -s 192.168.150.0/24 -p tcp --dport 53 -j DNAT --to-destination 85.214.20.141:53 || true $IPTABLES -t nat -D OUTPUT ! -s 192.168.150.0/24 -p udp --dport 53 -j DNAT --to-destination 85.214.20.141:53 || true
# Set dns 
$IPTABLES -t nat -I OUTPUT ! -s 192.168.150.0/24 -p tcp --dport 53 -j DNAT --to-destination 85.214.20.141:53
$IPTABLES -t nat -I OUTPUT ! -s 192.168.150.0/24 -p udp --dport 53 -j DNAT --to-destination 85.214.20.141:53


See: https://www.kuketz-blog.de/android-dns-server-fuer-mobiles-netz-einstellen/
