### ISSUE TITLE
[Request] Quick rules

### ISSUE THREAD

**Issue by Sharvyn** [ukanth/afwall#769]
I have some suggestions concerning the app.

1. New app installed. Display pop-up. Contains a drop-down menu. Select profile, current profile selected by default. Two or three buttons depending on connections "allow/deny". Button changes color "red/green" on click. Bottom of pop-up menu "Ok/later" buttons.

2. Allow macrodroid and tasker to allow/deny app rules. When application installed, action prompted. User is presented with features mentioned above.

3. Quick apply options made available from notification (when application installed). *might be difficult when many profiles present. 

4. When click on notification, filter list and jump right to new app.

**Comment by ukanth** [comment]
Added default behaviour in 3.5.0
