### ISSUE TITLE
Accessing only a single IP 

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#774]
Hi

I am trying to make an app to access a single ip and block its access to everything else.

The app does not have permissions in the ui of Afwall.

This is what I have i my custom script

iptables -A OUTPUT -m owner --uid-owner 10762 -s $IP -p tcp  -j ACCEPT
iptables -A INPUT -m owner --uid-owner 10762 -s $IP -p tcp  -j ACCEPT

**Comment by ildar** [comment]
Mm, you intended a `-d` instead of one `-s`?

**Comment by gerroon** [comment]
@ildar, still it does not work

**Comment by ildar** [comment]
Menu, Show rules, analyze!
If failed, save somewhere and give the link. Mangle if required.

**Comment by gerroon** [comment]
@ildar 

Please try this
https://paste.debian.net/hidden/b19c7f27/

Thanks for your help.

**Comment by ildar** [comment]
@gerroon ,
1. As your IP is "THIS_IP_SHOULD_BE_ACCESSED_NO_MATTER" then you probably
want it "-I 1" rather then "-A"
2. Use ACCEPT, not RETURN
3. Contact me privately if still fail.

**Comment by gerroon** [comment]
I think it works now, Thanks for your help. I will try to contact you if I have issues with it.
