### ISSUE TITLE
[Playstore] Confusion about different versions

### ISSUE THREAD

**Issue by d0k3** [ukanth/afwall#778]
There are currently three versions of AFWall in Google Play: Free, Paid, Donate. As a lot of users, I'd actually like to support development, but I also like the additional features (quick apply). With two paid options available, I got none so far.

Any chance you could remove one of the paid options from the store so we know exactly which one to get? Maybe even better to make the donation an IAP, cause that way we wouldn't have to export / import our ruleset when switching / upgrading.

Also... could you maybe provide a way of testing the quick apply feature before the purchase / donation?

**Comment by walrus543** [comment]
AFWall+ is also available on F-Droid for years which means that it's a FLOSS app.
In other words, IAP can't be added into the main app.

**Comment by d0k3** [comment]
Alright, that I understand.

**Comment by Fry-kun** [comment]
So what's the difference between (Free + Unlock) and (Donate)?
FAQ#55 doesn't do a good job explaining it. Are they effectively the same feature-wise but one requires 2 apps to be installed?

**Comment by ukanth** [comment]
These are features available only in donate version( or when using unlocker with free version).

1. Enhanced log 
2. Use device password to protect AFWall+
3. Quick apply

you can use donate version as a single app to use the above features.

or you can install free version from playstore/f-droid without the above features ( technically those are present in free version but locked ) . Some people after trying free version wants to use the above features. They can buy the unlocker and unlock these features without installing donate version.

Hope this is clear. If not let me know

**Comment by Fry-kun** [comment]
The very last part, (Free + Unlocker) == (Donate) is very clear, thanks!

**Comment by d0k3** [comment]
Okay, I think that can be closed now, thanks @ukanth !
