### ISSUE TITLE
Translations not appearing

### ISSUE THREAD

**Issue by FTno** [ukanth/afwall#780]
As I understand it norwegian (nb) was added to AFWall+ in v2.9.7, but the translated strings don't appear in the app. But there are strangely? an exception with the filters in the main view. All, Core, System, User with the radio buttons in front are in the translated form (not absolutely sure about 'System' because that's the same word in both english and norwegian). Else I cannot see any translated strings.

In the preferences where you can change language, norwegian is not on the list of languages!

**Comment by FTno** [comment]
Noticed that the arrays.xml file in the values folder (https://github.com/ukanth/afwall/blob/beta/aFWall/src/main/res/values/arrays.xml) is missing norwegian (nb). Is that the reason why translations do not appear (as described above and that also applies to v2.9.8), despite being part of the app code?

**Comment by FTno** [comment]
In the new 2.9.9 version a System language option is added in the preferences, and by selecting that option the app will be in norwegian.
But norwegian is still not represented on the list of languages in the preferences!

**Comment by ukanth** [comment]
Probably missed to add it to list. I will look into it.
