### ISSUE TITLE
Apps goes through AFWall+

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#783]
How i can fix that . I have block them through afwall but they still keep using the internet pinging adresses . Any idea what i can do? Im looking for a good uninstaller/freezer too .
4 adresses . (SSL Server Rating PENDING) com.xiaomi.discover runs  ... (7 unecrypted connections http/tcp6) and 2 UIDs (10012 + 1000 ) app.anroid.unkown a lot pending unsucesful and unecrypted connections
 Thank you

**Comment by aryoda** [comment]
How did you discover these connection leaks (Net Monitor App on your mobile, wireshark in your network...)?

**Comment by ghost** [comment]
through net monitor

2018-01-06 10:46 GMT+02:00 aryoda <notifications@github.com>:

**Comment by ukanth** [comment]
Please provide details extracted from menu-firewall rules.
