### ISSUE TITLE
Can't switch language

### ISSUE THREAD

**Issue by MaxXor** [ukanth/afwall#785]
When selecting a different language in settings and restarting the app it's still using the default language.

**Comment by ukanth** [comment]
Which language you selected ?

**Comment by MaxXor** [comment]
I select English and after restart every text is still in my system language.

**Comment by ukanth** [comment]
Yes. it's a bug. will fix it. thanks for reporting it.

**Comment by ukanth** [comment]
Fixed. will be available in next version (2.9.9)

**Comment by MaxXor** [comment]
Hello, this issue is not fixed in 2.9.9, I selected english and it still defaults to my system language.

**Comment by ukanth** [comment]
what version of OS ?

**Comment by MaxXor** [comment]
Android 8.1 Patch Level April 2018
