### ISSUE TITLE
Potential Compatibility Issue

### ISSUE THREAD

**Issue by strooonger** [ukanth/afwall#786]
Hi, I notice in class `RulesPreferenceFragment.java` you have used function `onAttach(Context)`, which is added in API version =  23. However, `onAttach(Context)` will not execute in API version < 23 (See this [link](https://stackoverflow.com/questions/32083053/android-fragment-onattach-deprecated)).

Class `RulesPreferenceFragment` directly extends `android.preference.PreferenceFragment`. As the official document of Android shows, `android.preference.PreferenceFragment` directly extends `android.app.Fragment`, unfortunately in practice `onAttach(Context)` will not executed if one use `android.app.Fragment`. If you put some important operation into this function, the program may not execute normally in API<23.

My suggestion is simply changing `android.preference.PreferenceFragment` to `android.support.v7.preference.PreferenceFragmentCompat`, which have the same function as `android.preference.PreferenceFragment`, but does not have this potential compatibility issue.

**Comment by ukanth** [comment]
Thanks for the suggestion. Is it possible to make a pull request ?

**Comment by huaxunhuang** [comment]
Sure, I am glad to, just wait for a while
