### ISSUE TITLE
Clearer documentation about "Chains" options in "Connectivity settings"

### ISSUE THREAD

**Issue by infinity0** [ukanth/afwall#789]
Hi, thanks for writing and maintaining this.

I'm trying to block everything on my device (dumpling) by using the "allow selected" mode. However in "Preferences -> Rules/Connectivity" there is another section called "IPv4 Chains" with toggle-options {INPUT,OUTPUT,FORWARD} chain.

It's unclear how these interact with "allow selected" mode. Do I need to be in "allow selected" mode as well as switching these three options OFF, to actually block everything? The thing is, the options automatically switch themselves back to ON for some reason I haven't figured out yet. (Also this phone has 2 SIM card slots, I'm not sure if that would keep triggering spurious "network changed" events that might be the cause of that.)

**Comment by ukanth** [comment]
This issue is fixed in 3.0.0. Now it respects the selected options from rules screen.
