### ISSUE TITLE
com.android.providers.downloads logcat spam

### ISSUE THREAD

**Issue by T-vK** [ukanth/afwall#790]
I get lot of messages in logcat:

```
01-07 10:25:57.716   225   225 W afwallstart: type=1400 audit(0.0:741): avc: denied { getattr } for path="/data/data/com.android.providers.downloads" dev="mmcblk0p23" ino=114494 scontext=u:r:sysinit:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
```
I get this multiple times per second.

I tried to kill the app and I even disabled it (`pm disable com.android.providers.downloads`).
But I still get the logcat messages.

Any ideas what the messages mean and why I am getting them?

My device:
Lineage OS 13
Android 7
Nvidia Shield Tablet
Afwall 2.9.7

**Comment by Atavic** [comment]
It's SELinux denying the action.

**Comment by Atavic** [comment]
Similar: https://github.com/ukanth/afwall/issues/700#issuecomment-296966755

>Seems like selinux it blocking AFWall+ from reading.

See: https://github.com/ukanth/afwall/issues/662#issuecomment-282189759
