### ISSUE TITLE
roaming loopback to local network, leaking network usage while roaming

### ISSUE THREAD

**Issue by jagr19** [ukanth/afwall#792]
[IPv4rules.log](https://github.com/ukanth/afwall/files/1629502/IPv4rules.log)
while roaming on my samsung note 8, apps which are given local network access are able to access internet. attached log. am using dual sim with the second card used for data roaming.

**Comment by jagr19** [comment]
any updates please

**Comment by ukanth** [comment]
Please reopen if you still have this bug in 3.x

**Comment by jagr19** [comment]
Hi, same problem persists. Log attached, any custom script to help stop it?

[log.txt](https://github.com/ukanth/afwall/files/2697244/log.txt)
