### ISSUE TITLE
Error while applying the basic ruleset and some other small things

### ISSUE THREAD

**Issue by Shadowghost** [ukanth/afwall#800]
Since I switched to Android 8.1 Oreo, I always get an error after applying 33/x rules of the basic ruleset (I just installed the app and enabled it). I checked the logs and that's what afwall writes down there:
```
command 'iptables -A afwall-reject -j REJECT' exited with status 1'
Output:
iptables: no chain/target/match by that name
```
Something else I encountered: While enabling log service from within the app, I get a toast message telling me, that my kernel does not support NFLOG, but when checking `/proc/net/ip_tables_targets` NFLOG and LOG are present, so it should be supported.

Besides that I noticed a typo in some log output:
`Total commamds: #xx` should be `Total commands: #xx`

I hope someone has an idea what the culprit of my main issue could be :)
Regards Shadowghost

PS: If you need more logs or anything else, just tell me.

**Comment by Shadowghost** [comment]
Should be resolved by now. Applying works, not sure about the log thing, thought.

**Comment by lucas-digital** [comment]
How did you resolve that issue? I have exactly the same problem.
