### ISSUE TITLE
security pattern bypass

### ISSUE THREAD

**Issue by mis2417** [ukanth/afwall#801]
in nova launcher (or possibly others too) when you long press app icon you can choose preferences/logs/rules. even with security pattern set up, you can enter those and change anything, including flushing rules without pattern.

**Comment by mis2417** [comment]
https://imgur.com/a/YaGWh

**Comment by ukanth** [comment]
Thanks for reporting. I have added password check only for firewall rules and preferences. Logs should be fine without password.
