### ISSUE TITLE
Reliabiltiy of status bar notification?

### ISSUE THREAD

**Issue by franconian** [ukanth/afwall#804]
After flashing an LOS update I forgot to re-root my device. Starting AFWall leads to the correct warning, that the firewall won't work on an unrooted phone. If you choose the "Continue" button, nevertheless the status bar notification will be launched immediately telling you the "Firewall is activated" though no rule can be applied at all. Same behavior, if you cancel the dialog and select "Apply" in the menu. Again the notification is talking about an activated firewall.
The trigger for the notification seems to be just the click but not the successful application of rules.

**Comment by ukanth** [comment]
Fixed, will be available in next version. Kindly reopen if it's not fixed.
