### ISSUE TITLE
Small usability enhancement request: New Column "Enable Notification Filter"

### ISSUE THREAD

**Issue by schittli** [ukanth/afwall#806]
Good evening
thanks a lot for this great firewall!, it's really a useful work.

**I have a small proposal:
The notification filter is very useful, but the handling is unnecessarily complicated:** 

1. Open Settings
2. Guess where to find the notification Filter (hint: Preferences)
3. Guess where to find the notification Filter (hint: Log)
4. Select Notification filter
5. Scroll up and down and try to find the application

**I suggest that afwall offers an additional column on the main screen** (optional, if applicable): "Enable Notification Filter"

Icon | LAN | WLAN | Notification filter | …
------------ | ------------- | ------------- | ------------- | -------------
:-) | x | o | x | [ 1011 ] (ADB) - …
:-( | x | x | x | [ -11 ] (Kernel) - …

if we could display such a column, the handling would be much easier.

kind regards, Thomas

**Comment by ukanth** [comment]
Instead of separate column ( there are too many columns already). it's moved under individual app detail screen ( when you click on app, you can get in)

**Comment by bonbonboi** [comment]
To me if that column isn't possible at least add a search box above the Notification filter popup. scrolling down and up is a pain meanwhile Notification filter doesn't offer the ability to check all or none or even a separate column of UID, apps names and the ckeck boxes.

**Comment by ukanth** [comment]
Adding search box is duplicate functionality of main screen. Now notification filter can be done through app detail screen.

**Comment by Maxxee** [comment]
ukanth, even if it is annoying, please consider it once again to add an extra column to the main list instead hiding it in the app's details.
With an extra column in the main list the user could immediately see for which apps the notification is enabled/disabled.
