### ISSUE TITLE
Big trouble with Android 5.1.1 (Lenovo K5)

### ISSUE THREAD

**Issue by abusr** [ukanth/afwall#808]
A clean installation of latest afwall in a brand new Lenovo K5 Vibe (Android 5.1.1) with latest Magisk installed yielded the following problems:

1. Without "fix startup data leak", when phone boots, no firewall is applied. Every app in the phone can communicate with the internet freely. When applying firewall manually, things come to normal.

2. With "fix startup data leak" enabled, when phone boots, no app can communicate with the internet (good) but when I activate cellular data, still no app can communicate with the internet. Same problem if the phone starts with cellular data enabled. If I apply the firewall manually, things come to normal.

3. Regardless of (1) or (2), when I re-apply the firewall for any reason, there is a big chance that it will stop blocking irreversibly. Only wayout out of this is to restart the phone.

4. In the preferences, when I try to change the sliders for ipv4 outgoing and forward, afwall crashes and immediately re-starts with the slider in the correct position. However, when I try to change the incoming slider, afwal does not let me at all (no crash this time). When I try to change the corresponding ipv6 sliders, I can't. Whatever I try, they remain disabled. Interestingly, when I instruct afwall to use my system's ip(6)tables and busybox, all ipv4 and ipv6 sliders now can be set or re-set without problems.

5. When using my system's busybox and afwall's ip(6)tables binary (or the reverse, I can't precisely remember), when applying the firewall results in an endless loop where firewall rules are enumerated again and again and the only solution is to kill the app.

My safe conclusions are:
a. Afwall is able to receive and process the boot_complete. However it appears to be missing/misprocessing the network_state_changed and does not apply correctly. Thus I need to apply it by hand when a network iface changes state.
b. Afwall exhibits sensitivities to the binaries used, in a degree that renders some of it's funcionalities unstable or even forces the entire program to crash.

For reference, I used the latest version from f-droid and also from github. Even tried with one version before the latest, still problems.

I ask you to look at these issues. In between, have you got any sort of graphic representation/schematic of the firewall you create with afwall, so I can replicate this with shell script? I can listen to netd directly if I want.

**Comment by CHEF-KOCH** [comment]
Is this issue still present (after 1 year)? 

Most leaks (startup) are been fixed with later version (starting with 3+).  The latest Magisk version (stable) should also now work with the latest beta version (did you tried it -> avbl. here on GitHub).

**Comment by abusr** [comment]
The startup data leak part always worked, mainly because it's being run before android (at post_fs_data, as magisk calls it). I no longer have the phone but I recall that flashing from stock image did correct the problem. Strange because since then I had never flashed the phone with any sort of rom whatsoever and had never run anything which could have altered the /system partition. Some silent mess with the app's permissions must have occurred and although the app was supposed to be getting the required permissions, it effectively didn't. Thanks for reminding me this open case. I'm closing it after having reported my solution.
