### ISSUE TITLE
Toaster popup reporting Linux Kernel blocked, when rules are set to allow.

### ISSUE THREAD

**Issue by Showerrodney** [ukanth/afwall#809]
Something very similar to issue #475 seems to have reappeared. Not sure if the messages are falsely reporting however - the destination addresses in the log for UID -11 resolve to typical analytics addresses like Google/Facebook/Amazon etc and also internal LAN IPs). Linux Kernel is whitelisted in the rules. 

Any idea what's happening here?

**Comment by bonbonboi** [comment]
I noticed that UID -11 of Linux kernel in the list is different than the UID logged by the log service which is UID 0

To me Linux kernel is a mystery network connection and I'm too lazy to dig into those IP destinations that trying to connect to since unfortunately AFWall doesn't resolve IP addresses while logging.

**Comment by ukanth** [comment]
Fixed. It will be shown as "Unknown".

**Comment by bonbonboi** [comment]
I'm on beta1, what's the point to rename it to unknown, for testing, log service and toast enabled, now there's  unknown(-1) popping up,   in Firewall log, there's Unknown(0), in the main app list there's no any process with uid (-1) neither (0)

**Comment by ukanth** [comment]
@bonbonboi , Thanks for raising this issue again. I have fixed it now.

**Comment by mcurly** [comment]
Hi @ukanth,

This is the info from the device/ROM I'm currently using:

> Model
> Redmi Note 4
> 
> Android version
> 8.1.0
> 
> LineageOS version
> 15.1-20180618-NIGHTLY-mido

"

I am noticing the same behavior the OP was noticing.

I have purchased donation version.

![screenshot_afwall _ donate _20180625-180435](https://user-images.githubusercontent.com/8215020/41864625-8ac02e72-78a2-11e8-8947-3fef6d5e9651.png)


Could you please look into it.

Thanks in advance

**Comment by ukanth** [comment]
I will look into it. Thanks.

**Comment by NicolaP8** [comment]
AFWall+ 3.0.1 Moto G5 Plus
I had stock 7.0 and AFWall worked well.
Now I updated to stock Oreo 8.1 and started to see messages in the log that the 
  (kernel) - Linux kernel(-11)
was blocked.
Despite this the phone works well, I can browse, message, etc without visible problems.
