### ISSUE TITLE
AFWall+ is allowing connections via mobile data despite app being blocked.

### ISSUE THREAD

**Issue by downloaderfan** [ukanth/afwall#815]
Ok, I've been using AFWall+ for 8 months now, but I didn't have to use mobile data frequently until a month ago. While checking data usage today, I noticed that apps that I've blocked with AFWall+ were using my data. 
https://i.imgur.com/IDc4ARb.png
I'm able to browse websites in Chrome even though I've blocked it with AFWall+. Yes, I clicked on "Apply" after checking Chrome. I enabled logging then & even though it shows blocked, Chrome is able to load websites.

Here's the log:
`
	---------
AppID :	10395
App Name:	Chrome
Total Packets Blocked:	6
[UDP]49.45.0.1:53(1)
[UDP]8.8.8.8:53(5)

	---------
`
 
AFWall+ v2.9.8
SlimROM 7.1.2 Nougat
One thing to note is that my phone is a dual SIM phone, not sure if that's causing this.
If further details are required, ask away.

**Comment by ukanth** [comment]
I need firewall rules not logs. You can find it under menu->Show rules-> Send error log ( or export ) and attach it here.

**Comment by downloaderfan** [comment]
Here are the firewall rules:
[IPv4rules.log](https://github.com/ukanth/afwall/files/1876639/IPv4rules.log)

**Comment by downloaderfan** [comment]
Ok, it's been quite a while now & I decided to just sit down & look into this issue. After some tinkering, I found that after enabling IPv6 support under Preferences --> Rules/Connectivity, AFWall+ was able to block connections even on mobile data. I'm not sure why it's left Off by default, hopefully this can benefit someone else.
