### ISSUE TITLE
Only one item ([1020] mDNS) in Notification filter list 

### ISSUE THREAD

**Issue by irontechmonkey** [ukanth/afwall#816]
Preferences > Log > Notification filter > [1020] mDNS

Lineage OS 14.1, Android 7.1.2, LOS SU, Afwall+ 2.9.9-BETA-1 installed on top of v2.9.8 with Unlocker 1.0.1.

Later I'll test a clean install without locker, then add locker.

[Afwall2018-04-01-22-04-58.txt](https://github.com/ukanth/afwall/files/1866912/Afwall2018-04-01-22-04-58.txt)
![screenshot_20180401-220337](https://user-images.githubusercontent.com/14972114/38180489-fc692622-35fa-11e8-8cf3-fa11be129f64.png)

**Comment by irontechmonkey** [comment]
D'oh! I was misinterpreting one of the new changes.
- Block log notification now moved under individual app detail screen
Still figuring it out.

**Comment by irontechmonkey** [comment]
Nevermind, apologies for the false possitive.

**Comment by code-issues-pull** [comment]
May want to add a little note on this screen to clarify to users who thought they were coming here to filter apps from blocked notifications. I was confused too and about to submit a report until I saw this. :)
