### ISSUE TITLE
init.d directory path needs updating for Magisk 16.3

### ISSUE THREAD

**Issue by jancm** [ukanth/afwall#821]
I'd swear that there used to be an entry in there for Magisk and/or SuperSU. I suspect the issue is that the /magisk symlink has been removed as of 16.3 and you have to use the /sbin/.core/img/ path instead.

**Comment by zelleb** [comment]
Have you looked into this, @ukanth?

**Comment by DaleBCooper** [comment]
I made a pull request: https://github.com/ukanth/afwall/pull/830

@ukanth Please have a look at it, should not break anything.

**Comment by varhub** [comment]
@DaleBCooper add paths instead replace them to do not break magisk versions <16.3

**Comment by DaleBCooper** [comment]
@varhub Done.

**Comment by varhub** [comment]
_closed by #830_. 
@ukanth , could you close it if you have time?
