### ISSUE TITLE
Afwall+ Donate does not see Simple Calendar

### ISSUE THREAD

**Issue by HerborenInVlammen** [ukanth/afwall#823]
Hi:  Afwall+ Donate does not see Simple Calendar.  It does not prompt for permissions on install, nor is it listed after install.  Nor is it blocked in any way.  This is a first for me, and not sure what to do.

I have not tried other "Simple Apps" to see if this is something that effects all their apps.

AFWall+ (Donate) v2.9.8
SlimROM 7.1.2 Nougat

**Comment by ildar** [comment]
It may be named differently, localized, in your native language.

**Comment by ukanth** [comment]
Simple Calendar does not have INTERNET permission. https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/AndroidManifest.xml

AFWall+ lists apps with INTERNET permission.
