### ISSUE TITLE
microG not in app list but blocked by Afwall+

### ISSUE THREAD

**Issue by WeaponsLeft** [ukanth/afwall#825]
Hello,

Afwall+ blocks internet access of microG but the application is not in the list of applications.
Due to this the app can not be unblocked and makes its usage impossible.

- Access denied recorded in "Firewall Logs" for the app
- "Access Blocked" message appears as toast message aswell
- App works fine if Afwall+ is disabled
- Triplle checked application list of Awall+, even used the search function
- "Show filters" disabled in the "UI Preferences"

Firewall log entry name:
"com.google.android.gms (10118)"

Additional information:
- Application path: "/system/priv-app/com.google.android.gms/base.apk"
- Original file: https://microg.org/fdroid/repo/com.google.android.gms-12221403.apk
- Device operating system "OREO (8.0.0)"
- Device: "Zuk Z2 Pro" / Model: "ZUK Z2121"

Any ideas how to solve this problem?

**Comment by ukanth** [comment]
App might be listed with different name. Check the app name and allow it. Apps which doesn't have internet access is not shown on AFWall+ and those apps can't connect to internet.

**Comment by WeaponsLeft** [comment]
Hello Ukanth,

I alreday checked the application list inside of Afwall+ but there is no related application.

In theory the "microG" application could appear as 2 possible application to the android system,
either it is identified as "microG Services Core" or "Google Play Services" as it tries to spoof
the system to be original google play services. However, none is shown in the list.

How can an app not have internet access -> Not being in the list -> But still try to access the internet -> Then being blocked by Afwall+? This makes no sence.

Please note that I dont't mind if you proof me wrong,
however believe something is not working like intended. 

**See for yourself:** 

![firewall-logs](https://user-images.githubusercontent.com/10565802/39178343-c90709d4-47b1-11e8-986a-333dece8ae38.png)
![afwall-list](https://user-images.githubusercontent.com/10565802/39178348-cb990148-47b1-11e8-9e03-dcb82133747b.png)

**Comment by ukanth** [comment]
it supposed to be listed as "microG Settings" in the AFWall+ list. For some reason I don't see that in the list screenshot. It could be issue with the way afwall query the installed apps or issue with the way microG keep this app.

I don't use microG , so not sure how to reproduce this

**Comment by WeaponsLeft** [comment]
I did some more research maybe it will help:

1) Afwall+ is not the only application that can not detect the microG application...
- Does not show in system buildin "apps manager", even not if "show system" is enabled.
- "system app safe remover" (root) can not see the application
- "lucky patcher" (root) can not see the application
- BUT the X-Posed based application "quick settings" CAN see it as "microG Services Core"
![quick-settings-microg](https://user-images.githubusercontent.com/10565802/39202854-789c5bf6-47f3-11e8-8c60-61cc7755acf8.png)
It can even see the activities of the application, for example the "microG Settings":
![quick-settings-microg-activity](https://user-images.githubusercontent.com/10565802/39202858-7ae9fc38-47f3-11e8-8e65-8c1cf90efad7.png)

2.) I can enable internet access of the application by using "black list" instead of "white list".
     It indirectly allows it because it is not blocked in the first place, still invisble.
- This however is not a real sulution to the problem, also comes with other side effects naturally caused by blacklisting...
- If whatever makes microG invisble to Afwall+ is used in other apps intentionally will silently bypass Afwall+ entirely without further notice when "black list" is used. Would consider this effect a security risk.

I will  try to open a seperate issue on the microG github aswell, may be worth asking why this application goes under the radar of several applications...

If you have any ideas or need some diagnostic information, dont hassle to ask me
I will try to provide necessary information.

EDIT, opened issue: https://github.com/microg/android_packages_apps_GmsCore/issues/535

**Comment by ukanth** [comment]
Please reopen if you still have this bug in 3.x
