### ISSUE TITLE
AFWall+ not working using android orio 8.1

### ISSUE THREAD

**Issue by SaddamRaut** [ukanth/afwall#826]
I am using AOSP Extended ROM 5.4 having android v 8.1.

**Comment by ukanth** [comment]
Please attach firewall rules from menu->Show rules-> Export

**Comment by Shadowghost** [comment]
Should be the same error than described in #788 and #800. Logs were provided over there.

**Comment by Spindletop** [comment]
I also have trouble with AFWall and Android 8.1.0 (CarbonROM). #788 and #800 did occur after install, logservice could not be started, currently it can be started but AFWall crashes when selecting the logged application.
Now "some" traffic is blocked, but not google-domains! Applications like built-in browser, NewPipe (for accessing youtube) work for ALL google related stuff (google.xxx, , youtube, etc.), but no other domains (e.g. github.com), even if they are blocked.

**Comment by Spindletop** [comment]
Enabling IPv6 support in the settings did the trick for me and the applications seem to be blocked again (as in #755).

**Comment by ghtux** [comment]
Los 15.1 doesn't work well here either. Dns resolving, openvpn aren't working like before. Can't provide logs since I switched back to android 7. Tried with enabling Ipv6 but this didn't solve anything

**Comment by ghtux** [comment]
Default firewall works. Any custom script breaks afwall for me

Tried again and it works with scripts! Guess I didn't delete all flush commands.
