### ISSUE TITLE
AFWALL DISABLED during sleep

### ISSUE THREAD

**Issue by AlbinoRetardedMutant** [ukanth/afwall#832]
When I wake up from sleep, i found AFWall **disabled**. This is a big leaks during sleep. I am sure my credentials is stolen and encryption key is stolen, and device ID and real IP address behind VPN is revealed and sent to bad people behind big company or Google servers. **Because AFWall so weak** and the developer are pro Google evil. AFWall should have Self-Protection! Mankind is more important than mutant.

AFWall: v2.9.9
OS: Oreo 8.1 LineageOS based

**Comment by bonbonboi** [comment]
I never found afwall got disabled by itself (despite the fact it does if it crashed) still i like the idea of self-immunity thing...

**Comment by ukanth** [comment]
Please reopen if you still have this bug in 3.x
