### ISSUE TITLE
Duplicate rules with Custom Scripts and IPv6 enabled

### ISSUE THREAD

**Issue by Aeodyn** [ukanth/afwall#837]
What I've seen is that adding lines to the "Set custom script" box that don't use the $IPTABLES variable (because of different IPs for v4 vs v6, for example, which would otherwise cause an error) seems to run the line twice.
This can be observed by keeping track of the number of rules before and after adding the line.

As far as I can tell this isn't normally an issue since duplicate iptables rules don't seem to actually be created. However, I'm also using it a bit as a convenient place for a Wireguard-related "ip rule add" command; That _is_ duplicated, and requires a duplicate shutdown script line to actually get rid of it.

I'm not sure what the easiest way to change this would be; adding an extra box for commands that don't use $IPTABLES might work.
I don't know if this is an issue for when a script file is loaded or not.

**Comment by v01ded** [comment]
Having the same issue here. When IPV6 is enable in the setting, AFWall+ seems to run the custom script twice resulting duplicated entries in the iptables
