### ISSUE TITLE
new error: package manager has died.

### ISSUE THREAD

**Issue by nutpantz** [ukanth/afwall#838]
Error:java.lang.RuntimeException: Package manager has died

Just started getting this in a toast. No idea why. It's from afwall donate latest version.

**Comment by EgonKrenz2** [comment]
Same here in 2.99 free version.
Additional info: 
lineageOS 12.1, opengapps nano, more than 1500 firewall rules.
Error appears several times an hour.

**Comment by ukanth** [comment]
It's a bug in 2.9.9. Disable log notification for now . Thanks.

**Comment by nutpantz** [comment]
I only had the log on, no notification on

**Comment by EgonKrenz2** [comment]
I can confirm nutpantz:
Log + Nofification: Error repeats often
Log - Notification: Error is still there, a little less often

**Comment by bontxa** [comment]
I have the same problem, is there a way to not show the toast?
thanks

**Comment by ukanth** [comment]
It's fixed in 3.0.0

**Comment by bontxa** [comment]
great!!!
just installed and testing. keep up the good job!
