### ISSUE TITLE
App restrictions are ignored?

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#839]
Hi

Yes I have a custom script and when I enable the custom script, app restrictions (ones done via the ui) are all ignored, like a limited app still able to connect to internet.

I can get the app restrictions back if I disable the custom script :( So I  messed up somewhere probably btu I do not know where.

Here is my custom script
https://paste.debian.net/hidden/4e022d2b/

I am using Afwall v2.9.9 donate version on Samsung phone Lollipop 5.1 with SuperSu with auto binaries.

thanks

**Comment by ukanth** [comment]
I'm unable to open that link.
