### ISSUE TITLE
Connection Confirm

### ISSUE THREAD

**Issue by Bunplugged** [ukanth/afwall#843]
First of all thanx for a great app
I saw this on issue 269 where a new connection is passed to the user for conformation, this is possible to do with NFQUEUE with a chain that sends to the queue and that sends to the user for conformation. It would have to be with connection tracking because without it every packet will need to be given a ok. This was done for discowall (a bachelor thesis) by the compiling the libnetfilter_queue  library for android (it is native c of course) and making a front end to pass on the users decision I would also suggest that their be a option to always enable the app also thus minimizing the use of the queue which is slow. Since that doc nfqueue has uid support and can do multiple queues. I will try to help with what I can.
Applied protocol

**Comment by ukanth** [comment]
Netfilter requires specific modules to be compiled with kernel ( with certain flags ). All the stock kernel's doesn't have these modules compiled , so it might not work on stock phones.  It might work with lineage.

**Comment by Bunplugged** [comment]
I thought that this is mainly made for the custom ROMs so to ask them to do that might not be a problem, plus this will also solve the problem of how to write rules to IPTables. This could be a option or only in a certain version.

**Comment by Viveur** [comment]
Was interested in reading about discowall and luckily found a cached version (as the original links didn't seem to be working anymore) here:

http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=4963AD17F32ABE83686018194154583E?doi=10.1.1.705.2552&rep=rep1&type=pdf
