### ISSUE TITLE
FR: Trim logs

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#844]
HI

It would be great if the logs for the donation version trimmed regularly. These logs getsinsane!!!! It takes like 10 mins to open the log window :(

**Comment by gerroon** [comment]
Btw I checked the data folder and the log was like 125mb at that moment. I had to gain root to delete it.

**Comment by ukanth** [comment]
Fixed in 3.x

**Comment by gerroon** [comment]
thanks
