### ISSUE TITLE
Logs should include timestamps

### ISSUE THREAD

**Issue by a3kov** [ukanth/afwall#845]
I am trying to investigate unauthorized mobile data usage on my phone. I know that the phone generates traffic not at the same time, but in a defined time periods (I know it because my cellular provider has this feature where it blocks data when I'm not subscribed to any data package and notifies me by sms). In the current state of logging in AFWall I can see the blocked traffic but without the timestamps I am unable to make a conclusion whether this traffic could be the cause of cellular data leakage before or not.
I guess the way AFwall "aggregates" streams in the log at least it could provide start and end timestamps. Right now it has some timestamps in the "new view" but it's not clear if its the start or the end time, and the "old view" doesn't have timestamps at all.

**Comment by ukanth** [comment]
Duplicate/Relate to #1002
