### ISSUE TITLE
Prevent apps from bypassing AFWall

### ISSUE THREAD

**Issue by stef204** [ukanth/afwall#848]
According to this [post](https://www.reddit.com/r/CopperheadOS/comments/7j57zd/gboard_privacy_and_security/dr5272t/) from the developer of CopperHeadOS, and this [one](https://www.reddit.com/r/CopperheadOS/comments/7j57zd/gboard_privacy_and_security/dr586zd/), apps can still _bypasss_ the firewall _"via APIs exposed from the base system or other apps "_

These posts would seem to indicate that in certain cases, AFWall (or any other firewall, for that matter) will NOT block access.

Can you please provide feedback on this issue which seems to be critical?

Are there any ways to prevent the above, currently with AFWall? If not, any plans to address it?

Edit: I see there are a number of related tickets, e.g. #723

**Comment by Jookia** [comment]
AFWall is a network firewall, so it should always block access when applications make network requests. Applications cannot bypass the firewall itself.

Unfortunately applications can communicate with other applications through various inter-process communications or sockets. This is how for example applications use the download manger to download files- they ask the download manager to download the file, and it does it.
The security term for this is the 'confused deputy problem'.

So if you're running a system and you don't want any LAN access, don't give any applications LAN access. The risk only happens when you let some have access and they provide it to others over IPC.

**Comment by stef204** [comment]
Thanks for your feedback. The concept of firewall and iptables is clearly understood, what is more tricky is in the overall context of Android.<br>
Moreover, my concern is a bit more on the upload (preventing an app which has the INTERNET permission from uploading data from device to an external server) than on the download (the DL Manager scenario you mention) using exposed api's or other non direct means--via core OS apps or components, etc.<br>
I am not looking at running AFWall in whitelist mode, rather in the blacklist mode where I block just a few apps.  You recommend blocking everything, than selectively whitelisting some apps--not easy to accomplish seeing that many core components or app will need whitelisting no matter what--and could be used by a "malicious" app.<br>
I believe this issue will be or has been addressed in Android 9+ though, but not quite sure yet.<br>
Happy to read any further comments you may have.  Thanks.

**Comment by bonbonboi** [comment]
> AFWall is a network firewall, so it should always block access when applications make network requests. Applications cannot bypass the firewall itself.
> 
> Unfortunately applications can communicate with other applications through various inter-process communications or sockets. This is how for example applications use the download manger to download files- they ask the download manager to download the file, and it does it.
> The security term for this is the 'confused deputy problem'.
> 
> So if you're running a system and you don't want any LAN access, don't give any applications LAN access. The risk only happens when you let some have access and they provide it to others over IPC.

That is totally unsafe, how come an app can use another app as a proxy to reach the internet, we need  more explanation and examples of such apps to never install on our phones...

**Comment by Jookia** [comment]
An app can use another app as a proxy to reach the Internet if the another app lets them. Which applications do this? I don't know, on my phone Orbot and the Download Manager at the very least let other applications connect to the Internet using their firewall rules. I think on my phone at least Browser will use Download Manager.

One solution to this would be for someone to create an Android IPC firewall, so you could say 'don't let Browser use Download Manager'. But I'm fairly sure this would break applications in weird ways that don't expect to be denied access to system resources.

Another solution would be to make a sandbox by using multiple users then setting a traffic rule for the sandbox. The only way I think to do this on Android requires switching between users which is annoying.

**Comment by 0pLuS0** [comment]
@ukanth can you please reply to this and share your thoughts as the developer?

Thank you

P.S. I wonder if using an app like XprivacyLua, or something else can help?

**Comment by ukanth** [comment]
Technically anything is possible in Android. No apps/system can protect if you are not careful enough. Yes. it's possible for application to bypass through system app. But this behavior is not allowed in general. Two scenarios what we have identified so far are "Download manager API" and "Google play services API"

The first one (download manager ) can be called by any application to get files from internet. If you allow "Download manager" and deny access to an specific app, still it can download it. There is no way for AFWall+ to block it until you enable Xposed module for AFWall+ 

The later can be used by apps to display ads which also cannot be prevented. But you can use any adblockers to disable it.

Another possible workaround would be route the traffic to local VPN and block it. But I have never tried it.

**Comment by 0pLuS0** [comment]
Thanks for your reply ukanth...
