### ISSUE TITLE
Network connections being allowed even when set to deny

### ISSUE THREAD

**Issue by t4777sd** [ukanth/afwall#853]
In the AFWall configuration I have "Allowed selected" configuration mode. For AlarmDroid I have not selected any permissions. Given this, it should be completely denied internet. However, using netmonitor I can see that AlarmDroid is making a connection to facebook.

Other considerations is that I have a VPN enabled (orbot). Of course AlarmDroid does not have VPN connection permissions. I have tested other apps like the browser and it does stop the connection so the firewall rules appear to work.

Also, I check netstat at startup and AlarmDroid is not lsited. So, it is not that alarmdroid is started before AFWall and therefore strated before rules are applied.

Any ideas?

**Comment by t4777sd** [comment]
Looking at the socket state the socket state is SYN_SENT. Does this indicate it is being blocked by the firewall?

**Comment by ukanth** [comment]
Try filter the apps through VPN.
