### ISSUE TITLE
[Enhancement] Auto-delete old logs, keep per-app log totals.

### ISSUE THREAD

**Issue by dimgel** [ukanth/afwall#856]
Hello ukanth! Amazing program. 

But i wonder for how long logs are stored? If i won't clear them manually for years, will i run out of space? So i propose an option in log settings: how long to keep logs (in days, or smth). Since you show recent log details first, you likely have means of quickly sorting them by date (maybe you store them in sqlite?), so deleting old logs should not be an issue i hope.

Also, when old logs are deleted (manually or automatically), maybe it's worth not to reset per-app totals ("N seconds/.../days ago", "Denied: M times"), and append "old logs are deleted on <time>" line at the bottom of log details screen (after oldest record). Not sure if such behaviour would suit everyone, maybe checkbox option in log settings, too.

**Comment by dimgel** [comment]
For ~3 hours, "Xiami service framework" was denied ~900 times. Phone being idle. So maybe it also would be good to limit max number of log records per app.

**Comment by ukanth** [comment]
Currently it purges after it crosses certain limit, but not app wise.

**Comment by Friday13th87** [comment]
hm this sounds like a really bad solution.
in my experience some apps are denied like thousand times and are very uninteresting for researching some not wanted behaviours. so if it is purging some helpful informations about apps/ips/ports denied only a couple of times because some other apps filling this limit these informations are gone

**Comment by dimgel** [comment]
I thought about this use case too, and looks like my proposal would not solve it either. This can probably be solved by grouping per-app log details by IP: "IP, [Host,] **last** attempt timestamp, **total attempts**". For now, I had to turn off logging because after 1-2 days of phone being mostly idle, logs opened really slowly.

**Comment by ukanth** [comment]
Not possible per app. But trimming is done in 3.x version.
