### ISSUE TITLE
Support App name changes

### ISSUE THREAD

**Issue by rancidfrog** [ukanth/afwall#857]
Currently app shows old name for an app:
![](https://i.imgur.com/usV2nFH.png)
The app was in alpha stage so a lot of changes were being made.
Now it is called Fair Email,
![](https://i.imgur.com/cbZIKcJ.png)
But, AFwall still displaying safe email, as shown above.

Pull to refresh should reload/refresh app list with proper app names. This is not the case, and old names remain.

**Comment by rancidfrog** [comment]
Strange as in Traffic details name appears correctly:
![](https://i.imgur.com/eBc2rX4.png)

Yet, in app list it remains as old name even after refreshing:
![](https://i.imgur.com/UwuRVwC.png)

**Comment by ukanth** [comment]
This seems like bug. But I remember not reading app label on every refresh due to performance issue (it takes time) when I fixed it last time. Will have to check it again.

**Comment by rancidfrog** [comment]
Maybe, add button in menu, (which uses separate code function than quick fast pull to refresh code):
![](https://i.imgur.com/WuGVTTG.png)

With appropriate name:
Refresh | Refresh App List | Deep Refresh
