### ISSUE TITLE
afwall not always on the top of OUTPUT chain.

### ISSUE THREAD

**Issue by ivantao8** [ukanth/afwall#858]
sometime afwall is the first rule of OUTPUT chain,
``Chain OUTPUT (policy ACCEPT 21 packets, 1772 bytes)``
 ``pkts bytes target     prot opt in     out     source               destination         ``
  ``782 94683 afwall     all  --  *      *       0.0.0.0/0            0.0.0.0/0           ``
  ``191 24147 wmsctrl_OUTPUT  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0          `` 
 ``1222  123K oem_out    all  --  *      *       0.0.0.0/0            0.0.0.0/0           ``
`` 1222  123K fw_OUTPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           ``
sometime its not,
`` Chain OUTPUT (policy ACCEPT 289 packets, 25204 bytes)`` 
``  pkts bytes target     prot opt in     out     source               destination         `` 
``   282 17707 wmsctrl_OUTPUT  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           `` 
``  1279  111K afwall     all  --  *      *       0.0.0.0/0            0.0.0.0/0           `` 
``   865 86943 oem_out    all  --  *      *       0.0.0.0/0            0.0.0.0/0           `` 
its jump to
``Chain wmsctrl_OUTPUT (1 references)``
`` pkts bytes target     prot opt in     out     source               destination     ``    
``    0     0 NFQUEUE    tcp  --  *      *       0.0.0.0/0            127.0.0.1            tcp dpt:53889 STRING match  "GET" ALGO name bm FROM 40 TO 200 NFQUEUE num 20 bypass``
seems a suspicious process:
``tcp        0      0 ::ffff:127.0.0.1:53889  :::*                    LISTEN      6271/com.miui.wmsvc``
my device:``xiaomi redmi5 Version: V9.6.3.0.NDAMIFD (MIUI9) Global  android 7.x``
how to make afwll always on the top?
non native english,sorry.

**Comment by ukanth** [comment]
Seems like you have another app which modifies iptables rules.
