### ISSUE TITLE
Most apps have multiple entries

### ISSUE THREAD

**Issue by marcelser** [ukanth/afwall#859]
On Android 8.0 my AFWall+ 2.9.9 with profiles enabled shows multiple entries for most apps. Some apps appear up to 8 times. If I whitelist an app I always check all checkboxes, if I then apply the changes it creates only 1 new rule for all checked entries. So I guess the rules file is working fine but Afwall is somewhat messed up. Any idea what causes this multiple entries or would you like a screenshot?

**Comment by ukanth** [comment]
Have you enabled "dual apps support" by any chance ?
