### ISSUE TITLE
Translatable strings have not shipped in a while.

### ISSUE THREAD

**Issue by comradekingu** [ukanth/afwall#860]
The translatable strings on Crowdin still draw from "master", whereas "beta" is the branch wherein fixes are present. If this is a "when will the next version be out", feel free to close.

**Comment by ukanth** [comment]
usually it's released from beta branch all time. I have imported latest translations from crowdin.

7330a144f55910eadbb52e3cd68d405030142c2c

Will release once I feel it's ready.
