### ISSUE TITLE
UID Process 10074 Google GMS Service Missing

### ISSUE THREAD

**Issue by framecap** [ukanth/afwall#861]
This particular service does not show up on app list, commonly known as com.google.android.gms.setup on system. Can anyone provide an input? Am I doing something wrong?

Thank you for this app!

**Comment by ukanth** [comment]
it might not have internet permission. That's the reason it doesn't show up.

**Comment by framecap** [comment]
I am not sure whether it has to have Internet permission, and I really don't know if that could be the reason behind its unavailability. But does that really matter though? Any app should show up in firewall, right?

**Comment by ukanth** [comment]
if you are talking about this app https://play.google.com/store/apps/details?id=com.google.android.gms.setup, it does not have internet permission. Thats why it's not showing on main list. 

It might be using Google play services to send/receive data.
