### ISSUE TITLE
Multicast not working

### ISSUE THREAD

**Issue by Friday13th87** [ukanth/afwall#862]
On my Xiaomi Mi 8, MIUI10, AFWall+ 2.99 incl. Donation key multicast is not working.
My Onkyo Remote App and Spotify Connect is not working.

If i disable the Firewall both is working directly without any waiting time.
I have LAN control enabled and both apps have access to WIFI and LAN (i am in WIFI)

If i disable the Firewall i can see these addresses in network log
239.255.255.255:1900
255.255.255.255:60128
224.0.0.22:0
224.0.0.251:5353

i tried several rules in my custom script and read all the available issues here - nothing helped.

what would be the correct custom script entry for allowing these adresses?

not even
$IPTABLES -A "afwall-wifi" --destination "192.0.0.0/2" -J "afwall-wifi-lan" 
worked - which should allow everything between 192.0.0.1 - 255.255.255.255

after a long online search i think this is a common issue when using afwall...

**Comment by ukanth** [comment]
You need to allow mDNS to make it work or other wise root and kernal with LAN access

**Comment by Friday13th87** [comment]
Thanks for your fast response. There is no mDNS to allow. I allowed normal tethering/dns and upnp

**Comment by ukanth** [comment]
Allow root from app list along with kernel. if not you need custom iptables rules to allow mDNS to LAN.

**Comment by Friday13th87** [comment]
both are allowed in my app list.
would the custom rule correct like this (depending on the ip address of course)
```
$IPTABLES -A "afwall-wifi" --destination "192.0.0.0/2" -J "afwall-wifi-lan"
```

**Comment by ukanth** [comment]
Try something like 

`$IPTABLES -A "afwall" -p udp --dport 53 -j ACCEPT`
