### ISSUE TITLE
SMS app blocked?

### ISSUE THREAD

**Issue by OhSoGood** [ukanth/afwall#865]
Hi,

A long-time user of afwall (thanks for it by the way!!!), I was surprised to see afwall+ blocked several communications from the SMS/MMS application (ID 10068). The following IP address were blocked, all on port 443
216.58.213.142
216.58.215.46
172.217.19.238
172.217.18.206
These IP belongs to google hosting, have self-signed certificate (and redirect to google.com if blindly via https://[theip] ).

My phone runs lineage os 15, updated on Sept 4th. It is rooted, runs microg, fdroid and xposed (xprivacylua, minminguard), and has very few apps on it. 

Is there any chance that it is not the SMS/MMS app but another one (and so the log would be wrong)? Else, does anybody know why Lineageos' stock SMS app would open communications to external servers? Is that legitimate or... ?

Thank you!

**Comment by ukanth** [comment]
You can ask in XDA, people might be able to answer.
