### ISSUE TITLE
AFWall Crashed While Changing Settings

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#870]
Hi,

My Specs:
--------------
OnePlus 5T
Oxygen OS 5.1.5 - Oreo 8.1.0
Magisk 17.2
AFWall+ 2.9.9 (From F-Droid)
Xposed 3.1.5 - AFwall+ Module
--------------

Experimental > Startup directory path for script - I had to mkdir init.d on Oxygen OS it only has init. I was having a previous issue, with the Main window showing the "User" apps listed twice, so I was trying to replicate this bug playing with various options. 

I clicked on "Startup directory path for script" it then showed two /paths;
/system/etc/init.d
/etc/init.d

I clicked back and forth on both of the paths a few times, and then I got a popup message saying AFWall+ stopped.

I've attached a logcat, hopefully this will show you the problem why it crashed/stopped.

Thanks

[logcat.txt](https://github.com/ukanth/afwall/files/2433453/logcat.txt)

**Comment by 0pLuS0** [comment]
Nothing in the logcat?

**Comment by ukanth** [comment]
Logcat was useful. Fixed the crash. Thanks.

**Comment by 0pLuS0** [comment]
@ukanth ahh good, I'm glad...

Keep up the great work!
