### ISSUE TITLE
Automatic change of default policies?

### ISSUE THREAD

**Issue by sukort** [ukanth/afwall#874]
I have a custom script with the following default policies:
```
$IPTABLES -P INPUT DROP
$IPTABLES -P FORWARD DROP
$IPTABLES -P OUTPUT DROP
```
After activating the firewall I checked the rules by **$ adb shell su iptables -vnL** getting:
```
Chain INPUT (policy DROP 0 packets, 0 bytes)
Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
```
After activating WLAN the following resulted:
`Chain INPUT (policy ACCEPT 0 packets, 0 bytes)`
Why have changed the default policies of the OUTPUT and of the INPUT chain?
Thanks for help!

Samsung SII, LOS 14.1, AFWall+2.9.9

**Comment by ukanth** [comment]
You can disable it now on afwall itself and behaviour of default chains fixed in latest beta.

**Comment by sukort** [comment]
Thank you for your answer. I will test it soon! sukort
