### ISSUE TITLE
Request: Color/Themes?

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#877]
@ukanth

Can you please add the ability to change the color/look of AFwall?

I'm not asking that you include a lot of code to make for many changes, but just the ability to make the background white with black text and the green trim along the top, with the ability to just change this to one or several colors, I personally would like this in blue.

White background > black text > blue trim on top

Thanks

**Comment by bonbonboi** [comment]
+1 or at least change the check boxes to another color, the current black on dark is unclear. Thank you.

**Comment by ukanth** [comment]
Themes were introduced for this. Hence closing this.
