### ISSUE TITLE
Bug. Unnecessary rules iptables

### ISSUE THREAD

**Issue by OmlineEditor** [ukanth/afwall#878]
I see that there are Unnecessary lines in the rules:

-A afwall-wifi-postcustom -m owner --uid-owner 1014 -j RETURN
-A afwall-wifi-postcustom -m owner --uid-owner 1010 -j RETURN

I don't have an app with these numbers. that this is a bug or a backdoor?
the old versions did not have these lines.

**Comment by ukanth** [comment]
Refer here 
http://android-dls.com/wiki/index.php?title=Android_UIDs_and_GIDs

1014 - DHCP ( for tether )
1010 - AID_WIFI 

There is no backdoor
