### ISSUE TITLE
changing font size and input field in custom scripts

### ISSUE THREAD

**Issue by OmlineEditor** [ukanth/afwall#879]
1) can you add the ability to make font size changes in custom scripts?
2) changing the size of the input field for a script. move below if the active "on" the script. move above if the active "off" the script. see pic:
[https://i.postimg.cc/TwC9KFwS/image.png](https://i.postimg.cc/TwC9KFwS/image.png)
[![image.png](https://i.postimg.cc/TwC9KFwS/image.png)](https://postimg.cc/Q9K5P6ck)

**Comment by ukanth** [comment]
Ideal way to apply this to point to script. I don't intent to improve this page.
