### ISSUE TITLE
Hide service related notification icon from status bar

### ISSUE THREAD

**Issue by runo280** [ukanth/afwall#882]
I think these options will hide the the notification icon from the status bar ([link](https://github.com/M66B/open-source-email/blob/acf3cfadd47da518d095c611ec8300debace92f0/app/src/main/java/eu/faircode/email/ServiceSynchronize.java#L343)) and make the status bar more clean 😌:
```
.setPriority(Notification.PRIORITY_MIN)
.setCategory(Notification.CATEGORY_STATUS)
.setVisibility(Notification.VISIBILITY_SECRET);
```

It might to be added as an option if you don't prefer it as global setting.
Thanks

**Comment by ukanth** [comment]
Added.
