### ISSUE TITLE
Feature request: lan/vpn/etc control with active rules disabled.

### ISSUE THREAD

**Issue by Efreak** [ukanth/afwall#883]
I find myself reconnecting to my home wifi every so often, either when the signal drops out or while changing around connection settings, and then unable to go online while afwall+ reloads its rules. Please enable a way to use LAN control (specifically) and possibly vpn control without refreshing all rules on every reconnect.

**Comment by ukanth** [comment]
There is no way to find out new ip address(DHCP) when there is a connection change.

**Comment by Efreak** [comment]
Perhaps this can be an experimental setting with a warning then? Usually assigned IP is the same on most networks if you reconnect relatively fast; personally I have dhcp addresses reserved for most devices on my network. If the network reconnected to is the same, then the IP is likely the same as well.

Don't both the `ip` and `ifconfig` commands both tell you the device's IP address?
```
shieldtablet:/ # ifconfig wlan0|grep -E inet6?\ addr
          inet addr:192.168.0.100  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::204:4bff:fe57:619f/64 Scope: Link
shieldtablet:/ # ip -br address |grep wlan0
wlan0            UP             192.168.0.100/24 fe80::204:4bff:fe57:619f/64
shieldtablet:/ #
```

Admittedly I am on LOS and this may not apply to everyone.

**Comment by ukanth** [comment]
You can get ipaddress without root. But iptables needs to be updated when there is a change. otherwise it won't work.
