### ISSUE TITLE
fdroid build fails

### ISSUE THREAD

**Issue by anothernewusername** [ukanth/afwall#884]
fdroid cannot build version 3.0.0 see here: https://f-droid.org/wiki/page/dev.ukanth.ufirewall/lastbuild_16400

**Comment by mueller-ma** [comment]
I've received the 3.0.0 update via F-Droid.

**Comment by DaleBCooper** [comment]
I wonder what you were seeing?
Version 3.0.0 is available on F-Droid

> see here: https://f-droid.org/wiki/page/dev.ukanth.ufirewall/lastbuild_16400

this build completed at 2018-10-19 18:03:04Z
[...]
Build succeeded

**Comment by anothernewusername** [comment]
Seems like they could build it now. But they could not as I opened the issue.
