### ISSUE TITLE
No Persistent Notification

### ISSUE THREAD

**Issue by Buntbart** [ukanth/afwall#885]
*Please* make the new persistent notification optional. I want the old behavior back, where AFWall+ only gives a notification, when a new app is installed.   Personally I always find persisting nofications a bad design, which makes it harder to manage urgent notifications.

**Comment by DaleBCooper** [comment]
At least on Oreo you can configure the Notifications in the android settings as follows: Go to "Apps & notifications -> All apps -> AFWall+ -> App notifications" and set the category "Firewall Service" to off.
This eliminates the persistent notification and keeps all other notifications untouched.

**Comment by Buntbart** [comment]
This means that approx. 80% of Android users only have the choice to switch the notification on or off completely.

**Comment by israel-lugo** [comment]
Agreed, please make the notification optional. I find it distracting as I use the notification bar as a way of knowing something requires my attention.

**Comment by ukanth** [comment]
Fixed in 3.0.1

**Comment by rancidfrog** [comment]
@ukanth
Does not work as it should.
Switched on Show notification icon to test it and notification icon appeared,
![](https://i.imgur.com/RZF7WE4.png) 

But, when I unchecked it notification remains, permenantly,
![](https://i.imgur.com/nrTq4g9.png)
And it does not go away  
![](https://i.imgur.com/LVzF4vk.png)

**Comment by ukanth** [comment]
I mentioned very clearly on the changelog. You need to force stop afwall and restart after disable "persistent" notification 

That behaviour is only for devices with 8.x because it's tied to "Firewall service".

**Comment by rancidfrog** [comment]
I did. I am also on 7.1.1
But, after FC app
a new notification remains persistent:
![](https://i.imgur.com/X60Pen6.png)
There is no icon but it remains in notification drawer.
Clicking it takes you to app info not app:
![](https://i.imgur.com/XdO2SgU.png)

**Comment by ukanth** [comment]
That's android behaviour, afwall needs to run in background due to sdk changes enforced by Google.

**Comment by code-spotting** [comment]
@ukanth Thanks for the explanation. So there is no possibility to turn the notification depicted by @rancidfrog off on Android <8.x without killing AFWall completely?

**Comment by illtellyoulater** [comment]
> At least on Oreo you can configure the Notifications in the android settings as follows: Go to "Apps & notifications -> All apps -> AFWall+ -> App notifications" and set the category "Firewall Service" to off.
> This eliminates the persistent notification and keeps all other notifications untouched.

Isn't disabling the service going to cause potential problems with the correct functioning of AFWall? Not an Android expert but I think I read that services are used in Android to prevent apps from being stopping when the RAM is full. 
If AFWall abruptly stopped working, would it cause that all the firewall rules are not respected anymore by apps/traffic?
