### ISSUE TITLE
System log fetch method is not working

### ISSUE THREAD

**Issue by iamrohanbro** [ukanth/afwall#886]
Under preferences/log/log fetch method, the system method isn't working but the busybox method is.
Issue found on latest v3.0.0, previously the issue wasn't present on v2.9.9.
Using Carbon ROM (8.1.0) official on lenovo zuk z2.
Magisk version - 17.2
Busybox version - 1.29.3 by osm0sis

**Comment by ukanth** [comment]
It's a ROM issue. It has nothing to do with AFWall
