### ISSUE TITLE
Android notification "AFWall+ uses battery"

### ISSUE THREAD

**Issue by MaxXor** [ukanth/afwall#887]
First of all, thanks a lot for continuing to work on AFWall+. Now with the latest update 3.0.1 I have a new persistent notification shown from Android System that says "AFWall+ uses battery"... was there any significant change?

(this is only happening when the option "Show notification icon" is false)

**Comment by ukanth** [comment]
It needs to run in background due to changes introduced by Google. Recent afwall versions start targeting SDK 26.

Background is required in order to receive status on network change. It was not required previously.

**Comment by MaxXor** [comment]
Okay thanks, so I will just keep the notifications icon.
