### ISSUE TITLE
Store and apply iptables rules without root

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#888]
Thanks for this app. It is a real life saver in today's times.

I prefer to use my phone without root for some reasons. I also have a number of apps, which have been the same for a long while (I don't install new stuff anymore as I don't need to). Is it possible to use `iptables-save` to save the rules created by afwall in a text file, and then use a `/etc/init.d` script to apply them using `iptables-restore` on reboot. Or does the blocking procedure require the afwall app in other ways?

I use mobile data exclusively, so I don't need to switch to wifi (and hence don't need afwall's functionality to reapply rules on connection change).

Hence, I would be able to keep afwall (albeit disabled) but the iptables still present, even without root. 

I should mention that when I try it, I get the following error.
```sh
$ iptables-restore < /data/firewall-ip4.conf                            
iptables-restore v1.6.1: quota2: option "--name" cannot be inverted.

Error occurred at line: 265
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```

Line 265 of the file (generated by `iptables-save` after using afwall to apply rules) has the following.
```sh
-A bw_INPUT -m quota2 ! --name globalAlert  --quota 2097152
```

**Comment by ukanth** [comment]
Those rules are not belong to afwall but Google/Android. afwall uses it's own chain. Try filter it only for afwall chains. But as of now no plans to support as non root

Also iptables-save and restore also requires root.
