### ISSUE TITLE
Rules not applicable with v3.01 on Pixel C

### ISSUE THREAD

**Issue by flattervieh** [ukanth/afwall#889]
Rules are not applicable anymore after upgrade to v3.0.1.

Assumption was: 
> Seems like nat rule was added as part of tor integration (even though you didn't enable tor integration) and that's causing issue with pixel C ( due to kernel ). 

Latest ruleset after fresh installation of 3.0.1 any applying rules once.
[IPv4rules3.log](https://github.com/ukanth/afwall/files/2507110/IPv4rules3.log)

**Comment by brackenhill-mob** [comment]
+1

**Comment by brackenhill-mob** [comment]
Not trying to bump this, but has it been resolved? I don't see it fixed in the git commits.

This is really important for me. Our work devices are Pixel C's and we run a VPN so we can't use any other firewall because they hook the VPN.

**Comment by ukanth** [comment]
this is the commit https://github.com/ukanth/afwall/commit/55282dc80fbb9c1bdaf46747ec81c7d33b668871 . That should fix the issue. Wil try release a patch this weekend.

**Comment by takiainen** [comment]
+1, except I have Oneplus One, running Tugapower Pie ROM. It worked fine until I flashed Franco's kernel after which Afwall could not apply rules anymore.

**Comment by brackenhill-mob** [comment]
@ukanth I haven't seen any patch. Did I miss it? It's been over 3 weeks ...

The commit patch says "failed"???

;)

**Comment by ukanth** [comment]
Please check here. 
https://forum.xda-developers.com/showpost.php?p=78425274&postcount=5019

**Comment by ukanth** [comment]
Fixed.
