### ISSUE TITLE
version differences between frdroid and yalpstore afwall

### ISSUE THREAD

**Issue by 0lm** [ukanth/afwall#890]
hello
it alwys takes a while until the newest afwall version reaches fdroid, but thats probably normal i tihnk. but what i noticed since last update is, when i finally got afwall v3 on fdroid,  my yalpstore still said there is an update for afwall. it said 16400 --> 16500.
so does it mean after v3 another update for afwall came out, or is there some problem with versioning between the fdroid and the googleplay/yalpstore version of afwall?
currently yalpstore is telling me, that there is an update from 3.0.0 to 3.0.1 but a few days before that, it was 16400 to 16500. that kind confused me.

**Comment by ukanth** [comment]
3.0.1 is 16500 , Wait for f-droid to update to 3.0.1
