### ISSUE TITLE
Language -> System always sets English

### ISSUE THREAD

**Issue by kolAflash** [ukanth/afwall#892]
When setting ```Preferences > Languages/Plugins > Change Language``` to ```System```, AFWall+ is always in English (my Android system language is der to German/Germany). Even after force stopping and restarting AFWall+ it's still in english.

Workaround: Set ```Change Language``` to German.

AFWall+: 3.0.1 (F-Droid)
OS: LineageOS 14.1-20180808-NIGHTLY
Device: Fairphone 2

**Comment by ghost** [comment]
@ukanth Please use the system language as default, as most other apps do. In most apps it is not possible to change the language and using English makes you think it is not possible to have it in an other language.

**Comment by ukanth** [comment]
It's added long back.

**Comment by breversa** [comment]
It still happens with AFWall+ 3.4.2.1 (F-Droid) on Android 7.1.2 (LineageOS 14.1) on Asus Nexus 7.
