### ISSUE TITLE
always shows "AFWall+ is running" notification message (not the icon)

### ISSUE THREAD

**Issue by kolAflash** [ukanth/afwall#893]
AFWall+ always causes an notification message (not the icon).

If I switch off  ```Preferences > UI Preferences > Show notification icon```, the actual icon disappears after restarting AFWall+. But the notification message ```AFWall+\nFirewall enabled``` is just being replaced by ```AFWall+ is running\nTap for more information or to stop the app.```

This behavior didn't appear before version 3.0.0 or 3.0.1.
Is this change intended?

AFWall+: 3.0.1 (F-Droid)
OS: LineageOS 14.1-20180808-NIGHTLY
Device: Fairphone 2

**Comment by ukanth** [comment]
It's an Android notification introduced in Oreo. Starting 3.x afwall requires to run in background in order to listen the connectivity change.

**Comment by alien2003** [comment]
I have this issue on Nougat, not Oreo. How can I disable it?
