### ISSUE TITLE
Disable background service when active rules are disabled

### ISSUE THREAD

**Issue by zroug** [ukanth/afwall#894]
If I understand it correctly the background service is there to listen for connectivity changes. Is it necessary to listen for connectivity changes when active rules are disabled? If not, could one disable the background service when active rules are disabled? That would hide the Android Oreo permanent notification.

**Comment by ukanth** [comment]
Background services is not just for connectivity. It also register broadcast of app added/removed implicitly. I might integrate other services like log and root shell service as well.

**Comment by zroug** [comment]
I understand
