### ISSUE TITLE
Can't download apps with Yalp/Aurora Store

### ISSUE THREAD

**Issue by dgtn-va** [ukanth/afwall#896]
Hi,

I can't download apps with Yalp/Aurora Store however these two stores are granted in AFWall.
When download starting, an error message occurs: 

> AFWall+ denied access to Download Manager for package

Connection to the Yalp (anonymous) account is also capricious: works once in three.
I've no issue with all my others apps and I did't have much issue before reflash ROM on my two smarphones. I've tried on several days apart and on two versions of the ROM.

![screenshot_afwall _20181104-113423](https://user-images.githubusercontent.com/43678844/48023820-241efd00-e13f-11e8-9376-e50a2de176d2.png)
![screenshot_afwall _20181104-113428](https://user-images.githubusercontent.com/43678844/48023821-241efd00-e13f-11e8-82eb-3cd14c84e0da.png)
![screenshot_afwall _20181104-113441](https://user-images.githubusercontent.com/43678844/48023823-24b79380-e13f-11e8-9920-d32b3308bc21.png)
![screenshot_aurora_store_20181024-195130](https://user-images.githubusercontent.com/43678844/48023824-24b79380-e13f-11e8-8428-5387f0819165.png)
![screenshot_aurora_store_20181104-155531](https://user-images.githubusercontent.com/43678844/48023825-24b79380-e13f-11e8-9b6c-05f294c3507a.png)
![screenshot_yalp_store_20181105-195210](https://user-images.githubusercontent.com/43678844/48023826-25502a00-e13f-11e8-8d63-ecacc6e98826.png)
![screenshot_yalp_store_20181105-195236](https://user-images.githubusercontent.com/43678844/48023827-25502a00-e13f-11e8-97fd-39a99c4b0225.png)

Yalp Store v0.45 + v0.43: https://f-droid.org/en/packages/com.github.yeriomin.yalpstore/
Aurora Store v2.0.5 + v2.0.3: https://f-droid.org/fr/packages/com.dragons.aurora/
F-Droid AFWall+ v3.0.1 + v3.0.0 + v2.9.9
Xposed v90.1 beta 3 (SDK27), via Magisk v17.1
Xiaomi Redmi Note 5 Pro (whyred)
- RR-O-v6.1.0-20180827-whyred-Official (Android 8.1.0)
- RR-O-v6.2.0-20180911-whyred-Final (Android 8.1.0)

Xiaomi Redmi 3S Pro (land)
- RR-O-v6.1.0-20180816-land-Official (Android 8.1.0)
- RR-O-v6.2.0-20180913-land-Final (Android 8.1.0)

**Comment by ukanth** [comment]
Disable xposed plugin. It has bugs with 3.xx versions.

**Comment by bonbonboi** [comment]
> Disable xposed plugin. It has bugs with 3.xx versions.

Xposed module will prevent built-in Download Manager leaks even if afwall is disabled but once its rule set to allow in afwall then everything will work as expected. I've Xposed module enabled and yalp store works...

**Comment by takiainen** [comment]
I have had this issue as well for several months! I thought it's a Yalp store bug, until today, when Afwall failed to apply IPtables rules and i had to uninstall it. After which Yalp store started downloading normally.

**Comment by nutpantz** [comment]
Same issue with me, if I disable xposed module and reboot it works fine. For me it blocks yalp and xposed installer. 
I've tried every possible configuring

**Comment by awsms** [comment]
> > Disable xposed plugin. It has bugs with 3.xx versions.
> 
> Xposed module will prevent built-in Download Manager leaks even if afwall is disabled but once its rule set to allow in afwall then everything will work as expected. I've Xposed module enabled and yalp store works...

Didn't work, had to disable the xposed module.

**Comment by takiainen** [comment]
I don't use xposed at all. Only way to download via Yalpstore is to turn off Afwall and flush iptables rules.
