### ISSUE TITLE
Suggest: Both Allow AND Block checkbox states.

### ISSUE THREAD

**Issue by a-raccoon** [ukanth/afwall#897]
Currently we can only specify apps to Allow or apps to Block, but not both. You can set up one of the two states before making your selections, but you cannot maintain two sets of selections.

I have three types of apps on my devices. Apps I do Trust and Want to have consistent use of the Internet.  Apps I neither necessarily trust or desire to have regular Internet access. And apps I absolutely Never want to lick the Internet ever, not even once, because they will download adds or steal my contacts if given the chance.

I cannot reasonably disable AFwall+ for this reason (the third group), but sometimes it is necessary to be more generous and let all system apps go through to figure out why something isn't synching or working properly, to narrow down what exactly needs network access. I have to first uninstall all UnTrustworthy apps before I let the firewall down temporarily.

I want to be able to switch into Block Only X mode and have those evil apps checkmarked without having to first clear all my existing checkmarks -- and lose my settings.

**Comment by ukanth** [comment]
You can use profiles.
