### ISSUE TITLE
3.0.1 - App Drawer Notification Icon Dot Doesn't Disappear

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#898]
In the latest 3.0.x versions the App Drawer Notification Icon Dot hasn't been Disappearing.

Nothing seems to make it go away, other then simply disabling it.

As long as it's enabled the Dot always appears on the icon.

Hmm

**Comment by ukanth** [comment]
You should be able to disable it using notification group. Which version of Android you are using ?

**Comment by 0pLuS0** [comment]
Oreo 8.1.0

Yes I mentioned Disabling it, this I have already done.

I've been trying to figure out what is it a Notification for?

Disabling it seems to be counter productive, when there's a nice feature to use, well I'd like to have the Notifications.

By the way, once such NOTIFICATION any firewall should offer is to be alerted on Blocks/Deny on incoming requests, and to be able to also see what these requests were, what was blocked, IP addresses, apps, etc... Since this is an iptables Front-End, it should have this ability...

Knowing what's attacking at you is very important, especially if there is something/someone that is persistent in attacks/attacking...

In Linux I use Shorewall, maybe you know it?

http://shorewall.net/

It's an iptables front-end, and I have it set up to log any incoming requests I block/deny and of course the ability to look at these logs.

If AFWall+ doesn't have the ability to show us what we block/deny or allow in a log, PLEASE make this feature!

THANKS

**Comment by 0pLuS0** [comment]
Oreo 8.1.0

Yes I mentioned Disabling it, this I have already done.

I've been trying to figure out what is it a Notification for?

Disabling it seems to be counter productive, when there's a nice feature to use, well I'd like to have the Notifications.

By the way, one such NOTIFICATION any firewall should offer is to be alerted on Blocks/Deny on incoming requests, and to be able to also see what these requests were, what was blocked, IP addresses, apps, etc... Since this is an iptables Front-End, it should have this ability...

Knowing what's attacking at you is very important, especially if there is something/someone that is persistent in attacks/attacking that are ongoing... Regardless, I like to know what's going on, always!

In Linux I use Shorewall, maybe you know it?

http://shorewall.net/

It's an iptables front-end, and I have it set up to log any incoming requests I block/deny and of course the ability to look at these logs.

If AFWall+ doesn't have the ability to show us what we block/deny or allow in a log, PLEASE make this feature!

THANKS

**Comment by Rikests** [comment]
Hey, I have also noticed this notification and status bar disc appearing in the new version. It must be a new feature implemented. A switch to turn it off in the settings would be nice, because I dont want to turn off all afwall notifications, only this one, because it serves no purpose. Im on android 7.1.2
Here is a screenshot. https://files.fm/u/bw3fnx8x#/

**Comment by 0pLuS0** [comment]
@Rikests looks like you're talking about the ```Overhead Notification```, I'm talking about the ```App Drawer Icon Notification```

**Comment by vitaliis** [comment]
I have the same problem with version 3.0.1. Using LineageOS 14.1 (Android 7.1.2).

Once it is enabled, it persists on active notifications.
Enabling/disabling this setting in "Preferences" > "UI Preferences" -> "Show notification icon" doesn't have any effect.

Disabling it and force stopping the application removes it. But when the application is started again it is still being displayed, although grayed out (not sure about terminology, but the ones that are in the very bottom and are not displayed when the phone is locked). Do you know what I mean?

**Comment by 0pLuS0** [comment]
@ukanth 

I know you're busy, I was hoping you might of been able to reply by now and explain what this App Drawer notification icon is for?

Thanks

**Comment by 0pLuS0** [comment]
@ukanth 

I know you're busy, I was hoping you might of been able to reply by now and explain what this App Drawer notification icon for?

![notification](https://user-images.githubusercontent.com/36190223/49053078-8327dd00-f1e6-11e8-9362-2366188069ab.jpg)




```Thanks```

**Comment by mMuck** [comment]
I want to agree with @vitaliis.  "Preferences" > "UI Preferences" -> "Show notification icon" doesn't have any effect anymore. Previous the notification could be switched off. Now (since 3.0.1) this isn't possible.
That's the original issue. (Please put feature requests in a new one.)
I think it's a bug. Thanks for re-enabling this.
