### ISSUE TITLE
Toasts keeps the screen on/phone awake

### ISSUE THREAD

**Issue by bonbonboi** [ukanth/afwall#899]
AFWall+ 3.0.1

Turn on log services -> On
- No issue (Screen will turn off as usual after x of inactivity)

Enable show toasts -> On
- A minor issue here (It keeps the screen on forever if the user forgot to press the power button)

**Comment by ukanth** [comment]
AFWall+ does not have permission to keep the device awake. It might be device specific setting when the toast are displayed it would keep the screen on. Again, I would need device details along with details like do you have xposed installed

**Comment by bonbonboi** [comment]
Redmi Note 4 (Mido) Oreo (MiracleDroid ROM) + Ethreal Kernel.
