### ISSUE TITLE
USB tethering not working unless....

### ISSUE THREAD

**Issue by DennedugazAsti** [ukanth/afwall#90]
phone: galaxy nexus
OS version: 4.21 JB
setup: USB tethering with Windows 8 pro
setup: nexus connectivity  by  wifi or by  3G = same results
setup: AFwall+ version 1.1.3
setup: AFwall+ in whitelist mode

whitelisting "applications as root" or "kernel" or any other DOES NOT work
enabling "alternate rules for ICS/JB" DOES NOT work
enabling/disabling "disable 3G rules on wired USB" DOES NOT change misbehavior (forgot to mention this on earlier post)

LOG reports this for : "ping www.google.com"

---

AppID : -1
Application Name:
Total Packets Blocked: 1
216.218.29.11(1)

---

LOG reports this for : click on a link from a 'pre-loaded' google results page

---

AppID : -1
Application Name:
Total Packets Blocked: 2
216.218.29.11(2)

---

misbehavior goes away if ( laptop gains internet connectivity: ping + web browsing)

AFwall+ disabled
OR
whitelist "all applications" in Afwall+

notice that in the log extracts that "Application Name:"   is empty...
having the FULL LOG would be very helpful

**Comment by bilbonotry** [comment]
Still the same issue on v2.6.0 on a CM13-based ROM, workaround on Linux by setting manually DNS servers. No issue with wifi tethering.
