### ISSUE TITLE
Security :: Enable FP Protection

### ISSUE THREAD

**Issue by bonbonboi** [ukanth/afwall#900]
AFWall+ 3.0.1

I cannot unlock it with FP that easily if I try to open the UI many times randomly,  unless I do this: press the power button to sleep the phone, then press the power button again to wake up the phone, enter PIN, unlock the phone, place my finger to unlock afwall, then it let me in) I have to repeat that once afwall is stopped to respond to the FP thing..

**Comment by ukanth** [comment]
Your device details please ?

**Comment by bonbonboi** [comment]
Redmi Note 4 (Mido) Oreo (MiracleDroid ROM) + Ethreal Kernel.
