### ISSUE TITLE
Tidal blocked even when whitelisted

### ISSUE THREAD

**Issue by mikekrunk** [ukanth/afwall#902]
Hi there,

I've been using the firewall for a few weeks now and generally love it. I've moved to the donate version. :)

I am having an issue with Tidal being blocked even though I whitelist it for the VPN connection type that I use for all the apps. I have tried whitelisting it for all the connection types as well, but that did not help.

I have found out in the FAQs that the Media Server has to be allowed as well so I have tried whitelisting it just for VPN and also other connection types, but this did not change anything.

The issue is strange in that Tidal CAN access internet as it is showing albums, playlists and everything else. It just cannot stream music. It can even download music so that it should be available offline, but fails to play it showing the same error message - that there is no connection (!!!).

The only workaround is to disable the firewall completely, which, of course, is not ideal.

Any help would be greatly appreciated.

**Comment by ukanth** [comment]
It might be using some specific port to stream. You need to find that port and add custom rules. App url please ?

**Comment by mikekrunk** [comment]
It's actually not only a problem with streaming. Even if I download music to my device, the app does not see any of it when the firewall is enabled. If i turn the offline mode on in tidal, none of it shows as downloaded. The app will not play any of the music I download through it (same feature as with Spotify that allows you to download music for offline use)

The link to the app: https://play.google.com/store/apps/details?id=com.aspiro.tidal

**Comment by ukanth** [comment]
Do you see anything in firewall log like kernel ?

**Comment by mikekrunk** [comment]
When I boot and then start Tidal and try playing a song and get the no connection error, I go to the logs and it lists the following: kernel, root, google play services, exchange services.

**Comment by mikekrunk** [comment]
It's sooo strange. I've just figured out which one is the offender. If I allow the root category access to the internet, it starts working again.

**Comment by ukanth** [comment]
Thanks for the confirmation. Closing this issue.
