### ISSUE TITLE
Can't open/parse apk

### ISSUE THREAD

**Issue by Ergonomicmike** [ukanth/afwall#905]
I installed 3.0.1 successfully on my Asus Zenpad tablet last week. (Lollipop.)  But when I tried to install it on my LG 15 smartphone today, (Kitkat) I got "could not parse" error at install of the apk. (Update: Same with my Nook HD+ running CM10.1, an Android 4.x variant.)

I tried the download twice, thinking perhaps a corrupted file? (Haven't tried to sideload yet.) 

I installed 2.9.9 on my LG 15 and that installed okay.

Update: I just now noticed a note a bug report on 3.0.0 that it dropped support for Android 4.x devices. Don't know if that's a statement - like, AFWall will not work on Android 4.x anymore - or a report of a bug.

If it's the former, then I suggest the statement about dropping support be moved to the Features section. (As opposed to the Bugs section.)

**Comment by ukanth** [comment]
2.9.9 is the last version supported for Kitkat. 3.x onwards supports only from Lollipop. 

Thanks.

**Comment by Ergonomicmike** [comment]
Okay, thanks. So as I said above, I suggest putting that info as a Note for versions > 3.x so that's clear.
