### ISSUE TITLE
Export option in New View

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#907]
Hello ukanth,

Old View does not show the same information as New View in 3.0.1.

Here are the steps:

1. I enable wifi, then make a connection online through various applications
2. I check the Log New View and see several applications listed
3. I switch to Old View and then I do not see everything that was listed in New View
4. What I see in Old View if I constantly switch back and forth to New View always changes

Sometimes if I switch from New View to Old View I will see all the same information, and at other times different, it's never the same. As an example, if I see 3 applications listed in New View and then switch to Old View I might see all of them, sometimes I see only 1 application, another time I switch I see 2 applications, it constantly changes.

Old View will also not show the correct amount of deny/blocks that New View does. Sometimes in New View it will say the application was denied as an example 500 times, then I look at Old View and it only shows 100 times, so the amount of deny/blocks between New & Old View is not accurate.

I also do not see any way to Export the Log with New View? 

If New View can be made to have a ```Export``` feature I say to get rid of Old View and take it out, it seems to be making more problems then what it's worth.

```Here's a screen shot of New View showing 3 applications```
![log_1](https://user-images.githubusercontent.com/36190223/49346216-d7b7d600-f686-11e8-9973-18cf39d191f0.jpg)

```Here I switched to Old View and now it only shows 1 application```
![log_2](https://user-images.githubusercontent.com/36190223/49346220-e8684c00-f686-11e8-8eef-a25ef38d4c18.jpg)

**Comment by ukanth** [comment]
New view is only for donate and can't get rid of it. I will add export option to new view.

**Comment by 0pLuS0** [comment]
@ukanth

Hi, I meant getting rid of the Old View, it doesn't work properly.

**Comment by ukanth** [comment]
Then I will fix the old view. I can't get rid of it.

**Comment by 0pLuS0** [comment]
@ukanth ahh ok, sounds great!

It actually looks really nice.

I know you have Priorites for certain things, but Logs are very important, and with no way to Export from the New, this only leaves the Old which doesn't work.

So I hope you will consider changing this Tag and place it on a High Priority to fix as soon as possible.

Thanks

P.S. Keep up the great work!
