### ISSUE TITLE
3.0.1 - (Logs) Currently Cannot Resolve Host

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#908]
Hello ukanth,

Using 3.0.1 I have AFWall+ allowed for WiFi, LAN, Mobile, and in the logs if I try to Resolve Destination I can't, I get this reply;

```Currently can not resolve Host for IP```

However I can successfully ping the destination, so not sure why I can't Resolve it?

I've attached a ```LOGCAT```

[logcat.txt](https://github.com/ukanth/afwall/files/2637560/logcat.txt)

Thanks

**Comment by 0pLuS0** [comment]
Also using the Donate Key the ```Show hostname``` option does not work.

All the ```Host``` sections are empty in the logs, see the screen shot.

![host](https://user-images.githubusercontent.com/36190223/49412349-02c42780-f764-11e8-9dfc-47bbeafdc637.jpg)

**Comment by ukanth** [comment]
Have you whitelisted AFWall itself to connect to internet. If not it will not be able to resolve hostname.

**Comment by 0pLuS0** [comment]
@ukanth

Yes, I mentioned I allowed it for everything; ```WiFi, LAN, Mobile```

**Comment by gadgetguy08** [comment]
Having the same issue.  Running Oreo 8.1.  Do not have the issue on my device running Nougat (7.1.2).

**Comment by Abu-Khulzat** [comment]
Same issue here. Oneplus 6T OS 9.0.7

**Comment by breversa** [comment]
Same here :
AFwall+ 3.0.1
LG G4 H815
MicroG for LineageOS 14.1

**Comment by gadgetguy08** [comment]
When I attempt to resolve manually, I get this message (always just ms):

Currently can not resolve Host for IP(151.101.0.133), timeout: 7 ms

**Comment by ukanth** [comment]
Fixed, will be available in next version.
