### ISSUE TITLE
error applying iptables rules

### ISSUE THREAD

**Issue by takiainen** [ukanth/afwall#909]
I'm using CarbomOreo 8.1. on Oneplus one. I cannot enable Afwall due to "error applying Iptables rules". I also cannot enable logging, it says something like "target file is empty". I have a rooted device and have given storage permission for Afwall. 

I had similar issue with some Pie ROMs aswell.

**Comment by ukanth** [comment]
Please attach Menu > Show rules > export to SDcard  and attach it here.
