### ISSUE TITLE
Stealth mode on pattern - Can't Uncheck

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#910]
I noticed in 3.0.1 when I check ```Stealth mode on pattern```, it can't be unchecked.

I turned the ```Enable Protection``` to none, then tried the pattern again, still can't get the check mark to remove.

Please see the screen shot showing ```Stealth mode on pattern``` with the check mark.

Thanks

![stealth](https://user-images.githubusercontent.com/36190223/49412658-23d94800-f765-11e8-90a8-3540bd71b542.jpg)

**Comment by ukanth** [comment]
It works when you use "pattern" as protection. It any other option it will be disabled.

**Comment by 0pLuS0** [comment]
@ukanth

I was trying to explain that if at some point in time I want to change this, I can't. ```Stealth mode on pattern``` will not uncheck.

So I if I didn't want to use Stealth, it's stuck and always stays this way.

I was asking to fix this so you can uncheck it, sorry I thought I made this clear.

Thanks

**Comment by ukanth** [comment]
As long as functionality is not broken, then it just UI change. I would rather leave it as it is.

**Comment by 0pLuS0** [comment]
@ukanth function is broken in the fact that if someone is simply trying out the Stealth Feature, then later decides to reveret back, you can't it's broke, you can't uncheck and revert back to not using this.

I hope you'll fix it...

Don't leave things like this in the UI, people will start to consider AFWall+ as not stable, when they see things not working as they should, meaning you should be able to check and uncheck something, this should be Basic UI Function.

I know this, otherwise I wouldn't say it, and in the long run it only helps you to have a UI that works correct and hopefully makes good support for you, money too... :)

Thanks

**Comment by ukanth** [comment]
I have been supporting AFWall+ since 2012 which is long for any software and mostly free/open.Also I don't get enough money through AFWall+ and mostly I'm the sole contributor (except few contributions done by community). I need to trade-off on certain elements in order to keep going. 

Also I don't have any statistics on how many users are using paid/donate vs Free because I don't like being tracked myself. 

So, I would love to fix everything, but simply not possible for me to do it alone :)

**Comment by 0pLuS0** [comment]
@ukanth I hear you, and I truly appreciate all the work, AFWall+ is great!

If I can suggest something at least change the wording to inform the end-user like this;

```Stealth mode pattern - once enabled can't be disabled```

**Comment by ukanth** [comment]
It can be disabled/enabled when you select "pattern" as your protection again. It only enables you to change when the protection type is pattern

**Comment by 0pLuS0** [comment]
@ukanth ok, it appears to be working, and I thought I tested it with Pattern and trying to uncheck it and it wouldn't work... hmm

Thanks
