### ISSUE TITLE
Donate Key - "Use Device Security Protection" Not Working?

### ISSUE THREAD

**Issue by 0pLuS0** [ukanth/afwall#911]
I have AFWall+Unlocker-OS.apk for the Donate key,  I'm using with 3.0.1. When I look in the Security Preferences for ```Use Device Security Protection``` I can't check it, the check mark box appears lighter/grayed out, when I don't have the option to use it, and it does nothing...

Please see the screen shot...

![protection](https://user-images.githubusercontent.com/36190223/49413614-68b2ae00-f768-11e8-8d0a-b924fb1d1f7c.jpg)

**Comment by ukanth** [comment]
It happens when it's not able to find the way (pin/password/fingerprint) as device protection. What does your device use ?

**Comment by 0pLuS0** [comment]
@ukanth

Ok not sure what I was thinking when I posted this, my bad...

To be clear here, if a pin/password/fingerprint was set on the phone, then AFWall+ is using this?

Thanks

**Comment by ukanth** [comment]
Yes. You are right.

**Comment by 0pLuS0** [comment]
Ok sorry for the post, my mistake... :(

**Comment by breversa** [comment]
Glad I found this issue, I was about to ask the same thing. :-)

Why not add it to the FAQ ?

**Comment by OdinVex** [comment]
Just found this issue, glad to know it just needs some form of screen-lock. Might need to add to FAQ, or better yet directly into AFWall.
