### ISSUE TITLE
Firewall Allow not working again....

### ISSUE THREAD

**Issue by cmh714** [ukanth/afwall#912]
Firewall Allow is not working again. I had to swap everything and Deny in order for it to work again. This was addressed for some time now, but seems to have returned. At least for me.

**Comment by ukanth** [comment]
Please export rules from menu > Show rules > export and attach it here when it's not working.

**Comment by cmh714** [comment]
my apologies that I cannot assist any further at this time.....my digitizer seems to have bit the dust...
