### ISSUE TITLE
MIUI - Support for Wifi-Assistant and Traffic Mode

### ISSUE THREAD

**Issue by gjf** [ukanth/afwall#913]
For some reason rules are applied in the way that leads to all process cannot connect to the internet.

Disabling/enabling firewall as well as re-applying does not help.

The only solution is to delete all iptables rules and then apply rules once again.

Strange, because I cannot see any major difference in iptables rules after that, but anyway - Internet access apeears.

Iptables logs are here: https://www114.zippyshare.com/v/3EFei7UN/file.html

**Comment by ukanth** [comment]
Something not right the working/non working logs. I don't see any issue on notworking log. There might be something else happening on the device ( could be something related to MIUI )

**Comment by gjf** [comment]
The issue is caused by conflict between AFwall and new MIUI 10 feature called "Wi-Fi Assistant" and/or "Traffic mode".
Disabling them both makes AFWall working properly.
It's a pity it is not possible to use modern firmware features together with firewall.
Could it be solved?

**Comment by ukanth** [comment]
No one has reported issues on this. Hence closing this.
