### ISSUE TITLE
AFwall+ don't get root with Magisk 18.0

### ISSUE THREAD

**Issue by blap** [ukanth/afwall#915]
AFwall+ don't get root with Magisk 18.0

**Comment by ukanth** [comment]
I'm using it with 18.0, try clean install of afwall and see if that works.

**Comment by blap** [comment]
Sounds good and worked.
But I needed to disable the module in Xposed after clean install, reboot,
activate the module and reboot again to works.
Thanks.

Em ter, 11 de dez de 2018 09:24, robo-mo <notifications@github.com escreveu:
