### ISSUE TITLE
Feature Request: per-app option to block traffic on all interfaces

### ISSUE THREAD

**Issue by Superluminar** [ukanth/afwall#93]
Some apps just shouldn't communicate, regardless over which interface. If a device has additional interfaces, like bluetooth PAN or ethernet, they are not controlled by AFWall + nor any other Firewall-App I know. So this would be a nice, outstanding feature ;)

I suggest a fourth checkbox for every app to block communication by the afwall-chain on all interfaces.

**Comment by ukanth** [comment]
Duplicate of #15
