### ISSUE TITLE
"Xposed related fixes" crashing picoTTS

### ISSUE THREAD

**Issue by tbart** [ukanth/afwall#930]
I am not really sure if this is the correct place to report this, but if "Xposed related fixes" is part of afwall this is the correct place ;-)

If I enable this module, picoTTS crashes on a lineageos 15.1 driven oneplus3.

Steps to reproduce:
- Install lineageos 15.1 on a oneplus3 (maybe any other 15.1 device would also work?)
- Install Xposed 90-beta3 (latest as of this writing)
- Enable "Xposed related fixes for Afwall+" in the modules
- Reboot
- Navigate to System settings - Accessibility - Text to speech output
- Hit play
- Get a toast: "picoTTS has crashed"; This happens whenever an application wants to use text to speech, e.g. osmAND for navigation which is what makes this bug relevant here.

Here is the tombstone it leaves behind:
https://gist.github.com/tbart/50effed321df634b14336baf896a0c51

If this is the wrong place to report this, please advise where to so, if possible, and forgive me for not finding it in the first place.

Thanks!
btw: Keep up the good work, afwall is a great tool!

**Comment by ukanth** [comment]
It has nothing to do with PicoTTS, the module might be blocking picotts to download during bootup.
