### ISSUE TITLE
Specify additional LAN networks.

### ISSUE THREAD

**Issue by sathlan** [ukanth/afwall#932]
Hi,

my ip range for wifi is different from the ip range where my local servers are running.

That makes the wifi-lan rules useless to me as only the network added to that rule is the one to which the wifi is attached.  That mean that I have to give "wan" access to all applications that need to access my local services.

Basically I would need to be able to have rules that like this

```
afwall-wifi-lan all -- * * 0.0.0.0/0 192.168.10.0/24  # wifi lan, automatically created.
afwall-wifi-lan all -- * * 0.0.0.0/0 192.168.20.0/24  # servers lan, could be specified by the user.
```

I'm aware of #436, but for my use case, a simple text entry that would enable the user to add ip ranges to the LAN definition would be enough.

Or a example userscript could be enough, but currently I'm not sure how to add that rule correctly.

Regards,

**Comment by ukanth** [comment]
This can be added via custom rules. Hence closing this.
