### ISSUE TITLE
other apps crash

### ISSUE THREAD

**Issue by qweiniq** [ukanth/afwall#934]
Some other apps crash immediately after opening or if you want to open something in the app (especially GMX.de, web.de, Flatastic, Pinterest).
I tested it with a new installation (complete ROM). Flatastic works fine, once the firewall is activated, the app crashes immediately.
The big problem, deinstalling the firewall does not fix the problem, also not reinstalling Flatastic.
Wipe cache for hole System does not help.
The entire system is not repairable destroyed.
Remember, its a clean install of System! (LineageOS 15 with microG and Magisk)
(this morning my wife said some apps does not work, same problem, but i have install the system on 15th of Dezember ?? and the problem is now ??,  (LineageOS 16  with microG and Magisk)
possibly there is a connection of LineageOS 16  with microG and Magisk or an update from this.
Other Firewall works, i use an old app (com.jtschohl.andoidfirewall) - only tested this firewall...

**Comment by ukanth** [comment]
Allow all "Core" apps and test it. Also if you have trouble with "allow selected" mode, try switching to "block selected" mode. 
AFWall+ does not crash the apps if you configured it the above way. Thanks.

**Comment by qweiniq** [comment]
thanks for helping, i tested it now on a clean install, now i cant reproduce the error...
there is a possibility that the error has another reason
