### ISSUE TITLE
Takes too long to apply rules

### ISSUE THREAD

**Issue by devsk** [ukanth/afwall#938]
This issue is an attempt to understand if there are ways to speed applying of the rules. Currently, its too long (1min). I am afraid we are leaking packets because of that both at startup and when we apply runtime. That leak may be enough for some apps to "steal" user info.

One idea: make it multi-threaded. Most phones have 8 cores these days. We should be able to use all of them. If we want to keep symmetric, we can use 4 of them.

Dividing the iptables rules in such a way that we can apply 4 sets of them at the same time should potentially give upto 4x speed up. Is there top-heavy skew in the rules? as in one chain has 1000 rules and another has only 10?

**Comment by ukanth** [comment]
Multi thread can't solve this problem as iptables does not support multi thread. It locks iptables if some other app/process uses the same.

It's a limitation with iptables. I did improve the speed of ipv4 and ipv6 (independent iptables) to apply rules in parallel.

One other way is to generate shell script file with all the rules and execute at once. But there will be isses with file IO.

**Comment by devsk** [comment]
> But there will be isses with file IO.

Can we not create the file in ramfs itself? Like in /dev/.iptables if we don't want to create a separate location for iptables by mounting / as 'rw'. It will temporarily eat a couple of MB of RAM but that's OK. If generating the script and applying the rules is significantly faster, I think we should explore this.

**Comment by ukanth** [comment]
It was like that from early days (droidwall). But the issue is if individual rules failes, AFWall+ will try to reapply the same rule for atleast 10 times before throw an error. Also, iptables been used heavily by Google/Android itself. So AFWall+ needs to be always on top of these chains.

it's a trade of stability vs performance. I choose stability over performance.
