### ISSUE TITLE
AFWall+ Can't Find XPrivacyLua App - Developed by M66B

### ISSUE THREAD

**Issue by bugnot** [ukanth/afwall#960]
Firewall can't find XPrivacyLua app developed by M66B!
Can anyone help about this? I am really surprised to see this.

**Comment by bugnot** [comment]
What sorcery is this @M66B?

**Comment by ukanth** [comment]
AFWall+ lists applications with INTERNET permission. XPrivacyLua does not require internet permission. So it's not listed in AFWall+

**Comment by bugnot** [comment]
Thank you so much for that information!
