### ISSUE TITLE
Application stuck after first try (checking root access)

### ISSUE THREAD

**Issue by TjrGithub** [ukanth/afwall#970]
The first time I try to apply firewall rules, I get the success toast and apps are (un)blocked correctly. The next time I try, Afwall gets stuck "requesting root access". The difference to https://github.com/ukanth/afwall/issues/479 is that I can usually apply firewall rules a few times before the bug gets triggered. But the screenshot is the same.

Running AFWall 3.1.0 from FDroid on a freshly installed LineageOS 15.1 on Xiaomi Redmi Note 4 with addon_su. (and Xposed flashed but not yet configured nor active)

https://download.lineage.microg.org/mido/lineage-15.1-20190327-microG-mido.zip

**Comment by TjrGithub** [comment]
A logcat (now with xposed and xprivacylua): 
I repeatedly applied the firewall rules while logcat was running. The following starts with right before the "hanging" apply-firewall-rules-tap, and it ends with me force-killing AFWall.


[04-02 12:40:24.340 29342:30985 I/AFWall]
Using applySaved4IptablesRules

[04-02 12:40:24.340 29342:30986 I/AFWall]
Using applySavedIp6tablesRules

[04-02 12:40:24.340 29342:30985 I/AFWall]
Received cmds: #127

[04-02 12:40:24.340 29342:30986 I/AFWall]
Received cmds: #127

[04-02 12:40:24.340 29342:30985 I/AFWall]
Start processing next state

[04-02 12:40:24.340 29342:30986 I/AFWall]
Start processing next state

[04-02 12:40:24.567 29342:29381 D/OpenGLRenderer]
endAllActiveAnimators on 0x75c8118400 (MenuPopupWindow$MenuDropDownListView) with handle 0x75d35ade20

[04-02 12:45:33.025 29342:29342 I/AFWall]
Selected Profile: AFWallPrefs

[04-02 12:45:33.049 533:533 D/SurfaceFlinger]
duplicate layer name: changing dev.ukanth.ufirewall/dev.ukanth.ufirewall.MainActivity to dev.ukanth.ufirewall/dev.ukanth.ufirewall.MainActivity#1


[04-02 12:48:20.225 29342:29342 I/AFWall]
Selected Profile: AFWallPrefs

[04-02 12:48:20.244 533:533 D/SurfaceFlinger]
duplicate layer name: changing dev.ukanth.ufirewall/dev.ukanth.ufirewall.MainActivity to dev.ukanth.ufirewall/dev.ukanth.ufirewall.MainActivity#1


[04-02 12:48:28.262 1528:1597 I/ActivityManager]
Force stopping dev.ukanth.ufirewall appid=10091 user=0: from pid 1528

[04-02 12:48:28.262 1528:1597 I/ActivityManager]
Killing 29342:dev.ukanth.ufirewall/u0a91 (adj 0): stop dev.ukanth.ufirewall

[04-02 12:48:28.263 1528:1597 W/ActivityManager]
Scheduling restart of crashed service dev.ukanth.ufirewall/.service.RootShellService in 1000ms

**Comment by dor1eo** [comment]
This is a big **** problem and very annoying at best.
- I have noticed this since update 3.1.0 - Random first times AFWall gets stuck on "Checking root access"
- When searching for the app in the search bar as well, and checking a couple boxes, applying rules from there gets stuck on "Checking root access"
- I have to clear the app from recent apps list and do it again and then it will pick it up.  This can happen 2 - 3 times before it picks up root.

Using Android 9.0 Pie (LineageOS) with latest magisk installed.
Ive also tested this on a fresh ROM of LineageOS 14.1

Would a developer care to respond?

PS: this didnt happen on the previous version before 3.1.0

**Comment by dor1eo** [comment]
Possibly became a bug after this commit: https://github.com/ukanth/afwall/commit/676153c1ba5474dd8808adf6b1a20773989903f9 or this https://github.com/ukanth/afwall/commit/f37fea2df0f3d2d0175f4b899fe640c2dd2c5546

**Comment by Bleep5143** [comment]
I'm also experiencing this issue.

- Android 9
- OnePlus 5T (A5010)
- OxygenOS 9.0.4
- Magisk v19.0 (19000)

After a fresh reboot enabling the firewall doesn't seem to have any issues. But if I disable and attempt to re-enable it gets stuck at "checking root access"

It appears I can work around this issue by simply clearing AFWall+ from my recent apps and then re-opening it. The firewall seems to work ok despite the appearance of freezing or getting stuck. I've tested applying updated rules after experiencing this and sometimes the applying rules dialog appears as expected, others it only displays the 'checking root' message, but the rules seem to get applied either way.

I don't have any logcats to share but planned to do some more digging later.

**Comment by TjrGithub** [comment]
After a lot of use, it seems this issue strikes at random. Sometimes the first try is affected, too. Sometimes you have to press apply a lot of times until you get the firewall rules applied. Force-killing AFWall+ usually doesn't help.

**Comment by ukanth** [comment]
i will look into it this week. Thanks.

**Comment by Bleep5143** [comment]
I'd like to report that this issue seems to have subsided for me. When applying rules there is an occasional 'lag' but it doesn't seem to last very long now and is definitely more infrequent than before.

**Comment by CircuitSerialKiller** [comment]
I'm getting the same issue here with 3.1.0. Downgrading to 3.0.4 resolved the issue. Nothing relevant showing in the logcat.
Samsung S8 Exynos, stock Oreo ROM brand new install
SuperSU 2.82 SR5
Also tried with Magisk 19.2, though SuperSU was having this problem with Magisk, as well as another intermittent issues with acquiring root access.

**Comment by TjrGithub** [comment]
I also get the occasional lag, like tracerfett. But the issue persists for me.

**Comment by AlphaDE** [comment]
Same problem here, AFWall+ runs fine and applies rules at startup, applying changes results in stuck in root check although Magisk toasts that root rights have been granted.
OP 6, OOS 9.05, Magisk 19.2

**Comment by openffchrome** [comment]
I get it a lot as well since i'm on pie (not sure if related) :s fail to detect root, hanging forever until killed (swipe up in app switcher) and reopened, sometimes it fails multiples times in a row, sometimes it hang a little and then applies rules.

**Comment by AlphaDE** [comment]
Do you plan to release that fix into a beta?

**Comment by ukanth** [comment]
Yes, this week mostly.

**Comment by AlphaDE** [comment]
The just released version crashes at start

**Comment by ukanth** [comment]
Please provide logcat. I will have a look

**Comment by AlphaDE** [comment]
Will do, restored the previous from TiB and now have to wait until PlayStore notices that and lets me install again.

**Comment by AlphaDE** [comment]
Debug message sent, logcat attached. Btw restore of the app via TiB fails
[Log_2019-07-03_08-30-12.txt](https://github.com/ukanth/afwall/files/3353558/Log_2019-07-03_08-30-12.txt)

**Comment by ukanth** [comment]
Could you please try this ?

https://drive.google.com/open?id=1k9mWdSSSHd1KGylyh9BDnLoK1XSsBnA8

**Comment by AlphaDE** [comment]
Did not solve the problem, finger print check comes and force closure thereafter. 
[Log_2019-07-03_13-55-40.txt](https://github.com/ukanth/afwall/files/3356269/Log_2019-07-03_13-55-40.txt)

**Comment by AlphaDE** [comment]
After trouble with installing the apk and the previous versions, I had to install it from scratch.. and then the beta doesn't crash anymore...

**Comment by chrcoluk** [comment]
Got the issue here, but I have to ask is afwall abandonware? given it was reported 6 months ago and isnt fixed.

Oneplus6
magisk 19.4
OOS 9.0.6

the beta has no settings carried over, how do I put it over the existing location so it preserves everything?

**Comment by selurvedu** [comment]
Same here.

@ukanth, do you have any roadmap for an upcoming 3.2.0 release? I would be very grateful for a usable fix for this problem.
If the answer is "no", is it worth to try a beta version? Is it stable enough for everyday use? I am using the whitelist mode if it matters.

**Comment by eaphooz** [comment]
AFWall 3.2.0 exhibits same behavior but 3.1.0 works as expected for now.

**Comment by est61** [comment]
This is solved in 3.2.0.  No longer hangs. thanks for the fix.
