### ISSUE TITLE
all-double or all-triple entries

### ISSUE THREAD

**Issue by TjrGithub** [ukanth/afwall#971]
Without any apparent pattern, sometimes in the list of blockable apps, all apps appear twice or three times.

Screenshot: https://imgur.com/a/u1l2MDf

Running AFWall 3.1.0 from FDroid with pro companion app on a freshly installed LineageOS 15.1 on Xiaomi Redmi Note 4 with addon_su. Xposed and XprivacyLua are installed but do not restrict AFWall+.

https://download.lineage.microg.org/mido/lineage-15.1-20190327-microG-mido.zip

**Comment by AlphaDE** [comment]
Same problem here, Oneplus 6, OOS 9.0.5, Magisk 19.1, Island app (separate profile to contain certain apps, but there is only Whatsapp which is not in the main profile).

**Comment by Klimmbimmel** [comment]
Same here, but I have never seen triples, only doubles.

Version 3.1.0 from F-Droid
LineageOS 14.1 on Honor 5X, SuperSU

(experienced also in earlier versions, 1 year ago or longer)

Edit: funny... I was browsing through all my installed apps (searching for the Root app) and removed 2 non-used apps. Now, **no duplicates** are listed anymore. I also have the feeling the duplicates appear after installing new apps.

Edit2: Unlike in #871 in my case all listed item is shown twice (not only user apps like in 871)

**Comment by DogDay7** [comment]
SOLUTION: I had the same problem too. I don't know what causes this problem but I found a really easy fix to remove the multiple listing of same apps on the firewall permission filter page. All u need to do is go to top of list and then swipe down on the screen. This refreshes the page. A pop-up says 'Retrieving installed apps". That removed the multiple listing if apps fast and easy. For now this is the solution I use. Hope this helps. Good Luck !
