### ISSUE TITLE
block specific ip address and domain names

### ISSUE THREAD

**Issue by carlos444** [ukanth/afwall#976]
this is a little far away from the app's function. but I think android phone really need a iptables based web/browser firewall, to block ad and ad websites. there are a lot of android apps using hosts redirect to block ads, but the effect was not good, a lot of https ad websites can not be block, and popup to interrupt the user action.
we don't need redirect the ad to 127.0.0.1 or 0.0.0.0, we just need block the data stream from these stupid websites, and iptables will doing it great.
At last, I looked for the app almost every market and websites,but I can not find one.
can you do that, help us?｡◕‿◕｡

**Comment by angela-d** [comment]
You can use a hosts file on Android if you're rooted.

[This one](https://github.com/angela-d/autohosts) has Firefox telemetry built in, too; though there is no Android app so you'll have to get the hosts file locally and adb it to `/etc/hosts` on your phone.

[uBlock Origin Adblocker](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) works on Firefox for Android, too (if you're using Firefox)

If you don't want to mess with any of the above, [DNS 66](https://f-droid.org/en/packages/org.jak_linux.dns66/) can handle hosts + custom DNS options.

**Comment by carlos444** [comment]
thanks
