### ISSUE TITLE
Linux Kernel [-11] being blocked although it's allowed in settings

### ISSUE THREAD

**Issue by anmith** [ukanth/afwall#981]
I'm using AFWall+ (F-Droid version) on LineageOS 16.

Although I allowed the kernel in the network settings to use both mobile and WiFi connections, the protocol shows it as being blocked - see attached screenshots.

![settings](https://user-images.githubusercontent.com/3750050/57723843-d523c880-7689-11e9-987a-8bda452724d9.png)

![protocol](https://user-images.githubusercontent.com/3750050/57723859-dd7c0380-7689-11e9-9603-6811677a631e.png)

**Comment by d3cim** [comment]
same on LOS16 with kernel and root apps. I need to enable anyapp to see apps work. Even if I enable all app manually doesn't work. Logs continue to show me blocked connection to app that I enabled

**Comment by ghost** [comment]
Same on OxygenOS

**Comment by gab854** [comment]
Same here on stock Moto G7 Pie

**Comment by ni-vo** [comment]
Same on Pixel 3

**Comment by lemmy04** [comment]
same on Magisk-rooted (stock) Android 9 on Samsung Tab S5e

**Comment by lemmy04** [comment]
still getting this, mostly after a reboot, only on android 9.

**Comment by raylon00** [comment]
I have the same issue on OnePlus 6t Running Android 9.0
I cannot connect to wifi or mobile network without either disabling the firewall or by allowing all apps Or all root apps.

**Comment by wwwdesign** [comment]
Same here on Xperia Xz.
Any workaround available ("Allow All" is not a workaround, IT just turns off the firewall😉) or fix in sight?

**Comment by AdamPS** [comment]
I would contribute towards a bounty for fixing this bug.

It's a shame as this bug make this excellent app almost unusable - if I have the firewall on then certain features of my phone are impossible to use.

**Comment by ukanth** [comment]
Duplicate/Related to #1002
