### ISSUE TITLE
Instant Crash/FC on app start with 3.2.0-BETA

### ISSUE THREAD

**Issue by yoshi7** [ukanth/afwall#989]
I installed the 3.2.0-BETA Update from the Play Store. Since then i cannot start AFWall anymore. The app is closed instantly (granting root access is still working, but nothing more). There is a permanent notification message "Applying iptables rules" though.

Google Pixel 3
Android 9 Stock (Security Patch May)
AFWall+ Version 3.2.0-BETA
Magisk 19.3
Magisk Manager 7.3.2

I captured a logcat (via MatLog).

[2019-07-03-15-36-22.txt](https://github.com/ukanth/afwall/files/3355220/2019-07-03-15-36-22.txt)

**Comment by ukanth** [comment]
Could you please try this ? 

<Removed Link>

**Comment by yoshi7** [comment]
Unfortunately, the same behavior.

[2019-07-03-17-11-07.txt](https://github.com/ukanth/afwall/files/3355600/2019-07-03-17-11-07.txt)

**Comment by ukanth** [comment]
Strangely, logcat does not have enough information. What is your device configuration ? Can you do a clean install and disable Log service ?

I have added possible fix in this build. Could you please check this ?

<removed>

**Comment by yoshi7** [comment]
This build is also not working, but after a new clean install the app (3.2.0-BETA in the Play Store) is working again.

I have made a Titanium Backup (App+Data) of the not working one, if you want to debug further.

Update:
Ok, it was just working for a few minutes, the fc/crash is back.
I will do a clean install with your 2nd build and take a look if this is working (longer).

**Comment by yoshi7** [comment]
I found a way to provoke the fc/crash behavior (but don't know if it something different as my main problem).
1. Clean install of your 2nd build
2. Enabled Firewall
3. Deactivate "Show notification icon" under Preferences -> UI Preferences
4. Force stop "AFWall" under Android App-Settings
5. Start AFWall

**Comment by ukanth** [comment]
Yes, I'm able to reproduce it. I have fixed it. Please check this. I will upload it on playstore once you confirm
https://drive.google.com/open?id=10Df7lJ5gUabnbYtXNTIqt9UG-Eysf435

**Comment by yoshi7** [comment]
This version is working, but the notification message 'Firewall enabled' is now permanent there, even when "Show notification icon" is unchecked?

**Comment by ukanth** [comment]
Yes. because that's why the crash. 8.1 devices will have permanent notification.
