### ISSUE TITLE
There is a problem with the language settings on Huawei honor V8 phone. (在华为honr V8手机上语言设置出现问题)

### ISSUE THREAD

**Issue by kmfiter** [ukanth/afwall#994]
华为honr V8手机，已经获取root权限，afwall工作正常，但设置在设置中，将语言设置成简体中文后，菜单无法转换成中文。
软件版本为3.1.0。在红米NOTE3和金立S7手机上，同样的版本，将语言设置成简体中文后，是能正常显示成简体中文的。

**Comment by 1688aa** [comment]
索尼xz1，安卓9.0系统也不能设置成简体中文，用夜神模拟器5.1.1系统可以设置简体中文，用7.1.2系统不能设置成简体中文，是从版本3.0.0 [API 21+]开始就不能设置的

**Comment by jonathanhzs** [comment]
修改/data/data/
dev.ukanth.ufirewall.donate/shared_ prefs/dev.ukanth.ufirewall.donate_ preferences .xml权限为只读，文件里的语言zh-CN为zh即可。

**Comment by leoxxx** [comment]
权限不用改。只要注意下面这段就行。改完重启一下。
`<string name="locale">zh</string>`
