### ISSUE TITLE
[3.2.0-beta] Afwall hangs in disabled state instead of reporting problems with SU

### ISSUE THREAD

**Issue by rancidfrog** [ukanth/afwall#995]
All of a sudden I am getting notifications on network switching from data to wifi and vice versa,
![](https://i.imgur.com/7dFXyi4.png)

When I click enable firewall from menu the first time I get a dialog without progress, it is just stuck at,
![](https://i.imgur.com/5fmRzQc.png)

After either dismissing dialog or clicking somewhere else,  enable firewall still appears in menu,
![](https://i.imgur.com/Ga6zugv.png)

But,
when clicked it asks to disable firewall completely,
![](https://i.imgur.com/95RNCpn.png)

This just started happening today. Not sure what is triggering it as I never had this problem

**Comment by rancidfrog** [comment]
My superuser app was acting up. Strangely.
Reflashed it and afwall back to normal.

However, afwall should have displayed su not found or something similar instead of having dialog with no progress. And wrong info in menus for Enable|Disable when enabling firewall not properly set due to su issues. 
As it should have detected a problem gaining root.

**Comment by ukanth** [comment]
Fixed in 3.3.0. Closing.
