### ISSUE TITLE
App Not Installed 3.2.0 Beta

### ISSUE THREAD

**Issue by markd89** [ukanth/afwall#996]
Hi,
I have a OP5 running Lineage 16. I have AFW+ 3.1.0 installed and running.

I downloaded the beta apk from Github but when I select Install, I see "App not installed."

**Comment by zputnyq** [comment]
If you get both from different place,  my assumption they have different key. Try by uninstalling v3.1.0 then install 3.2.0 beta, but back up v 3.1.0 first. I guess it will work.

**Comment by markd89** [comment]
That worked, thanks!
